### ISSUE TITLE
Add Other Videos fields to CSV export

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#100]
- See #47 
- First idea: create a semi-colon-separated list in a single field in the CSV export of all related file names

**Comment by vanlummelhuizen** [comment]
@ocrasborn Is this issue still relevant?

**Comment by ocrasborn** [comment]
@vanlummelhuizen Yes still relevant, as it will help us keep things tidy. Note (but probably clear anyway): we don't need an accompanying CSV import function for this, that's taken care of by the video import routines.

**Comment by susanodd** [comment]
This might be relevant again. There's an export for hyperlinks on the Manage Datasets page.
Is that sufficient @ocrasborn ?

**Comment by ocrasborn** [comment]
Ah yes @susanodd , brilliant! I had forgotten about that, very useful indeed. @Jetske , this relates to #875 , I mean, you can quickly get a list there of the missing ones. (The signs that miss a video but do have an image for some reason lost the video... we'll just re-upload them, there's not that many for NGT.)
