### ISSUE TITLE
Error CNGT scripts

### ISSUE THREAD

**Issue by susanodd** [Signbank/Global-signbank#1000]
Out of the blue, code that worked an hour ago just stopped working with this error:

```
    from CNGT_scripts.python.signCounter import SignCounter
    from lxml import etree
ImportError: cannot import name 'etree' from 'lxml' 
```

**Comment by susanodd** [comment]
I had to force reinstall of `lxml` and also `numpy`.
It's working again.

**Comment by susanodd** [comment]
The numpy in the requirements does not exist.

**Comment by vanlummelhuizen** [comment]
> It's working again.

@susanodd Close?

**Comment by susanodd** [comment]
Yes, I upped the numpy version in the requirements (on the senses branch).

**Comment by susanodd** [comment]
This is still messed up.

I create a new virtual environment. But gradually, it gives this as an error again:

```
    from CNGT_scripts.python.signCounter import SignCounter
  File "/Users/susaneven/Documents/virtualsignbank/lib/python3.10/site-packages/CNGT_scripts/python/signCounter.py", line 13, in <module>
    from lxml import etree
```

**Comment by vanlummelhuizen** [comment]
I cannot replicate your problem. The server also seems to be fine.

**Comment by susanodd** [comment]
It just happened yet again.

Could PyCharm be checking the status of site packages that are in requirements and "updating" them or something?
The only solution is to totally remove all site packages files from the virtual environment.
Reintall pip. Then reinstall all the requirements.

There keep appearing more copies of old installs with " 2.py" or " 3.py" etc at the end. Like it's replacing the site packages but not removing the old files.
But I have not done anything to the requirements at all. Nor to the virtual environment.

So it must be PyCharm that is doing this?

**Comment by susanodd** [comment]
The virtual environment is outside of the Git stuff.

It keeps finding "copies" of the migration files of the installed modules that have migrations.
Then it complains that there are unapplied migrations. (But it's duplicates with " 2" etc.)

**Comment by susanodd** [comment]
It just happened again.
It's always the same error message as shown in the issue description.

The requirements has a github link to the cngt scripts.

https://github.com/Signbank/Global-signbank/blob/7c19cc49e41b8fdd0ab43d932bf1cf83d3b4fab2/requirements.txt#L19

Is it possible it's somehow getting "touched" and that github thinks it's been updated?
I have GitHub desktop installed.

**Comment by vanlummelhuizen** [comment]
> Is it possible it's somehow getting "touched" and that github thinks it's been updated?

The CNGT-scripts repository is not change for some time now, so I don't think that is the problem.

**Comment by susanodd** [comment]
It happened again today. After using PyCharm for several hours, without doing anything to the virtual environment. It just got the same error message.
I suspect it's GitHub Desktop now since the CNGT_scripts are also a Git in the requirements.
No idea.

**Comment by susanodd** [comment]
This is the error:

`Original error was: No module named 'numpy.core._multiarray_umath'
`

**Comment by susanodd** [comment]
@vanlummelhuizen @Woseseltops Is it possible to modify the requirements so it doesn't CLONE the CNGT scripts?
This is somehow causing lots of problems on MacOS. It is consistently complaining about that numpy module.
PyCharm actually "checks" the installed modules and it is causing an error. Then it attempts to reinstall the requirements. Then there are duplicates for some reason.
This is getting extremely annoying because I keep having to remove all the site packages and reinstall all of them.

**Comment by Woseseltops** [comment]
Hey @susanodd , the CNGT script is in `requirements.txt` because it really is a requirement for Signbank to run, see https://github.com/Signbank/Global-signbank/issues/803 . If PyCharm doesn't like it, I think the prettiest solution is to find some sort of workaround for PyCharm... for example, isn't it possible to manually maintain the virtualenv, and only tell PyCharm to use this virtualenv when running the application?

**Comment by susanodd** [comment]
Okay, I'll see if I can change a setting.
My computer turned itself off and stopped all my applications yesterday due to low battery.
So I was forced to reboot and restart all the applications as well as GitHub.
So far it hasn't caused that error again.
Maybe PyCharm just gradually messed itself up.  :)
