### ISSUE TITLE
Public View template and views functions (mystery match request)

### ISSUE THREAD

**Issue by susanodd** [Signbank/Global-signbank#1001]
This code seems obsolete. Is it?

https://github.com/Signbank/Global-signbank/blob/7cc797e33c501c9bccd60cf89b464f3503136e49/signbank/dictionary/urls.py#L26-L29

https://github.com/Signbank/Global-signbank/blob/7cc797e33c501c9bccd60cf89b464f3503136e49/signbank/dictionary/models.py#L190-L222

https://github.com/Signbank/Global-signbank/blob/7cc797e33c501c9bccd60cf89b464f3503136e49/signbank/dictionary/views.py#L68-L150

**Comment by susanodd** [comment]
If this code is not used by any API interface or other applications, then it should be removed.

**Comment by vanlummelhuizen** [comment]
@susanodd The re_path `words`  in *urls.py* and the `word` view in *views.py* are use in:

https://github.com/Signbank/Global-signbank/blob/7cc797e33c501c9bccd60cf89b464f3503136e49/signbank/dictionary/models.py#L157

and

https://github.com/Signbank/Global-signbank/blob/7cc797e33c501c9bccd60cf89b464f3503136e49/signbank/dictionary/templates/dictionary/search_result.html#L78

**Comment by vanlummelhuizen** [comment]
The method `match_request` is used in:

https://github.com/Signbank/Global-signbank/blob/7cc797e33c501c9bccd60cf89b464f3503136e49/signbank/dictionary/views.py#L82

which is in the `word` view.

**Comment by vanlummelhuizen** [comment]
> If this code is not used by any API interface or other applications, then it should be removed.

I do not know of any API/application that uses this, but there seems to be code that still depend on it. Perhaps you could dig some deeper with the info I gave above.

**Comment by susanodd** [comment]
I tried using the urls you point out, but they don't work because there are bugs in the code.

**Comment by vanlummelhuizen** [comment]
You could apply this git-diff on branch add_sense_examplestc_884:

```diff
diff --git a/signbank/dictionary/views.py b/signbank/dictionary/views.py
index c3159a1b..375bcc18 100644
--- a/signbank/dictionary/views.py
+++ b/signbank/dictionary/views.py
@@ -110,7 +110,7 @@ def word(request, keyword, n):
 
     if request.user.has_perm('dictionary.search_gloss'):
         update_form = GlossModelForm(instance=trans.gloss)
-        video_form = VideoUploadForOjectForm(initial={'gloss_id': trans.gloss.pk,
+        video_form = VideoUploadForObjectForm(initial={'gloss_id': trans.gloss.pk,
                                                       'object_type': 'g',
                                                       'redirect': request.path})
     else:
@@ -135,7 +135,7 @@ def word(request, keyword, n):
                                # lastmatch is a construction of the url for this word
                                # view that we use to pass to gloss pages
                                # could do with being a fn call to generate this name here and elsewhere
-                               'lastmatch': trans.translation.text.encode('utf-8')+"-"+str(n),
+                               'lastmatch': (trans.translation.text+"-"+str(n)).encode('utf-8'),
                                'videofile': videourl,
                                'update_form': update_form,
                                'videoform': video_form,
```

**Comment by susanodd** [comment]
That is really old code. Nothing to do with senses.

**Comment by susanodd** [comment]
I suspect the code is obsolete and not used anymore.
`translation_set` are the old keywords.

**Comment by susanodd** [comment]
@Woseseltops  is the above code (see issue description) used by the ASL users ?
(See the url.)

**Comment by susanodd** [comment]
This page:

https://github.com/Signbank/Global-signbank/blob/7cc797e33c501c9bccd60cf89b464f3503136e49/signbank/dictionary/views.py#L62

is not found on the server.

**Comment by vanlummelhuizen** [comment]
@susanodd An example of a url matching the first re_path: https://signbank.cls.ru.nl/dictionary/gloss/3117.html. An url matching the second: https://signbank.cls.ru.nl/dictionary/gloss/3117.

**Comment by susanodd** [comment]
Do we want senses to be visible to anonymous users?
It's actually still showing the translations.

**Comment by susanodd** [comment]
So the one with `.html `is for anonymous users.
The one without asks for a login.
So the method in views (for with `.html`) is maybe messed up because it wants to offer an upload form

**Comment by ocrasborn** [comment]
>Do we want senses to be visible to anonymous users?
>It's actually still showing the translations.

Ah, yes, good point: for anonymous users, senses should also replace the translations.

**Comment by susanodd** [comment]
@vanlummelhuizen this code still looks iffy

https://github.com/Signbank/Global-signbank/blob/7cc797e33c501c9bccd60cf89b464f3503136e49/signbank/dictionary/views.py#L68-L85

It's prefaced with a login check so this is not the anonymous view code. (So why is this being done for anonymous users? Does it somehow get overridden in other code?) It shares the same template as the Public View (`word.html`).

And this line:

https://github.com/Signbank/Global-signbank/blob/7cc797e33c501c9bccd60cf89b464f3503136e49/signbank/dictionary/views.py#L85

the "gloss" is being referenced by the "keyword", and it's totally disregarding the dataset permissions and languages. The code looks like it's circumventing all the stuff built around the datasets.
That's messed up.

It's supposed to be anonymous users doing this, because it is not via the search form.
I don't really see how users would be getting to this. Users don't search via the url. They would need to already know the existence if the url since it's not via the menus.
It is the same template as the Public View. But the Public View is gone to via the normal search and glosses in the gloss list. When the user is anonymous, those links in the gloss list go to this code.
So it would have a gloss id, not a keyword.

**Comment by susanodd** [comment]
and here, following that code:

https://github.com/Signbank/Global-signbank/blob/7cc797e33c501c9bccd60cf89b464f3503136e49/signbank/dictionary/views.py#L91

The homophones are being obtained via the Keyword (Translation)

That's actually one of the advanced features not for anonymous users. But it's not actually displayed in the Public View either.

**Comment by susanodd** [comment]
I'm revising the template word.html to use Senses instead of translations.
I removed "extra" context variables that do not appear in the template.
There are several functions that share the template. The only javascript code imported by the template is the scroll bar of search results. So its variables are remaining.
There is also #568 that added notes to the Public View.
Then I discovered that something is messed up with the NoteType field choice in GlossDetailView. It's not possible to change the role.

**Comment by vanlummelhuizen** [comment]
> Neither of these are reachable. Nothing calls the `get_absolute_url` method of Translation. (First piece of code.)
> 
> The second was subsumed by the scroll bar of results.

Agreed. So I guess the `word` view can be removed.

**Comment by susanodd** [comment]
Okay, thanks. I'm working on the Public View.

**Comment by susanodd** [comment]
The Public View has been revised to show Senses instead of Keywords.

As part of this, old code that used the keywords in weird ways was removed.
The "context" variables in the view functions for gloss and morpheme (public views) were modified to remove all variables that are not used in the word.html template, which they share.

The Morpheme View was repaired (in a separate commit) so that Notes and Other Media (for logged in users) can be edited. It was necessary to explictly "coerce" a gloss into a morpheme when it is a morpheme. Otherwise the gloss the Note points to was not matching and the Morpheme Edit kept switching over to become a Gloss Edit. (This was a non-reported bug that became evident while debugging the Public View for Morphemes.)

**Comment by vanlummelhuizen** [comment]
@susanodd I think this issue can be closed then.

**Comment by susanodd** [comment]
Yes, probably, although it's on the Senses branch so it's not live.
