### ISSUE TITLE
Mystery code videos

### ISSUE THREAD

**Issue by susanodd** [Signbank/Global-signbank#1005]
This code makes use of the _meta construct, which I'm programming out since PyCharm flags its use.

https://github.com/Signbank/Global-signbank/blob/7cc797e33c501c9bccd60cf89b464f3503136e49/signbank/video/management/commands/makeglossvideos.py#L75-L83****

I can't find any match for using this code.
@vanlummelhuizen you are the one who originally wrote this.

**Comment by vanlummelhuizen** [comment]
> you are the one who originally wrote this.

I am. I also cannot find code that calls this function, so it can be removed.

> This code makes use of the _meta construct, which I'm programming out since PyCharm flags its use.

`_meta` is part of the Django API: https://docs.djangoproject.com/en/4.2/ref/models/meta/, so using it is not a problem.

**Comment by susanodd** [comment]
The other uses of `_meta` have been moved inside of methods in the models. PyCharm kept flagging them elsewhere as exposing the model.

The above function looks like maybe you were testing something in the python interpreter to see what was going on with the videos.
