### ISSUE TITLE
NGT json file

### ISSUE THREAD

**Issue by susanodd** [Signbank/Global-signbank#1008]
There is a file that has not been changed for eight years:

`signbank/dictionary/fixtures/ngt.json`

My local PyCharm keeps deleting it by itself (I am not deleting it)
Then it gets out of sync with GitHub.
Then I restore it so I won't accidentally delete it on GitHub.
But then my virtual environment breaks for some reason (see the other issue).

Can this file be deleted?
`signbank/dictionary/fixtures/ngt.json`

**Comment by vanlummelhuizen** [comment]
I don´t know anything about this file. It seems to be there from the initial commit in 2014. Perhaps @Woseseltops knows.

**Comment by Woseseltops** [comment]
I vaguely remember that Signbank's initial data came from some other source, like an Excel file, and that I had some script that transformed this data source into a fixture. I think this file is that fixture. In any case, I think fixtures are always 'snapshots' of the database that become outdated as soon as there's a change in the source database, so I think all fixtures can be deleted.

**Comment by susanodd** [comment]
Okay, I removed the very old fixtures. I left the two ASL ones.
