### ISSUE TITLE
Mystery code import authors

### ISSUE THREAD

**Issue by susanodd** [Signbank/Global-signbank#1009]
https://github.com/Signbank/Global-signbank/blob/7cc797e33c501c9bccd60cf89b464f3503136e49/signbank/dictionary/views.py#L634-L641

**Comment by vanlummelhuizen** [comment]
A hard coded file path to a JSON-file. Ouch. I cannot imagine we want to keep this, so please remove this view.

**Comment by susanodd** [comment]
See also
https://github.com/Signbank/Global-signbank/commit/72e64656bf89fdf56d1257903b712efeae582ad4

**Comment by vanlummelhuizen** [comment]
@susanodd I you are happy, I think you can close this issue.

**Comment by susanodd** [comment]
Okay, this is on the Senses branch.
