### ISSUE TITLE
Hover videos not showing in GlossListView

### ISSUE THREAD

**Issue by susanodd** [Signbank/Global-signbank#1020]
After the most recent deploy for #963 (merge of #1018 ) the preview videos stopped showing.

In the Detail View, there is this message now in the browser Ontwikkelaarshulpmiddelen:
`Ongeldige URI. Laden van mediabron  is mislukt.`
https://signbank.cls.ru.nl/dictionary/gloss/4477/

(This gloss showed the moving video in the list view with hover previously.)
(It could be that there is a javascript error or a graceful try except that is causing code to be skipped without an error message.)

**Comment by susanodd** [comment]
@Woseseltops it's impossible to debug this using PyCharm runserver.

**Comment by susanodd** [comment]
On some of the methods, Django converts things to "string" rather than returning an object.
Then it's not able to apply a method to a gloss in the template, for example.

**Comment by Jetske** [comment]
I think 'Ongeldige URI. Laden van mediabron  is mislukt.' is the javascript for recording video that doesn't work in Firefox. It gives no errors in Chrome.

**Comment by susanodd** [comment]
Oh, that would explain it. It didn't finish something.

It's working now after rebooting my computer. (Like the good old days when that solved everything.)

**Comment by susanodd** [comment]
Solution: Reboot your computer.
