### ISSUE TITLE
Signbank is very slow

### ISSUE THREAD

**Issue by susanodd** [Signbank/Global-signbank#1035]
@Woseseltops I just got this message in the Ontwikkelaars venster of Firefox:

```
GET | https://signbank.cls.ru.nl/dictionary/gloss/752/
-- | --
Status
500
Internal Server Error
VersieHTTP/1.1
Overgebracht808 B (grootte 616 B)
Referrer-beleidstrict-origin-when-cross-origin
Prioriteit aanvragenHighest

```

`Deze pagina bevindt zich in de Quirks-modus. De pagina-indeling kan worden beïnvloed. Gebruik voor de standaardmodus ‘<!DOCTYPE html>’.`

I think something is going on with the google region1.google-analytics.com

It's showing a status 204, no content.

@vanlummelhuizen said Google Analytics would change per 1 July.
It sends data to @ocrasborn
@vanlummelhuizen did not refresh it, nor did @ocrasborn 
We can remove it from the base layout.

**Comment by susanodd** [comment]
It took 3.54 minutes to load NGT gloss AANBELLEN (752)

(See #1003 also.)

**Comment by susanodd** [comment]
I removed the google analytics from the base layout. The time above is still absurdly long.
But at least it didn't crash this time.

**Comment by susanodd** [comment]
https://en.wikipedia.org/wiki/Quirks_mode

> Additionally, a web page which does not include a DOCTYPE at all will render in quirks mode. 

There are no DOCTYPE hits.

**Comment by susanodd** [comment]
![aanbellen-ngt-752](https://github.com/Signbank/Global-signbank/assets/24272544/f5154ef1-ce9f-4240-ac05-be610b78e6f1)

![server-stats-aanbellen-ngt-752](https://github.com/Signbank/Global-signbank/assets/24272544/0635a65d-50e8-48f6-8e97-1b8d384ff5f4)

**Comment by susanodd** [comment]
So html is whatever the Django template is being generated.

**Comment by susanodd** [comment]
What's taking a long time is the time between clicking on a link in the Gloss List and the new page being generated for that gloss.
Nothing appears in the above pie charts for several minutes while it's doing whatever it is doing. (Generating the template?)

@Woseseltops what is going on? Is lightning being used for other process heavy computations? Bitcoin?

**Comment by susanodd** [comment]
@Woseseltops @vanlummelhuizen @Jetske I have no idea what is wrong with the Gloss Detail page.
It won't open at all on my macbook either. The rest of the site works. Except for the Gloss page.
Django processes the get_context just fine so that's not the problem.
There must be something going on with the template.
But console logs at the start of the template do not show up in the logs.
It's like it's not generating the html at all.

**Comment by susanodd** [comment]
Somebody deleted the group NGT.
Users used to get permission for NGT from this as they were put into this group when first getting a login as the glosses are public.

**Comment by susanodd** [comment]
There might be something going on with guardian permissions.

All the sense related permissions are used quite a lot now.
The group Editor did not have these permissions.
Moreover, I did not have permission the change NGT. Because this used to be from group NGT.
I repaired these on my local computer, but still I can not view the glosses in NGT.

**Comment by susanodd** [comment]
@Woseseltops as you know I've been having trouble with migrations that are included installed modules in the requirements.
Because the gloss detail view stopped working, I'm running signbank locally using runserver in the virtual environment rather than PyCharm. (PyCharm keeps installing things multiple times regardless of what I do and then it stops because of duplicate migrations in the requirements.)
So I've reinstalled all the requirements after deleting them all in my virtual environment.
So I'm working outside of PyCharm.
And to my surprise, on the fresh install, there are duplicate migrations in the installed tagging package!!!
This is why it's not working.

**Comment by susanodd** [comment]
I figured out what is causing problems in Gloss Detail View (see #1003 ).

It's the combination of `forloop.counter` in the template and the use of `?edit` in the url.
These are incompatible because the former is dynamically generated at template rendering, whereas the latter reuses the existing template.
My local server is getting errors for non-existent reverse urls.

**Comment by susanodd** [comment]
@Woseseltops could this have anything to do with the upgrade of Ubuntu on lightning?

**Comment by Jetske** [comment]
There are a lot of queries executed on the detail page, probably because of all the manytomany relations. Do you think doing prefetch_related in for loops would help here?

**Comment by susanodd** [comment]
> There are a lot of queries executed on the detail page, probably because of all the manytomany relations. Do you think doing prefetch_related in for loops would help here?

Yes!

**Comment by susanodd** [comment]
@Woseseltops this is from the new wsgi log after a signbank restart

```
your memory page size is 4096 bytes
detected max file descriptor number: 1024
building mime-types dictionary from file /etc/mime.types...1516 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8000 fd 6
Python version: 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
PEP 405 virtualenv detected: /var/www/env
Set PythonHome to /var/www/env
Python main interpreter initialized at 0x55cbd4fab9a0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 1094560 bytes (1068 KB) for 16 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x55cbd4fab9a0 pid: 209 (default app)
mountpoint  already configured. skip.
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 209)
spawned uWSGI worker 1 (pid: 336, cores: 4)
spawned uWSGI worker 2 (pid: 337, cores: 4)
spawned uWSGI worker 3 (pid: 341, cores: 4)
spawned uWSGI worker 4 (pid: 345, cores: 4)
```

**Comment by susanodd** [comment]
Removing the duplicate method call in the template did not really help at all.
It took **4.68 min** to load ACCEPTEREN-C (4160)

**Comment by susanodd** [comment]
The new and improved similar senses method is live now.

Signbank is considerably faster now!

**Comment by Woseseltops** [comment]
I just read through this thread, and if I'm not mistaken all problems and questions to me have been solved, is that correct? And if so, could this be closed?

**Comment by Jetske** [comment]
@Woseseltops yes it is fixed

**Comment by susanodd** [comment]
Okay, it seems to be operating okay.
