### ISSUE TITLE
Some sense methods do not complete in the template

### ISSUE THREAD

**Issue by susanodd** [Signbank/Global-signbank#1036]
The GlossDetailView is not showing in the browser, or takes what seems like infinity.
There are many new sense methods in the view, which are applied by Django when generating the html from the template.

Here is an example of one, with explanation.

`{% for similar_sense in sense.get_senses_with_similar_sensetranslations_dict %}`
                                             

I put the similar senses into a context variable:

```
 {% with sense_to_similar_senses|get_item:sense as similar_senses %}
   {% for similar_sense in similar_senses %}
```

```
        sense_to_similar_senses = dict()
        for sense in context['senses']:
            sense_to_similar_senses[sense] = sense.get_senses_with_similar_sensetranslations_dict()

        context['sense_to_similar_senses'] = sense_to_similar_senses
        print(sense_to_similar_senses)
```

This method takes an extremely long time to complete  does. See #1035 

The detail view still does not appear in the browser for a long time. Before this repair it was 4 minutes before it was loaded.
There are probably other such methods applied in the template that do not complete.

**Comment by susanodd** [comment]
@Jetske I temporarily put a (python) print statement (locally) inside the similar senses method.
It literally looks at all other senses for similar strings!!!!
I discovered that the method was indeed being called twice, as there was a second occurrence in the template!!
I modified that, although there doesn't seem much improvement in the speed. But at least locally it doesn't timeout anymore.

**Comment by susanodd** [comment]
@Jetske I'm not sure if a similar fix is needed for the example sentences methods.
When adding the revision history I noticed some code that looks like it could become slow as more and more senses and sentences are added.

**Comment by Jetske** [comment]
@susanodd yes I think it can be improved in other places as well, I'll look at it.

**Comment by Jetske** [comment]
This issue can be closed, right? @susanodd

**Comment by susanodd** [comment]
Yes, it has been subsumed by #1047
