### ISSUE TITLE
Double quotes in CSV dependent on locale and spreadsheet

### ISSUE THREAD

**Issue by susanodd** [Signbank/Global-signbank#1045]
The CSV regex needs to match other double quotes (dependent on locale and spreadsheet)

`[\"\u201c] ` (left double quote pattern)

`[\"\u201c]` (right double quote pattern)

For installation of new Signbanks, this may need to be modified if totally other double quote characters are replaced into the " character (used in export CSV to surround the sentence text in tuples)
by (multilingual) spreadsheet software.

Can you add a note about this? Otherwise it will be a mystery to developers why it doesn't work if it doesn't.

_Originally posted by @susanodd in https://github.com/Signbank/Global-signbank/issues/1030#issuecomment-1683461793_

**Comment by susanodd** [comment]
(This was very annoying because I could not see that the double quote had been changed into a slanted double quote. And the update CSV kept not finding any changes....

**Comment by Woseseltops** [comment]
How about making this a setting @susanodd ? Something like

```python
LEFT_DOUBLE_QUOTE_PATTERNS = ['\"\u201c']
RIGHT_DOUBLE_QUOTE_PATTERNS = ['\"\u201c']
```

**Comment by susanodd** [comment]
This is live.
