### ISSUE TITLE
Spurious commas in list display of senses

### ISSUE THREAD

**Issue by susanodd** [Signbank/Global-signbank#1057]
![spurious-commas](https://github.com/Signbank/Global-signbank/assets/24272544/e7fc32da-3008-4918-92c8-dd6ce4caf196)

The list display includes extra commas when an empty string is present in the list comprehension, apparently.

(Present in Gloss List View as well as Query View.)

**Comment by susanodd** [comment]
The extra commas that are visible in the screenshot above are caused by empty string translations being created via empty rows in the Sense input window of Gloss Detail View.
The extra commas (empty sense translations) are now hidden in the various displays.

The code that creates them needs to be modified next.

**Comment by susanodd** [comment]
I revised the code so that "empty text" senses are no longer created (accidental side effect from typing returns).

These can still exist but are no longer visible.

[NOTE: One way to get access to them to remove them is via the Map Keywords to Senses page under Analysis.
Although that seems to take a very long time to load for some datasets at the moment. If you are in the modal for editing senses for a particular language, you just click on the UPDATE button and it will remove them. That button is intended to allow erasing a sense by just setting it to be empty.]

**Comment by susanodd** [comment]
There is a virtual environment command now to remove the spurious empty translation objects (see description above).
They have been removed from the live server...

**Comment by susanodd** [comment]
@Jetske I see what went wrong.
It's the change I made to the method in models.py
I modified a setting in the if-clause because I was using it inside the new find_empty_translations command.
But then didn't use it after all.
I didn't realise the command was used as a filter in the template.

**Comment by susanodd** [comment]
The code is putting a None value into the list instead of skipping it.





{'Engels': ['referee'], 'Nederlands': [None]}


<br class="Apple-interchange-newline" style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;">

**Comment by Jetske** [comment]
Yes, I see! I made a pull request for it, can you check? #1058

**Comment by Jetske** [comment]
@susanodd I'm confused because everything seems to work except for the messages (see linked branch).

**Comment by susanodd** [comment]
Okay, I'll get working on that.

**Comment by susanodd** [comment]
> @susanodd I'm confused because everything seems to work except for the messages (see linked branch).

Did the syntax (if - else) changes in sense_changes_1057 to the templates resolve the messages ?

**Comment by susanodd** [comment]
@Jetske I'm working on the consistency now.
There is something wrong with the Detail View editing of senses.
There seem to be keyword "copies" floating around that are not visible in the correct sense.
(They show up inside the wrong sense. So they have become inserted into a different sense.)

I suspect this arises from remove the code that was for sharing senses.
Because it used to skip some code for "not shared" if the sense was "shared".
(So the bug is when the keywords appear in a different sense of the same gloss.)

I've revised the consistency check to print all the translations (all fields) when it finds something inconsistent.
(For when the setting is turned on.)

**Comment by susanodd** [comment]
Okay, I put it live.
I removed the "adjusting the ordering of the keywords" inside of the reorder_senses, since that is done inside up the update now.
For some reason (not possible to duplicate), when various combinations of editing senses and reordering senses (using the arrows) was done in the Gloss Edit Detail View, it seems like the database operations on the senses had not completed the transaction before the page was reloaded. There is a consistency check on reload and it kept finding "copies" of the translations inside the old and the new sense (old order, new order).
So I revised the code to just remove spurious translation objects.
(With a message to the output log.)
As far as I can tell, it only happens if you're deliberately making up non-realistic test data examples.
It is apparent that we needs tests for senses.

**Comment by susanodd** [comment]
The commas are no longer visible and the empty translations in the senses causing them are no longer created.

**Comment by susanodd** [comment]
I’ll add a test to show they’re no longer a problem in the Gloss Detail View.

**Comment by susanodd** [comment]
The test for no empty translations is completed and the code passes the test. Hup hup hup!
