### ISSUE TITLE
Harvest classifier constructions from corpus based on meaning

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#107]
For the process of deciding on what is lexicalised and what is not, it would be useful if classifier constructions could be harvested in the corpus and ingested in Signbank based on overlapping meaning. That is, the value of the Meaning tier in ELAN should match one of the translation equivalents in Signbank. They could be listed in a separate field with the meaning between brackets, or appear in the table of Related Signs, or perhaps form a new type of list somewhere. The frequency of the classifier tokens should be visible as well in Signbank, as that is key in deciding on the lexicalisation. Conversely, this will help us in re-analysing existing signs as non-lexical complex constructions.

**Comment by vanlummelhuizen** [comment]
@ocrasborn Could you explain a bit more and/or give examples of what you want here? If this is still relevant of course.

**Comment by ocrasborn** [comment]
This might still be useful, but we don't have time to actually work on the (NGT) data for a while, so I've made this 'low-priority'.
An alternative option, for some future moment: harvesting all annotations on the meaning tier for classifier glosses (those starting with AT_, BE_, MOVE_, PIVOT_) and SHAPE_ glosses, and adding these meaning annotations to the Translation Equivalents for that gloss.

**Comment by susanodd** [comment]
> For the process of deciding on what is lexicalised and what is not, it would be useful if classifier constructions could be harvested in the corpus and ingested in Signbank based on overlapping meaning. That is, the value of the Meaning tier in ELAN should match one of the translation equivalents in Signbank. They could be listed in a separate field with the meaning between brackets, or appear in the table of Related Signs, or perhaps form a new type of list somewhere. The frequency of the classifier tokens should be visible as well in Signbank, as that is key in deciding on the lexicalisation. Conversely, this will help us in re-analysing existing signs as non-lexical complex constructions.

This seems related to Senses.

**Comment by vanlummelhuizen** [comment]
@ocrasborn Is this issue still relevant? If not, we can close it.
