### ISSUE TITLE
Bugs introduced by #1070

### ISSUE THREAD

**Issue by susanodd** [Signbank/Global-signbank#1073]
There are quite a few formatting bugs with the senses when multiple datasets are chosen and senses are missing for languages.
This is in Gloss List View.
![gloss-list-view-misaligned-handshape-1-under-norwegian-sense](https://github.com/Signbank/Global-signbank/assets/24272544/669de317-5030-4778-b365-ed7b5df1e884)

There is a column shift and the Gloss fields appear under the Senses fields where the translations are missing.

This is because the lookup (generation of the gloss rows) is done over a "list" rather than a "language indexed dictionary".

**Comment by susanodd** [comment]
The relations view is also messed up by this function.

It's changes made in #1070

**Comment by susanodd** [comment]
I resolved this on the streamline branch (#1071 )

**Comment by susanodd** [comment]
This has been repaired and deployed.

**Comment by Jetske** [comment]
From the screenshot I can't really tell where the bugs are, can you show them more specifically?

**Comment by susanodd** [comment]
I fixed this on Friday. It was getting run-time errors for an empty dictionary value. I fixed this.

**Comment by susanodd** [comment]
The example above shows that the columns are not aligned with the header. I fixed that.
The other error was a run-time error on a NoneType. (Empty dictionary.)

**Comment by susanodd** [comment]
![relations-view-spacing-senses](https://github.com/Signbank/Global-signbank/assets/24272544/9d09fb3b-c72f-4d08-a42d-375cd6617dfe)

**Comment by Jetske** [comment]
Yes that looks good! I also see the problem now with the columns

Then it's only in the gloss list view that they don't line up:
![image](https://github.com/Signbank/Global-signbank/assets/10157482/34bede94-95d8-40f6-8ba9-cac8360285db)

**Comment by susanodd** [comment]
I'll try to repair the list view, unless you want to. I was working on the context variables in #1071 (those are deployed)
That's when I came across the bug.
Probably I made something undone for the format.
It looks like I just replaced the code in GlossListView (gloss_row.html template).

But in the gloss list view, there can be more columns for other languages. In the Relations view there are only columns for the dataset of the gloss.

I think the bug had something to do with the languages not existing in the dictionary.
It didn't want to loop over sensetranslations.items

**Comment by susanodd** [comment]
Maybe if keys (orders) are skipped the code doesn't work properly?

https://github.com/Signbank/Global-signbank/blob/9477776f856d6ca361ccf4d0ea6b7aad8fd0bb2f/signbank/dictionary/templatetags/annotation_idgloss_translation.py#L204-L217

This code assumes that all the order numbers exist?

**Comment by susanodd** [comment]
https://github.com/Signbank/Global-signbank/blob/9477776f856d6ca361ccf4d0ea6b7aad8fd0bb2f/signbank/dictionary/templates/dictionary/gloss_row.html#L59-L72

**Comment by susanodd** [comment]
`             new_dictionary[key] = "<br>" `

**Comment by susanodd** [comment]
I got it so that it has an empty row.

However, because of line wrapping in the columns, and that the languages are in separate columns, it is not known whether there is line-wrap or not.

![horizontal-vertical-sense-order-gloss-list](https://github.com/Signbank/Global-signbank/assets/24272544/b554127a-231f-436a-ac3c-3126b44a0166)

**Comment by susanodd** [comment]
Probably it needs a table inside the display for senses so the order is on a separate row and the line wrap forces the rows to align.

**Comment by Jetske** [comment]
Yes, I thought that as well.. Although I think for most senses they will probably line up ok if not too many translations are given and it's a big screen. It's not ideal though either way.
