### ISSUE TITLE
"editor status" doesn't seem to give editing rights

### ISSUE THREAD

**Issue by uklomp** [Signbank/Global-signbank#1077]
Hi all - I actually wanted to wait with questions / issues until we properly met, but this is a bit too important.
The SignBank manual writes that assigning people the "editor" status should give them editor rights (I'm talking about adding phonological information etc). I tried this with two users, raypelupessy and GStern but both users don't have the possibility to edit, they say. With GStern this could be a lay-out issue (will get back to that in another issue later), but with Ray it should simply work. I then tried also giving them "researcher" status and this didn't help. So, in case I misunderstood something, I have the question: what status do the users need to edit entries from the NGT dataset?

**Comment by susanodd** [comment]
You need to have change dataset permission for dataset NGT.
They can look in their own account under available datasets and it shows permissions in different columns. Normally users are first given view permission. They need to request change permission from the dataset owner (or admin).

**Comment by Jetske** [comment]
@uklomp the dataset permissions can be changed here: https://signbank.cls.ru.nl/datasets/manager
I think you have the rights to do that, let us know if it works

**Comment by uklomp** [comment]
Thanks, this was probably it. I asked these users, if it doesn't work, I'll re-open it.
