### ISSUE TITLE
After changing the owners in one dataset at the Global Signbank website, I jumped to another

### ISSUE THREAD

**Issue by uklomp** [Signbank/Global-signbank#1080]
Hi. I added a new dataset, like we agreed upon last week. I made the dataset "Oefenproject SignBank NGT-UvA" and wanted to access it from the homepage. In the banner on the top of the page is now a new "flag", an empty one, so that's probably the new dataset. I clicked it and indeed, its the page Dataset Detailbeeld of the Oefenproject. I saw that one of my team members was made owner. Don't know if really only 1 person was owner, or that only 1 person was visible. I wanted to add myself, and did that in the "gebruikersnaam" field, which seemed to be happening, and then the Dataset Detailbeeld of the NGT dataset appeared. With now me and another person's name as members. This is unexpected, as I think I should have stayed at the page of the Oefenproject Dataset. It's now also unclear who the owners are (I can check in Django of course, but it should be the same here). 

(by the way, I asked last time where to find 'labels' and you showed me, and I can see it, but I can't add any - there's no "settings wheel")

**Comment by susanodd** [comment]
Did you set an acronym for the new dataset? (without spaces)

There are some shortcuts in the urls that make use of the dataset acronym, so it is visible in the url instead of a dataset ID.

(That could explain the weird behaviour. We need to duplicate it.)

**Comment by uklomp** [comment]
Right. I set it to "oefen". The "flag" is now indeed also not empty anymore.
