### ISSUE TITLE
Request: make grey bars fully clickable

### ISSUE THREAD

**Issue by uklomp** [Signbank/Global-signbank#1081]
When a sign (an entry) is displayed, there are these gray bars with morphology, phonology etc to click on and see all the information. The words in the grey bars are clickable ("morphology" etc), but I'd like the full bar to be clickable, that feels more intuitive. 

I can't add labels but I'd like it to have medium priority.

**Comment by susanodd** [comment]
@vanlummelhuizen are you working on this too?
I just finished it.

**Comment by susanodd** [comment]
I removed the href implementation in favor of data-target as is done for the search panels.
This has the advantage that lots of excess divs can be removed.
I also resized the "logo" elements that appear on the bar as they were too tall for the display and caused weird empty space.

**Comment by susanodd** [comment]
I'm going to do the Morpheme Detail as I did the other.

**Comment by susanodd** [comment]
Morphemes are done. Same pull request.

**Comment by susanodd** [comment]
@vanlummelhuizen your commit on master is actually already in my branch grey_bars.
Maybe it didn't work on Safari?

**Comment by vanlummelhuizen** [comment]
> Maybe it didn't work on Safari?

I have no idea. I don't have Safari. Do you?

**Comment by susanodd** [comment]
Yes, that's what I'm working on.

**Comment by uklomp** [comment]
works great, thank you
