### ISSUE TITLE
error after weird search 

### ISSUE THREAD

**Issue by uklomp** [Signbank/Global-signbank#1084]
I was playing around with the search engine at "glos zoeken" and searched for the opening bracket ( , and then I got the following error: 
link: https://signbank.cls.ru.nl/signs/search/?search=%28&translation=
screenshot: 
<img width="1920" alt="operationalerror at signssearch" src="https://github.com/Signbank/Global-signbank/assets/147159596/39ed7128-c2ee-4d1f-a1b2-bb94fb2e34e4">

context of why I was searching for ( is that the instructions for searching says: In many text fields, you can use patterns as follows: A bevat A (....) ending with "( gebruik backslash om speciale karakters te zoeken". I don't understand this instruction but probably this should be in a different thread so I'll do that.

**Comment by susanodd** [comment]
This could possibly be influenced by some "anti-abuse" code that looks for attempts to insert code into the url.
The "search fields" that search for regular expressions are prone to this.

The tooltip text that explains the searching is very old. (@Woseseltops)

**Comment by susanodd** [comment]
That error is weird. It's actually a malformed regex that has been typed in.
On my local server searching on `(|`, I get a warning not an error.

This works searching on `#(A|B)`
yields two glosses: #A and #B.

**Comment by uklomp** [comment]
I had an error again today, when searching at the field for Dutch lemma's and searching for 'pt'. My colleagues searched for the same and didn't receive it by the way. 
<img width="960" alt="sessioninterrupted at signssearch" src="https://github.com/Signbank/Global-signbank/assets/147159596/f9b568ad-081f-46d5-88bf-be4d0f191db1">

**Comment by susanodd** [comment]
We know this kind of error. Easiest is to close/logout of all of your open windows and login again.
This can happen if you are logged in on two different computers and have altered the selected datasets on one.
The selected datasets is stored in the user profile. There are also session variables maintained, such as last used dataset and various query parameters, the interface language, the number of pages you wish to view. So sometimes the session variables become inconsistent across the various browser windows. If you are waiting for the display of search results and then start using a different window that can also interrupt the transaction.

If the system is very busy this can also cause weird transaction errors. There is an issue to switch the database system to MySQL from Sqlite. (#673)

The Lemma List View takes a very long time to load for NGT.
The Gloss List View does for each row is a separate database call and the rows added dynamically.
But the Lemma List View has an entire list to generate the page for.

**Comment by uklomp** [comment]
> @uklomp This could possibly be influenced by some "anti-abuse" code that looks for attempts to insert code into the url. The "search fields" that search for regular expressions are prone to this. (I tried the link you show and yes, this is the error from "user trying to insert code in url." It is weird that you got this error. What browser?

> I'm pretty sure it was Chrome

**Comment by susanodd** [comment]
@uklomp the examples I gave of regex searches were in the Gloss (Dutch) field.

Is your error arising in the menu bar search fields? Those are a bit different because they always lead back to Signs Search (also when you are on other pages).

**Comment by uklomp** [comment]
It's indeed in the menu bar search fields (and indeed in Chrome, but the same happens in Edge).

**Comment by susanodd** [comment]
Okay, I'm repairing this.

**Comment by susanodd** [comment]
This should be working now.

I added a setting USE_REGULAR_EXPRESSIONS and set it to False.
Hereby turning off all the tooltips related to regular expressions and no longer accommodating regular expression searches, nor needing any backslashes in the input for special characters.

Caveat, now it's not possible for the user to use regular expressions for search.
The regular expression code needs to be debugged before this setting can be set to True.
(@Woseseltops and @vanlummelhuizen can figure out what is wrong with the regular expressions.)

**Comment by uklomp** [comment]
OK, clear to me. I believe a lot of people like to use regular expression so I think this should receive some priority then. At least the instruction is also not there now (otherwise it would be confusing).

**Comment by vanlummelhuizen** [comment]
See https://github.com/Signbank/Global-signbank/issues/1089#issuecomment-1820638909

**Comment by vanlummelhuizen** [comment]
> (@Woseseltops and @vanlummelhuizen can figure out what is wrong with the regular expressions.)

I think it is the `re.escape` in https://github.com/Signbank/Global-signbank/blob/f744d023dfe32bb1458910664088910e49cab724/signbank/dictionary/adminviews.py#L750-L754. It seems strange that a regular expression is escaped before it is used as regular expression.

**Comment by vanlummelhuizen** [comment]
And also https://github.com/Signbank/Global-signbank/blob/f744d023dfe32bb1458910664088910e49cab724/signbank/dictionary/adminviews.py#L772-L774

**Comment by susanodd** [comment]
> > (@Woseseltops and @vanlummelhuizen can figure out what is wrong with the regular expressions.)
> 
> I think it is the `re.escape` in
> 
> https://github.com/Signbank/Global-signbank/blob/f744d023dfe32bb1458910664088910e49cab724/signbank/dictionary/adminviews.py#L750-L754
> 
> . It seems strange that a regular expression is escaped before it is used as regular expression.

The special characters are not being backslashed. It causes the error (screenshot) shown when you try to backslash characters you think are special characters. It thinks it's a function being applied.
Try some on your local server with the USE_REGULAR_EXPRESSIONS turned on.
The "input" is not accepting regular expressions.

**Comment by susanodd** [comment]
Consider input search:
`(A+`
Apparently this is a malformed regex because there is nothing after the plus and no closing paren.
So then the paren and the plus should be backslashed.
There was additional code that checked an input did not start with plus.
Apparently that is secret code for a function.
Also consider:
`^A `or `[^A`
The first one looks okay, ... starts with A
But the second one probably needs backslashes. Or it needs a clothing square bracket.
The problem is all the malformed input generates runtime errors.

**Comment by susanodd** [comment]
https://docs.python.org/3/library/re.html

**Comment by susanodd** [comment]
I found this example:

```
import re

try:
    re.compile('[')
    is_valid = True
except re.error:
    is_valid = False
```

So I guess we don't bother to parse, we just try-except.

**Comment by susanodd** [comment]
With the USE_REGULAR_EXPRESSIONS set to True, the following queries work as shown:

![ngt-move-plus-5-no-results](https://github.com/Signbank/Global-signbank/assets/24272544/b55cdf06-71cb-4fbc-ae94-908a0e338d31)

No results unless a backslash is used before the plus as below:

![ngt-move-backslash-plus-five](https://github.com/Signbank/Global-signbank/assets/24272544/705e7dd5-4392-4601-9178-f8596c43ef99)

**Comment by susanodd** [comment]
For the original query "`( ,`" feedback is given now:

![user-feedback-regex-special-characters](https://github.com/Signbank/Global-signbank/assets/24272544/39e1699c-1871-442e-b36c-c0c976ffa6f7)

**Comment by susanodd** [comment]
The feedback is a bit touch and go. But that's what the site is supposed to do. (Instead of cause run-time errors if the user forgets backslashes.)

**Comment by susanodd** [comment]
The newest code is on master. With regexs that more or less work. Except if you are intent on making it crash you most probably will.

**Comment by susanodd** [comment]
The regular expressions are available on the live server again.
The expression of this issue results in a message as shown below, instead of a run-time error:

![weird-expression-menu-bar-feedback](https://github.com/Signbank/Global-signbank/assets/24272544/24bdd8ec-0b68-4d84-a2fb-3a4746fd85a6)

**Comment by susanodd** [comment]
@uklomp wrote:

> context of why I was searching for ( is that the instructions for searching says: In many text fields, you can use patterns as follows: A bevat A (....) ending with "( gebruik backslash om speciale karakters te zoeken". I don't understand this instruction but probably this should be in a different thread so I'll do that.

There is an issue for the tooltip #1095

**Comment by vanlummelhuizen** [comment]
@susanodd Perhaps the error message could also inform the user that Signbank expects a regular expression here.

**Comment by uklomp** [comment]
it's solved, thanks!
