### ISSUE TITLE
question: more info on searching for special characters? 

### ISSUE THREAD

**Issue by uklomp** [Signbank/Global-signbank#1085]
(see also my last submitted issue)

I was playing around with the search options under 'glos zoeken' and I understand the first lines but I don't get this last instruction: ( gebruik backslash om speciale karakters te zoeken. (the instructions that appear when you hover over the box 'glos zoeken') 
I don't really get this open bracket. Does this instruction mean: if you, in theory, would want to look for (, please use a backslash? And: When and why would we search for special characters and how should we do this, do you maybe have an example?

**Comment by susanodd** [comment]
To search on `#[A-Z]$` yields finger spelling glosses.

**Comment by uklomp** [comment]
Ok, that's clear! Thank you
