### ISSUE TITLE
Searching for the gloss move+5 doesnt yield the gloss move+5 

### ISSUE THREAD

**Issue by uklomp** [Signbank/Global-signbank#1087]
I searched for the gloss "move+5", which is an existing gloss, in the 'glos zoeken' field in the menu bar. It doesn't yield any results, while it is a gloss. A colleague tried it as well and he also doesn't get any results. I also tried "move+4" and "move+3" and this also doesn't work. "move+" does work by the way.
link: https://signbank.cls.ru.nl/signs/search/?search=move%2B5&translation=

**Comment by susanodd** [comment]
Can you try it in the Gloss (Dutch) field?

I'm working on the menu bar fields. (#1084 )

**Comment by uklomp** [comment]
I now tried it through Gebaren -> Zoeken -> Glos (Nederlands). It doesn't give any results. Interestingly, if I now try move+, which worked in the menu bar fields, it tells me to add a backslash: 
"Error in search field Gloss (Dutch): Please use a backslash before special characters."
https://signbank.cls.ru.nl/signs/search/?csrfmiddlewaretoken=UIKThF1yyoMEfS0TeFMbRhPfsfrQ3om3Nyp7NkSZFrwBQtnT6h9PPG3yT6gLTeWu&sortOrder=&search_type=sign&search=&glosssearch_nl=move%2B&lemma_nl=&keyword_nl=&glosssearch_en=&lemma_en=&keyword_en=&useInstr=&morpheme=&weakdrop=0&weakprop=0&domhndsh_letter=0&domhndsh_number=0&subhndsh_letter=0&subhndsh_number=0&locVirtObj=&phonOth=&mouthG=&mouthing=&phonetVar=&repeat=0&altern=0&iconImg=&concConcSet=&relation=&relationToForeignSign=&hasRelationToForeignSign=0&inWeb=0&isNew=0&hasvideo=0&hasothermedia=0&hasmultiplesenses=0&definitionContains=&defspublished=0&createdBy=&createdAfter=&createdBefore=&excludeFromEcv=0&show_all=False

But if I then try \move+ or move\+, I still get these same errors.

**Comment by susanodd** [comment]
This is very weird. I suggest @Woseseltops looks at this.

**Comment by susanodd** [comment]
As far as I can tell, this isn't a matter of escaping the special characters. It's something to do with the `__iregex` search of the database.
The character `+` seems the culprit.

**Comment by susanodd** [comment]
This might be a browser issue.

It works okay on Safari on branch streamline.

**Comment by susanodd** [comment]
Okay, but not in the Gloss (Dutch) field. :(

**Comment by susanodd** [comment]
After a lot of fiddling. The plus character does not need to be backslashed. It's not a special character apparently.

**Comment by susanodd** [comment]
I repaired it to work on the language-based search fields. However, sometimes you do need the backslash.
For example, to search

`MOVE\+[A-Z]$`

But to search `MOVE+`
you do not need to.
The backslash gets added automatically in the menu bar fields and shows up there.

(This is not live yet.)

**Comment by vanlummelhuizen** [comment]
The fields in the top bar (and perhaps other fields as well) are interpreted as regular expressions. A plus sign is a special character, meaning 'repeat the character just before the plus sign 1 or more times'. To match the plus sign and not interpret it a special, you should escape it by putting a slash before the plus sign: `MOVE\+5`. An alternative is using a period sign which is a wildcard, it means 'one character of any kind': `MOVE.5`.

I think we should discuss how we want to handle the input of these fields: as regular expression or not. Or perhaps let the user explicitly mark a field as regular expression.

I don´t think it is a good idea to use only part the regular expression special characters. This is uninterpretable by the user.

**Comment by susanodd** [comment]
That's the problem, the backslash is not working.

**Comment by susanodd** [comment]
If we just remove all the iregex filters and just use icontains, they work. I did this for the other text lookups.

Recall that something was done to prevent users putting code in the regex fields. Is that still active?

**Comment by vanlummelhuizen** [comment]
> That's the problem, the backslash is not working.

It does: https://signbank.cls.ru.nl/signs/search/?sortOrder=&search_type=sign&search=move\%2B5

Let's not try to fix this by adding more code, more interpretation of what a user means, more complication. We should interpret the search value as either a regular expression or as a simple search string, not something idiosyncratic to Signbank that is hard to interpret for the users. As I said before, we probably should let the user explicitly decide what it is: regular expression or simple string. Simple for us developers, clear to the user.

**Comment by susanodd** [comment]
Probably get rid of the Regex Tooltip. That seems really confusing.

Is it possible that the regex things with the database changed as Python and Django have been upgraded earlier this year?

**Comment by uklomp** [comment]
interesting, yesterday move\+5 didn't work as well.

**Comment by susanodd** [comment]
> > That's the problem, the backslash is not working.
> 
> It does: [https://signbank.cls.ru.nl/signs/search/?sortOrder=&search_type=sign&search=move\%2B5](https://signbank.cls.ru.nl/signs/search/?sortOrder=&search_type=sign&search=move%5C%2B5)
> 
> Let's not try to fix this by adding more code, more interpretation of what a user means, more complication. We should interpret the search value as either a regular expression or as a simple search string, not something idiosyncratic to Signbank that is hard to interpret for the users. As I said before, we probably should let the user explicitly decide what it is: regular expression or simple string. Simple for us developers, clear to the user.

So the value in the URL is already "messed about".

**Comment by susanodd** [comment]
Here's the NL Tooltip. Totally confusing.

![regex-tooltip-Nederlands](https://github.com/Signbank/Global-signbank/assets/24272544/89abe490-3aee-431e-8b9f-1b10c274f70c)

**Comment by susanodd** [comment]
Example given here:
https://stackoverflow.com/questions/75064809/difference-between-icontains-and-iregex-in-django
to explain `__iregex` 

`MyModel.objects.filter(t__iregex=r'X\d{6}-\d{4}[\da-z]{0,3}')`

Do we want to allow the user to type in such complicated patterns?

**Comment by susanodd** [comment]
So I found out where the bug is  by narrowing the "regex" part of the code to only consider the character `"+"`

The code was too eagerly trying to make sure backslashes are present.

Q @Woseseltops : WHAT ARE THE SPECIAL CHARACTERS?

We can make a Setting for this.

**Comment by susanodd** [comment]
I can successfully check that special characters are backslashed, but "this" is happening first: #987

**Comment by susanodd** [comment]
This is solved.

![ngt-menu-search-move-plus-five](https://github.com/Signbank/Global-signbank/assets/24272544/cb4a40b3-457f-4612-a502-c4e9de45ef4a)
