### ISSUE TITLE
Setting USE_REGULAR_EXPRESSIONS

### ISSUE THREAD

**Issue by susanodd** [Signbank/Global-signbank#1089]
Default is False

**Comment by susanodd** [comment]
This is implemented for the case that no regex are used.
If the setting is turned off, the tooltips are not shown and the queries are all `icontains` queries.

For the time being, this resolves the problems with the regex searches.
The original `iregex` query code is still available if the setting is turned on.

**Comment by susanodd** [comment]
This is live now.

**Comment by vanlummelhuizen** [comment]
@susanodd Is this setting intended as temporary solution to either let users enter a plain search string of a regular expression? As I said in https://github.com/Signbank/Global-signbank/issues/1087#issuecomment-1814213137 it would be a good thing if each individual user could indicate whether a string should be interpreted as plain search string of regular expression, for instance by clicking a check box or selecting from a drop down.

@uklomp what do you think?

**Comment by susanodd** [comment]
> @susanodd Is this setting intended as temporary solution to either let users enter a plain search string of a regular expression? As I said in [#1087 (comment)](https://github.com/Signbank/Global-signbank/issues/1087#issuecomment-1814213137) it would be a good thing if each individual user could indicate whether a string should be interpreted as plain search string of regular expression, for instance by clicking a check box or selecting from a drop down.
> 

It can be a permanent setting. I implemented it robustly.

One thing to consider is languages like Chinese, Hebrew, Arabic. Do regular expressions make sense?
I think the setting solves problems when regular expressions are problematic for the installation.

The regular expressions are totally buggy. To debug on a local server, turn the setting to True and the code is as it was.
It does not make sense to give the user a toggle for regular expressions when they don't work at all now.

I am not able to fix them myself. I made a setting for special characters to make them explicit. But Django and Python do not like this at all. My impression is that the "original" use of regular expressions is a subset (restricted syntax) of the actual Sqlite regular expressions. And that this is causing problems.

**Comment by susanodd** [comment]
Unfortunately, the new setting USE_REGULAR_EXPRESSIONS needed to be added to the context variables of ALL views in numerous files!
That has been done.

I'm not running this locally turned on.

@vanlummelhuizen: I removed the dodgy "re.escape" code.

But there are **runtime errors** if there is a malformed regex from the user.

**Comment by susanodd** [comment]
It's kind of working now. The trick to try-escape compile the regular expression works.

**Comment by susanodd** [comment]
@vanlummelhuizen can you have a go on your local server with the setting turned on and see how it performs.

**Comment by susanodd** [comment]
It's possible to turn this on again on the live server. It should be working for the most part. But if you're intent on crashing it, you probably can.

**Comment by uklomp** [comment]
> @susanodd Is this setting intended as temporary solution to either let users enter a plain search string of a regular expression? As I said in [#1087 (comment)](https://github.com/Signbank/Global-signbank/issues/1087#issuecomment-1814213137) it would be a good thing if each individual user could indicate whether a string should be interpreted as plain search string of regular expression, for instance by clicking a check box or selecting from a drop down.
> 
> @uklomp what do you think?

Yes, good idea. Happy to see that this was the outcome (if I understood correctly)

**Comment by susanodd** [comment]
Not exactly there yet.

For one thing, the "type of query" would need to be passed around and more or less be saved with the query search fields.
(This in order to prevent run-time errors.)
At the moment, it's "all queries are regex" or "no queries are regex".

**Comment by Woseseltops** [comment]
I think we have 3 options:
A. Only plaintext search
B. Only regex search
C. Optional regex search

Currently live is A. B would be easy to turn on, but @susanodd indicates it contains various bugs. Before we start listing and fixing them, I think it would be good to have confirmation from someone like @uklomp that regex search is still actively used and worth the time investment.

If we decide to go for B, we could consider going to C. @susanodd indicates that this would be a significant time investment, though, so again it would be good to have an idea what this option would bring. My personal expectation would be that plain text search would never interfere with regex search (if you search for 'ball', you get all glosses with 'ball' in them, whether a regular expression or not), but perhaps there are counter examples?

**Comment by susanodd** [comment]
For the user, the glitch is that if there are special characters, then you need to know to backslash these.

The example `MOVE+5` shows this. The `+` is a regex character, so it won't find this without a backslash.
Otherwise "no matches" in spite of the gloss existing. But the user has no idea this is a special character. There's no mention of what the special characters are in the tooltip.

Likewise if you are searching for things with parentheses in the gloss.
At the moment, those don't work at all. I found examples on stack exchange of expressions where they had to use four backslashes on things because Python also does stuff to the code.
I tried to put the special characters in a setting, but it does not work to put (backslashed) parentheses there as a special character. (Django or Python won't parse it as a string.)

**Comment by susanodd** [comment]
@Woseseltops this code checks for characters in a regex (see the context in the code, it is checked on a well-formed regex.)

https://github.com/Signbank/Global-signbank/blob/2fa094c47c9a042637c25b68be5fcbd73ba1cb15/signbank/dictionary/forms.py#L354

There was an issue with the first character and the last.

But this does not work anymore.

**Comment by susanodd** [comment]
As far as I can tell, the USE_REGULAR_EXPRESSIONS  set to True is working okay now.

Although we still need some information for the tooltip about what the special characters are. Otherwise it remains confusing.
(I was not able to find a clear definition of what they are. For Signbank, this depends on Django, Python, and Sqlite. @Woseseltops where is this defined?)

**Comment by susanodd** [comment]
The setting can be set to True again.

Once on, these need to be checked #714, #938, #1095

**Comment by susanodd** [comment]
The regular expressions have been turned back on via the setting (in the server specific settings file on the server, not that on GitHub.)

**Comment by susanodd** [comment]
This can be closed now as completed.
