### ISSUE TITLE
Explicitly list special characters in regular expression tooltip

### ISSUE THREAD

**Issue by susanodd** [Signbank/Global-signbank#1095]

**Comment by susanodd** [comment]
@Woseseltops said @vanlummelhuizen wrote the text of the tooltip.

**Comment by vanlummelhuizen** [comment]
We could just inform users that Signbank expects a regular expression here. 

(I repeat some thoughts here: because not all users know enough about regular expressions, or even know what they are, we should give users the option to use either regular expressions or plain text.)

**Comment by susanodd** [comment]
> We could just inform users that Signbank expects a regular expression here.
> 
> (I repeat some thoughts here: because not all users know enough about regular expressions, or even know what they are, we should give users the option to use either regular expressions or plain text.)

@Woseseltops pointed out that if it's not a regular expression, it works for a non-regular expression. (i.e., no need to add a tag whether it's a regular expression.)

It's more about making it clear what a regular expression is.
Unfortunately, in repairing code for the Python update (streamline updates to regular expressions), it seems whether a particular character needs a backslash is also context sensitive. (So it just seems arbitrary)

I'll add the text to the error feedback message if the "regular expression" does not compile, that a regular expression is expected because of the special characters. (Again. what are they?)

"The text entered in the search field contains non-alphabetic characters that need to be prefaced with backslashes."

(How to explain this? It's the special characters.)

**Comment by susanodd** [comment]
How to explain this?

```
    # check for matches starting with: + * [ ( ) ?
    # or ending with a +
```

Regular expressions that parse undergo this check. If they fail, the user gets the error message (fail gracefully instead of runtime error that Django thinks it's a function.)

How to explain this in the tooltip? This is Django causing this, not the regular expression.

**Comment by susanodd** [comment]
- The tooltip needs to be translated to Chinese, Hebrew, Arabic.

**Comment by susanodd** [comment]
For regular expressions for Hebrew, here is a link with examples:
https://www.johndcook.com/blog/2020/09/20/unicode-regex/

The expressions rely on `\W`, `\w`, `\b` patterns, plus unicode constants.
