### ISSUE TITLE
Upgrade server virtual environment to Python 3.12

### ISSUE THREAD

**Issue by susanodd** [Signbank/Global-signbank#1098]
This works after some changes to regular expression literal syntax.

I read through the specs and there are lots of updates to support Windows.

@Woseseltops can you install Python 3.12 on lightning, or set it up so the virtual environment uses it? (This works when the minor changes to regex are merged. Branch streamline.)

I bumped Django to 4.2.7 (branch streamline) (which uses Python 3.12). Some minor changes to the `develop.py` imports: separated and at the top.

This might be relevant for the CNGT_scripts (I was getting deprecation warnings in PyCharm and it didn't want to import the scripts):

> [xml.etree.ElementTree](https://docs.python.org/3/library/xml.etree.elementtree.html#module-xml.etree.ElementTree): The module now emits [DeprecationWarning](https://docs.python.org/3/library/exceptions.html#DeprecationWarning) when testing the truth value of an [xml.etree.ElementTree.Element](https://docs.python.org/3/library/xml.etree.elementtree.html#xml.etree.ElementTree.Element). Before, the Python implementation emitted [FutureWarning](https://docs.python.org/3/library/exceptions.html#FutureWarning), and the C implementation emitted nothing.

**Comment by susanodd** [comment]
To upgrade to Django 4.1.12 the `'multiple' ` attribute in the EAF form upload needed to be removed. This is no longer safe.

Now I've gone to Django 4.2 and it works. It looks for the most part to be new features (which we do not use yet).

This is interesting:

> [makemessages](https://docs.djangoproject.com/en/4.2/ref/django-admin/#django-admin-makemessages) command now supports locales with private sub-tags such as nl_NL-x-informal.

**Comment by Woseseltops** [comment]
Note to self, or whoever ends up deploying this: don't manually change the python version in the production environment, but instead:
* Verify the ansible in signbank and signbank-dev are in sync
* Change the python version in dev, test whether it works
* If so, update the ansible playbook in the production container and run it

**Comment by susanodd** [comment]
This is running on the signbank dev now.

**Comment by susanodd** [comment]
One thing the playbook doesn't do is create the necessary folders for glossimage, handshapeimage, eafs, sensevideo
