### ISSUE TITLE
Query, Display, Retrieval of Morphology, Morphemes

### ISSUE THREAD

**Issue by susanodd** [Signbank/Global-signbank#1101]
What is this code supposed to do?

https://github.com/Signbank/Global-signbank/blob/da2a82ddf8bec0f489ad76f998c0dc52fec89fe8/signbank/dictionary/adminviews.py#L2323-L2325

This column of the Morphemes CSV is headed Morphology

But despite filling in all possible information for glosses and morphemes in the test dataset, this column is always empty. Also using different combinations of the code.

What is this supposed to contain?

(Perhaps when morphemes were deleted in the past, some information was never restored. See #127.)

UPDATE: @ocrasborn suspects this was part of a copy paste from a column used for CSV export of glosses. He will look at the morphemes after the holiday season.
I'm working on the display of morphology so it's possible to actually retrieve what's in the database. Some examples are below.

**Comment by susanodd** [comment]
@ocrasborn I am condensing various templates and I came across the code for "compounds" that for some strange reason wasn't displaying anything in the Relations View.
So for glosses that have or are part of compounds (based on what the code seemed to be doing), here is the repaired Relations View for the gloss Book.
Does the nomenclature look okay to you?

![relations-view-ngt-book-with-compounds](https://github.com/Signbank/Global-signbank/assets/24272544/4d5aa8ca-9541-4e1d-8b77-904dd326b293)

**Comment by susanodd** [comment]
I revised the Blends so that they are visible in the Relations View. There are hardly any blends in the database at the moment and it's not possible to query them. (I did this by adding some code to look for them. But that code isn't used anywhere. We probably need to add something to the query form... Need to figure out how to map this to form query fields....)

There is a blend for WEEKEND-A. So the glosses in its blend now show up here in the relations view of gloss ZATERDAG. Does the nomenclature look okay?

![relations-view-blends-zaterdag](https://github.com/Signbank/Global-signbank/assets/24272544/c8daa61a-54f7-49d0-9aba-c11ff7bfe91c)

**Comment by susanodd** [comment]
The above screenshots are live on signbank-dev now.

**Comment by susanodd** [comment]
Here is the other half, Part of a Blend

![part-of-blend-query-view](https://github.com/Signbank/Global-signbank/assets/24272544/87572a3d-86c8-4c4c-b698-3e3c38f8a1a2)

**Comment by susanodd** [comment]
The morphology code described above has been deployed to signbank-dev.

It's possible to view the terminology there and offer suggestions for improvement here.

**Comment by susanodd** [comment]
I found more examples of blends in other datasets and modified the display in the relations view to include the role field.

![kata-kolak-relations-view-ten-B-blends](https://github.com/Signbank/Global-signbank/assets/24272544/e1b6fe17-d684-47cc-9bfe-5c0481c9a3e0)

![csl-shanghai-january-relations-view-blends](https://github.com/Signbank/Global-signbank/assets/24272544/32ed679a-e7df-472d-9042-424556165c57)

**Comment by susanodd** [comment]
Here's some more blends. (That's it.)

![grammar-blends-is-wfd1975](https://github.com/Signbank/Global-signbank/assets/24272544/ec711828-bd3b-4fa8-ad3d-af26b4090787)

**Comment by susanodd** [comment]
This is live on Signbank. Is the query mechanism sufficient?

It seems a bit weird for sequential morphology, since the "role" searched on is Component 1, Component 2, ...
(It has always been this way.)
I can add a Boolean "Has Sequential Morphology" instead.

**Comment by ocrasborn** [comment]
@susanodd Yes, the nomenclature (the use of 'compound' and 'blend' is appropriate.
