### ISSUE TITLE
Change display in list of Available Datasets

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#1111]
Please make two changes in the table of Available Datasets on https://signbank.cls.ru.nl/datasets/available:
1. Only count signs, not also morphemes, for any dataset (column 4): the set of bound morphemes will be a closed set for any language, the count is less interesting here. And adjust the column header accordingly, of course.
2. Add a column after this fourth one counting the number of signs that are 'In Dictionary' (checkmark under panel Publication in the detail view): this way users can see to what extent a dataset is open access.

@uklomp: agree?

**Comment by susanodd** [comment]
This needs to be done on the newest pull from master, @Jetske. The master branch is using the upgraded Python and Django. It can't be deployed on global until @Woseseltops is back next week since the script for the container needs to be upgraded. (Deployment will fail since it needs upgraded Python outside of the container. It can be deployed on signbank-dev though.)

**Comment by susanodd** [comment]
@Jetske you can get the database in the usual spot if yours is older.
One glitch in the upgraded Django is a weird layout problem with the admin section. (There is a darkmode button that seems to need a newer version of bootstrap. I hacked this on my local version to change display to none using the old syntax. Upgrading bootstrap is another issue.)

**Comment by uklomp** [comment]
Yes, agree!

From: ocrasborn ***@***.***>
Sent: woensdag 27 december 2023 10:11
To: Signbank/Global-signbank ***@***.***>
Cc: Ulrika Klomp ***@***.***>; Mention ***@***.***>
Subject: [Signbank/Global-signbank] Change display in list of Available Datasets (Issue #1111)


Please make two changes in the table of Available Datasets on https://signbank.cls.ru.nl/datasets/available:

  1.  Only count signs, not also morphemes, for any dataset (column 4): the set of bound morphemes will be a closed set for any language, the count is less interesting here.
  2.  Add a column after this fourth one counting the number of signs that are 'In Dictionary' (checkmark under panel Publication in the detail view)

@uklomp<https://github.com/uklomp>: agree?

-

**Comment by Jetske** [comment]
@ocrasborn For point 2., do you mean with "number of signs that are 'In Dictionary'" that the new column shows the number of public glosses, just like it already does on that same page if you're logged out?
