### ISSUE TITLE
can't access the lemma

### ISSUE THREAD

**Issue by rosestamp** [Signbank/Global-signbank#1122]
We added a lemma called AT+2. It appears on the lemma list but when I search for it as a gloss, it does not appear. When I find it on the Lemma list (by doing Show all lemmas), it does not let me edit it and it gives an option of UPDATE. When I click on this, it says: Lemma ID Gloss is not unique to that language.
So, how do I edit the sign? I need to add the video and then phonology, etc. 
I am using Google Chrome.

**Comment by susanodd** [comment]
I found this gloss.

![admin-at-plus-2](https://github.com/Signbank/Global-signbank/assets/24272544/91c3c64e-4baf-4fc4-8a3a-f499b6557925)

![isl-at+plus-2](https://github.com/Signbank/Global-signbank/assets/24272544/94046de0-7973-4200-bd47-0c5cbf8d0fce)

**Comment by susanodd** [comment]
To find it, the dataset ISL needs to be selected.
Then the gloss search needs in the English field a backslash: ` AT\+2`
It allows to do Edit. You're right there is no phonology.

**Comment by susanodd** [comment]
@rosestamp are you able to access the lemma as described above?

Can we close the issue as completed?

**Comment by rosestamp** [comment]
with the \ i can find it. thank you!
