### ISSUE TITLE
SignBank down?

### ISSUE THREAD

**Issue by uklomp** [Signbank/Global-signbank#1126]
I can't reach SignBank at the moment, please let me know when it's up and running again. Error: 

Proxy Error
The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request

Reason: DNS lookup failure for: signbank.lxd

**Comment by susanodd** [comment]
The containers are being moved from Twist back to Lightning today.

I'm not sure when they will be done.

**Comment by susanodd** [comment]
It's working again.
