### ISSUE TITLE
Import corpus frequencies about one-handed vs. two-handed articulations of signs

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#113]
- Extension of #55 
- Create three fields in phonology panel, display numbers after Handedness field (to discuss)
- Three types of situations: one-handed, two-handed (min. 75% overlap with gloss with same value for other hand), complex construction (overlap with gloss with other value) (to discuss)

**Comment by vanlummelhuizen** [comment]
@ocrasborn Do we still need to discuss this?

**Comment by ocrasborn** [comment]
Nah, we'll drop this :-)
