### ISSUE TITLE
For the CSV upload, add delimiter detection

### ISSUE THREAD

**Issue by Woseseltops** [Signbank/Global-signbank#1132]
There some unclarity with MS Excel where it doesn't use the delimiter it says it does. Would be nice if there was something in Signbank that said 'You selected delimiter x, but it looks like you are using delimiter y'. 

Idea came out of a conversation with @uklomp

**Comment by susanodd** [comment]
I'm making some progress on this, but it's a bit like down the rabbit hole. There are so many different combinations of input commands. I'm making the code share functions using parameters for the kind of command. Now it's more obvious how confusing the instructions in the help text are!

**Comment by susanodd** [comment]
Delimiter detection is available live on signbank-dev.

**Comment by susanodd** [comment]
The CSV routines on Global Signbank use delimiter detection now. You no longer need to guess-choose.

**Comment by susanodd** [comment]
This is completed.
