### ISSUE TITLE
settings.FILE_UPLOAD_TEMP_DIR

### ISSUE THREAD

**Issue by susanodd** [Signbank/Global-signbank#1142]
This setting is used in the code but is not defined anywhere.

It's referenced inside of some code for Flash videos, class `VideoUploadToFLVField`

- signbank/feedback/models.py:from signbank.video.fields import VideoUploadToFLVField
- signbank/dictionary/forms.py:from signbank.video.fields import VideoUploadToFLVField
- signbank/pages/admin.py:from signbank.video.fields import VideoUploadToFLVField
- signbank/pages/admin.py:    video = VideoUploadToFLVField(label='Video',

The code in Admin ought to be broken since the setting is undefined.
Is this code used in ASL? Is this obsolete?
Anybody remember this code? PyCharm thinks @Woseseltops wrote the code.

**Comment by susanodd** [comment]
This code seems linked to Summernote.

In the admin, there are places where you may fill in contents for pages. This is (only) used for the pages in the About menu. 

The interactive pages all use Python, Django templates, classes, database queries.

**Comment by Woseseltops** [comment]
This has been there since the initial commit. Feel free to remove

**Comment by susanodd** [comment]
Vintage Signbank!

**Comment by susanodd** [comment]
This causes problems with all the video upload routines. This is "internal Django stuff". For some reason it keeps using this setting and gets permission problems or file system problems.

**Comment by susanodd** [comment]
This has been resolved in other more recent issues about videos.
