### ISSUE TITLE
Abstract the CSV row commands into a virtual machine

### ISSUE THREAD

**Issue by susanodd** [Signbank/Global-signbank#1162]
Employ the CSV staging routines (error and consistency checks on input) and the proposed changes (actual commands for updates as displayed in the table) as basis for update commands.
Make use of the underlying syntax used in the form to identify the commands per gloss, rather than inside a loop. Create urls as such. For use in #1158 update interface.
A primary benefit is also to improve readability and maintainability of the (complex and long-winded) CSV routines.

**Comment by susanodd** [comment]
This is going to form the basic structure for the API gloss creation and gloss update.

**Comment by Woseseltops** [comment]
Can this be closed @susanodd ?

**Comment by susanodd** [comment]
Probably. I implemented the Batch Edit using this strategy.
I was planning to employ the little commands (field update urls) also to the CSV.
