### ISSUE TITLE
Panel "video's met non-manuele elementen"

### ISSUE THREAD

**Issue by uklomp** [Signbank/Global-signbank#1169]
We would like a field to add video's with non-manual expressions (see also issue #1168).
In this field, we'd like to be able to add 1-3 video's from left to right, with the possibility to add text underneath. In the text fields under the video's, we want information on the sense of the sign that is visible in the video. We still need to decide if we want this text field to ben an "open text field" or to be a drop-down menu with all the listed senses for that Annotation Glos ID. I will get back to this.

We have something like this in mind (but then, again, as the first field, not as the last field)

![image](https://github.com/Signbank/Global-signbank/assets/147159596/55d088ec-1c59-4354-86c6-c98537f696f2)

**Comment by susanodd** [comment]
Would you prefer the overall layout of the page to be in a single column? This may help create the display as shown above in Signbank.

In the page layout as it is, there are two columns and this impacts what is shown now, also when editing.

Do you need or want additional panels for the Gloss? There is a Video View, but it's not possible to upload in that view.

Do you have a particular naming convention for the different video files?
We use for example, '_small' now with the rest of the name the same. (Those are generated.)

**Comment by uklomp** [comment]
Lets talk about these questions when we talk later today, so there is no confusion on what we mean :)

**Comment by uklomp** [comment]
The field under the videos should be a text field where we can write a translation of the sign.

**Comment by susanodd** [comment]
Any idea how much text will be added? (To make the field type in the database.)

**Comment by uklomp** [comment]
In most cases it will be a single word, sometimes it might be a short phrase. 
It is indeed something that needs to be multilingual. It's actually the case that the Dutch word that is typed should also appear in the Dutch senses, and the English word should appear in the English senses.

**Comment by uklomp** [comment]
But it doesn't need to be linked literally to one of the senses, btw. This is why we chose for a typing field, and not for a drop-down menu with senses. Because a sense can be multiple synonyms, representing a single concept, and we usually want a single word to appear under the video.

**Comment by Jetske** [comment]
@susanodd yes!

**Comment by susanodd** [comment]
@Jetske I did the translations for the entire po file. So make sure to:

(on YOURBRANCH)

git stash
git checkout master
git pull
git checkout YOURBRANCH
git merge master
(optionally git push to sync)
git stash apply

(I get paranoid that code update histories will overlap and the GitHub automatic merging will undo things.)

**Comment by uklomp** [comment]
Is there an update on this? :)

**Comment by susanodd** [comment]
I'm on the last thing for the API now. The Notes.

**Comment by susanodd** [comment]
I've implemented a subclass of gloss video for these videos, with the idea being to suffix the name, as is done for '_small'.

But the method for retrieving the video filename is used for both creation, as well as retrieval. (Overloading.)
This method: `get_video_file_path`
This method also computes the version and number of "bak's" to add to the file name.

The method does not work to use a parameterized type / subclass object and direct control flow based on that.
For some reason, it won't inspect the object instance parameter. (I can code this, but it is just ignored.)
It keeps reverting back to the normal video upload for the gloss and not saving the new video with the proper name.

There are also numerous classes all sharing the same form: `VideoUploadForObjectForm`

**Comment by susanodd** [comment]
> I've implemented a subclass of gloss video for these videos, with the idea being to suffix the name, as is done for '_small'.
> 
> But the already existing method for retrieving the video filename is used for both creation, as well as retrieval. (Overloading.) This method: `get_video_file_path` This method also computes the version and number of "bak's" to add to the file name.
> 
> The method does not work to use a parameterized type / subclass object and direct control flow based on that. For some reason, it won't inspect the object instance parameter. (I can code this, but it is just ignored.) It keeps reverting back to the normal video upload for the gloss and not saving the new video with the proper name.
> 
> There are also numerous classes all sharing the same form: `VideoUploadForObjectForm`

Any preferences about this code I'm complaining about?

I would suggest, separate forms for each different kind of video upload.

Something else instead of the `uploads_to` weirdness in the Django File field.
That method is overloaded and it also conflicts with the `Video` class.

`    videofile = models.FileField("Video file in h264 mp4 format", upload_to=settings.VIDEO_UPLOAD_LOCATION)`

Here, it's a folder.

But elsewhere, it's a call to a method.
But that method is also used for retrieval of the video.

**Comment by uklomp** [comment]
Hi Susan, you're not asking for my preferences, right? Because I don't understand this. If you need my opinion, lets talk about it on a Thursday.

**Comment by susanodd** [comment]
> Hi Susan, you're not asking for my preferences, right? Because I don't understand this. If you need my opinion, lets talk about it on a Thursday.

No, I'm hoping that either @Woseseltops or @Jetske will respond.

I disagree with some of the code that has existed a very long time. But I hesitate to rewrite things that aren't broken.
We're missing @vanlummelhuizen here for the video storage setup.

**Comment by Jetske** [comment]
I believe get_video_file_path is a different method for each type of video so it leads to a different folder. You could make another one for these nonmanual videos (or how do we call them?). And then my approach would be to make a model for nonmanual videos with foreignkey to a Gloss. Then it would for a large part be similar to the annotated videos panel. 

I tried to reuse code in the forms and method addvideo to reduce overlap but agree that the way all different types of videos are processed can probably be improved. 

If you're in the office on Monday we can look at it together!

**Comment by susanodd** [comment]
> I believe get_video_file_path is a different method for each type of video so it leads to a different folder. You could make another one for these nonmanual videos (or how do we call them?). And then my approach would be to make a model for nonmanual videos with foreignkey to a Gloss. Then it would for a large part be similar to the annotated videos panel.
> 
> I tried to reuse code in the forms and method addvideo to reduce overlap but agree that the way all different types of videos are processed can probably be improved.
> 
> If you're in the office on Monday we can look at it together!

Yes, I implemented a new model for the NME videos, but I made it be a subclass of GlossVideo.
But the get_video_file_path method only partly works. I put print statements before it is called, and inside the method, and confirm that the correct file name is being created. But the actual creation does not use this file path at all. It keeps using the original video name. So it ignores the type of the instance. I think it's somehow a lazy function with already bound parameters (a closure) and it won't let the code override it.

I was hoping to just store them in the same table in the database.
I think the FileField declaration that refers to that method is somehow embedding the path and not allowing a subclass.

Yes, let's look at it on Monday!

**Comment by susanodd** [comment]
@uklomp do you need to be able to re-order the sequence of NME videos?

**Comment by susanodd** [comment]
This is working now. It needs a few tweaks in the Edit mode.

The video names are similar to the gloss videos, as discussed once upon a time in the video chat.

As is done for the small videos, where '`_small`' is used, the NME videos have the suffix '`_nme_N`' where the user specifies N, which is the order in which they are displayed. The N can be updated by the user.

**Comment by susanodd** [comment]
This is on signbank-dev

**Comment by Jetske** [comment]
@susanodd that's part of the reason why I made a new page for annotated video uploads/edits. It makes drag and drop easier. 

dropVideoArea and inputVideoArea are used inside the functions so then the functions would need to be changed or duplicated to work for the new identifiers.

**Comment by susanodd** [comment]
This is on signbank now.
