### ISSUE TITLE
Cannot search for 'Creator'

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#1170]
Whatever I type in this field (like my own name, or a reg expr), nothing is returned. Is the lookup function for user names perhaps broken?

**Comment by susanodd** [comment]
@ocrasborn can you try it out on this page?

https://signbank-susan.cls.ru.nl/analysis/toggle_view/

I know it works there. I fixed a bug in the creator search there.
(It's on a separate branch.)

**Comment by susanodd** [comment]
@ocrasborn this is live now on Signbank !!

I tested the search on created by onno, this gloss is awesome!

https://signbank.cls.ru.nl/dictionary/gloss/41908/

**Comment by susanodd** [comment]
This is completed.
