### ISSUE TITLE
Dataset Media Manager View

### ISSUE THREAD

**Issue by susanodd** [Signbank/Global-signbank#1172]
Includes json compatible methods for uploading videos via the API interface

The new view allows a dataset manager to:

- Upload a zipped video files archive to the `import_videos` location.
- See the list of videos that have been unzipped.
- Import those videos to the various glosses.

**Comment by susanodd** [comment]
Yes, the above is the goal. This is still a work in progress.
The json urls will be available when the rest is bug-free.

**Comment by susanodd** [comment]
Here are before and after screenshots after uploading a zip file, with the unzipped files stored in the import_videos folder.

![dataset-media-manager-1](https://github.com/Signbank/Global-signbank/assets/24272544/08cfce15-3d58-4f21-88a3-ea9977a54d4a)

![dataset-media-manager-2](https://github.com/Signbank/Global-signbank/assets/24272544/6a4e374c-9fd5-4b14-8842-a3e9be695e36)

**Comment by susanodd** [comment]
A command already exists for putting those videos into the glosses.
That's going to be integrated into this.
Then the respective commands also offered in the api.

**Comment by susanodd** [comment]
I forgot the hash in this commit:

https://github.com/Signbank/Global-signbank/pull/1173/commits/4d31ae5fa0aef53c95abb68f2ee6a3315b1d9644

**Comment by susanodd** [comment]
The  interface looks like this now, with the pathnames of the uploaded, unzipped video files.
They are stored in the location for importing videos.
They follow the subfolder structure required in the zip file the manager uploads (the api functions mimic this #1152)

![dataset_media_view_uploaded_files](https://github.com/Signbank/Global-signbank/assets/24272544/3c67e987-74f8-4b4c-90b2-450b9d2c652a)

**Comment by susanodd** [comment]
I wondering to what extent it is useful to provide functionality here?

I made it have a hover over the individual file names.

The existing functionality for importing videos (going to be revised and put here), does a batch import over the files shown here.

@uklomp @rem0g would you like to be able to do things at the individual file level?

Like some check boxes at the side?

And what about the api? Is a batch command for importing them sufficient?

This will appear on the signbank-dev when it is ready, then it's possible to try out different things without messing up the real signbank.

**Comment by susanodd** [comment]
Okay, that's clear. Most of the templates use txt response. (They all started out in Django 1.11.)
I've been using the JsonResponse in the more recent code, and gradually updating things.
The JsonResponse is a Django class. Do you need additional things in it?
Our templates that use it fetch the things out of the json.
I added an "errors" field in the upload zip archive one.
If you get a failed result then that is Django doing that. (Like using an alphabetic field instead of a numeric.)
Django also handles the csrf tokens. (We don't generate those.) It also inspects the request.user. But we add additional permissions checks. We can't make some of the things "open" so a login is required.)
I guess if I modify the DatasetMedia template to use the same json methods, then you'd be able to use the same.
Luckily if the template interface is designed well, Django give you some things for free in updating the visible data.

I'll find out about adding your server to the trusted ip's. I know I can just modify stuff in the settings (they are different on the actual server than the ones in GitHub), but we only do the "containers" and that the container is accessible isn't done by us. I thought @Woseseltops could do that but he can't. So I'm not sure if they would just take down the container if it started doing extra stuff. I know they can't modify anything outside of the container.

**Comment by susanodd** [comment]
Oh yes, if you get some weird errors that the url isn't found, it could be that the url isn't specified that something is a "digit" pattern. I only encountered this yesterday when testing out the urls. They worked on Ubuntu at the uni, but they didn't work on PyCharm running the local server in iCloud. Django complained the url didn't exist.
I'll check the various urls to make sure the digit pattern is used.

**Comment by susanodd** [comment]
@rem0g do you have any need to "keep" the zip files archived on signbank? (Like maintain an archive of uploaded zip files so you can see them stored there.)

**Comment by susanodd** [comment]
Here's with showing the zip files and they contents, in the case there are already uploaded zip archives.

![dataset-media-zip-archives](https://github.com/Signbank/Global-signbank/assets/24272544/1f1f3f07-9478-4de2-a461-c891f333700e)

**Comment by rem0g** [comment]
> @rem0g do you have any need to "keep" the zip files archived on signbank? (Like maintain an archive of uploaded zip files so you can see them stored there.)

No not required.

**Comment by susanodd** [comment]
I added some visual information about the zip file contents and the uploaded files (that are staged for processing)

![manage_media_tstMH](https://github.com/Signbank/Global-signbank/assets/24272544/3b5ef25c-ef59-4f4f-907b-7b26cabbace9)

![manage_media_status_jmported](https://github.com/Signbank/Global-signbank/assets/24272544/efd6e21f-5a2d-499c-a1c0-057311838430)

**Comment by susanodd** [comment]
The same kind of information will be added to the data returned by the json upload zip archive. Probably as a dictionary showing the uploaded files and the ignored files.
I'm not yet sure the best way to convey the "success" of uploading an archive.
Above, the files that are not mp4 are ignored from the zip contents.
And on inspecting the "files in the import_videos" folder, then whether or not a matching gloss was found.
The import is several steps that depend on each other.

On my local computer, I have lots of "bogus" or "wrong" stuff that has been put in the import_videos folder during debugging. Also in the past. Probably the timestamp of the file is also useful.
(To be able to figure out and allow the dataset manager to remove stuff. Or a command to clear the folder.)

**Comment by susanodd** [comment]
So far, I think it needs to be several steps.
1. uploading and unzipping the videos to the import_videos folder of the dataset.
2. Import the properly formatted videos to the glosses assuming they exist.
For both parts, it kind of needs to be atomic. Well, for the second, it can be per gloss, assuming the files that have not been processed yet remain there.

**Comment by susanodd** [comment]
Here's another screenshot of NGT. Here you can see actually none of the files in the zip file have corresponding glosses.
Plus there are a bunch of "old" files in the import location that weren't inside the zip.


![media-import-ngt-showing-status](https://github.com/Signbank/Global-signbank/assets/24272544/5782f44b-7888-4943-a3be-b9928d2d7af1)

**Comment by susanodd** [comment]
I'll add the timestamp to the information. Otherwise it's too confusing if there is old stuff.

**Comment by rem0g** [comment]
> For both parts, it kind of needs to be atomic. For the second, it can be atomic per gloss, assuming the files that have not been processed yet remain there.
For an api interface, this is a bit trickier since the api should not execute extremely long transactions on the database.
Thus for the second, it can be some kind of loop in the background, that the api initiates an import on the import_videos staged videos. Then somehow get notice when it has been completed.

We just can handle one video per transaction via JSON API, so its best to have a limit of videos per API request at your side. 

Callback on that same transaction is important so its best to work with for loop in one large request and then for every item send back callback to user interface and API via JSON. Otherwise the browser and API at the other side will assume the upload failed after x seconds of timeout.

**Comment by susanodd** [comment]
@rem0g what about using jsonlines so that a json file containing all the uploaded videos per gloss can be streamed?

This would work, similar to how csv files are generated. (Because this also takes time, because there are thousands of lines, we already do this.)

Then you'd get a json (json lines) file as a result.

**Comment by rem0g** [comment]
How can it be streamed?

**Comment by susanodd** [comment]
It's a Django class StreamingHttpResponse. I guess for the end user it's not streamed, but it makes it so the results can be fed into the result file over time. Before we used this, the file object would time out before being completed because it took so much time to generate the result.
So on your end it would just be waiting for the file to be available. As it is for the zip file being generated by the package url.

**Comment by susanodd** [comment]
I'm going to try and see if this works with each json object row being the result of an atomic operation to save the gloss video, so that saving each videos is completed as a transaction. Then it will just write the results to a json file.

**Comment by susanodd** [comment]
In the above, for the actual "import", a link to the gloss video will be included, too.
(It makes coding a mess because I can't keep running the same example once it completes.)

**Comment by susanodd** [comment]
Here's for the tstMH dataset, with videos as shown above:

{
  "import_videos_status": [
    {
      "import_videos/tstMH/nld/GEVEN-E-3689.mp4": {
        "errors": "Gloss not found for GEVEN-E-3689"
      }
    },
    {
      "import_videos/tstMH/nld/GEVEN-E.mp4": {
        "errors": "Gloss not found for GEVEN-E"
      }
    },
    {
      "import_videos/tstMH/nld/STOMP-B.mp4": {
        "gloss": "42090",
        "videfile": "STOMP-B.mp4",
        "Video": "http://localhost:8000//dictionary/protected_media/glossvideo/tstMH/ST/STOMP-42090.mp4",
        "status": "Success",
        "errors": ""
      }
    },
    {
      "import_videos/tstMH/nld/comments_ZIEK-B-529.mp4": {
        "errors": "Gloss not found for comments_ZIEK-B-529"
      }
    },
    {
      "import_videos/tstMH/nld/POMPOEN-A.mp4": {
        "gloss": "42087",
        "videfile": "POMPOEN-A.mp4",
        "Video": "http://localhost:8000//dictionary/protected_media/glossvideo/tstMH/PO/POMPOEN-42087_o1pOkHU.mp4",
        "status": "Success (Video File Overwritten)",
        "errors": ""
      }
    }
  ]
}

**Comment by susanodd** [comment]
Unfortunately for that last one, the "backup" video system is interfering with this. The suffix `_o1pOkHU` on the filename of the "Video" link should not be there. (It's referring to a backup video.)
@Jetske is working on this in #1129

**Comment by susanodd** [comment]
It's the add_video method that is doing that.
I noticed there is an if-else clause and the if clause does stuff with GlossVideo versions, and the else clause (for if it's not an in memory stored), just ignores this. So I'll try to fix that for the second case, since it's already a real file.

This is the if test (so it goes wrong when that is false):

`        if isinstance(videofile, File) or videofile.content_type == 'django.core.files.uploadedfile.InMemoryUploadedFile':
`

**Comment by Jetske** [comment]
When it fails that if test, it doesn't save the video though. So then in that case it shouldn't create a file with the suffix either

**Comment by susanodd** [comment]
I could disallow to overwrite an existing file. Then to figure out how to get the versioning to work.
Those Django File objects are annoying because the path is inside them.

**Comment by susanodd** [comment]
UPLOADED UNZIPPED ZIP ARCHIVE READY TO IMPORT

![display-videos-to-import-archive-before-import](https://github.com/Signbank/Global-signbank/assets/24272544/30d5bd91-0125-4311-b911-763a501d9741)

AFTER IMPORT LISTING

![imported-videos-listing-after-import](https://github.com/Signbank/Global-signbank/assets/24272544/f6ebd274-43c1-412c-9a89-aaabfa9d42fc)

**Comment by Woseseltops** [comment]
Just tried uploading @ocrasborn's  zip, as requested by @susanodd . If I make it a flat folder (so the videos are on the highest level directly), I get a nice red bar telling me the structure is incorrect (but not what it should be, would be an improvement I think). If I make it so the videos are inside a folder called NGT, I get

![image](https://github.com/Signbank/Global-signbank/assets/1909317/adbd52fc-0b92-47da-9369-71b17d129271)

Is the zip still incorrect? Let me know

**Comment by Woseseltops** [comment]
* Okay with that filestructure uploading works! Please put this example in the error message and everything should be fine :).
* I do note that the videos do not show after it marks an import as successful... but perhaps that's related to settings on `signbank-dev` ?

**Comment by susanodd** [comment]
Did you do the Import button?

> * Okay with that filestructure uploading works! Please put this example in the error message and everything should be fine :).
> 
>     * I do note that the videos do not show after it marks an import as successful... but perhaps that's related to settings on `signbank-dev` ?

@Woseseltops did it show anything?
I looked at the Media Manager page again, because it keeps the zip files there.
I checked two of the glosses. Gloss 24.B has a video now. But Gloss 32 did not import because that's a Lemma translation, not a Gloss annotation. (It needs the annotation text, not the lemma to identify the gloss.)

I checked some of the videos, whether they exist:


![imported-videos-NGT-BE](https://github.com/Signbank/Global-signbank/assets/24272544/1b49d6a4-0883-45ce-aadb-1fdb40daef21)

I'll check to see what it's doing. In the Zip upload section, it hasn't yet checked whether the gloss exists.
In the "import/videos/NGT" part it has the Status and shows there if it didn't find the gloss. (With a red X.)

I revised the error reporting on the zip file structure. That's on signbank-dev now.

**Comment by susanodd** [comment]
It could be that the video has not completed yet on the file system?

I'll modify the Search form on Gloss List so if you search on Has Video, it checks that the file exists also.
(It should do that anyway.)

**Comment by susanodd** [comment]
@Woseseltops I modified the Search so that when you search on "Has Video" it checks that the gloss also has a video file.

This helps on signbank-dev since you can see the videos you just imported.

The Search used to only look in GlossVideo, so all the "missing videos not on signbank-dev" ended up showing up in the search.
Now it's easier to debug the code since missing video files are not shown as Has Video results.

**Comment by susanodd** [comment]
The code still finds really old videos (locally, at least) where the video file exists but there was never an entry in GlossVideo.
I suspect there are some really old glosses on signbank where this is true.
Also, if the citation image is missing, but there is a video, it looks empty in the results. But you can create a citation image from the video.

(Should this kind of information be added somewhere? It's like "quirks" about video files.)

**Comment by susanodd** [comment]
This is on signbank now.

**Comment by susanodd** [comment]
This is live on all signbanks.

**Comment by ocrasborn** [comment]
@susanodd , great that this is possible now! I would suggest also adding a button on the Dataset Management page, which to me sounds like a bit more natural a location -- it's related to managing the dataset, after all. Same for the 'Corpus Overview' button, really. @uklomp , what do you think?

**Comment by susanodd** [comment]
I agree, actually. But we're missing @vanlummelhuizen a bit here with the Dataset Management page. I first tried to add the buttons there, without success. 
(The buttons need to be caught by the python View code. There are zillions of permissions checks on this page!!!! I was not able to add the buttons in a way to display them to look nice. Probably we need to introduce panels or some other layout here.)

**Comment by uklomp** [comment]
I guess this is finished?

**Comment by susanodd** [comment]
I didn't implement the request from @ocrasborn yet about the video tags.
