### ISSUE TITLE
Fix external reference in the ECV

### ISSUE THREAD

**Issue by Woseseltops** [Signbank/Global-signbank#1176]
As requested by ELAN-dev Divya Kanekal, the ECV currently returns this:

```xml
<CV_ENTRY_ML CVE_ID="42492" EXT_REF="signbank-ecv">
<CVE_VALUE DESCRIPTION="2s, (5_klauw,5_klauw; Sluiten + wiebelen), -, -, -, - [14/4], quotes, aanhalingstekens" LANG_REF="nld">AANHALINGSTEKENS</CVE_VALUE>
<CVE_VALUE DESCRIPTION="2s, (5_claw,5_claw; Closing + wiggling), -, -, -, - [14/4], quotes, aanhalingstekens" LANG_REF="eng">QUOTATION</CVE_VALUE>
</CV_ENTRY_ML>

<EXTERNAL_REF EXT_REF_ID="signbank-ecv" TYPE="resource_url" VALUE="https://signbank.cls.ru.nl//dictionary/gloss/"/>
```

while it used to used to work something like this:

```xml
<CV_ENTRY_ML CVE_ID="42492" EXT_REF=“Identifier1”>
<CVE_VALUE DESCRIPTION="2s, (5_klauw,5_klauw; Sluiten + wiebelen), -, -, -, - [14/4], quotes, aanhalingstekens" LANG_REF="nld">AANHALINGSTEKENS</CVE_VALUE>
<CVE_VALUE DESCRIPTION="2s, (5_claw,5_claw; Closing + wiggling), -, -, -, - [14/4], quotes, aanhalingstekens" LANG_REF="eng">QUOTATION</CVE_VALUE>
</CV_ENTRY_ML>

<CV_ENTRY_ML CVE_ID="42493" EXT_REF=“Identifier2”>
<CVE_VALUE DESCRIPTION=“3s, (5_klauw,5_klauw; Sluiten + wiebelen), -, -, -, - [14/4], quotes, aanhalingstekens" LANG_REF="nld">SOMEVALUE</CVE_VALUE>
<CVE_VALUE DESCRIPTION=“3s, (5_claw,5_claw; Closing + wiggling), -, -, -, - [14/4], quotes, aanhalingstekens" LANG_REF="eng">OTHERVALUE</CVE_VALUE>
</CV_ENTRY_ML>

<EXTERNAL_REF EXT_REF_ID="Identifier1" TYPE="resource_url" VALUE="https://signbank.cls.ru.nl//dictionary/gloss/42492"/>
<EXTERNAL_REF EXT_REF_ID="Identifier2” TYPE="resource_url" VALUE="https://signbank.cls.ru.nl//dictionary/gloss/42493”/>
```

Can we return it to that second state?

**Comment by susanodd** [comment]
@Woseseltops I looked at the history of this file in the code and the last time it was changed was 6 years ago.

**Comment by susanodd** [comment]
It's in this commit:

2e02f7687b6b3cf05ab922101ce5dcd30bb79793

It looks like maybe an external file is missing?

**Comment by Jetske** [comment]
EXT_REF was first added here: https://github.com/vanlummelhuizen/ASL-ELAN/issues/9 and it looks like it has been set to "signbank-ecv" ever since.

So I'm not sure what else to change it to such that it works again with ELAN.

**Comment by dkanekal** [comment]
I discussed the issue and the comments with my colleague Han Sloetjes  and we think,
If the EXT_REF_ID is set to "signbank-ecv" ever since it was implemented, then you can leave it like that and we will make the changes in ELAN to make the “Show in browser” work by appending the CVE_ID to the external reference value.
From ELAN perspective it will not be generic but “Show in browser” will function for the elan + sign bank users.

**Comment by Woseseltops** [comment]
Hey @dkanekal , to be sure, my colleagues are not saying they don't like your proposal... just that it doesn't seem to have worked differently before. @Jetske and @susanodd , are there any arguments against the proposed XML?

**Comment by dkanekal** [comment]
@Woseseltops absolutely, Thank you. 

@Jetske 
Considering identifier names it doesn't matter to ELAN as long as it matches the xml schema (EXT_REF_ID type is type="xsd:ID").  Reading point of view , maybe it would be easier if the names are glossID along with some prefix.
For example 
```
<CV_ENTRY_ML CVE_ID="42492" EXT_REF=“er42492”>
<CVE_VALUE DESCRIPTION="2s, (5_klauw,5_klauw; Sluiten + wiebelen), -, -, -, - [14/4], quotes, aanhalingstekens" LANG_REF="nld">AANHALINGSTEKENS</CVE_VALUE>
<CVE_VALUE DESCRIPTION="2s, (5_claw,5_claw; Closing + wiggling), -, -, -, - [14/4], quotes, aanhalingstekens" LANG_REF="eng">QUOTATION</CVE_VALUE>
</CV_ENTRY_ML>

<EXTERNAL_REF EXT_REF_ID="er42492" TYPE="resource_url" VALUE="https://signbank.cls.ru.nl//dictionary/gloss/42492"/>
```



Where 42492 = CVE_ID and "er" = external reference.
It can be anything else as well. :) 

and its value expected as a complete url as shown in above proposals.
 ie  VALUE="https://signbank.cls.ru.nl//dictionary/gloss/42492" 

Once the proposed xml is implemented, we can maybe test it in ELAN as either a test ecv file or with the dev ecv urls before moving to your prod environment?

**Comment by susanodd** [comment]
I vaguely remember the existence of an external "exported glosses" file being linked to the ELAN. Is it possible something used to exist? (There was some step that an ecv needed to be exported and used together with the xml?) I wish @vanlummelhuizen would respond.

**Comment by susanodd** [comment]
@Woseseltops did `NGT.ecv` used to be called `signbank.ecv` ? (Before there were datasets.)

**Comment by susanodd** [comment]
There's a file called `eafGlossChanger.py` in the CNGT_scripts with links to the science url.
(I'm looking through old code, trying to find references.) It looks like that may do something similar to this issue. It looks for an ecv file.

We have so much try-except code, sometimes the errors are hard to find because it doesn't report anything to the end user if it doesn't crash.

**Comment by susanodd** [comment]
My opinion is that some of the CNGT scripts code ought to be included in signbank. Like the video routines that are broken, so we can fix them.

**Comment by Jetske** [comment]
@dkanekal sorry for the delay. 

Here are two examples:
```
<CV_ENTRY_ML CVE_ID="2599" EXT_REF="er2599">
    <CVE_VALUE DESCRIPTION="2s, (V,V; Krommen), Variabel, -, -, - [178/28], aanhalingstekens, een soort van, haakjes, tussen haakjes, zogenaamd, zogezegd, zoiets, zeg maar" LANG_REF="nld">AANHALINGSTEKENS</CVE_VALUE>
    <CVE_VALUE DESCRIPTION="2s, (V,V; Curving), Variable, -, -, - [178/28], " LANG_REF="eng">QUOTATION-MARKS</CVE_VALUE>
</CV_ENTRY_ML>
<EXTERNAL_REF EXT_REF_ID="er2599" TYPE="resource_url" VALUE="127.0.0.1:8000//dictionary/gloss/2599"/>

<CV_ENTRY_ML CVE_ID="44087" EXT_REF="er44087">
    <CVE_VALUE DESCRIPTION="2s, (Snavel2_open,Snavel2_open; -), Neutrale ruimte, -, -, - [ / ], aanhalingstekens, een soort van, haakjes, tussen haakjes, zogenaamd, zogezegd, zoiets, zeg maar" LANG_REF="nld">AANHALINGSTEKENS-B</CVE_VALUE>
    <CVE_VALUE DESCRIPTION="2s, (Beak2_open,Beak2_open; -), Neutral space, -, -, - [ / ], " LANG_REF="eng">QUOTATION-MARKS-B</CVE_VALUE>
</CV_ENTRY_ML>
<EXTERNAL_REF EXT_REF_ID="er44087" TYPE="resource_url" VALUE="127.0.0.1:8000//dictionary/gloss/44087"/>
```

If this looks ok, I can send you a new ecv file to test. Would that work?

**Comment by Jetske** [comment]
@dkanekal The newest ecv can be downloaded from
https://signbank.cls.ru.nl/dictionary/protected_media/ect/ngt.ecv

Do you have access to this page: https://signbank.cls.ru.nl/datasets/available ? From there, you can update the ecv (in case glosses have been added/changed/deleted) by clicking the button for the dataset, and then download it again

**Comment by dkanekal** [comment]
Hi @Jetske ,  I tested the linked ngt.ecv file in ELAN and I am able to open the gloss IDs directly from ELAN. It works. 
Thank you very much.

**Comment by Jetske** [comment]
Great! Then I'll close the issue
