### ISSUE TITLE
Panel "Voorbeeldzinnen"

### ISSUE THREAD

**Issue by uklomp** [Signbank/Global-signbank#1178]
We would like a panel to show example sentences (as discussed with @Woseseltops and @Jetske). (see also issue #1168 for the location of the panel).

The title of the panel should be "Voorbeeldzinnen" / Example sentences. 
We want to be able to upload a video of a sentence in this panel. The sentence will exemplify the use of a sign. There should also be a possibility to upload a linked ELAN file, because we want to show a gloss-by-gloss translation of the video in the sentence. And there should be Dutch translation underneath as well. Something like this: 

![image](https://github.com/Signbank/Global-signbank/assets/147159596/04d3723f-527c-44ed-b2d7-2af53f3edafa)

Additionally, we would like the gloss in the gloss-by-gloss translation to light up / change colour when this specific sign is shown, something like this: 

![image](https://github.com/Signbank/Global-signbank/assets/147159596/7263707c-cf46-4eb9-98c5-5f5e32b0a630)

Last but not least, it would be good if the sentences are able to appear for every gloss that they include - BUT for some glosses, this will automatically lead to many connected sentences and some of them may be good examples for this specific gloss but others might not. Wessel & Jetske and me therefore thought of a functionality to be able to categorize an example sentence as 'representative yes/no' for a specific gloss. If yes, it will appear in the top three or so. If not, it is shown as a written option in the panel of that specific gloss, but not immediately shown as a video. Or something like that. Up for discussion.

**Comment by Jetske** [comment]
Models:
![IMG_20240305_165851732~2](https://github.com/Signbank/Global-signbank/assets/10157482/415938f5-88b4-4704-b0da-34295dd07355)

**Comment by Woseseltops** [comment]
About the upload panel:
* The connection between videos and the glosses in that video will be made with the eaf file, right? Not sure if it makes sense to have the upload panel on the detail page of an individual gloss then?
* How would setting `isRepresentative` work? Perhaps, after uploading, it shows the end result with the highlighted glosses already, with an extra row/box to uncheck glosses that are not representative?

**Comment by Jetske** [comment]
Discussed with @uklomp :
The input will be a video of a sentence, with two tiers that should be read from the eaf file: 'Glosses' and "Sentence". The glosses are read as they are currently. The sentence is added to a textfield (only Dutch for now) that can be edited during upload. Another textfield is added to fill in 'context'. This is shown underneath the video just before the sentence translation.

**Comment by susanodd** [comment]
I think @Woseseltops meant to ask whether  it necessary to have the upload on the Gloss Detail page?

There is kind of way too much code on Gloss Detail View.

**Comment by Jetske** [comment]
@uklomp 
Update: uploading works, but I need to add functionality to edit & delete the sentences and then do some more testing.

Because only 3 videos are shown, I think we need to have an option to manage all example sentences. We could make something like a 'manage example sentences' page. Or we can show all example sentences found for a gloss in the 'video' tab of a gloss page. Let me know if you have ideas about that. 

This is what it looks like to far.

Upload page:
The glosses and one Dutch sentence are added from the eaf file. The gloss for which the sentence is created (see button in next image) is automatically checked to be representative (if found). This can all be edited.  
![image](https://github.com/Signbank/Global-signbank/assets/10157482/2769f107-e023-46ef-abb4-8f96bd29984f)

Panel (1 example but can show up to 3 videos)
![image](https://github.com/Signbank/Global-signbank/assets/10157482/2fc9cc2b-05b3-4a9e-83da-89d308f0cca8)

**Comment by uklomp** [comment]
Great!! I like it a lot.

>> "Because only 3 videos are shown, I think we need to have an option to manage all example sentences. We could make something like a 'manage example sentences' page. Or we can show all example sentences found for a gloss in the 'video' tab of a gloss page. Let me know if you have ideas about that." 

I need to think about this a bit more, but I think something like 'manage example sentences page' would be good, with maybe a list of the sentences (with their translations) as possible options. The other option, to list all the videos that are found for a gloss, would potentially mean hundreds of videos for a very frequent gloss and I think that wouldn't benefit the processing of the site?

**Comment by Jetske** [comment]
@uklomp I've made it so that you can edit the texts for the sentence and context given below the video. That means that if you want to edit the actual video/annotations you'd need to make the edits in the eaf file and create a new 'sentence'. Would that be sufficient?

**Comment by uklomp** [comment]
Yes, that is sufficient! It's maybe not the neatest solution for research/annotations in general but the easiest and most efficient solution for putting the example sentences online. So I agree.
