### ISSUE TITLE
Move phonology fields

### ISSUE THREAD

**Issue by uklomp** [Signbank/Global-signbank#1179]
We'd like a new order of the fields within the phonology panel. The fields

Relative orientation: movement
Relative orientation: location
Orientation change

Are now under "Location", but should go under "Movement direction"

**Comment by susanodd** [comment]
Okay, that's really easy. The fields are listed in the Settings file in the order they appear.

**Comment by uklomp** [comment]
Right, I see. Thanks. I forgot about another move, sorry. Could you move 'Repeated movement' and 'Alternating movement' up, to appear underneath 'Movement Direction'?

**Comment by susanodd** [comment]
Sure.

**Comment by uklomp** [comment]
Yes, like the list you made here.

**Comment by susanodd** [comment]
This is live on signbank now!

**Comment by uklomp** [comment]
Thank you!
