### ISSUE TITLE
Save and display search history

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#118]
- Allow the user to browse his past searches, in principle an unlimited list.
- See the screen shot of the Asian Signbank (Hong Kong) for how they display it: rather useful, I find: users can re-run previous searches (updating the no. of results), and combine previous searches.
- Missing, please add: The date the search was last executed.
- List searches by last-used-date, most recent one at the top.

![Uploading Screenshot 2016-01-17 14.18.33.png…]()

**Comment by henrinie** [comment]
In FinSL we are saving the latest search results for every user (in users session), and then we show those results as an inline list on the gloss page. User can then browse the search results without having to leave the gloss_detail page.

Do you want to save the search results or the search terms?

**Comment by vanlummelhuizen** [comment]
@ocrasborn Is this still or your wishlist?

**Comment by ocrasborn** [comment]
Yes, I would still like to see this; not sure about the priority though.
@henrinie : I would prefer to save the search terms, so that it can be run again over either updated data or another selection of datasets.

**Comment by susanodd** [comment]
Here's what it looks like now. I added a Save button to the Query View, and another panel showing the Search History.
In this example the last query in the list is the one saved.

This needs some basic user functionality, to remove queries, and to modify the name. (At the moment that can be done in the admin.)

I experimented with different displays for the parameters of each query. This is the most concise as a string. I'll make a View button where the user can examine a saved query.

![query-view-save-button](https://user-images.githubusercontent.com/24272544/217548943-b4d11305-d5a0-4b5d-b950-da8ffc77deb7.png)

![search_history_last_shown](https://user-images.githubusercontent.com/24272544/217548979-6341f003-7ece-4456-b858-4e2a1e5ad648.png)

**Comment by susanodd** [comment]
Here's with the boolean parameters added, queries most recent first.

![query-view-boolean-parameters](https://user-images.githubusercontent.com/24272544/217813454-8107ce05-267b-44bc-9ca9-1d74e2f64796.png)

![search-history-boolean-parameters](https://user-images.githubusercontent.com/24272544/217813487-b590c89a-0861-46db-bc7d-3d999de11fe4.png)

**Comment by susanodd** [comment]
I added some buttons to the search history view.
Here's an example showing editing the query name of a new query, and that it gets updated in the list outside of the modal

![query-view-save-query-multiselect](https://user-images.githubusercontent.com/24272544/218112170-06b6fad1-41fe-4cca-8769-b1bc12cf58b3.png)

![search-history-showing-new-query](https://user-images.githubusercontent.com/24272544/218112200-ce167423-551d-420a-8010-6cbf7b25f254.png)

![search-history-updating-query-description](https://user-images.githubusercontent.com/24272544/218112234-13ad5604-67eb-4825-955d-7a4ff438fd3e.png)

**Comment by susanodd** [comment]
Clicking on Run for that query redirects to the Gloss Search page. The results are shown (again) and the query parameters are in in the search form.

![run-query-in-search-history-fills-parameters-search-form](https://user-images.githubusercontent.com/24272544/218113119-ab6cb753-4838-440d-b7e4-4f865b42af91.png)

**Comment by susanodd** [comment]
I added the language-based search parameters to the history. (Annotation, Lemma, Keywords)
Screenshots showing the Query View, the Search History (newest on top), and the opened Search Form after running the saved query, showing the fields filled in

![query-view-language-parameters](https://user-images.githubusercontent.com/24272544/218452729-1cf1c1e1-cde8-4871-85f2-44d6e906f862.png)

![search-history-language-parameters](https://user-images.githubusercontent.com/24272544/218452757-e953caba-bff9-43e7-9727-1071b6c7584e.png)

![search-history-after-run-search-form](https://user-images.githubusercontent.com/24272544/218452776-b1288e27-a099-4a9f-9925-c92ceb0c5a71.png)

**Comment by susanodd** [comment]
The language fields are those where the user can enter search text for specific languages for the selected datasets.
(as shown in the screenshot).

@ocrasborn what would be the preferred behaviour if a stored query is run, which has language fields, but the languages don't appear in the current selected datasets (at time of running a stored query)?

At the moment, the selected datasets at the time of querying are not stored.

If the datasets were stored and used, it would have the peculiar side-effect on changing the selected datasets.

The simplest would be to just ignore irrelevant languages. But that might defeat the purpose. I suppose the Run button could somehow check whether the selected datasets have the required languages.

As the search history is now, they are stored and viewed for the user.
But in practice, they could be shared. (To be added later.)

**Comment by susanodd** [comment]
Here's another example. I added a Languages column to the search history table. And this shows an error message when a query is run on missing languages.

![search_history_showing_languages_feedback](https://user-images.githubusercontent.com/24272544/218497520-c7f78bae-b6de-4bc9-838c-3585a892ece2.png)

**Comment by susanodd** [comment]
Here the Run / Submit Query button is hidden if the languages queries upon are not present in the selected datasets.

![search-history-hidden-button-if-languages-not-in-datasets](https://user-images.githubusercontent.com/24272544/218712301-f53d28b3-87d8-488b-9c13-b58b6c3d0a45.png)

**Comment by ocrasborn** [comment]
Looks great @susanodd , very useful for many people
About the languages and datasets: just having the languages displayed in the column like you have now would give the user sufficient control, I think. Most users won't have more than 2-3 datasets at their disposal anyway, so it will quickly clear whether a query was applicable to the dataset(s) they've currently selected. (So, no need to make this more complex by linking queries explicitly to datasets, I'd say.)

**Comment by susanodd** [comment]
This code is in a pull request and awaiting review.

**Comment by susanodd** [comment]
This is live now. The (user's own) search history is viewable via the Query View (under Analysis).
New queries can be saved in the Query View. There is a panel there to switch between Query View and Search History.

**Comment by ocrasborn** [comment]
Hi @susanodd , now I’m testing this out, I find that the Query View shows the most recent query and allows me to run it again, but nothing appears under the tab Search History…

**Comment by susanodd** [comment]
@ocrasborn you need to save them first. You can do that in the Query View.

**Comment by ocrasborn** [comment]
Aha! :-)

**Comment by ocrasborn** [comment]
Saving works, in the sense I can click Save and an entry in the list is added, but they are all empty. No query parameters are stored. (Safari/Mac)

**Comment by susanodd** [comment]
Can you try a simple basic query like on handshape 2s?

**Comment by susanodd** [comment]
@ocrasborn this works on old Safari 15.6.1 for me.

Indeed I can see in the Search History Admin that there are no parameters on your queries.

Can you try it out on Chrome?

Can you also try it with a basic query to see if it's something tied to specific parameters, or the number of parameters, or just to the new Safari.
Since no parameters were saved I need to know more about what parameters were set.

Also, as usual try reloading the page a few times. And closing/reloading other windows because they might also need to refresh with newer code. I noticed if you have different datasets selected in different browser windows, or different browsers where you're logged in, they mess each other up because the selected datasets is kept in your profile. So this has a side effect on other windows, because a dataset can become unavailable (by yourself unselecting it elsewhere).
Since the new signbank "jumps back to global" via the sliding results bar, then unknowingly you could be using the old server in a new server window.

(Just trying to rule out things for debugging why it doesn't work on new Safari.)

**Comment by susanodd** [comment]
Okay, just a guess, maybe you're searching on the creator?

That's not showing up for me.

**Comment by susanodd** [comment]
I added a check as to whether the specific query parameters shown in the Query View are implemented for the Save Query.
If not the Save Query button is a popup rather than a save. It shows which parameters are not yet available.
Otherwise it works as shown above.

I need to implement additional subclasses for the remaining parameter types. Basically ones that have relations between objects such as Notes, Relations, and some publication attributes, such as creation date and user.
This will be done after we get on the new server.

**Comment by susanodd** [comment]
I added Tags as well to the search history. (The branch search_history has not been merged yet, so it can't be used yet.)

Now searches can be done on Notes and Tags. (once merged and deployed.)

**Comment by susanodd** [comment]
I added Note Contains to the search history parameters. Now it's possible to save a query with e.g. Note Contains: FMU.

(Not live yet.)

**Comment by susanodd** [comment]
The new parameters mentioned above are live now.

**Comment by ocrasborn** [comment]
Hi @susanodd , saving works fine now, parameters are displayed, and query handedness=2n I can re-run without problems. However, query translation equivalent = help leads to an error: "ValueError at /signs/search/
The QuerySet value for an exact lookup must be limited to one result using slicing."

**Comment by susanodd** [comment]
Oh ouch!!
I'll look into that.

**Comment by susanodd** [comment]
I fixed this @ocrasborn. All the text fields had the same bug. (Awaiting deployment)

Note that if you use the search in the menu bar, you need to click the search icon up there. The fast search looks in all languages, so it doesn't show up in the individual language fields. But it only is accessible via the magnifying glass search button.
The fast search are not yet saved in the history! I'll fix that.

**Comment by susanodd** [comment]
The translation search field of the menu bar has been implemented in search history. It's in a pull request.

**Comment by susanodd** [comment]
The creation date fields have been revised. This is live now.

**Comment by susanodd** [comment]
I added the search history to the user profile for easier navigation.
It shows up for logged in users that have saved queries. 
Recently Saved Queries, with a link to the search history page.

**Comment by vanlummelhuizen** [comment]
@susanodd This seems to be deployed on the live server. So, close this issue?

**Comment by susanodd** [comment]
Yes, okay.

I added more parameters to those that get saved in the history. Nearly all are available.

A message is shown to the user if some of the parameters to their query are not included in saving.
Those not available yet are "searches that refer to other glosses" (e.g., other gloss of relation).
