### ISSUE TITLE
drop-down menu is not completely visible

### ISSUE THREAD

**Issue by uklomp** [Signbank/Global-signbank#1181]
A colleague is working on the phonology of a sign (so editing the phonology fields) in Firefox (Windows).
She cant select the option she wants to because a panel seems to be blocking the lower part of the menu.

![image](https://github.com/Signbank/Global-signbank/assets/147159596/278f3772-2146-4357-8bf6-eda516fdd980)

**Comment by susanodd** [comment]
It should scroll.

**Comment by Jetske** [comment]
When I try it (Windows+Chrome) it looks the same as in the screenshot above, so part of the list is somehow blocked

**Comment by susanodd** [comment]
> When I try it (Windows+Chrome) it looks the same as in the screenshot above, so part of the list is somehow blocked

But can you scroll the list itself?

**Comment by susanodd** [comment]
@uklomp this is fixed now!!

**Comment by uklomp** [comment]
thank you!
