### ISSUE TITLE
Translations and Text: Vertalingen en tekst in de interface

### ISSUE THREAD

**Issue by susanodd** [Signbank/Global-signbank#1182]
Kindly report here any phrases that are confusing or have weird translations in het Nederlands.

The translations have been generated and the fuzzy ones disambiguated. We hadn't done translations since before the Senses were added (one year ago), so lots of text now has translations.

For interface languages other than NL, the translations have not been updated. It is unclear the status of those files, since @ocrasborn had colleagues in other countries working on them and sending him the .po files. So to not "undo" their work, I did not generate new translation files. (Django adds new things, but since we need the .po files we don't want Django to overwrite them for the translators until those files are on signbank. Any status on that?)

**Comment by uklomp** [comment]
In the main menu bar, Analysis should be 'Analyse'

**Comment by uklomp** [comment]
In the drop down menu of 'about', there is 'release notes'. I think this should be 'updates en wijzigingen' in Dutch.

**Comment by uklomp** [comment]
next to the search bar for senses, it says 'profile', this should be 'profiel'

**Comment by susanodd** [comment]
> next to the search bar for senses, it says 'profile', this should be 'profiel'

Fixed!

**Comment by uklomp** [comment]
'Example Sentences' should be 'Voorbeeldzinnen' in the Dutch interface.
Additionally, in this panel, we see the video, then the glosses (titled 'glosses') and then the translations. Here, 'glosses' should be 'glossen' in Dutch.

**Comment by susanodd** [comment]
> 'Example Sentences' should be 'Voorbeeldzinnen' in the Dutch interface. Additionally, in this panel, we see the video, then the glosses (titled 'glosses') and then the translations. Here, 'glosses' should be 'glossen' in Dutch.

I added these translations, as well as for Batch Edit, Split Up Sentences, and the two new Search Annotated Gloss and Manage Annotated Sentences pages. This has been deployed to signbank.

**Comment by Woseseltops** [comment]
Sounds like this is done. feel free to reopen

**Comment by susanodd** [comment]
A lot of new text has been added to the interface. This needs to be in the translation files.

I recalled an annoyance about the "f-strings". This leads to weird Python expressions in the translation files. That is why I often make multiple "gettext" expressions so they obtain independent translations, for the subexpressions.
