### ISSUE TITLE
Order of languages in senses is not consistent

### ISSUE THREAD

**Issue by uklomp** [Signbank/Global-signbank#1186]
The order of English and Dutch senses is not consistent. I think it is dependent on whether you add them while working on Signbank in Dutch or in English, because then the order of input is different, depending on the alphabet I suppose (so when I add a sense in the Dutch working environment, I have the English senses on the left, but when I work in the English environment, the Dutch senses are on the left).

We'd like it to be consistent, with the Dutch senses appearing first. 
![image](https://github.com/Signbank/Global-signbank/assets/147159596/e4accd5b-cb38-49bb-8d9d-f53be9eb43d9)

**Comment by susanodd** [comment]
This has something to do with the Dataset ID versus the Language Name.

For the Senses, the modal's where you enter data are sorted by language name.
But elsewhere, they are most often sorted by ID.
