### ISSUE TITLE
Extend API fields for multiple videos and example sentences

### ISSUE THREAD

**Issue by rem0g** [Signbank/Global-signbank#1203]
API should have extended fields for example sentences and accepting multiple videos per gloss. 

To be discussed.

**Comment by susanodd** [comment]
The storage system for videos needs to be extended. @Jetske is working on that in another issue.
This needs to be put on signbank-dev for extensive testing before it can be deployed on signbank.

**Comment by rem0g** [comment]
Up. We will need API for creating, removing, modifying voorbeeldzinnen + upload video attached to voorbeeldzin.

**Comment by susanodd** [comment]
This is not implemented yet.

**Comment by Jetske** [comment]
Just discussed with @rem0g 

Fields for create api:

- "Video_url"
- "Annotations_url"
- "Source"
- "Url" (to be added still)

Fields for edit api:

- "Context (language)"
- "Translations (language)"
- "Source"
- "Url" 
- "Respresentative_glosses": ["gloss_id_1": True, "gloss_id_2": False, "gloss_id_3": False, ...]

(or something like it)
