### ISSUE TITLE
how to change phonology/morphology on SignBank

### ISSUE THREAD

**Issue by rosestamp** [Signbank/Global-signbank#1219]
[new_ISL_lemma_updates (1).csv](https://github.com/Signbank/Global-signbank/files/14968708/new_ISL_lemma_updates.1.csv)

I am trying to upload this CSV in order to update existing entries on our ISL dataset with new morphological and phonological information.
When I try, using "Import CSV Update Existing Glosses", it states: Attempt to update Lemma translations. Use Import CSV Lemma Update instead.
When I do what it suggests using Lemma Update, it states:
The header row of the csv file looks like this: Handedness, Strong hand, Weak hand, Strong hand letter, Contact type, Location, Movement direction, Movement Shape, Relation between Articulators, Handshape Change, Repeated movement, Alternating movement, 42719, ISL, DUCK, 2s, B, no, , neutral space, to and fro, straight, next to, Yes, yes, 42687, DEER, W, beak2_open_spread, initial, forehead, forwards, arc, No

I do not understand what is wrong with my file. 
Please let me know. Thanks!

**Comment by susanodd** [comment]
@rosestamp the easiest is to remove the columns you do not need to update from the CSV file.
Update only needs the Signbank ID column and the specific columns you are updating.

If you remove the Lemma columns it won't tell you to use the Lemma Update.

(More later.)

**Comment by susanodd** [comment]
IMPLEMENTATION CODE COMMENTS
@Woseseltops any ideas here? This is the first time this comes up.

https://github.com/iamoracle/django_case_insensitive_field

The Tags model (prefab) is case sensitive as well. If you create new tags that differ in case, they are different tags.
In this issue, the case of the field choice values does not match those in the database.
The easy fix is to just convert either side to all upper or all lower. The icontains match may find substrings that match.

**Comment by susanodd** [comment]
Hmmmm. The `iexact` will need to be on a model translation multilingual `name` field for the FieldChoice model.

**Comment by susanodd** [comment]
I revised the code to use iexact.
There are much fewer field choices that don't match.
But this one needs to be changed:

@rosestamp:
`For DUCK (42719), could not find option next to for Relation between Articulators`
(There are about 800 rows with this error.)

There is a field "Next-to" as a choice. It requires the hyphen. (You can use next-to now, without the cap. But the code is not yet live.)

I'll put the revision up asap.

**Comment by susanodd** [comment]
@rosestamp here's another one:

`For CORRECT (42658), could not find option downwards + contralateral for Movement Direction`

This needs to be a `>` instead of a `+` to match.

You could ask @ocrasborn if your research needs this to be different.

**Comment by uklomp** [comment]
@susanodd those kind of changes can come to me now :) There happens to be a difference between the > and the + categories.

@rosestamp I will change downwards + contralateral/ipsilateral (which is a weird category anyway) to downwards + contralateral.

**Comment by susanodd** [comment]
> @susanodd those kind of changes can come to me now :) There happens to be a difference between the > and the + categories.
> 
> @rosestamp I will change downwards + contralateral/ipsilateral (which is a weird category anyway) to downwards + contralateral.

Great! I have no idea what symbols are syntax or have semantics. Thanks.
There are a few more that didn't match any field choices.

**Comment by susanodd** [comment]
@rosestamp the CSV import is now case insensitive for the choice fields.
So your file will give far fewer feedback errors. Now only if no match is found, as for the examples above.

**Comment by susanodd** [comment]
@uklomp are there other fields where the syntax of the choice can vary?
For example, the Next-to above. If the `-` is only syntax and some people don't use it, I can code it so it also looks that up.
(To match Next-to as well as Next to.)
I modified the code so it's case insensitive for the choices now. What about the use of `_` in the names? Could that also be used with a space instead?

**Comment by uklomp** [comment]
next-to and next to would be the same indeed. 
> and + and / are not interchangeable in most cases. For the rest, I can't think of any examples where it matters. 
_ in names also doesnt seem very important, but which names do you mean? names of the fields?

**Comment by susanodd** [comment]
> next-to and next to would be the same indeed. the ">"and + and / are not interchangeable in most cases. For the rest, I can't think of any examples where it matters. the underscore in names also doesnt seem very important, but which names do you mean? names of the fields?

Like in the choices for e.g., Strong Hand:
```
1_curved
Baby_beak
```
...

**Comment by rosestamp** [comment]
Thank you. I updated 'next to' to 'next-to'. I understood that the other changes were made but maybe I missed something? When I enter it now, there are still multiple errors saying that the options for example "fingertips" for "location" are not found. Is there a more general problem I am missing?
For the duplicate rows, I will look into that now and delete them. 
Here is my file and here is the screenshot when I tried to upload it:
[new_ISL_lemma_updates.1e.csv](https://github.com/Signbank/Global-signbank/files/15061392/new_ISL_lemma_updates.1e.csv)
<img width="861" alt="Screenshot 2024-04-22 at 11 19 49" src="https://github.com/Signbank/Global-signbank/assets/63103864/d3aed052-9eec-4942-aa10-c6ba8432db00">

**Comment by susanodd** [comment]
If you look at the page for uploading, there is a scroll bar where it shows a pull-down list of choices for the field.
https://signbank.cls.ru.nl/signs/import_csv_update/
If you see that the syntax is different (as for the example above with the plus sign), then @uklomp can change that or add a choice.

If the choices are in the pull-down, then it could be something with extra spaces or no spaces around the symbols? (I will check this.)

If there are more than one that match, then that needs to be corrected in the system. (The names should be unique. But it could be that we didn't notice there are duplicates.)

If none of those are the case, then there is something going on with the query search. (That would be a bug.)

**Comment by susanodd** [comment]
@rosestamp @uklomp 
there is no choice 2n for Handedness.
there is no choice U for Handshape (Strong Hand and Weak Hand)

It's Location 
      Weak hand: finger tips (not fingertips)
It's Weak Hand
     C2_closed (not C2-closed)

**Comment by susanodd** [comment]
@rosestamp another place you can see the existing choices for fields is on the `Analysis > Frequencies` page.
They are sorted there.

**Comment by susanodd** [comment]
> Can i just ask if spaces matter between words like 'upwards' and > or + etc?
> if yes, can this be changed?

It's because that's how they were defined when created by @ocrasborn.

I shall add some additional parsing to allow them without spaces. (There can only be one in the list of choices in the interface, in order to allow searching. So internally they will be mapped -- after parsing away/adding back the spaces for the particular operations `+` and `>` -- to the internal representation.) I can see it's quite annoying as it is.

Is this also the case for the `_` that you also use a `-` for your research? I'm guessing you write them for publication in a certain way.

If you use a different interface language, you can also check what the translations look like for the field choices, to see if any of those are written differently in practice. (I can only read the English and Dutch.)

At the moment, the CSV uses English for the values.
The API interface allows other languages now.

If you need operators themselves (the `+` and `>`) to be modified, @uklomp can do that.
I'll do the spaces.

**Comment by susanodd** [comment]
FYI

```
input:       mouth>weak hand
normalised:  mouth > weak hand
input:       mouth>weak hand
normalised:  mouth > weak hand
input:       eye>neutral space
normalised:  eye > neutral space
input:       Chin>neutral space
normalised:  Chin > neutral space
input:       mouth>weak hand
normalised:  mouth > weak hand
input:       forehead>neutral space
normalised:  forehead > neutral space
```

**Comment by rosestamp** [comment]
Thank you, I managed to solve all of the errors now so thank you for your help and for solving these issues.

**Comment by uklomp** [comment]
so, just to clarify, do I still need to look into the fields with > and + etc or did you find these as well?
And should Susan still look into the 'motivated' form ?

**Comment by susanodd** [comment]
For this one,

`For EYEBROWS (42746), could not find option motivated for Movement Shape`

It should be "Motivated shape"

(You can see the choices in the Import CSV update example pull-downs. Those are computed dynamically when you view the page.)

**Comment by uklomp** [comment]
> sorry, i didn't manage to keep up with all of the questions...what is the question about > and +? motivated form?

See my last message with the bullet point list. I went through all the errors and described if we needed to do something about it, or if you needed change the input in the fields. Then you said you managed to solve everything, and my question is if this means I don't need to check things like 'backwards > upwards' for movement direction anymore.

**Comment by rosestamp** [comment]
Thanks! so i think it's all resolved. Yes 'motivated' should have been 'motivated shape'. and yes, sometimes some < + combinations don't exist and if they don't, I guess they do need to be added. they are not interchangable. but it's possible that the combinations doesn't appear in NGT but does in ISL
