### ISSUE TITLE
Restructure Gloss Detail Template

### ISSUE THREAD

**Issue by susanodd** [Signbank/Global-signbank#1224]
This code is a mess.

ADDITIONAL

The Django forms are generated dynamically. The structure of this page is a gigantic "`editable`" table. (Dynamic javascript plus ajax for every cell.)
Because it is all dynamic, this causes the width of cells you click on in Edit mode to adjust their width and layout. There are OK and Cancel buttons for all of these. It so happens that things generated dynamically end up overlapping each other. Some of this has been repaired in #1199. But many fields still have this problem.

LAYOUT
Because Bootstrap shows extremely thin borders on things, the lack of structure is not apparent.

But there are rows of different lengths all masquerading as a giant table.

The element nesting "`table tr`" without any `thead` of `tbody` structure causes problems.

For illustration purposes, the table rows are show in dark mode. Here the problem with the lack of structure is obvious.

![table-borders-varying-length-1](https://github.com/Signbank/Global-signbank/assets/24272544/c2f2beed-c66e-42b2-8a2a-d8c3ec5cd152)
![table-borders-varying-length-dark-1](https://github.com/Signbank/Global-signbank/assets/24272544/1288776f-6c3d-4279-8627-ee2d28198eb7)
![table-borders-varying-length-2](https://github.com/Signbank/Global-signbank/assets/24272544/732c9bb0-e593-4685-a124-22508fdfbfd6)
![table-borders-varying-length-dark-2](https://github.com/Signbank/Global-signbank/assets/24272544/7d4057c8-6789-481b-be1a-7d0184013eb2)

**Comment by Jetske** [comment]
```
<style>
    tr {border-bottom: hidden;}
</style>
```

@susanodd In the gloss detail html this works, so in dark mode change the border-bottom of tr (and/or th and td) to either 'hidden' or maybe a darker grey ('1px solid grey' or something).

We can also think about keeping them hidden in both light & dark mode, I think it looks quite nice without the lines

**Comment by susanodd** [comment]
The above tweak is n signbank-susan (where dark option is available).

But now this is having adverse effects on pages that make use of borders. They're all missing the bottom border now.
It also does not seem possible to override this to put the border back. At least I don't know how yet. It's not clear what the order of evaluation is for the css directives.

**Comment by susanodd** [comment]
GlossDetail is still a mess.
Some code has been modified by other issues.
Ideally extra templates would be used inside the page.
