### ISSUE TITLE
Add labels and description to JSON

### ISSUE THREAD

**Issue by rem0g** [Signbank/Global-signbank#1225]
We need extra fields in JSON for every gloss:
labels
description
"Voorbeeldzinnen"

**Comment by susanodd** [comment]
By labels, you mean the Tags, right? I can add the Tags to all api.

Are the other two the ones being added in #1178 ?

**Comment by susanodd** [comment]
I started working on this.
Even without the new Tags field, it looks like the package function is broken.

**Comment by susanodd** [comment]
The package functionality has Tags now. It's on signbank.

**Comment by Jetske** [comment]
@rem0g with "voorbeeldzinnen" you mean example sentences for senses, right? Not the new annotated sentences.

**Comment by Jetske** [comment]
@uklomp Okay! Then from now on I'll assume when you talk about voorbeeldzinnen that it's about the annotated sentences.

Voorbeeldzinnen would look something like this in json:

```
{
       "voorbeeldzinnen" : [
              "zin_id_123" : {
                    "sentence_nl" : "Dit is een voorbeeldzin",
                    "sentence_en" : "This is an example sentence",
                    "context_nl" : "Dit is een voorbeeldcontext",
                    "context_en" : "This is an example context",
                    "eaf_file" : [some link?],
                    "video_file" : [some link?],
                    "glosses" : [
                           "gloss_id_123" : {
                                  "begin" : 2000,
                                  "end" : 3000,
                                  "representative" : True
                           },
                           "gloss_id_234" : {
                                  "begin" : 3000,
                                  "end" : 4000,
                                  "representative" : False
                           }, 
                           ...
                    ]
              },
              ...
       ]
}
```

@rem0g This means voorbeeldzinnen are linked almost always to multiple glosses and glosses in return may have multiple voorbeeldzinnen. 

I don't understand what to do here. What do you need the json field to look like? 
- It would be possible to make an api to get/add/delete voorbeeldzinnen for a gloss in a format such as above. Update is more difficult. 
- add the field voorbeeldzinnen as shown above (or more limited) to every gloss. That would give a lot of copies, in each gloss that it shares..

**Comment by susanodd** [comment]
The JSON tuples are strings, not tuples. It doesn't seem to work to generate just tuples, it converts them to lists in the zipped file.

```

        "Notes": [
            [
                "Source",
                "True",
                "1",
                "Number produced by Henk Betten in 2011 as one of three elderly Groningen signers for BA thesis of Maike van Raam at Radboud University; supervision Onno Crasborn"
            ]
        ],
```

```
        "Notes": [
            [
                "-",
                "False",
                "3",
                "Dit gebaar kan als discriminerend worden ervaren. Het gebaar verwijst naar de hoofddoek die de medewerkers bij ALDI dragen."
            ]
        ],

```

**Comment by susanodd** [comment]
Here it's modified to dictionaries for each note:

```
        "Notes": [
            {
                "Published": "True",
                "Index": "1",
                "Type": "Source",
                "Text": "Number produced by Henk Betten in 2011 as one of three elderly Groningen signers for BA thesis of Maike van Raam at Radboud University; supervision Onno Crasborn"
            }
        ],
```

```
        "Notes": [
            {
                "Published": "False",
                "Index": "3",
                "Type": "-",
                "Text": "Dit gebaar kan als discriminerend worden ervaren. Het gebaar verwijst naar de hoofddoek die de medewerkers bij ALDI dragen."
            }
        ],
```

I'm going to use this json, although cumbersome it has less chance for parsing glitches for users.

**Comment by susanodd** [comment]
This is deployed now on signbank. The third representation has been used.

**Comment by rem0g** [comment]
Can you describe how to use the API in Wiki?
