### ISSUE TITLE
Manage example sentences page

### ISSUE THREAD

**Issue by Jetske** [Signbank/Global-signbank#1227]
Because right now the example (annotated) sentences will only be shown as top-3 results on the gloss detail page, we also need a way to browse through all of them and at least be able to delete sentences on that page. Discussion needed on how to show/order them and other functionality.

**Comment by susanodd** [comment]
Are these new sentences replacing the already existing sentences?

There is a menu `Signs > Search Senses`
There is a search panel for filling in searches related to e.g., sentence type and sentence contains.
It's possible to add the searchs on the new sentences to that page, n'est ce pas?

**Comment by Jetske** [comment]
@susanodd This is about the annotated sentences shown in the new panel, so they are a separate thing from the senses' example sentences, not a replacement. 

On an annotated sentences overview page we can add a search bar and, if given change permissions, options to edit those sentences.

**Comment by uklomp** [comment]
this is about a page per gloss? or a general page with all the sentences?

**Comment by Jetske** [comment]
About a general page with all sentences such that you can search through them and see which glosses they contain.
