### ISSUE TITLE
can't add a new tag

### ISSUE THREAD

**Issue by uklomp** [Signbank/Global-signbank#1232]
I wanted to add a new tag for checking example sentences. It's not working, this is the error: 

![image](https://github.com/Signbank/Global-signbank/assets/147159596/48416880-13be-4c92-bf0e-21442dfd7feb)

**Comment by susanodd** [comment]
@uklomp you need to use underscorea instead of spaces

**Comment by uklomp** [comment]
OK, thank you! Would it be possible to change the error so that the user knows an underscore is needed?
