### ISSUE TITLE
.eaf doesn't upload with annotated sentence after changing the .eaf.

### ISSUE THREAD

**Issue by uklomp** [Signbank/Global-signbank#1233]
I uploaded an annotated sentence and noticed a mistake in the glosses. I went to change the .eaf file in ELAN and wanted to upload it again but that didn't work. I guess it has something to do with something I did in the new .eaf file but what is it? See screenshot.

![image](https://github.com/Signbank/Global-signbank/assets/147159596/e1c60924-41ea-4fbc-9d80-4b6a60745c00)

**Comment by Jetske** [comment]
@uklomp Can you send the changed eaf file?

**Comment by Jetske** [comment]
Did you try to upload this to NGT or to a test dataset? I get the same error in another dataset when none of the glosses in the eaf are in the dataset.

**Comment by uklomp** [comment]
I uploaded it to a gloss in the NGT data set. I'm pretty sure all the glosses are in the set actually. 
I tried again later and then it worked, so I would need to check if I can reproduce this error when I again upload an .eaf file, see that it needs changes, change it, and then upload it again.

**Comment by Jetske** [comment]
Yes, it worked for me as well in NGT, but not in other datasets (which makes sense, I will change that to give better feedback before upload)
