### ISSUE TITLE
Annotated sentences improvements

### ISSUE THREAD

**Issue by Jetske** [Signbank/Global-signbank#1234]
The following edits will be made:

- Ability to edit which glosses are representative
- Add that you can download an eaf file and upload an improved one on the edit annotated sentence page
- Underneath the video show the annotation gloss id rather than the lemma (e.g. PT -> PT-1 hand)
- Add the source of the sentence (that is, which corpus)

**Comment by uklomp** [comment]
It should be possible for us to upload multiple sentences under one gloss.

**Comment by Jetske** [comment]
@uklomp Uploading multiple sentences under one gloss is already possible, or what do you mean?

**Comment by uklomp** [comment]
Ah, sorry! You're right! Ignore this.

Another point: what did we decide again on the left hand glosses? When there's overlap, only the right hand is selected, but otherwise the left hand is also included?

**Comment by Jetske** [comment]
Yes, all glosses from the right hand tier are added and only those from the left hand tier if they don't have overlap with a gloss on the right hand tier

**Comment by susanodd** [comment]
This is deployed on signbank

**Comment by uklomp** [comment]
Refreshing doesn't work. Uploading it again also doesn't work. I can send you an email with two .eafs that I could upload today and two that I couldn't, maybe you can spot the difference?

**Comment by Jetske** [comment]
Yes please do!

**Comment by Jetske** [comment]
Looks like the error was caused by a "_" that should have been "__" in my code... anyway I hope this solves it!
Also made small improvements to the feedback in case it finds annotations that are not in the dataset.

**Comment by susanodd** [comment]
@Jetske are you able to add the gettext to the feedback so that it will be added to the PO files for translation? (Eventually.)

**Comment by uklomp** [comment]
Ok, I will try again soon.

I have a new request (please let me know if you want me to make separate issues for these things, now or in the future); 
namely (actually like was done for the old example sentences connected to senses), if we could provide information if it's in question or a sentence containing negation. So, in the upload process, I'd like two boxes we can tick, one with 'question' ( 'vraagzin')  and one with 'contains negation' ('bevat ontkenning'). If these boxes are ticked, I'd like this information to appear on signbank as well.

And a question: I see that there's a field now, where I think it is possible to say something about the corpus / source, was it the idea that we put the link there? And should we do this manually for now, or were you maybe still looking into a way to do this automatically?

**Comment by uklomp** [comment]
.eaf 43 and 72 still don't really upload so I'm afraid the bug isn't solved yet!

**Comment by Jetske** [comment]
@uklomp the changes are not online yet :) when it's gone from the pull requests you can try again.

For new requests, please make a separate issue with some priority tag. Problems encountered afterwards can be added to the existing issue (like the bug you found here). 

Yes the corpus field was meant to add the corpus name or a link to the corpus. I wouldn't know how to add it automatically but if you have ideas about that let me know!

For the question about cropping: I'll look into it a little bit but I think it is difficult to implement.

**Comment by Jetske** [comment]
For annotated sentences a difficulty with cropping is also that the annotations each have a start and end time. This would need to be adjusted when cropping from the beginning of a video. That's possible, just not very efficient maybe.

**Comment by susanodd** [comment]
This is live on master.

**Comment by susanodd** [comment]
I'm getting this warning after the new updates:

`unable to import get_creation_time from CNGT_scripts`

Maybe this function is needed in the Signbank Python files instead?

**Comment by Jetske** [comment]
@susanodd Any idea which function it occurred in?

**Comment by susanodd** [comment]
> @susanodd Any idea which function it occurred in?

No idea. It was just a general run.
I was working on the feedback, which has nothing to do with eaf files. But I hadn't run a branch that included the sentences yet.

**Comment by Jetske** [comment]
Yeah I think that it's unrelated to the new code

**Comment by Jetske** [comment]
@uklomp the cropping functionality crops both the video and eaffile, cutting out irrelevant annotations.

Then I believe this issue can be closed. Other changes are still to be done in other issues.
