### ISSUE TITLE
Signbank API webDic issue

### ISSUE THREAD

**Issue by rem0g** [Signbank/Global-signbank#1236]
When setting "In The Web Dictionary" to True, it works. But when setting to False, I am getting: NOT FOUND. 

This is weird as i see False values in retrieved JSON data at bootlean items, like those: 

```
            "In The Web Dictionary": "False",
            "Is This A Proposed New Sign?": "False",
            "Exclude From Ecv": "False",
            "Repeated Movement": "False",
            "Alternating Movement": "False",
```

**Comment by susanodd** [comment]
This has been deployed.
