### ISSUE TITLE
Signbank API: dictionary/package/, add morphology and Rabound / UVA tags

### ISSUE THREAD

**Issue by rem0g** [Signbank/Global-signbank#1238]
Can you please add those fields to json file: 

Morphology
Tags, we want to know if the gloss is made by UVA or RU.

**Comment by susanodd** [comment]
Yes, but these will have their own dictionary field. These will be read-only since they are added automatically based on the user that creates the gloss.

**Comment by rem0g** [comment]
For the morpohology, gloss ID or gloss name is sufficient and if it's a list that's fine.

**Comment by susanodd** [comment]
> For the morpohology, gloss ID or gloss name is sufficient and if it's a list that's fine.

There are three kinds of morphology, with examples shown below:

https://signbank.cls.ru.nl/dictionary/gloss/3910

![regenpijp-d-ngt](https://github.com/Signbank/Global-signbank/assets/24272544/078c7d97-5830-4d32-a9aa-2d19b9e7b1ab)

https://signbank.cls.ru.nl/dictionary/gloss/3968/

![wegdoen-ngt](https://github.com/Signbank/Global-signbank/assets/24272544/d7784b3f-b49d-4b1c-a445-5a639c3bdf77)

https://signbank.cls.ru.nl/dictionary/gloss/726

![binnen-ngt](https://github.com/Signbank/Global-signbank/assets/24272544/ae5b0a12-21bf-40e9-b515-83b533b3f205)

**Comment by susanodd** [comment]
I suggest this can be put in the package, retrieval. But not sure about the update. There are database constraints and relations between objects.

Finding the simultaneous morphology and blend morphology examples is a needle in a haystack. There are not that many stored in the database. You can search on blends, but to find simultaneous morphology examples, you need to keep trying morphemes.

**Comment by susanodd** [comment]
Is this syntax okay for package?

`"Sequential Morphology": "FABRIEK-A + WEBCAM + AANHALINGSTEKENS"`

A string of glosses, separated by `+`.
(This syntax is used elsewhere in Signbank for display.)

**Comment by rem0g** [comment]
Great thanks, will it work for glos update too?

**Comment by rem0g** [comment]
Ok, is it ok if i  create an seperate issue and tag others so they can work on that too?

**Comment by susanodd** [comment]
> Ok, is it ok if i create an seperate issue and tag others so they can work on that too?

Yes, good idea.
I found it in the CSV, so that helps.

Will you need other relations?

**Comment by susanodd** [comment]
I've got it implemented now. I'm testing it on signbank-dev.

As it appears, I forgot how to update the fields. The syntax of the new value for morphology is not obvious.
This will need to be written down somewhere.

Sequential morphology and Blend morphology both work now for updating.

The sequential needs to be separated by '` + ' ` (with spaces around)
The blend needs to be separated with commas `', '` (comma space) of  GLOSS:role, where role is the same as in Gloss Edit.
(It's text, but remember this still needs to parse, so do not put comma's inside the role text)

**Comment by susanodd** [comment]
@rem0g this is live on signbank-dev

**Comment by susanodd** [comment]
This is live on signbank.
