### ISSUE TITLE
Signbank API: Allow to update gloss/lemma when there is max one gloss connected

### ISSUE THREAD

**Issue by rem0g** [Signbank/Global-signbank#1243]
As we want to change glosses because of wrong order in A,B,C,D suffix we want to fix the order via Signbank API, only allow glosses name/lemma name to be changed when there is not more than one gloss connected. If there is more than one, then the update should be done at Signbank website.

**Comment by susanodd** [comment]
Do we want this to ignore case? Or allow to create with different cases?

**Comment by susanodd** [comment]
This is almost done. It ended up needing three different kinds of lookups for the language fields, since they are referred to by different kinds of keys.

**Comment by susanodd** [comment]
@rem0g this is live on signbank-dev now.

The language fields for Annotations and Lemmas are there (using the same keys as for creating a gloss).

Will you try out some of your updates on `signbank-dev` ?
If a lemma is shared it won't work.
There are additional checks if the language fields are already in use.
It will report errors in the returned value as before.

It needs to be tried out some more to make sure all potential constraint violations are caught and not executed.
Kindly see if the new fields work as you want them to.

**Comment by susanodd** [comment]
This is on signbank now.
