### ISSUE TITLE
How to Display Senses as a String?

### ISSUE THREAD

**Issue by susanodd** [Signbank/Global-signbank#1247]
There is some inconsistency in the display of Senses. In the Gloss List View, they are displayed per Language.
In the Gloss Detail View, they are displayed per Sense Number, then for each one, per language.

In the Revision History, it's using the following syntax in the display:

`{ "nl": [["nederlands"],["woorden"]], "en": [["sense keywords", "more keywords"], ["another sense"]]}`

This looks like computer code!!

How to display this in a user friendly way?

The revision history stores the values as "strings", old and new.
It would be preferable if it was stored as an update "per sense" rather than as a huge dictionary of lists.

**Comment by susanodd** [comment]
Pardon the silly example that is for illustration purposes.

**Comment by Jetske** [comment]
That does look better!
