### ISSUE TITLE
deteled video for APART-C

### ISSUE THREAD

**Issue by uklomp** [Signbank/Global-signbank#1251]
I accidentally deleted the video for APART-C in the NGT dataset just now. Is it still available somewhere in the background?

**Comment by susanodd** [comment]
I don't see it in the folder.

@Woseseltops implemented the backups for the entire writable. But I don't know where they are stored on the server.

**Comment by uklomp** [comment]
Ok, thanks. If it's not there, I'll make sure we record it again quickly.

**Comment by susanodd** [comment]
@uklomp how did you delete the video? Was this in the admin, or in Gloss Edit?

I'm wondering why it did not make any backup video file. Perhaps it only makes a backup when you upload a new video and replace the old. (I don't know the answer.)

@Woseseltops can you check if there is a video for this in wherever the backups are?
I found an archive folder but it is very sparse, so not the correct one.

**Comment by uklomp** [comment]
Thanks Gomer! It has been solved.
