### ISSUE TITLE
Remove Onno from hardcoded texts

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#1260]
Hi all, I'm still getting the nightly log email from the cron job that does write_ecv_files_for_all_datasets; it'd be good to take me off, and perhaps send the logs to @uklomp (or @Woseseltops ?)

**Comment by uklomp** [comment]
I suggest to Wessel indeed.

**Comment by Woseseltops** [comment]
Hey @ocrasborn ! I just looked around in various crontab files, looking for places that still referenced your email, and found 2:
* On Applejack, where Signbank lived >3 years ago
* In the container `signbank-archive`, where Signbank lived >1 year ago

I've turned all of these cronjobs off, does that help?

**Comment by susanodd** [comment]
Here are a couple more:

https://github.com/Signbank/Global-signbank/blob/da651aba6d6b6f37e14d47733dfe0af040ad3c35/templates/global-templates/404.html#L10

https://github.com/Signbank/Global-signbank/blob/da651aba6d6b6f37e14d47733dfe0af040ad3c35/templates/ASL-templates/404.html#L10

https://github.com/Signbank/Global-signbank/blob/da651aba6d6b6f37e14d47733dfe0af040ad3c35/signbank/registration/views.py#L255

**Comment by Woseseltops** [comment]
That's a different problem @susanodd , but well spotted... didn't realize we hardcoded Onno into Signbank ;). Let's use this issue to make it dynamic.

**Comment by Woseseltops** [comment]
If you're looking for work @susanodd , I think you'll like this one :)

**Comment by susanodd** [comment]
This has been deployed and the language file compiled. Although multiple language files were changed, only the NL file was compiled on the server.
