### ISSUE TITLE
Show warning when deleting a gloss that is referenced elsewhere

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#127]
places to check for references: 
- In all the tables in the Morphology panel
- In the table in the Relations to Other Signs panel

**Comment by susanodd** [comment]
NOTE TO SELF
Bump up to relevant.
Elsewhere has expanded.

**Comment by susanodd** [comment]
Here's what this looks like for a totally nonsensical sign in dataset tstMH:

![delete-sign-modal](https://github.com/Signbank/Global-signbank/assets/24272544/72f004c9-8e13-47ce-bf64-9343d7fd0f76)

**Comment by susanodd** [comment]
And again with the interface language NL:

![delete-sign-modal-NL](https://github.com/Signbank/Global-signbank/assets/24272544/674323bd-91e3-49de-8577-c2f1154d98c9)

**Comment by susanodd** [comment]
Here are the latest screenshots.
This shows the setting GUARDED_GLOSS_DELETE turned ON (delete does not happen if the gloss is related to other glosses. (The default is OFF so the gloss is deleted. In that case the user is redirected to the Gloss List View.)

![verwijder-stekker-B](https://github.com/Signbank/Global-signbank/assets/24272544/511c6b11-b30e-47c7-9eee-168cc354f380)

![verwijder-stekker-guarded-gloss-delete-message](https://github.com/Signbank/Global-signbank/assets/24272544/2d229cf6-ec4d-43ee-9729-9a1b0ae22a90)

**Comment by susanodd** [comment]
@ocrasborn can you have a look and see if this looks all right?

**Comment by susanodd** [comment]
This is live now.

**Comment by susanodd** [comment]
I did the same for the Morpheme Delete button

**Comment by susanodd** [comment]
Show this information to the new API command (#1210 )

**Comment by ocrasborn** [comment]
Looks good @susanodd !

**Comment by susanodd** [comment]
Glosses are archived now.
