### ISSUE TITLE
Split Up Keywords into Different Senses

### ISSUE THREAD

**Issue by susanodd** [Signbank/Global-signbank#1273]
There already is a batch edit for senses (#1268).

But after checking, it seems it doesn't load properly for NGT due to the extensive dataset. (FIXED)

Modified title of page to Batch Edit Senses

Reworking to use panels instead of modals (open/close panels instead of popups)

Here are some ORIGINAL screenshots for tstMH:

![batch-edit-senses](https://github.com/Signbank/Global-signbank/assets/24272544/3e0804d8-b227-4b2c-bb4f-2a315d0a756d)

![batch-edit-senses-matrix-popup](https://github.com/Signbank/Global-signbank/assets/24272544/8f8202e1-64d6-4d0b-89ab-c7299c3532a9)

**Comment by susanodd** [comment]
@uklomp can you try this out for dataset Oefen?

Unfortunately this page does not load for NGT.

It's in-line batch editing of senses.

The page does not need to be reloaded at all. You can just keep editing the senses of different glosses.

**Comment by susanodd** [comment]
This page was intended to help update the original glosses that have all the keywords in one sense.

You can split those keywords (for the Dutch language) up into separate senses, and reorder them, without needing to type everything again.

**Comment by susanodd** [comment]
This has been deployed.

**Comment by susanodd** [comment]
I can put Dutch first.

[CODE SPECIFIC]
There is not an easy way to do this globally.
I modified the Batch Edit to do that, by ordering on "`-id`" the reverse of the Language ID.
Probably something like a sorting order field in Dataset for translation languages of the dataset?

Care must be taken in the template to use the same iteration over languages so the sorting stays the same for all occurrences in the template. (i.e., if there are forms, the form language fields need to be associated with the correct language.)

**Comment by uklomp** [comment]
Hmmm. It still means a lot of clicking, because I first need to select which one I want to edit (English or Dutch), then I need to edit, but I can't just type in a text field going from one gloss to another in the same overview, if you know what I mean.

**Comment by susanodd** [comment]
> Hmmm. It still means a lot of clicking, because I first need to select which one I want to edit (English or Dutch), then I need to edit, but I can't just type in a text field going from one gloss to another in the same overview, if you know what I mean.

You  mean you don't like the pop-up "modals"?

These were made this way to hide all the "update" stuff.
I will duplicate the page and make another that removes the code from the modals and shows it inline instead.

**Comment by susanodd** [comment]
@uklomp that there is a separate "edit area" for each language has to do with that there are thousands of glosses with only Dutch and no English.
The code is meant to be used to that you can "browse" the glosses, and click on "check senses" to add a TAG to those glosses that need to have multiple senses.
The you can search on labels "Check Senses" to remove the other glosses.
Then Edit Dutch to "partition" the existing keywords into multiple senses.
(Without doing any copy past or typing! it's just upping the number.)

Then go to the Matrix Edit and add the translations for the separated senses there.

Likewise, if you have English filled in (or some other language) then you can start with Edit English, etc.

You can create senses both in the Edit Dutch area as well as the Matrix area.

It is not necessary to have all languages for the senses. They can include just one language.
(The lemmas and the annotations need all dataset languages.)

**Comment by susanodd** [comment]
![batch-edit-senses-aka](https://github.com/Signbank/Global-signbank/assets/24272544/abedc0a9-3470-43cd-8819-55bf152b07ee)

![batch-edit-senses-matrix](https://github.com/Signbank/Global-signbank/assets/24272544/491ce77d-3a0f-42c1-b57b-aa91e26f956f)

**Comment by susanodd** [comment]
This is already existing functionality. Revised so that the popups are panels.

Next up "split into senses" (whatever it should be called, when the keywords are redistributed among (new) senses instead of all of them in one sense.)

**Comment by susanodd** [comment]
Language panel

![batch-edit-senses-dutch-top](https://github.com/Signbank/Global-signbank/assets/24272544/2c074dba-b9dd-4c5b-9860-218cd263f0df)

![batch-edit-senses-dutch-bot](https://github.com/Signbank/Global-signbank/assets/24272544/aec68d0f-530d-4fc6-b79d-af3788da44ec)

**Comment by susanodd** [comment]
When necessary, the existing keywords can be split up into separate senses.

**Comment by susanodd** [comment]
This is what the layout with panels looks like.

![batch-edit-senses-panels](https://github.com/Signbank/Global-signbank/assets/24272544/2675f7c6-a15d-462b-a216-76b6a533ed11)

**Comment by susanodd** [comment]
This is live on signbank-susan

(Under the old name: Analysis -> Keywords Mapping)

**Comment by susanodd** [comment]
I revised the modals to make them less crowded, added boxes, and placeholders where fields empty.

![split-senses-afhankelijk-A](https://github.com/Signbank/Global-signbank/assets/24272544/7824228a-e11b-4aa1-876f-513c85322ce5)

![split-senses-afhankelijk-A-2](https://github.com/Signbank/Global-signbank/assets/24272544/5f9423a3-1fe9-4d68-bf2f-b8f348f25254)

**Comment by uklomp** [comment]
Hi Susan. I like the functionality. I can easily split the senses here, regroup them and translate them. Thanks!

One thing that I don't really like is the placeholder text fields that stay there while they're not necessary anymore. For example, in the following screenshot, the gloss used to have 3 senses. They were split, but when I go to the translation part, I still see 3 text boxes under (1). This is a bit distracting. Can those be removed?

![text fields](https://github.com/user-attachments/assets/d4c50f5f-cf60-4db3-a3a6-f15148b24064)

**Comment by susanodd** [comment]
I fixed the "undefined" placeholders as shown in your screenshot.

I just finished removing the surplus "empty" cells.
The original intent was that the user could enter separate keywords as on the Gloss Edit for senses where they are on separate rows.
So after removing the extra empty cells, there is only one empty language cell for senses that do not have it filled in yet.

One undocumented feature, if you're in the "matrix" view and there are empty rows (empty senses after moving stuff around), you can do "update" and this removes the empty senses.
(This used to be as a hint on the button, but it looked kind of confusing, since it's not apparent why you would need to do this until you have actually used the editing and seen empty senses. They are not automatically deleted because it's not clear when the user is finished.)

**Comment by susanodd** [comment]
In contrast to the Batch Edit (#1268) of senses, the senses and keywords here are updating the actual objects.

To accomplish this, there are zillions of object ids in the template.

**Comment by susanodd** [comment]
@uklomp can you check this again if it is okay for you now?
signbank-susan

**Comment by uklomp** [comment]
Hi Susan. 

1. Something is incorrect I believe: I first regrouped senses and then worked on the translation, but the regrouped senses were not implemented in the translation yet. See screenshot: I made different groups for 'mooi' and 'ergens goed in zijn' but then I went to 'translation' and they're still in the same line/group. 
<img width="1365" alt="image" src="https://github.com/user-attachments/assets/7184537c-31ef-4910-990a-05f3160a45e9">

2. In the panel of splitting senses, would it be possible to first show Dutch and then English? We now always have to scroll down because English is there first (often empty, btw). It will (almost) never be the case that we want to edit English only or English first, but it will often be the case that we need to edit the Dutch senses, and later translate them in the other panel.

**Comment by susanodd** [comment]
For (2) that is kind of a problem because it depends on what interface language is being used, what the sort order is.
It's making use of the Language ID now. Behind the scenes, the Language ID is used everywhere.

(We would need to change the Language ID itself in the database to put Dutch ahead of English. The IDs are generated by Django. I can see about this but ought to ask the others. We could say add an additional key number (like is done for the Field Choices, they have machine values and 0 and 1 are exactly the same for all languages.)


(I tried to alter that but Django itself does stuff when it retrieves and sorts objects, so this is not consistent.)

For (1) I'll see what is happening.
I see an "undefined" in your example screenshot.
That means that something internally is messed up.

If possible can you try it again after reloading the page a few times, or going to different pages, etc. to get the most recent javascript?
I thought I had fixed that "undefined" bug yesterday.

I'm not used to seeing the little fields next to each other. They depend on the screen size I guess. Normally they show up above each other.
I'll try to duplicate what you did to get the same error.

**Comment by susanodd** [comment]
Just a guess for myself, it looks like where it has "undefined" that that cell was supposed to be the "ergens" text.
(Behind the scenes the little "subtree" (html code for the text field) is moved. So it looks like it didn't actually move it correctly.)

**Comment by uklomp** [comment]
I tried it again and reloaded the page first a few times, then the error didn't occur.

**Comment by susanodd** [comment]
Since the page does not need to be reloaded, then if the code has been changed it does not know, it keeps using the old code until you actually do reload it again. (This is annoying for debugging too.) (It should maintain your search though!)

**Comment by susanodd** [comment]
@uklomp I succeeded in getting Dutch/Nederlands first in the display.

**Comment by susanodd** [comment]
That the different language areas appear in a column instead of next to each other I don't know how to alter this.
I'll ask @Woseseltops next week.
