### ISSUE TITLE
When adding myself as owner of tstMH, I am added to NGT instead

### ISSUE THREAD

**Issue by vanlummelhuizen** [Signbank/Global-signbank#1275]
Also, the response is the NGT details page instead of the tstMH page.

**Comment by susanodd** [comment]
That is totally messed up.

**Comment by vanlummelhuizen** [comment]
> That is totally messed up.

Yup, but I fixed it already. Now wondering how publish it, i.e. where to commit, on a new branch?

**Comment by susanodd** [comment]
> > That is totally messed up.
> 
> Yup, but I fixed it already. Now wondering how publish it, i.e. where to commit, on a new branch?

We've been adhering to your original policy of branches for big changes and on master if it's a small bug fix.

Just don't edit in on the live server. (That prevents the deploy from working since there end up changes so it won't pull on the live server.)
