### ISSUE TITLE
Shorten sentence videos

### ISSUE THREAD

**Issue by Jetske** [Signbank/Global-signbank#1277]
@uklomp after thinking of a doable way to implement video cropping functionality, I'd like to give it a try anyway. No promises though.

**Comment by Woseseltops** [comment]
For completeness, this is 'temporal cropping', that is 'trimming' or just 'cutting'

**Comment by Jetske** [comment]
@uklomp FYI this seems to be working! We need to test it on signbank-dev though. But first I'll add a way to add sources because that will be in the same update.

**Comment by susanodd** [comment]
> @uklomp FYI this seems to be working! We need to test it on signbank-dev though. But first I'll add a way to add sources because that will be in the same update.

Can we put the batch edit on signbank yet? It's on signbank-dev. And the "moving keywords to different senses" is on signbank-susan. Those are both pull requests.

**Comment by uklomp** [comment]
Hi Jetske, I just tried it for the first time and received an error: 

<img width="1920" alt="image" src="https://github.com/user-attachments/assets/37e277a3-6ddc-4c97-921e-5adb181322a0">

**Comment by uklomp** [comment]
@Jetske I just tested it and it seems to work, at least for adapting the starting time!

**Comment by uklomp** [comment]
Would you like me to test more things? like also adapting the end time? 
I was wondering if it's true that I first need to upload the video and save everything, then get back to editing before I can adapt the video?
