### ISSUE TITLE
The dictionary/info/ API endpoint does not check for the API token in Authorization:"Bearer ..."

### ISSUE THREAD

**Issue by vanlummelhuizen** [Signbank/Global-signbank#1278]

**Comment by vanlummelhuizen** [comment]
> can we do this everywhere?

Yes, I already did in https://github.com/Signbank/Global-signbank/pull/1279/commits/cf9b1693daaa4e3499c41cc29a7e889930099548 which is now included in the PR.

> * let's make sure to also support the 'old' way of authenticating to this endpoint, so we're not suddenly forcing ELAN to make the switch.

To be sure I just tested the dictionary/info endpoint from my browser and it seems to work correctly.

> * Related recent pull request

@Woseseltops Just a reference or do you want me to look into that PR?

**Comment by Woseseltops** [comment]
Just a reference!

**Comment by vanlummelhuizen** [comment]
I am closing this issue because the solution was merged in #1279.
