### ISSUE TITLE
User has problems creating annotated sentences

### ISSUE THREAD

**Issue by Jetske** [Signbank/Global-signbank#1283]
One user has reported that they are unable to create annotated sentences. Everyone else who has tried has succeeded, so it's hard to say what is the problem. I'm thinking that the video (this could be the videofile and/or eaffile) never ended up as InMemoryUploadedFile/TemporaryUploadedFile correctly, so it was lost before processing the request. 

![image](https://github.com/Signbank/Global-signbank/assets/10157482/b1c3f391-782b-42f2-85db-fb8107f8683a)

**Comment by Woseseltops** [comment]
The first step is (nearly) always that we are able to reproduce... in the past, users that create videos of their problem have been really helpful, perhaps this user is willing to create one too?

**Comment by Jetske** [comment]
@susanodd this was just solved while calling and editing live on signbank-jetske, thanks for your help to set it up!!
