### ISSUE TITLE
BUG / ASAP: Adjusting Morphology doesnt reflect since_timestamp

### ISSUE THREAD

**Issue by rem0g** [Signbank/Global-signbank#1292]
When making changes to ZUID-AFRIKA-A regarding morphology I am not seeing reflection in updates at glosses.json. 

For example: 
https://signbank.cls.ru.nl/dictionary/package/?extended_fields=true&since_timestamp=1721730585

I am not seeing updates to ZUID-AFRIKA-A, but when i adjust phonology of AAP there are updates. 

This should be solved as priority.

**Comment by susanodd** [comment]
Okay, I'm on it.

**Comment by susanodd** [comment]
There might be something else wrong, too. If you search on signbank on "zuid" you will see that the names don't match:

![search-on-NGT-ZUID](https://github.com/user-attachments/assets/4a00c0e7-5820-40c2-ab78-828129a1ee2c)

**Comment by susanodd** [comment]
I added an update to the gloss timestamp to all the methods that implement "relation type changes".
This happens via via, so before changes are saved to the revision history.
I'm not sure why the bug occurred. Deploying now.
Deployed!!

@rem0g Can you check it again now?

**Comment by rem0g** [comment]
Thank you for quick reply! 

Is it deployed on production? Because the issue is still there, and i have tested it also on AAP and no reflection in changes.

**Comment by susanodd** [comment]
> Thank you for quick reply!
> 
> Is it deployed on production? Because the issue is still there, and i have tested it also on AAP and no reflection in changes.

Yes, it is deployed.
Are you able to inspect the gloss history (panel of gloss detail) to see if the update shows up there?
What is the gloss id?

**Comment by susanodd** [comment]
You need to do the update again to the morphology, of course.

**Comment by rem0g** [comment]
When updating morphology, it doesnt reflect in gloss history: 

https://signbank.cls.ru.nl/dictionary/gloss/48689/history

**Comment by rem0g** [comment]
I have updated morphology +10 times.

**Comment by susanodd** [comment]
> When updating morphology, it doesnt reflect in gloss history:
> 
> https://signbank.cls.ru.nl/dictionary/gloss/48689/history

Okay, that is the problem.

I have the error log being displayed on the server in the virtual environment.
There are some other errors appearing.
Are you performing some other updates at the same time as that of morphology?
It is complaining about updating the Annotation.

**Comment by rem0g** [comment]
Interesting! But no, I'm only updating morphology.

**Comment by rem0g** [comment]
I think this happens generall as i dont see reflection in history of https://signbank.cls.ru.nl/dictionary/gloss/45744/history

This is also only adding morphology.

**Comment by susanodd** [comment]
Yes, I can see that you updated in in the Gloss Edit?

The changes using Gloss Edit are not saved to the history. (!!)
The history was added more recently and we didn't consistently add all the operations.
I did it for the API operations, and for the new Batch Edit operations (signbank-test).

I need to figure out if something else is going wrong and it doesn't complete the operation.

(I'm working on Delete at the moment. That's going to work with the archived field. So far so good.)

**Comment by susanodd** [comment]
I will add the other Gloss Edit fields to the revision history, except this is going to be delayed because I implemented a nice generic function for this in the batch edit branch. So I don't want to repeat work. That hasn't been approved yet.

**Comment by susanodd** [comment]
I found some more places I can update the lastUpdated field.

**Comment by susanodd** [comment]
@rem0g can you confirm whether or not this is working for you now?

It should be working because there are no other places within the control flow to update the timestamp of the gloss.

**Comment by rem0g** [comment]
Working and closed. Thanks!
