### ISSUE TITLE
Feature request for displaying 3D animation of gloss

### ISSUE THREAD

**Issue by rem0g** [Signbank/Global-signbank#1298]
For this year we have a target to capture a certain amount of signs, it may be between 100-1000 depending on quality of the animations. Now we have about 200 animated signs on signCollect we would like to publish on Signbank. 

We would need: 
- An API to save/overwrite FBX file
- Display FBX file and showing the sign
- Interface to modify the FBX file, that would be: delete and add new FBX file

We already have 3D animation interface running on https://leffe.science.uva.nl:8043/jari/BabylonSignLab/LoadingAnimation/main.html?limit=10. This is developed by me and my colleague Jari. When implementing the interface on Signbank, Jari would be able to assist.  Click on "Load animation sequence and play them", it will then load 10 animations and play them. 

Let me know what is needed to implement such a feature. This is not a priority but deadline would be somewhere in oct/nov. 

Also tagging @uklomp about this topic, and i would like to add Jari Andersen (https://github.com/J-Andersen-UvA) to this issue. Our github repo is: https://github.com/J-Andersen-UvA/BabylonSignLab

**Comment by susanodd** [comment]
- to display the animations within the Gloss Detail View
- a separate Animated Sign View (with links between)
- a separate Search / List View for the animated signs

**Comment by rem0g** [comment]
@uklomp we should discuss this seperatedly with our colleagues. 

Would it be possible to start ahead with backend code and discuss the integration with Jari, Susan?

**Comment by susanodd** [comment]
> @uklomp we should discuss this seperatedly with our colleagues.
> 
> Would it be possible to start ahead with backend code and discuss the integration with Jari, Susan?

Yes, sure.

To connect the code to the rest of signbank, those are suggested "connections". Plus urls, of course.

**Comment by Woseseltops** [comment]
Cooool. Indeed, the backend could already be implemented, I guess it could be called something like `GlossAnimation`, similar to `GlossVideo`, with `fbx` files instead of `mp4` files. 

@rem0g , can you also display these files in a 'small windows'? I'm wondering about the UI, whether it could go in between the video and the image in the gloss detail view.

**Comment by rem0g** [comment]
It would the best to display in a seperate window, indeed. The UI is already busy at it is.

**Comment by Jetske** [comment]
Cool! If no one started on this yet, then I will.

**Comment by susanodd** [comment]
@rem0g does this work on Firefox / Chrome on Ubuntu?
The example link https://leffe.science.uva.nl:8043/jari/BabylonSignLab/LoadingAnimation/main.html?limit=10
just seems to be a guy hanging in space with a pineapple. There isn't any signing going on.

**Comment by susanodd** [comment]
@rem0g do you want your display window (the link you sent with the pineapple), the code to be included in a signbank view, as it is? (But shrunk to fit.) Should this be fetched from your server? Or should the code live on the signbank site?

**Comment by susanodd** [comment]
I created the first "upload new animation" page.

To keep it simple, there is a gloss lookahead for choosing the gloss to upload the animation for.

![upload-new-animation](https://github.com/user-attachments/assets/f263d44f-ae90-46ec-a9fb-6ac962fe27fe)

**Comment by susanodd** [comment]
I put the babylon code that is referred to in the html window on your example into a folder on signbank.
I made a detail view that includes the javascript code.
I modified the src references accordingly to where the files are.

This is what it looks like.

![animation-detail-view](https://github.com/user-attachments/assets/662bdcf0-346c-4702-9724-529f5655497f)


There are a number of bugs. It seems to be wanting to use glb files, which I have put in a /MeshesAndAnims folder (that the code refers to.)
But then it also seems to be trying to do stuff with the same filenames as fbx.
It is unclear what it should actually use.
The issue says to have the fbx files. But the code seems to use the fbx files that it gets from https://leffe.science.uva.nl:8043/gebarenoverleg_media/fbx/ in spite of referring to glb files in MeshesAndAnims.

(Some of the called functions.)

**Comment by susanodd** [comment]
Okay, after much tweaking, I've got the pineapple.

![guy-with-pineapple](https://github.com/user-attachments/assets/064bb7b7-9791-4efa-8964-6f31f534c627)

**Comment by susanodd** [comment]
@rem0g the animation viewer page is here:

- https://signbank-test.cls.ru.nl/dictionary/animation/1



I created one animation using this page:

- https://signbank-test.cls.ru.nl/dictionary/animation/add/

for the gloss APPEL-A, with the fbx from your site.
It's animation with id 1. The above "display" should actually be showing that for apple. But I don't know how to adjust the code yet.

**Comment by rem0g** [comment]
Looks ok! I want to park this for a bit to prioritize other issues.

**Comment by susanodd** [comment]
The branch that includes the UvA javascript animation code has been updated to include the current master code.

That branch is not on any server yet. It is waiting for either signbank-dev or signbank-test to be deployed on.

**Comment by susanodd** [comment]
This should be put back on `signbank-dev`. Are you finished with using that server for the "make install" @vanlummelhuizen ?

**Comment by rem0g** [comment]
Why is this reopened? As far as I see there are still a lot of open issues. Closed.

**Comment by susanodd** [comment]
> Why is this reopened? As far as I see there are still a lot of open issues and we need to figure yet how to display the avatar properly. Closed.

@Jetske reopened it after a meeting at UvA because she said you were asking about how it was going with the animations.

**Comment by Jetske** [comment]
Actually, Floris asked how it was going with the animations as it was the last bigger priority on the list for this year. That's why I reopened the issue. But that was a month ago, so maybe the status has changed.

**Comment by rem0g** [comment]
Ok thank you. This remains closed. I will communicate to him.
