### ISSUE TITLE
index sign doesn't show up in annotated sentences

### ISSUE THREAD

**Issue by uklomp** [Signbank/Global-signbank#1305]
Hi @Jetske,
I thought you were already working on this but I'm not sure anymore so I also made an issue. 
In this annotated sentence https://signbank.cls.ru.nl/dictionary/gloss/44092 - the pointing sign is glossed twice and should appear in the annotations but is not there. It concerns glosses like PT-1hand:1

**Comment by susanodd** [comment]
Maybe related to this?

Q: @Jetske 
I'm working on #1303 and finally have it showing a list. But this took some time.

It seems the data stored in the model `AnnotatedGloss`, the field stored in "`gloss`" is actually an ID, not a foreign key.
So an additional lookup is needed to actually retrieve the `Gloss` object using this ID.
(Normally, if you retrieve the value in a foreign key field it should be an object.)

**Comment by Jetske** [comment]
@uklomp do you happen to have the annotation file for that sentence? I'll look into it asap but that would help to debug it.

**Comment by Jetske** [comment]
@susanodd that's not directly related so let's discuss in another issue.

**Comment by Jetske** [comment]
Found the problem. The annotations are sent to the form as "ann1:ann2:ann3;" and when adding them split by ":" so this obviously fails if the gloss contains a ":". I changed it to json format, that should be more robust.

**Comment by Jetske** [comment]
Sorry, this fix was done in the manage sentences branch, so it will be merged hopefully soon when we complete #1314

**Comment by susanodd** [comment]
The manage annotated sentences is available under the Datasets menu on signbank.

**Comment by susanodd** [comment]
This is live.
