### ISSUE TITLE
AnnotatedGloss model field gloss [CODE]

### ISSUE THREAD

**Issue by susanodd** [Signbank/Global-signbank#1309]
[THIS ISSUE IS ABOUT CODE]

It seems the data stored in the model `AnnotatedGloss`, the field stored in "`gloss`" is actually an ID, not a foreign key.
So an additional lookup is needed to retrieve the `Gloss` object using this ID.
(Normally, if you retrieve the value in a foreign key field it should be an object.)

This method doesn't work:

https://github.com/Signbank/Global-signbank/blob/afaa5ce1006d80e60aee8580606469ee8edd8f50/signbank/dictionary/models.py#L3956-L3957

Inside my loop, I have both the annotated gloss (variable `this`) and the gloss object (`this_gloss`), and the following:

```
    this = AnnotatedGloss.objects.get(id=annotatedgloss_id)
    this_gloss = Gloss.objects.get(id=this.gloss_id)

......

    print(this.annotatedsentence)
    print(this.show_annotationidglosstranslation())
    print(this_gloss.annotationidglosstranslation_set.all())
```

where "this" is an annotated gloss and "this_gloss" is the gloss.
The second print does not output anything, but the first and third do.

_Originally posted by @susanodd in https://github.com/Signbank/Global-signbank/issues/1305#issuecomment-2277504193_

**Comment by susanodd** [comment]
There might need to be a migration to make the ForeignKey be an object and not just an ID ?

(We had this problem with handshapes at the start because they started out as a machine value and needed to become an object. @vanlummelhuizen is an expert in this. Maybe he can take a look.)

**Comment by Jetske** [comment]
I'm not sure that is the problem because the function does work in other places, and gloss is linked to as ForeignKey
See in AnnotatedGloss mode:
`gloss = models.ForeignKey("Gloss", on_delete=models.CASCADE)`

What do you want to retrieve?

**Comment by susanodd** [comment]
Just a guess thinking about this, it may have something to do with how data is created.
Whether the constructor is used, or whether the create_or_get is used.
The constructor creates an object, the create_or_get inserts into the table.
(Need to ask @vanlummelhuizen about this.)

**Comment by susanodd** [comment]
This has been programed away in various places.
