### ISSUE TITLE
Better API docs

### ISSUE THREAD

**Issue by Woseseltops** [Signbank/Global-signbank#1317]
I noticed @rem0g is asking for more documentation (and rightfully so), so I had another look at the wiki... and I noticed that despite my attempts to make it easy to process, it still looks messy. There are multiple cleaner API UIs available, though, so I experimented with translating our API to OpenAPI specs, and then visualizing it with Swagger UI:

https://cls.ru.nl/staff/wstoop/swagger/

It's far from complete, but what do you say @susanodd and @rem0g ? If you like it, I'll make sure to host both the specs and the UI via Github pages, in this repo, so we can all update them.

Notes: the UI also has the option to actually try the API, but that doesn't seem to work yet. It even allows you to define that we use bearer tokens, and allows you to enter your token while experimenting, so it should fully work eventually.

**Comment by susanodd** [comment]
AWESOME @Woseseltops !!

**Comment by rem0g** [comment]
Nice start! That's something I can rely on if i want to test API commands

**Comment by Woseseltops** [comment]
Okay cool. Progress:
* Deployed using Github pages
* Added more endpoints
* Got some endpoints working inside the UI (even with authentication)
* Added dev server to the list

**Comment by Woseseltops** [comment]
I've added them all now! See https://signbank.github.io/Global-signbank/

You can also test some of the endpoints with this tool (didn't test this extensively). For example, this is the result for `get_gloss_data`:

![image](https://github.com/user-attachments/assets/ca6a4bbc-2f18-4620-96c3-a1f98d4c05f4)

You get more data if you put in your auth token.

**Comment by susanodd** [comment]
@Woseseltops did you try using NL?
