### ISSUE TITLE
Morphemes should datasets share them?

### ISSUE THREAD

**Issue by susanodd** [Signbank/Global-signbank#1319]
The Handshapes as they are are shared by all datasets.

The morphemes are used in Simultaneous Morphology. Morphemes are referred to, not glosses. The other two kinds of morphology refer to glosses.

Should the morphemes be available to everybody, as is done for handshapes?

This question is motivated by #1270 where we are making an empty database for VGT.
The handshapes and field choices need to be maintained (they are like predefined data) otherwise signbank won't run without.

**Comment by uklomp** [comment]
I don't think so. The list of morphemes seems very project-specific to me, and the UvA team hasn't been using this feature at all. Handshapes, however, should indeed be shared.

**Comment by susanodd** [comment]
Okay, that is good.
