### ISSUE TITLE
Add field for specific sentence video to annotated sentences

### ISSUE THREAD

**Issue by Jetske** [Signbank/Global-signbank#1327]
A text field must be added to the sentence upload and edit pages. It can contain a url to a specific video (so it's something different than the general source).

Also add this in the API!

**Comment by Woseseltops** [comment]
And if something is added to the API, also add it to the API docs here: https://github.com/Signbank/Global-signbank/blob/master/docs/signbank-api.json

**Comment by susanodd** [comment]
@Jetske on which models does this have a migration?
(dictionary, video) ?

**Comment by Jetske** [comment]
@susanodd only dictionary probably

**Comment by Jetske** [comment]
@susanodd correction: only on video
