### ISSUE TITLE
API functionality for perspective videos

### ISSUE THREAD

**Issue by susanodd** [Signbank/Global-signbank#1333]
This can be implemented now. The models are in the master branch.

The only arguments needed by the API are the gloss id, the video, and "left" or "right"

**Comment by rem0g** [comment]
Is this for Glos Video, NMM video and voorbeeldzinnen? Can I have a link to example API template how to upload left and right video?

**Comment by susanodd** [comment]
This is for the perspective videos.
@Woseseltops wants to do this one. :)

- What naming convention do you use on your side for video files?
- The example perspective videos from @uklomp was the initial character of the filename 'M', 'L', 'R'.
- Normally, the Django form uploads do not look at the filename. A new filename is given to them.
- For perspective videos, then either the filename would need to be inspected, or an extra parameter would be needed for direction.

**Comment by Woseseltops** [comment]
I kinda like the approach where we just add extra parameters to the existing video upload end point. @rem0g , can I get your approval before I implement?

```python
url = 'http://54.93.111.92/dictionary/api_update_gloss/14/video'

# The path to your video file
left_video_file_path = 'left_video.mp4'
right_video_file_path = 'right_video.mp4'

# Auth
headers = {'Authorization': f'Bearer {BEARER_TOKEN}'}

# Open the video file in binary mode and send it in a POST request
files = {'left': open(left_video_file_path, 'rb'), 
         'right': open(right_video_file_path, 'rb')}
response = requests.post(url, files=files, headers=headers)
```

**Comment by rem0g** [comment]
Yes, perfect!

**Comment by Woseseltops** [comment]
To be sure, @rem0g , this is live! :)
