### ISSUE TITLE
Failed to upload videos

### ISSUE THREAD

**Issue by rem0g** [Signbank/Global-signbank#1341]
DISNEY+-C
ALPHEN-AAN-DEN-RIJN
ARMENIË
#BMW
WEEK+1-A
WEEK+2-A
WEEK+3-A
WEEK+4-A
WEEK+5-A
#WWW
#PSV
DISNEY+-A
INFLATIE-B
SAMEN+2-B
SAMEN+3-B
SAMEN+4-B
#CDA
#EUD
#PVDD-B
#PVV
#VVD
#WFD-A
#WFD-B
ANTONI-GAUDÍ
GLETSJER
#ID

Those are the videos I am not able to upload via API.

**Comment by susanodd** [comment]
@rem0g can you try the same command on the `signbank-test` server?

I'm fixing bugs and that has the improved code on it. @vanlummelhuizen identified some bugs in the zip code. Those fixes are on that server.

It has the most recent database on it. (Since yesterday.)

You can see if it completes now.
It ought to report back more errors if it fails in between.
Then @vanlummelhuizen and I can inspect the logs on the server.

**Comment by susanodd** [comment]
After you have done it via the API, if it still does the same, you can do the same zip file via the Manage Media page.

That page does more or less the same, but the error reporting is on the screen. Hopefully it will show the individual files and we can see if it has an error next to them in the listing.
And detect the bugs if that also does not work.

On the branch that's on signbank-test, I modified the code to put the actual message from an attempt from the file system to put the file in the proper location, the message should be in the json now.
Before it was a generic message.

If it's something with the filename on the file system, or something with the path, or something with the GlossVideo object, we need to determine when it's going wrong.

I can see that it has worked to upload some videos. It looks like as above that it doesn't work for special characters in the gloss. This bug could happen at numerous places in the code.
It could also be that the "os.path.join" is not working correctly, that the parameters are not correct when there is a special character.
Some code does something with this, but other code does not. There are server settings that determine whether the files can be saved with special characters.
But some of the code that moves files around using the Python "os" package, and other code uses "shutil".
Some of the file system code for videos does try except with a pass. I'm working to fix those to give feedback.
But since the development servers do not have any video files, this sometimes does not give any helpful information.

**Comment by rem0g** [comment]
Sorry, it is not my responsiblity to find the bugs as why the videos are not able to upload as I'm in process to finish the Signbank project this months because of the deadline in December. Maybe you or one of your colleagues could try that.

In meanwhile I'm still getting error when uploading videos, in total about 800 gloss videos have status as Failed. But yet I see the videos are there. I would like to know when the bug would be fixed.

**Comment by susanodd** [comment]
> Sorry, it is not my responsiblity to find the bugs as why the videos are not able to upload as I'm in process to finish the Signbank project this months because of the deadline in December. Maybe you or one of your colleagues could try that.
> 
> In meanwhile I'm still getting error when uploading videos, in total about 800 gloss videos have status as Failed. But yet I see the videos are there. I would like to know when the bug would be fixed.

Do you have them inside of a zip file and it's only those specific ones that fail, but others do not?

(True / False)

**Comment by susanodd** [comment]
We have the difficulty that we should not put code onto the production server until it is approved.
But for this issue, we need to have the bug fixes already on the production server and not wait for a review.
It is taking several weeks for others to review code on our side. (@Woseseltops)

**Comment by susanodd** [comment]
I deployed the bug fixes so you can try it again on Signbank

**Comment by susanodd** [comment]
https://signbank.cls.ru.nl/dictionary/gloss/48425/

DISNEY+C has a video

**Comment by susanodd** [comment]
I made this (hidden) command that reports video files that do not have a GlossVideo object (pointing to them).

https://signbank.cls.ru.nl/dictionary/missing_video_view/

**Comment by susanodd** [comment]
ALPHEN-AAN-DEN-RIJN 

also has a video

https://signbank.cls.ru.nl/dictionary/gloss/46872/

**Comment by susanodd** [comment]
Did you actually get an error message, but it uploaded to video?
So it reported incorrectly that it failed?
Perhaps it was not finished with one file before it had to report back.

**Comment by susanodd** [comment]
#WWW is also there:

https://signbank.cls.ru.nl/dictionary/gloss/49509/

**Comment by susanodd** [comment]
I can see on the file system, for NGT there are some differences in the permissions on the folders (in which the video files are underneath):

```
drwxrwxr-x 2 root   wwwsignbank  57 Sep 26 09:45  BI
drwxrwxr-x 2 root   wwwsignbank  83 Oct 10 14:30  BL
drwxr-xr-x 2 ubuntu www-data      2 Jul 18 14:26  BM
drwxrwxr-x 2 root   wwwsignbank 110 Oct 11 08:56  BO
drwxrwxr-x 2 root   wwwsignbank  80 Oct 11 09:15  BR
drwxr-xr-x 2 ubuntu www-data      4 Jun  6  2023  BS
drwxrwxr-x 2 root   wwwsignbank  37 Sep 26 09:45  BU
drwxrwxr-x 2 root   wwwsignbank  40 Sep 26 09:44  CA
drwxrwxr-x 2 root   wwwsignbank   5 Sep 26 09:44  CE
drwxrwxr-x 2 root   wwwsignbank  38 Sep 26 09:45  CH
drwxrwxr-x 2 root   wwwsignbank  33 Sep 26 09:44  CI
drwxrwxr-x 2 root   wwwsignbank  14 Oct 11 08:55  CL
drwxrwxr-x 2 root   wwwsignbank  99 Oct 11 08:57  CO
drwxrwxr-x 2 root   wwwsignbank  13 Sep 26 09:45  CR
drwxrwxr-x 2 root   wwwsignbank  13 Oct  7 10:28  CU
drwxrwxr-x 2 root   wwwsignbank   9 Apr 11  2024  CY
drwxr-xr-x 2 ubuntu www-data      3 Jun 26 15:29  D6
drwxrwxr-x 2 root   wwwsignbank  39 Sep 26 09:45  DA
drwxrwxr-x 2 root   wwwsignbank  79 Oct 11 08:57  DE
drwxr-xr-x 2 ubuntu www-data      4 Apr 17  2023  DH
drwxrwxr-x 2 root   wwwsignbank 111 Oct 11 09:39  DI
drwxr-xr-x 2 ubuntu www-data      4 Apr  4  2024  DJ
drwxrwxr-x 2 root   wwwsignbank   3 Mar 30  2023  DN
drwxrwxr-x 2 root   wwwsignbank 136 Oct 11 08:56  DO
drwxrwxr-x 2 root   wwwsignbank  99 Oct 11 08:58  DR
drwxrwxr-x 2 root   wwwsignbank  44 Oct 11 08:59  DU
drwxrwxr-x 2 root   wwwsignbank   3 Mar 30  2023  DV
drwxrwxr-x 2 root   wwwsignbank   7 Mar 11  2024  DW
drwxr-xr-x 2 ubuntu www-data      5 Sep 26 09:44  DY
```

**Comment by susanodd** [comment]
When you upload a video, it should create this folder if it does not exist yet.

**Comment by susanodd** [comment]
The DISNEY files are under DI:
```

-rw-r--r-- 1 ubuntu wwwsignbank 1865797 Oct 11 09:34 DISNEY+-A-48284.mp4
-rw-r--r-- 1 ubuntu wwwsignbank 2328424 Oct 11 09:32 DISNEY+-B-48426.mp4
-rw-r--r-- 1 ubuntu wwwsignbank 2388390 Oct 11 09:32 DISNEY+-C-48425.mp4
-rw-r--r-- 1 ubuntu wwwsignbank  589824 Oct  3 10:32 DISNEY+-D-48424.mp4
-rw-r--r-- 1 ubuntu www-data    1319804 Mar 25  2024 DISNEY-A-47512.bak.bak
-rw-r--r-- 1 ubuntu www-data    1899244 Sep 23 10:09 DISNEY-A-47512.mp4
-rw-r--r-- 1 ubuntu www-data    1805995 Sep 23 10:09 DISNEY-B-47513.mp4
-rw-r--r-- 1 ubuntu wwwsignbank 2260995 Oct 11 08:58 DISNEY-C-48427.mp4
-rw-r--r-- 1 ubuntu wwwsignbank 2442557 Oct 11 08:59 DISNEY-D-48428.mp4
```

If you look at really old videos in the same DI folder, you can see completely different permissions:
```

-rwxrwxr-x 1 root   wwwsignbank  115099 Mar 30  2023 DIRECTEUR-A-1264.mp4
-rwxrwxr-x 1 root   wwwsignbank  144904 Mar 30  2023 DIRECTEUR-B-1221.mp4
-rwxrwxr-x 1 root   wwwsignbank  111013 Mar 30  2023 DIRECTEUR-C-2697.mp4
-rwxrwxr-x 1 root   wwwsignbank  117509 Mar 30  2023 DIRECTEUR-D-4452.mp4
-rwxrwxr-x 1 root   wwwsignbank   28481 Mar 30  2023 DIRECTEUR-D-4452_small.mp4
-rwxrwxr-x 1 root   wwwsignbank  111737 Mar 30  2023 DIRECTEUR-E-4453.mp4
-rwxrwxr-x 1 root   wwwsignbank   32262 Mar 30  2023 DIRECTEUR-E-4453_small.mp4
```

It kind of looks like the DISNEY operations maybe weren't finished and the permissions were not changed.
That could be why it reported an error.
@vanlummelhuizen @Woseseltops  look here.

**Comment by susanodd** [comment]
These videos are also imported, folder WE:

```
-rw-r--r-- 1 ubuntu wwwsignbank 1635091 Oct 11 09:32 WEEK+1-A-49314.mp4
-rw-r--r-- 1 ubuntu wwwsignbank 1997687 Oct 11 09:32 WEEK+2-A-49315.mp4
-rw-r--r-- 1 ubuntu wwwsignbank 1965564 Oct 11 09:32 WEEK+3-A-49316.mp4
-rw-r--r-- 1 ubuntu wwwsignbank 2168597 Oct 11 09:32 WEEK+4-A-49317.mp4
-rw-r--r-- 1 ubuntu wwwsignbank 2278307 Oct 11 09:32 WEEK+5-A-49318.mp4
```

**Comment by susanodd** [comment]
Also imported today:

```
-rw-r--r-- 1 ubuntu www-data    1129128 Oct 11 09:41 7.ORD-A-48453.mp4
-rw-r--r-- 1 ubuntu wwwsignbank 1129128 Oct 11 09:15 7.ORD-A-48453_npDeuuN.mp4
-rw-r--r-- 1 ubuntu wwwsignbank 1129128 Oct 11 09:15 7.ORD-A-48453_vggM2OQ.mp4
-rw-r--r-- 1 ubuntu wwwsignbank 1072651 Sep 19 07:15 7.ORD-B-48454.mp4
-rw-r--r-- 1 ubuntu www-data    1386884 Sep 19 07:01 7.ORD-C-48465.mp4
```

You can see by the weird file names that reversion was done apparently.

**Comment by susanodd** [comment]
@vanlummelhuizen what is causing the video files to have different owners and different groups?

**Comment by susanodd** [comment]
There have been zero errors in the Apache log today.

**Comment by susanodd** [comment]
https://github.com/Signbank/Global-signbank/issues/1331#issuecomment-2410156648

**Comment by vanlummelhuizen** [comment]
> @vanlummelhuizen what is causing the video files to have different owners and different groups?

I think it is because some videos are uploaded through the website (www-data) or from a zipfile (wwwsignbank). Why different groups I don't know.

**Comment by susanodd** [comment]
> > @vanlummelhuizen what is causing the video files to have different owners and different groups?
> 
> I think it is because some videos are uploaded through the website (www-data) or from a zipfile (wwwsignbank). Why different groups I don't know.

Can this ever be a problem?

**Comment by susanodd** [comment]
- This has been addressed in other issues.


- Plus there is a new management page for inspecting stored GlossVideo objects and their paths.
