### ISSUE TITLE
Missing still picture from video on irregular basis

### ISSUE THREAD

**Issue by rem0g** [Signbank/Global-signbank#1346]
I am getting reports from colleagues there is sometimes picture missing from video still, for example: 

https://signbank.cls.ru.nl/dictionary/gloss/49457/

**Comment by susanodd** [comment]
I noticed this error too, but I can't fix it. Sometimes the script that generates them does not work. I suspect it has to do with permissions on the file system. Another possibility is that the video coding is not as expected by the code that generates the image.

**Comment by vanlummelhuizen** [comment]
> I am getting reports from colleagues there is sometimes picture missing from video still, for example:
> 
> https://signbank.cls.ru.nl/dictionary/gloss/49457/

In the logs I found

```
Video file: /var/www/writable/FIETSEN-B-49457.mp4
ffmpeg -v quiet -i /var/www/writable/FIETSEN-B-49457.mp4 -filter:v scale='iw*max(1,sar)':'ih*max(1,1/sar)' /var/www/writable/tmp/signbank-ExtractMiddleFrame/FIETSEN-B-49457.mp4-frames/all/frame-%5d.png
```

There is no error. But I  noticed that the path  of the video file does not include 'glossvideo' and dataset acronym. Perhaps this is a problem. I will investigate further. 

@rem0g how was this video uploaded: via the website of using the API with zip file?
In the meantime, you can extract a still image from the video by clicking `Create` under *Create Citation Form Image from Current Video* in edit mode.

**Comment by susanodd** [comment]
I made this  (hidden) url to show the video files that do not have a GlossVideo object. (There was already a command to do this that was hidden. I merely modified the code to look at the files.)

(It assumes the correct video path where it looks.)

https://signbank.cls.ru.nl/dictionary/missing_video_view/

**Comment by susanodd** [comment]
Some places in the code use a string coercion on a GlossVideo file object to retrieve the path/name (?)

I will look for them. (As above, PyCharm complains about using path or url. So probably that is why code is using a string coercion.)

**Comment by susanodd** [comment]
[API ZIP ARCHIVE]

Probably the Squiggle API tester is not correct.

This api for the zip archive was *before* the API token, so it relies on the user being "logged in".
The zip file itself is in a url as a GET parameter. (I am rewriting this code to put it inside the request. #1344, but running into some file system permission problems)

**Comment by susanodd** [comment]
I found another code that could affect the path of the GlossVideo:

https://github.com/Signbank/Global-signbank/blob/a9a4110ebbff99a3fed4d6db65caeadc9919c8b1/signbank/video/models.py#L165-L167

Is it possible that this could set the path to empty?

**Comment by susanodd** [comment]
The zip imported files use the correct path when the still image is being created.
I just got the new version working and it logs the create image paths as you show above. Those are correct.

**Comment by susanodd** [comment]
@rem0g is this still a problem?

I might be that the video has a wrong format. The conversion to mp4 is no longer done (as previously requested for the API)

**Comment by rem0g** [comment]
I havent heard anything from colleagues, so this can be closed and reopened later when problem appears back.
