### ISSUE TITLE
two weird things when searching for annotated sentences

### ISSUE THREAD

**Issue by uklomp** [Signbank/Global-signbank#1363]
When I go to Signs -> Search annotated gloss -> and search for .* to see all annotated sentences, I get this: 

Annotated Glosses  Number of Matches: 542 out of 664. Datasets: NGT

1. Why are 542 out of 664 shown, and not all of them? 
2. On the right, "results per page" says that 500 sentences are not shown but this is not correct, I think some 25 glosses are shown per page. Which is a nice number of results per page, I would say, I don't want the 500 to be shown, but it's weird that it pretends to show 500 results.

**Comment by susanodd** [comment]
This is completed.
