### ISSUE TITLE
Cleanup old and completed issues

### ISSUE THREAD

**Issue by rem0g** [Signbank/Global-signbank#1367]
It would make sense to close issues before start of 2024 and check issues of 2024 if they are completed already. Who is willing to do this?

**Comment by Woseseltops** [comment]
Discussed this with @uklomp yesterday (probably not a coincidence). It's on my schedule for Nov 8!

**Comment by Woseseltops** [comment]
I've looked at every issue that was still open, and indeed closed quite a few. All of the remaining ones are (1) issues we want to remember, but won't work on immediately (marked 'lower priority') or (2) issues that a developer looking for a task could work on. As far as I'm concerned we can continue using the 'high priority' and 'blocking' labels to distinguish the issues that need attention right now.
