### ISSUE TITLE
can a lemma still have multiple glosses?

### ISSUE THREAD

**Issue by uklomp** [Signbank/Global-signbank#1376]
When changing a lemma, we sometimes get the error that the lemma is not unique. But this is not a problem, right? A lemma can have multiple glosses and this is even what it is meant for. How come we get this error? An example: the glosses VERANDEREN-A, -C, -D are under the lemma 'veranderen'. But the gloss VERANDEREN-B has its own lemma 'veranderen-b' per accident. If I want to change it to 'veranderen', I get the message: Lemma ID Gloss is not unique for that language.

**Comment by susanodd** [comment]
> When changing a lemma, we sometimes get the error that the lemma is not unique. But this is not a problem, right? A lemma can have multiple glosses and this is even what it is meant for. How come we get this error? An example: the glosses VERANDEREN-A, -C, -D are under the lemma 'veranderen'. But the gloss VERANDEREN-B has its own lemma 'veranderen-b' per accident. If I want to change it to 'veranderen', I get the message: Lemma ID Gloss is not unique for that language.

Yes, a lemma can still have multiple glosses. That is true. But this is not allowed to do it in the API.

In order to do it, a different kind of command is needed. The ID of the (shared) lemma needs to be used instead of "text".
At the moment, you can only change this in Gloss Edit.

**Comment by uklomp** [comment]
I did 'choose other' now and I chose VERANDEREN, I clicked 'set lemma' and it doesn't work: 

<img width="1920" alt="image" src="https://github.com/user-attachments/assets/f1757aa0-2885-469f-85d8-157529a200b6">

**Comment by susanodd** [comment]
Okay, I know what is causing that. (It's in the signals code that wants to move around video files.)

**Comment by susanodd** [comment]
@uklomp this should be working now! I just deployed it.
