### ISSUE TITLE
BUG: {"error": "Upload zip archive: The folder API_VIDEO_ARCHIVES is missing."}

### ISSUE THREAD

**Issue by rem0g** [Signbank/Global-signbank#1384]
When uploading new video's i am getitng: 

{"error": "Upload zip archive: The folder API_VIDEO_ARCHIVES is missing."}

**Comment by susanodd** [comment]
Yes, I just fixed that.

I modified the url to be a POST request, as requested. It's documented in Swagger.

**Comment by rem0g** [comment]
What url? My script is using: "https://signbank.cls.ru.nl/dictionary/upload_zipped_videos_folder_json" and "https://signbank.cls.ru.nl/dictionary/upload_videos_to_glosses/5/"



Can I use /dictionary/api_update_gloss/{glossid}/video now?

Thanks! 

Gomer

**Comment by susanodd** [comment]
> What url? My script is using: "https://signbank.cls.ru.nl/dictionary/upload_zipped_videos_folder_json" and "https://signbank.cls.ru.nl/dictionary/upload_videos_to_glosses/5/"

The upload one is now POST instead, so the file does not need to be in the url.

> Can I use /dictionary/api_update_gloss/{glossid}/video now?

YES!!!

> 
> Thanks!
> 
> Gomer

**Comment by rem0g** [comment]
It's working. Thanks!
