### ISSUE TITLE
Excess number of backup videos being created with version 1

### ISSUE THREAD

**Issue by susanodd** [Signbank/Global-signbank#1397]
For some reason, numerous video uploads are being done for the same gloss repeatedly, each creating a new backup of the previous video upload. Sometimes upwards of 30 video files. There are matching requests for each of these. "Op hol slaan"

**Comment by Jetske** [comment]
After asking @rem0g  it turns out this was probably an upload script stuck in a loop. Has been fixed. 

To clean up the duplicate backup files, is there already command for that (if so I can't find it)? Or what would be the best way to do this?

**Comment by susanodd** [comment]
There were some more today, so I don't know if it's totally fixed.

There isn't a command for them. The files need to be deleted before you can delete the objects.
But then the version numbers need to be modified, because they won't be correct anymore.
I was working on that for the old format "bak.bak" files. But I didn't delete files. I only removed objects if there was no file.
The enumerated over what was left to give them new version numbers.
I'm guessing thought that all the backup files created can safely be deleted.

I guess we could implement a command to do that in the admin.
The files need to be "unlinked". You can see that in the video code.

If you just remove the files you can also just remove the objects.
We don't really know how extensive this is.

**Comment by susanodd** [comment]
1. unlink the file if a file exists
2. delete the object
3. renumber all the versions of all the other backup videos for the same gloss

**Comment by susanodd** [comment]
See #1412 a command has been added to the Manage Video Storage to repair incorrect version numbering

**Comment by susanodd** [comment]
This is fixed now. Some administration functionality is being added in order to repair the wrongly numbered gloss video objects and their files, if necessary. (#1406 )
