### ISSUE TITLE
Allow for more keyboard use in Edit mode

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#140]
- In particular, enable use of tab to jump from editing a value in a text box or selecting a menu item to the OK button, then allow for enter to "press the OK button" / confirm the change

**Comment by Woseseltops** [comment]
Looks like the problem you're trying to solve here is that editing a (for example) phonology field takes these actions:
1. Go to the page
2. Click the edit button
3. Open the phonology panel
4. Scroll down
5. Click the field
6. Change it
7. Click okay to confirm

Proposal to make this shorter:
1. Go to the page
2. Hit 'P' to go to edit mode, open the phonology panel and scroll to it 
3. Click the field
4. Change it and hit enter to confirm 

I count 4 as one action as your hands don't need to leave the keyboard after typing.

Besides P, we could have M for morphology, S for semantics, etc.

**Comment by Woseseltops** [comment]
P, M and S already go to edit mode, and open the correct panels!

**Comment by ocrasborn** [comment]
I love this proposal! Go ahead!

**Comment by Woseseltops** [comment]
Fixed the problem by adding this oneliner... 

`if (document.activeElement.tagName == 'INPUT') {return;}`

... meaning that shortcuts are ignored if you're in a text field. I also added that the panel corresponding to the shortcut (phonology, morphology, semantics) scrolls into view. @ocrasborn , can you educate Signbank users about this?

**Comment by susanodd** [comment]
This has been expanded in #628. Now, inside Phonology, once you've selected your item in a list, if you hit return, you jump to the next field list.
