### ISSUE TITLE
Retrieve more signs when working with function 'split up senses'? 

### ISSUE THREAD

**Issue by uklomp** [Signbank/Global-signbank#1400]
Would it be possible to retrieve / analyse about 500 glosses in the function "Split up senses", instead of max 100? 
If the answer isn't easy, let's talk about it tomorrow.

**Comment by Woseseltops** [comment]
Proposal: just try to make it longer. If our browsers explode (the page might to heavy to everything at once) we move to an Ajax-based approach like @susanodd pioneered herself within Signbank.

**Comment by susanodd** [comment]
This is on `signbank-susan` now.

I can't tell whether the browser is choking on the amount of code. The "debug" of Firefox won't show all the nodes.

Can you try it out @Woseseltops ?

**Comment by susanodd** [comment]
@uklomp to clarify, do you want 500 search results, or 500 results per page?

What would be ideal?

It's on signbank-susan now so you can test it.

**Comment by uklomp** [comment]
Ideally, we get all the results from the search query, and still have the option to show a limited number per page - let's say 50 or 100 per page.

**Comment by susanodd** [comment]
> Ideally, we get all the results from the search query, and still have the option to show a limited number per page - let's say 50 or 100 per page.

Okay, that is good to hear for the results per page. That should be possible.

For a technical question about the browser truncating data, I need to ask @Woseseltops. It's a problem with the amount of data per page.

**Comment by susanodd** [comment]
This is live now on Signbank.
