### ISSUE TITLE
Recover glos video BINNEN-B 727

### ISSUE THREAD

**Issue by rem0g** [Signbank/Global-signbank#1402]
Can you please restore backup of BINNEN-B?

**Comment by susanodd** [comment]
> Can you please restore backup of BINNEN-B?

It looks like it's there:

https://signbank.cls.ru.nl/dictionary/gloss/727/

**Comment by rem0g** [comment]
It would be the first one:

-rwxrwxr-x 1 root   wwwsignbank  154465 Mar 30  2023 BINNEN-726.mp4

**Comment by susanodd** [comment]
https://github.com/user-attachments/assets/f1b131fc-223e-40f0-86f2-0b7c25370ba3

**Comment by susanodd** [comment]
> > @rem0g do you recall how you deleted the BINNEN gloss here #1402 ?
> > There was no information about it stored in the DeletedGlossOrMedia table.
> > Thanks in advance
> 
> The video was overwritten by accident because of wrong ID that was used in signcollect table, we never delete videos.

Okay, thanks. I'll work with that.
