### ISSUE TITLE
export ECV updates ECV but doesnt download it

### ISSUE THREAD

**Issue by uklomp** [Signbank/Global-signbank#1411]
I'd like to use the ECV of the NGT dataset in ELAN and wanted to download it from this page https://signbank.cls.ru.nl/datasets/available 

I thought the button for 'export' would let me download it, but instead, it says 'ECV successfully updated' and I don't have a download. Is this what should happen? If yes, can we also have a download function?

**Comment by susanodd** [comment]
Okay, because this involves changes to the settings because of a problem with a setting for the location of the ECV files, this did not deploy the most recent code to Signbank.

**Comment by uklomp** [comment]
thanks!
