### ISSUE TITLE
Create a general signbank email account

### ISSUE THREAD

**Issue by Jetske** [Signbank/Global-signbank#1416]
This will be useful for connecting to e.g. Sign Wordnet (https://www.sign-lang.uni-hamburg.de/easier/sign-wordnet/index.html) where it is necessary to log in to download the files needed for updating the synsets (through a django command). With a general email, it does not need to be linked to one person specifically.

**Comment by Woseseltops** [comment]
Requested

**Comment by Woseseltops** [comment]
Apologies, never reported here that this was created on the same day! signbank@cls.ru.nl
