### ISSUE TITLE
Page 'manage annotated sentences' doesn't work

### ISSUE THREAD

**Issue by uklomp** [Signbank/Global-signbank#1439]
My colleague and I both can't open the page 'manage annotated sentences', we get the following error: 

<html>
<body>
<h1 style="padding: 0px; margin: 0px; font-weight: normal; color: rgb(0, 0, 0); font-family: sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">NameError at /annotatedsentences/show_all/</h1><pre class="exception_value" style="padding: 0px; margin: 10px 0px; font-size: 1.5em; white-space: pre-wrap; word-break: break-word; font-family: sans-serif; color: rgb(87, 87, 87); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">name 'get_selected_datases' is not defined</pre>
Request Method: | GET
-- | --
http://signbank.cls.ru.nl/annotatedsentences/show_all/
4.2.17
NameError
name 'get_selected_datases' is not defined
/var/www/repo/signbank/dictionary/adminviews.py, line 364, in get_queryset
signbank.dictionary.adminviews.AnnotatedSentenceListView
/usr/bin/uwsgi
3.12.2
['.',  '',  '/usr/lib/python312.zip',  '/usr/lib/python3.12',  '/usr/lib/python3.12/lib-dynload',  '/var/www/env/lib/python3.12/site-packages']
Tue, 17 Dec 2024 10:38:06 +0100

</body>
</html>

--

I used Chrome and she used Firefox.

**Comment by susanodd** [comment]
That has to be a deployment problem.

I just checked to confirm the Python code is correct.

<details>
The `get_selected_datases` function is correctly imported into the Python file `adminviews.py`

Guess: the python file was not compiled to match the updated python code file.

**Comment by GalyaSTERN** [comment]
Hey it still does not work for me and also not for Ulrika

**Comment by susanodd** [comment]
Okay, thanks. I see there is another similar bug with the Search Annotated Glosses page.

(The type-checker in editor does not seem to catch all the errors.)

Just a sec.

**Comment by susanodd** [comment]
@GalyaSTERN @uklomp this should be working now, both pages!

**Comment by uklomp** [comment]
thank you!
