### ISSUE TITLE
glosses appear twice on split senses page

### ISSUE THREAD

**Issue by uklomp** [Signbank/Global-signbank#1442]
My colleague searched for Dutch glosses starting with a B and then used the split senses page, but some glosses appear twice. We'd like to have unique results only.

![image](https://github.com/user-attachments/assets/d460b2e3-e16f-43ae-b54c-9238ae663020)

**Comment by susanodd** [comment]
Yes, I see.

**Comment by susanodd** [comment]
@uklomp it should be working now.

**Comment by uklomp** [comment]
oke, thanks!
