### ISSUE TITLE
roles and rights

### ISSUE THREAD

**Issue by uklomp** [Signbank/Global-signbank#1443]
Where can I find what the viewing and editing rights are per role? 
So what can you do as an Guest, Editor, Publisher, Researcher and Dataset_Manager ?

**Comment by uklomp** [comment]
right, thank you so much :)

**Comment by susanodd** [comment]
Just to add, Anonymous users do not have any of these permissions!

The code needs to explicitly "do stuff" in the case of anonymous users. (Mainly to prevent them from doing things.)

Guest users are users with an account that have been put in group Guest.

**Comment by uklomp** [comment]
Ok, but the public view is accessible for anonymous users, right?

**Comment by susanodd** [comment]
> Ok, but the public view is accessible for anonymous users, right?

Yes, that's correct.

I wrote that to make sure you know that Anonymous is different than the group Guest. 
Group Guest has some permissions. Onno would put students and people in workshops into group Guest.
Anonymous can't store any information about the user. For the public (anonymous) view, stuff can only be stored in session variables.
