### ISSUE TITLE
Trying to recover a deleted gloss throws an error

### ISSUE THREAD

**Issue by ghost** [Signbank/Global-signbank#155]
in the Django admin, at Home › Dictionary › Glosses, you can recover glosses (button in the upper right corner). However, most glosses (in a random sample) throw an error like the following:
###### 'NoneType' object is not iterable

Request Method:     GET
Request URL:    http://signbank.science.ru.nl/admin/dictionary/gloss/recover/18179/
Exception Type:     DeserializationError
Exception Value:    'NoneType' object is not iterable
Exception Location:     /var/www2/signbank/live/virtualenv/signbank/lib/python2.7/site-packages/django/core/serializers/python.py in Deserializer, line 117

Please fix.

**Comment by richardbank** [comment]
Related to this (same error) is when I try to view the Change History of a gloss. Take for example gloss UUR-LANG+10-C. This gloss has 5 history states. The most recent two and the oldest are viewable (and supposedly recoverable), however the other two throw the same error as above:

##### DeserializationError at /admin/dictionary/gloss/2630/history/25421/
###### 'NoneType' object is not iterable
Request URL: 	http://signbank.science.ru.nl/admin/dictionary/gloss/2630/history/25421/
Exception Type: 	DeserializationError
Exception Value: 	'NoneType' object is not iterable
Exception Location: 	/var/www2/signbank/live/virtualenv/signbank/lib/python2.7/site-packages/django/core/serializers/python.py in Deserializer, line 117

**Comment by henrinie** [comment]
One thing to remember about this gloss recovering feature and the gloss (version) history feature:
They will not work if the model has been changed in a way that the stored versions of the glosses don't meet the requirements/restrictions of the new model.

So if someone is relying on these features, changes to the models should be avoided.

And to answer this issue @richardbank has created:
The versions are stored in json format in the database. Might it be that the data is missing completely for these *versions* that throw errors, or that some of the fields values are empty?
The data in the database is stored in a table called reversion_version which has a ForeignKey to reversion_reversion. Maybe by looking in these you could get more insight into this problem.

**Comment by vanlummelhuizen** [comment]
Closing this issue as no longer relevant.
