### ISSUE TITLE
Build Signbank package functionality

### ISSUE THREAD

**Issue by Woseseltops** [Signbank/Global-signbank#187]
This is a sub-issue for #186 .

Subsubtasks:
- Create a function that turns the Signbank database into JSON, taking only the simple fields.
- Include the references to other tables (languages, keywords, etc) into the JSON.
- Create function that lists the urls to all videos and images in a json file. 
- Create a function that creates a package, with al the JSON files.
- Make the last function accessible from a url.

**Comment by Woseseltops** [comment]
The final result should be that going to `signbank.science.ru.nl\package` would result in something like:

```
Signbank_package.123456.zip
* glosses.json
* video_urls.json
* image_urls.json
```

where 123456 is the timestamp.

**Comment by Woseseltops** [comment]
Already did:

> Create function that lists the urls to all videos and images in a json file.

You enter either 'glossvideo' or 'glossimage', and out comes a list of urls that can later be packaged into JSON.

**Comment by Woseseltops** [comment]
Also did

> Create a function that creates a package, with al the JSON files.
> Make the last function accessible from a url.

Give it a try at http://signbank.science.ru.nl/dictionary/package . For the creation of the zipfile I created a function create_zip_with_json_files, that takes a dictionary with filenames as keys and file content as values. This content can be either a json string or a list, which will then be transformed to a json list.

**Comment by ocrasborn** [comment]
@Woseseltops , can you make sure this will only work for authenticated users -- and ideally just the system and Administrators?

**Comment by Woseseltops** [comment]
Added argument small_videos=true at the request of @vanlummelhuizen . It does not work yet, because (1) the small videos are not yet in the correct location and (2) there is some weird problem with a regex added by @vanlummelhuizen .

Two questions for @vanlummelhuizen:
* Shall I also move all small videos to glossvideo_small ?
* Could you fix that regex problem (when back from holiday)? I tried, but it did not fully understand what the regex was supposed to do and did not want to spend too much trying to figure that out.

**Comment by vanlummelhuizen** [comment]
@Woseseltops 
> Shall I also move all small videos to glossvideo_small ?

Yes, please.

> Could you fix that regex problem (when back from holiday)? I tried, but it did not fully understand what the regex was supposed to do and did not want to spend too much trying to figure that out.

What regex exactly? I might look into it if I got bored (or I am too tired to lift anything, or ...). Don't count on it though.

**Comment by ocrasborn** [comment]
Can this be closed now, @Woseseltops and @vanlummelhuizen ?

**Comment by Woseseltops** [comment]
Closed. Made a separate issue for the last remaining thing, so you can prioritize https://github.com/Signbank/Global-signbank/issues/447 , @ocrasborn
