### ISSUE TITLE
Build Signbank patch functionality

### ISSUE THREAD

**Issue by Woseseltops** [Signbank/Global-signbank#188]
This is a sub-issue for #186 .

Sub-subtasks:
- Create a function a that takes a path and a date as input, and returns a list of all filenames newer than date.
- Keep a list/database of deleted files and their deletion dates.
- Add an item to this database each time a video or image is deleted.
- Add a field 'last_modification_date' to glosses.
- Update the above field every time something is changed.
- Keep a list/database of deleted glosses and their deletion dates.
- Add an item to this database each time a video or image is deleted.
- Create a function b that returns all glosses with a last_modification_date newer than x.
- Create a function c that returns all glosses/videos/images deleted since date x.
- Create a function that creates a package with the results of functions a, b and c.
- Make the last function accessible from a url.

**Comment by Woseseltops** [comment]
The final result should be that going to signbank.science.ru.nl\package?from_timestamp=12345 would result in something like:

```
Signbank_patch.12345-34567.zip
* glosses.json
* videos_urs.json
* image_urls.json
* deleted_glosses.json
* deleted_videos.json
* deleted_images.json
```

**Comment by Woseseltops** [comment]
Already did:

> Create a function a that takes a path and a date as input, and returns a list of all filenames newer than date.

You enter either 'glossvideo' or 'glossimage', and a timstamp, and out comes a list of urls that can later be packaged into JSON.

**Comment by Woseseltops** [comment]
Also did

> Create a function that creates a package with the results of functions a, b and c.
> Make the last function accessible from a url.

Give it a try at https://signbank.science.ru.nl/dictionary/package/?since_timestamp=1438992000 . For the creation of the zipfile I created a function create_zip_with_json_files, which takes a dictionary with filenames as keys and file content as values. This content can be either a json string or a list, which will then be transformed to a json list.

**Comment by Woseseltops** [comment]
@vanlummelhuizen , today I had a go at storing the data needed for deleted_glosses.json . Reversion, a Django-extension we use, does store history but does not store deletion dates (see #149). One option was to extend it, but I chose to create my own DeletedGloss object instead because reversion is a separate Python package with a separate database; it is unclear what would happen if we would modify this for a live project. Furthermore, it is likely that we will want to make changes or extend how we want to store info about deleted glosses in Signbank, and with the DeletedGloss object we can do this easily.

The division of labour between the two is thus: reversion is for gloss versioning and recovery, DeletedGloss is for saving gloss deletion dates in the Signbank database for the patch functionality. I have committed my work so far, including migration files. 

To do:
* Make the stored data actually available in deleted_glosses.json
* Check what happens when you recover a gloss with reversion.

**Comment by Woseseltops** [comment]
Okay, deleted_glosses.json is now filled.

@vanlummelhuizen , please look at 9068914

Subtasks remaining:
* Extending the database of deleted things with images and videos.
* Check what happens when you recover a gloss with reversion.

**Comment by vanlummelhuizen** [comment]
@Woseseltops Deleting a gloss on my local development environment leads to the following error:

```
Exception Value: 	

int() argument must be a string or a number, not 'NoneType'

Exception Location: 	/home/micha/sources/projects/signbank/source/virtualenv/signbank/local/lib/python2.7/site-packages/reversion/revisions.py in get_version_data, line 100
```

Any idea where this error may came from?

**Comment by Woseseltops** [comment]
Yes this is #244, @vanlummelhuizen

**Comment by Woseseltops** [comment]
Also completed: `Extending the database of deleted things with images and videos.` That is, deleted_images.json and deleted_videos.json are now also present.

Remaining:
* Check what happens when you recover a gloss with reversion.

**Comment by vanlummelhuizen** [comment]
@Woseseltops I saw deleted_videos.json and deleted_images.json contain the path to those files as they were on the server. I think it will be a good thing to make them similar to video_urls.json, so gloss ID and download url, but leaving out download url. So only gloss ID. 

I will try to do this now.

**Comment by vanlummelhuizen** [comment]
Done that.

**Comment by ocrasborn** [comment]
Can this be closed now, @Woseseltops and @vanlummelhuizen ?

**Comment by Woseseltops** [comment]
Closed. We're unsure how the patch functionality works in combination with glosses that were first deleted and then recovered with the reversion extension. I believe reversion is barely used, but if you want to verify/add support for this feel free to create another issue, @ocrasborn .
