### ISSUE TITLE
Convert existing videos to thumbnail versions

### ISSUE THREAD

**Issue by vanlummelhuizen** [Signbank/Global-signbank#196]
For ELAN to show gloss videos, it only needs small versions. For efficiency, the conversion should be done on the server so that downloading will be quick and converting is not left to each individual ELAN instance.

**Comment by vanlummelhuizen** [comment]
Converting videos to half the height and half the width:

`ffmpeg -i <input file> -filter:v scale="'trunc(iw*max(1,sar)/4)*2':'trunc(ih*max(1,1/sar)/4)*2'" <output file>`

Note that on Ubuntu the ffmpeg command is `avconv`.

The strange scale formula is for keeping the aspect ratio correct and make both the height and the width dividable by 2 which is necessary for x264 encoding.

Also applicable to #197.

**Comment by vanlummelhuizen** [comment]
Yes, what was the definitive amount of frames?

**Comment by ocrasborn** [comment]
10 at the start, 30 at the end

**Comment by vanlummelhuizen** [comment]
@ocrasborn I think I am going to write a dedicated Python script for this, since there is stuff that is hard to do from the command line. OK?

@Woseseltops If OK, I will make it available similar to https://github.com/vanlummelhuizen/CNGT-scripts/blob/master/python/signCounter.py .

**Comment by ocrasborn** [comment]
of course OK!

**Comment by vanlummelhuizen** [comment]
@Woseseltops The script can be found at https://github.com/vanlummelhuizen/CNGT-scripts/blob/master/python/resizeVideos.py

**Comment by vanlummelhuizen** [comment]
This also needs a change in the packaging system so that the video/image urls are refering to the small videos.

**Comment by ocrasborn** [comment]
@Woseseltops , what is still required from me here?

**Comment by Woseseltops** [comment]
Nothing afaik, @ocrasborn , @vanlummelhuizen added you as an assignee in August ;)

**Comment by ocrasborn** [comment]
@vanlummelhuizen , can this be closed now?

**Comment by vanlummelhuizen** [comment]
@ocrasborn yes
