### ISSUE TITLE
Restrict access to data sets dependent on user

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#223]
When data for multiple sign languages are entered, we need to be able to restrict access for users to specific languages. Perhaps by adding a list of data sets as a separate pane in the admin/users or admin/groups interface?

**Comment by ocrasborn** [comment]
See https://github.com/Signbank/FinSL-signbank/issues/180

**Comment by susanodd** [comment]
For export_csv, this should be working because the Gloss List query now restricts the results to the selected datasets, or if none are selected, to those the user is allowed to view. The export_csv exports the results of the query.

**Comment by susanodd** [comment]
The import_csv only allows import into the datasets the user has access to.

**Comment by susanodd** [comment]
The code for Gloss Detail also only allows setting / updating to datasets the user has access to.

**Comment by susanodd** [comment]
Curiousity, there is no display of the Dataset when inside the Morpheme Detail View, yet in the Datasets pulldown menu Available Datasets where it shows the datasets the user has access to, the counts shown include both glosses and morphemes.
So it's not entirely clear how a morpheme's dataset gets set.

**Comment by susanodd** [comment]
Ah, it seems the Edit button in the Morpheme Detail view isn't working.

**Comment by susanodd** [comment]
Okay, the Edit button has been repaired.

**Comment by ocrasborn** [comment]
I should have made this explicit right from the start, but now Susan made me aware: both glosses and morphemes should belong to datasets! And so everything we do for glosses should also happen for morphemes (restricting access, specifying for dataset, visualising, enforcing specification on CSV import, listing in CSV export, ...).

**Comment by vanlummelhuizen** [comment]
Adding a morpheme from the morpheme search page does require the user to select a dataset.
So far so good.

**Comment by vanlummelhuizen** [comment]
Morpheme search wasn't using datasets. Now it is. (Not live as of this writing.)

**Comment by vanlummelhuizen** [comment]
I added object permission check for the morpheme detail view. 

I also made the checking of permissions a bit more strict: before the *global* permission used and tje global 'view_dataset' permission was enough to view *all* datasets. Now, only the *object* permission are used.

**Comment by ocrasborn** [comment]
Way cool, man. 8-)
Any open ends here, or can we close this issue?

**Comment by vanlummelhuizen** [comment]
I think we need to check the CSV import/export. Hold on.

**Comment by vanlummelhuizen** [comment]
OK, exporting a morpheme CSV seems to be correct.

**Comment by vanlummelhuizen** [comment]
Importing an CSV is for staff or members of the group Publisher only. That goes for both morphemes and glosses, as far as I can see. No, dataset permission are involved. What say you, @ocrasborn ?

**Comment by ocrasborn** [comment]
Ah! That's not good. Any dataset editor should be able to import CSV files to be able to batch change data. I don't see a permission that I can assign myself to a group though, is that right?
And after assigning it to Editors, please link it to data set object permission 'edit'.

**Comment by vanlummelhuizen** [comment]
Now, for each row in the CSV the dataset is checked against the list of datasets the user has the 'change_dataset' permission for.

**Comment by ocrasborn** [comment]
👍
