### ISSUE TITLE
Create dataset field separate from language field

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#224]
* See FinSL Signbank who have a notion of 'dataset'
* It may be better to create something like this, rather than use the existing language field for separating datasets for different languages. The reason is that we also want to include loan signs from other sign languages in NGT Signbank that have not yet lexicalised in NGT, whereas we do find them used in our corpus. (Or in other words, there is code-mixing in our corpus, we do want to include glosses for foreign signs in NGT Signbank to describe this use.)

**Comment by henrinie** [comment]
We are indeed using this kind of separation for 'lexicons'(?), we currently have two datasets that are of the same language.
We changed the behaviour of the Language field, glosses no longer have a connection to language(s), the language is stored in the Dataset. This is because we don't expect to have multiple languages in a Dataset.

The original Language now is SignLanguage, and it represents signed languages, and describes what sign language the Dataset is based of.

We use Language in Dataset as well to define the amount of translation fields each Datasets glosses will have. Language is a many-to-many field in Dataset, you can set multiple languages for a Dataset, and the gloss page will show translations for these languages in the gloss page.

**Comment by ocrasborn** [comment]
Thanks @henrinie . That sounds like a good idea to me, moving Language to Dataset as a variable that determines which gloss fields there are, and distinguishing it from SignLanguage as a property for the signs for which we now use Language. If I understand you correctly.
We originally thought we might also use Language in its current form to indicate loan signs from other languages, but we should use the panel Relation to Foreign Signs for that, that makes more sense.

**Comment by henrinie** [comment]
> moving Language to Dataset as a variable that determines which gloss fields there are
Did you mean translation fields? For each dataset you can set multiple languages, the glosses will then have a translation field for each of the languages. So you don't need to define the translation fields in the code.

SignLanguage is what Language was before.

**Comment by ocrasborn** [comment]
We actually need both translations of the gloss, and translations of the translation equivalents (or really, separate translation equivalents in that other language).

**Comment by henrinie** [comment]
> We actually need both translations of the gloss, and translations of the translation equivalents (or really, separate translation equivalents in that other language).

Sorry for unclear communication!
I meant translation equivalents, not translations of the gloss. We will probably do the same for translations of the gloss names later.

**Comment by ocrasborn** [comment]
See the useful overview on what 'language' can mean in #182 by @Woseseltops

**Comment by vanlummelhuizen** [comment]
### How to do the 'modeltranslation' and related migrations

This relates to commits: 49b3152, c35b0a4, 67c1ff4, 2179dc5, 1e9ce6c

0. Make backup
1. Install modeltranslation: `pip install django-modeltranslation`
2. Pull from git
3. `python bin/develop.py migrate dictionary 0009_auto_20170802_1541`
4. `python bin/develop.py loaddata signbank/dictionary/fixtures/ngt_data_languages.json`
5. `python bin/develop.py migrate dictionary 0010_auto_20170802_1648`

**Comment by ocrasborn** [comment]
@vanlummelhuizen , can this be closed?

**Comment by susanodd** [comment]
When editing is disabled because of lack of permission, the Edit button indeed disappears, but the Delete Video and Delete Image buttons still appear.

**Comment by susanodd** [comment]
The Delete Sign button is also visible.
