### ISSUE TITLE
Rename NGT Signbank to Global Signbank

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#226]
* Or is there a better name?
* Suggest to leave "Universal Signbank" for the merged version of the codes for the different Signbanks which we plan to create, cf. the icon of the <a href="https://github.com/Signbank">Signbank organisation</a> in Github
* Rename needed in many places! How to make more dynamic?

**Comment by ocrasborn** [comment]
Alternative: Global.
Font used in the header image is Arial Rounded MT Bold. Is this so universally available that we could just as well change the image to text?

**Comment by ocrasborn** [comment]
We'll keep the present URL for a while, but it'd be good if we can make the new name more findable for search engines, given that the url is a wee hard to memorise. Any ideas on how to do this? Add some tags at the top of the html or something?

**Comment by Woseseltops** [comment]
> Is this so universally available that we could just as well change the image to text?

No, but the font 'Nunito' is. I secretely removed the image and replaced it with real text in this Nunito font. Let's see if anyone notices. 

![image](https://media.tenor.com/images/00fd4e0c3c683d5e35a43ed7a6c08b81/tenor.gif)

> but it'd be good if we can make the new name more findable for search engines

Search engine optimization (SEO) is the keyword you're looking for here. What exactly do you want to achieve? Because when I google 'signbank' in incognito modus (so I get no personalized results), the NGT Signbank is the first result.

**Comment by ocrasborn** [comment]
Hi @Woseseltops , I see the difference! NGT is thinner now, isn't it? But while you're at it, could you replace "NGT" by "Global" in the header? A logo has been designed, coming up soon.

**Comment by ocrasborn** [comment]
Not sure about SEO, maybe nothing is needed.

**Comment by Woseseltops** [comment]
> could you replace "NGT" by "Global" in the header

Done. 

Furthermore, I had a look at what more needs to be renamed/changed :
* The page contents, in all interface languages "NGT Signbank is the lexical database of the annotated NGT corpora at Radboud University"
* The name of the repository
* The folder 'NGT-templates' and all references to it
* The ngt.py settings file
* The setting 'SIGNBANK_VERSION_CODE'

The first one can be done already, but before I do the rest I should probably coordinate a date with @vanlummelhuizen and @susanodd ; if change whole folder names and settings filenames while they are working on a separate branch I expect horrible merge conflicts.

**Comment by ocrasborn** [comment]
* The page contents, in all interface languages "NGT Signbank is the lexical database of the annotated NGT corpora at Radboud University"

Done.

**Comment by Woseseltops** [comment]
@vanlummelhuizen and @susanodd , I did the following things, please update your local repos:

> * The name of the repository

At least here at Github, not sure what the exact results will be for the various installations.

> * The folder 'NGT-templates' and all references to it

Done. Also found a separate css folder that I renamed.

> The ngt.py settings file

Renamed to global_sb.py . 'Global' is a Python keyword, so using just that would be a recipe for disaster.

> The setting 'SIGNBANK_VERSION_CODE'

Done, as wel as 'language name'.

While making these changes I did notice some extra mentions of NGT in the comments etc, let's use this issue to clean these as well.

**Comment by vanlummelhuizen** [comment]
Can we remove the High priority label for this issue?

**Comment by ocrasborn** [comment]
sure

**Comment by Woseseltops** [comment]
> While making these changes I did notice some extra mentions of NGT in the comments etc, let's use this issue to clean these as well.

Done.
