### ISSUE TITLE
Can't edit page content in admin

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#279]
I tried changing the home page of the ASL Signbank, but can't edit the content field of the home page. Didn't check other pages, please do. Incidentally, the "Edit page" button on the home page doesn't lead to the right URL for editing; please fix that as well.

**Comment by vanlummelhuizen** [comment]
I was able to fix the second part. The link of the Edit Page button was so called absolute but is lacking the host name. This means it is put right behind the hostname (and port number if there is one, technically). But ASL is in a subfolder so to say, i.e. /asl-signbank/. This part is missing when using the absolute URL. I fixed it by adding the base URL of the Signbank instance. See also #302.

**Comment by vanlummelhuizen** [comment]
It seems that the Javascript-library (Summernote) that makes that you can edit the page content is not available in the ASL-signbank instance. I will try to find out why and tell Wessel.

**Comment by vanlummelhuizen** [comment]
@Woseseltops the symlink in the media folder was broken. I fixed that now, but I think the Apache conf for ASL-signbank needs to grant access to the django_summernote static folder. Although it seems I have authorization to do so, I'd rather let you do it.

**Comment by Woseseltops** [comment]
Did this ever work? I don't think anything was changed related to this feature and the configuration for the ASL SB...

I tried some basic stuff to set the rights correctly, but couldn't get it to work within 10 mins. Before I spend more time on this: @ocrasborn , are you aware of the fact that this would have to be redone on the new ASL SB server, and it might thus not be the most efficient use of time to try to get it working on Applejack?

**Comment by ocrasborn** [comment]
not sure I understand: fixing it on applejack = fixing it for ASL in its current form, no?

**Comment by Woseseltops** [comment]
> fixing it on applejack = fixing it for ASL in its current form

Yes. That is, we are instructing Applejack how to serve the Django-summernote extension. Once we move from Applejack to another server (which I still hope is really soon, in particular now we're almost done updating), these instructions will no longer be used.

**Comment by henrinie** [comment]
My suggestion is to use 'static files' instead of the symlink. Then you can collect all the static files (and summernote files as well) into a folder that you can grant access to the web server.
https://docs.djangoproject.com/en/1.11/howto/static-files/

**Comment by Woseseltops** [comment]
Working my way through the 'tbc after asl migration' issues. I think the ASL SB has this now, agree this can be closed @ocrasborn ?

**Comment by Woseseltops** [comment]
Fixed. Caused by the migration to the new Applejack, was a double problem (dead symlink to static files, permissions not okay).

**Comment by Woseseltops** [comment]
Happy @ocrasborn ?
