### ISSUE TITLE
Move choices "note type" to field values

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#290]
The values for the type of note (panel Notes) are now hard-coded; please move them to the django admin so we can edit them as field values.

**Comment by vanlummelhuizen** [comment]
@Woseseltops For this changes to work, you to do the following:

1. Transform the DEFN_ROLE_CHOICES list of tuples to FieldChoices in the database.

**Comment by Woseseltops** [comment]
I think this was already done back in May. Can be closed?

**Comment by ocrasborn** [comment]
:-)

**Comment by ocrasborn** [comment]
It appears that NoteType does not yet appear in the ASL Signbank's admin for Field Choices, although it does for Global SB. Please make it (re)appear.

**Comment by Woseseltops** [comment]
The functionality is working @ocrasborn , but what the American users understandably did not know is that they should add field choices in the category 'NoteType'. Also, I just noted that the field choices for notes are a little different from the 'normal' gloss field choices in that the require a restart of the server to be visible on the site. I would say: ask them to add the field choices they need, and then email me for a restart?

**Comment by ocrasborn** [comment]
Will do!
