### ISSUE TITLE
Change "Missing Sign Feedback" page

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#303]
* The "Missing Sign Feedback" page is outside the admin environment.
* Change the text at the top (above the Video Comment button) to the following:
“Please submit a video comment showing the sign you think is missing. Please produce the sign in isolation and then in an example sentence. Please also type in the English translation equivalent below as well as your contact information (name and email address) so we can contact you for a follow up if need be. Thank you for taking the time to contact us and help ASL SignBank grow.”
* Remove the Sign Description section.
* Keep the final section (Details)
* For both ASL and NGT

**Comment by henrinie** [comment]
@ocrasborn are you actively using the feedback features (application)?
If not, it might be worth it to start working on https://github.com/stevecassidy/signbank-feedback to make it meet your requirements, that way we could have only one codebase for a feedback application instead of several.

**Comment by ocrasborn** [comment]
No, we're not yet using it. Thanks for your suggestion, @henrinie , we'll take it up.

**Comment by susanodd** [comment]
The feedback code has been debugged for Global Signbank. (See also Issue #29.)
The changes above have been made for missing signs.
