### ISSUE TITLE
Make the horizontal scroll bar also appear when coming from the Recently Added Signs menu

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#304]
* So that we don't have to go back to this menu item and load that page first, but can jump to signs for discussion more quickly
* See #182

**Comment by susanodd** [comment]
This has been completed. Awaiting deployment.

**Comment by susanodd** [comment]
This is live @ocrasborn

**Comment by susanodd** [comment]
For some very strange reason, this works on my local machine but not on the live server.
(With exactly the same code on both.)

**Comment by susanodd** [comment]
This seems to be working.
