### ISSUE TITLE
Make header, menu and panel bars more condense

### ISSUE THREAD

**Issue by Woseseltops** [Signbank/Global-signbank#305]
> [T]his might be a good time to create a bit more of a condensed header and menu bar, to reduce that problem. I find the top and bottom spacing on both menu bar and panel headers rather large. Not sure if they're controlled by the same css element or something like that, but they could both be more reduced.
-- @ocrasborn

**Comment by vanlummelhuizen** [comment]
I edited some CSS (in the browser, so temporary). This is the result:
![schermafdruk van 2017-06-19 09 30 31](https://user-images.githubusercontent.com/16682631/27274082-2c28e0ce-54d2-11e7-841b-663414197c05.png)

Is that what you want, @ocrasborn ? Forget about the language picker for now.

While we are on the topic of header, did you notice the background color of the NGT Signbank and RU logo (#BB2F2C) is slightly different from the rest of the header (#B82B22)?

**Comment by ocrasborn** [comment]
Yes, this is what I had in mind. I know about the colours, yes, if they're easy to fix then please do, otherwise we do it when tackling  issue # so and so about renaming the site

**Comment by vanlummelhuizen** [comment]
Do you mean #226? Changing the background color of the header is done easily. I will do it when I work on this issue.

**Comment by ocrasborn** [comment]
yes, that one.

**Comment by ocrasborn** [comment]
Good!
