### ISSUE TITLE
Show video on search page when hovering over a gloss

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#312]
Adopt feature from FinSL Signbank: https://github.com/Signbank/FinSL-signbank/issues/219

**Comment by Woseseltops** [comment]
I was thinking about this a bit, and realized that the Finnish hover would not really make sense because we already have the pictures visible. Instead, I thought it would be could if the pictures started to move as soon as you hovered them. Would look like this (temporary view): https://signbank.science.ru.nl/dictionary/try/

**Comment by ocrasborn** [comment]
Yes @Woseseltops , play-when-mouse-over would be just what we need.

**Comment by vanlummelhuizen** [comment]
FYI: In Firefox on Ubuntu 14.04 the videos are quite large. Chrome on Ubuntu 14.04 is working correctly as well as Safari on Mac OSX 10.11.6.

**Comment by ocrasborn** [comment]
Way cool! Safari/Mac: window pops up to large size. Hefty effect, but possibly users will appreciate it. Because, Chrome/Mac: the in situ size of the list view images that start to play is rather small. Let's wait and get some feedback from people in January first, I suggest, before making it the same in all browsers/platforms.

**Comment by Woseseltops** [comment]
I'm guessing your video size problems are due to cached stylesheets

**Comment by Woseseltops** [comment]
Just discovered that this functionality breaks the list view when there are lots of glosses, as all the videos are preloaded by the browser: it first downloads the html, shows it, and then spends a very long time also loading all the videos, sometimes crashing the browser tab. On top of this, if you hover an image while the browser is still loading the video, and then leaving again, you pause a video which hasn't started yet, leading to an error.

As a solution, I'm leaning towards disabling this feature when there are too many glosses. A prettier solution might be to figure out how to only preload videos currently in view.

By the way, I'm really talking about lots and lots of glosses. Just 200 glosses is no problem.

**Comment by vanlummelhuizen** [comment]
@Woseseltops, or perhaps load the video when it is needed, i.e. when hovering over the image?

**Comment by ocrasborn** [comment]
@Woseseltops : perhaps set a max to the first 200, then? And then make sure that the pagination menu has '200' as an option (not sure whether it does now). I'm not sure how quick they would load (also in another part of the world) if we follow @vanlummelhuizen 's suggestion, I think users often compare multiple forms one after the other, so the way it is now is great for the user.

**Comment by susanodd** [comment]
On the new server, in the gloss list view, if a video is missing the "hovering" goes beserk.

I attempted to fix this myself, but the javascript code is implemented in such a way that it needs things to be present.

**Comment by vanlummelhuizen** [comment]
@susanodd I cannot reproduce this and I don't understand what you mean by 

> the javascript code is implemented in such a way that it needs things to be present

Could you be more clear/specific?

**Comment by vanlummelhuizen** [comment]
@susanodd I fixed it just now.

**Comment by susanodd** [comment]
Great!
