### ISSUE TITLE
The import_videos script seems to be broken

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#325]
* After the recent updates?
* There are corrections of existing videos in .../import_videos, but the script gives a feedback page that indicates nothing has been imported or overwritten; the videos remain in the folder.

**Comment by Woseseltops** [comment]
Hi @ocrasborn , just to be sure, what location are you using to upload your videos? The new Applejack location should be: /scratch2/www/signbank/writable/import_videos . I just updated the wiki :).

**Comment by ocrasborn** [comment]
I sent them to the old location, of course...  Solved :-)
It'd be a good idea to remove the old Signbank directory, no, @Woseseltops ?

**Comment by Woseseltops** [comment]
I've requested the removal of the Spitfire version!

**Comment by ocrasborn** [comment]
Issue applies again, unfortunately, this time with the following error message:

"FieldError at /dictionary/import_videos/
Cannot resolve keyword 'dataset' into field. Choices are: StemSN, absOriFing, ..."

**Comment by vanlummelhuizen** [comment]
This was caused by the new gloss -> lemma -> dataset hierarchy that was not used yet in the import_videos. This should be solved now. @ocrasborn can you confirm?

**Comment by ocrasborn** [comment]
Yes! Thanks, @vanlummelhuizen !
