### ISSUE TITLE
Make the feedback page for CSV import more human-readable

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#326]
See this screen shot of a test import I did recently. The source and the target of the change are both listed twice, does that have a function for a different type of import? And why are the values in the first line preceded by 'b'?

![screenshot 2017-05-27 19 18 16](https://cloud.githubusercontent.com/assets/10242207/26523182/48534b58-4312-11e7-9108-c309cef3b42f.png)

**Comment by susanodd** [comment]
The Lemma ID gloss ONNOTEST2222 has as its Annotation ID gloss: Dutch the value 'ONNOTEST22223'.

What is the preferred functionality?

**Comment by susanodd** [comment]
To get to the Changes list, I modifed the CSV cell to:
homonym:testonnoz, hyponym:ONNOTEST22223

This is what the Changes look like:

**Comment by susanodd** [comment]
Okay, on the Live Server, searching on testonno and then clicking on TESTONNOZ gives an error.
It looks like something is wrong with the FieldChoice.
On my local copy, I don't get this error.
In Issue #381, you mention deleting a FieldChoice. Did something get deleted?

**Comment by susanodd** [comment]
To answer the Issue question: The part between parentheses are the machine values.
The current version of import_csv only shows the "between parentheses" part when it is different.
For fields that are FieldChoices, the machine values are different than the human values.

**Comment by ocrasborn** [comment]
@Woseseltops manually fixed a gloss with a deleted field choice last week or the week before, apparently this needs to be done for some more records. Let's wait until he gets back, he'll probably quickly figure out how to address it.

**Comment by ocrasborn** [comment]
Oh, to answer your question: relations to other signs should refer to Annotation ID Glosses, not to Lemma ID Glosses.

**Comment by susanodd** [comment]
Okay, that's how it's implemented.
(So the TESTONNOZ and ONNOTEST2222 relations in gloss testonno1633 need to be modified.)

**Comment by susanodd** [comment]
![csv-import-table-of-changes](https://user-images.githubusercontent.com/24272544/31119223-856b7104-a830-11e7-9466-75928a954c60.png)

**Comment by susanodd** [comment]
In the screenshot, the list of changes is in a table to make it more readable.
The first column is actually Lemma ID Gloss.
(It has always been the Lemma column. I left it that way, but that is no longer unique.)
I can change it to be Annotation ID Gloss: Dutch. (or something else ?)
(Perhaps the Language or Dataset should also be included as for comments in Issue @79.)

**Comment by susanodd** [comment]
Maybe a nested table so that each row gets a table but the first column isn't repeated?

**Comment by susanodd** [comment]
The main use of the table would be to assist the user in checking that what was imported from the CSV is actually what the user wants to do.

**Comment by ocrasborn** [comment]
Hi @susanodd , yes, please change the Lemma gloss to Annotation ID Gloss, and add as a first column Data Set (just to help people be sure that they're working on the right data set).

**Comment by susanodd** [comment]
I'm also working on creating new glosses via CSV import (Issue #79).
There one is working with the columns Dataset, Lemma ID Gloss, Annotation ID Gloss : Dutch and : English. (The identifying properties of a Gloss.)
But what happens with these columns for a normal CSV import?
Should one not be allowed to modify these columns during import?
(I.e., If Dataset is a column that is part of the display of changes, then it seems dodgy to  be also trying to change the Dataset field - or the other Lemma and Annotation fields at the same time.)

**Comment by susanodd** [comment]
![import-csv-change-dataset-field](https://user-images.githubusercontent.com/24272544/31230287-e408c342-a9e3-11e7-94bd-9ee030fac5f4.png)

**Comment by susanodd** [comment]
![import-csv-with-dataset-column](https://user-images.githubusercontent.com/24272544/31232313-d1173d8a-a9e9-11e7-93cb-f1d422d834a5.png)

**Comment by susanodd** [comment]
I added additional error checking. One more check I can add is if the user has additional data to the right of the columns (with headers) (rows that are too long), since this will be ignored.

**Comment by ocrasborn** [comment]
Hi @susanodd , just got a new type of error, never seen before. I was updating records with both lemma gloss columns (English, French) for dataset LSFB. Can you provide an instruction for this one as well?
<img width="1057" alt="screenshot 2019-02-06 12 22 53" src="https://user-images.githubusercontent.com/10242207/52338273-3cd2d380-2a0a-11e9-91de-4517b23eb5dd.png">

**Comment by susanodd** [comment]
@ocrasborn, the Keywords are also known as Translation equivalents, which in turn have an associated language in the Gloss Detail View.
The import csv update Keywords is actually looking for a language code suffix for each keyword (phrase) between comma's.

This is quite tedious to add to the data by hand....

![import-csv-update-keywords-suffix](https://user-images.githubusercontent.com/24272544/52348127-d8247280-2a23-11e9-9a00-1694163ce63d.png)

**Comment by susanodd** [comment]
We probably need separate columns for the Keywords for each language.
The text of the keywords is all stored in the Keyword table.
There is a Translation table which tuples keyword ids with gloss ids and language ids.
So for example, Keyword verantwoordelijkheid is tupled with gloss id 3 and language id 2 (Dutch).
If you export NGT, it gets the language code nl as a suffix: verantwoordelijkheid:nl
That is what the import csv is looking for.

(Although low and behold, I see the export csv has put verantwoordelijkheid:nl in the Sequential Morphonology column. Not very responsible.)

https://signbank.cls.ru.nl/dictionary/gloss/3/

**Comment by susanodd** [comment]
@Woseseltops made the suggestion that instead of columns, we could allow the user to specify which language to use for the keywords upon import.

**Comment by ocrasborn** [comment]
@susanodd, @Woseseltops : we could do that, yes, but for Glosses we now do it in columns, let's just do that for keywords as well, have column headers that spell out 'keywords (French)' and 'keywords (English)', for example. On both export and import, of course. The language suffixes are not convenient for the user.

**Comment by susanodd** [comment]
Keywords per language columns have been added for both CSV export and import (update).
