### ISSUE TITLE
Entering a non-existing gloss ID in the url returns an error page

### ISSUE THREAD

**Issue by vanlummelhuizen** [Signbank/Global-signbank#327]
E.g. https://signbank.science.ru.nl//dictionary/gloss/1241234

This should probably give a 404 instead.

**Comment by henrinie** [comment]
It seems that you have `debug = True' in the settings of the production
server. It is recommended not to use debug mode when in production.
So normally people would not see that kind of an error I guess?

**Comment by vanlummelhuizen** [comment]
This issue seems to be solved. Closing.
