### ISSUE TITLE
Find and save homonyms

### ISSUE THREAD

**Issue by susanodd** [Signbank/Global-signbank#332]
Related to Issues #277 and #110 I created a find_and_save_homonyms page to search for matching phonology and create Homonym relations.
The output is a chart, similar to how find_and_save_variants is done.
The routine find_and_save_homonyms also shows glosses incorrectly saved as homonyms.
It does not delete these.

The new gloss_detail page for Issue #277 shows homonyms that have not been saved as well as saved homonyms that are not homonyms.
An example is SOLDAAT-B which has a saved homonym POLITIE-B but a different phonology.
There is a synonym relation going the other direction.

I created this routine to use to fill in extra information in the database. It could be run in a similar way to find_and_save_variants.

**Comment by ocrasborn** [comment]
@susanodd , just to check what will happen: it should be the case that homonym relations are always added by hand, is that still the case?
I'm glad that 'apparent homonyms' (identical phonology, no homonym relation yet) are listed now!

**Comment by susanodd** [comment]
Yes, that is the case.
The gloss_detail view does not do anything to homonyms. It shows saved homonyms that are not the same phonology (in a red panel) as well as other signs with the same phonoology that are not saved as homonyms for the sign (also in a red panel).

I adjusted the find_and_save_homonyms view so it's just find_homonyms now.
[functionality to automatically find and save has been removed]

(Once merged)
The new page can be viewed at: signbank/dictionary/views/find_homonyms/

The view shows a table of all the glosses with at least Handedness defined, with columns for the already saved homonyms, followed by "other signs with identical phonology", followed by "those saved homonyms that have a different phonology".

**Comment by susanodd** [comment]
https://signbank.science.ru.nl//dictionary/gloss/1775/

**Comment by vanlummelhuizen** [comment]
@susanodd, perhaps you should also instruct users which new URLs they can use for the new functionality. Also for #110.

**Comment by ocrasborn** [comment]
For basic access to the 'Variant View', it would be useful to have a button with that text appearing in the Detail View, next to the 'Public View' button. Is there not something like that in @susanodd 's code?

**Comment by ocrasborn** [comment]
The signbank/dictionary/views/find_homonyms/ page is really useful @susanodd , thank you for adding this option!
As for instructions to this specific page, how about we add a menu item under Signs, called "Homonym list", to be added above "Import CSV", to load it?

**Comment by susanodd** [comment]
Okay, this menu choice has been pushed.
[It takes a couple of minutes for the table to show up.]
[Each focus gloss row generates query to find the homonyms (matching phonology) from the perspective of that sign.]
There isn't a template for this page yet.

**Comment by susanodd** [comment]
The Homonyms list now displays with the Signbank logo above it, as a template.
I modified the query a bit and hopefully it's a bit faster.
There's now only three columns. The focus gloss, the saved homonyms, and the computed homonyms.
These replace the columns for "saved but not homonym" and "homonym but not saved".
Only homonyms for glosses with both the Handedness and Strong Hand phonology fields set are considered as focus glosses.

![homonyns-list-as-template](https://user-images.githubusercontent.com/24272544/33262734-a58b8d86-d367-11e7-91e2-fe4f905a5f8a.png)

**Comment by susanodd** [comment]
This is live now.

**Comment by susanodd** [comment]
Duplicate explicitly saved homonym relations are now shown in red.

![red-duplicate-homonyms](https://user-images.githubusercontent.com/24272544/46526204-e011b180-c88d-11e8-9e55-55059690e7e9.png)

**Comment by vanlummelhuizen** [comment]
@susanodd @ocrasborn Is this one done?

**Comment by ocrasborn** [comment]
Yes I think so; thanks for spotting this open issue. Time to close.
