### ISSUE TITLE
"Cannot operate on a closed database"

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#335]
Deleting videos seems to have become impossible again, please double-check. I get an error message that I've seen several times today, which typically disappears after trying again or reloading the page. Related to ongoing development work?
See https://github.com/Signbank/NGT-signbank/issues/124

---------------------------------------------------
ProgrammingError at /video/delete/571
Cannot operate on a closed database.
Request Method:	POST
Request URL:	https://signbank.science.ru.nl/video/delete/571
Django Version:	1.11
Exception Type:	ProgrammingError
Exception Value:	
Cannot operate on a closed database.
Exception Location:	/scratch2/www/signbank/lib/python3.4/site-packages/django/db/backends/sqlite3/base.py in create_cursor, line 218
Python Executable:	/usr/bin/uwsgi-core
Python Version:	3.4.3
Python Path:	
['.',
 '',
 '/scratch2/www/signbank/lib/python3.4',
 '/scratch2/www/signbank/lib/python3.4/plat-x86_64-linux-gnu',
 '/scratch2/www/signbank/lib/python3.4/lib-dynload',
 '/usr/lib/python3.4',
 '/usr/lib/python3.4/plat-x86_64-linux-gnu',
 '/scratch2/www/signbank/lib/python3.4/site-packages']
Server time:	Thu, 15 Jun 2017 14:51:20 +0200
Traceback Switch to copy-and-paste view

**Comment by ocrasborn** [comment]
I get the same kind of error message when testing out whether @vanlummelhuizen 's solution to #330 was already online, finding it is not, the page keeps reloading after switching to Chinese, and after a few reloads it stops with the error below:

ProgrammingError at /
Cannot operate on a closed database.
Request Method:	GET
Request URL:	https://signbank.science.ru.nl/
Django Version:	1.11
Exception Type:	ProgrammingError
Exception Value:	
Cannot operate on a closed database.
Exception Location:	/scratch2/www/signbank/lib/python3.4/site-packages/django/db/backends/sqlite3/base.py in create_cursor, line 218
Python Executable:	/usr/bin/uwsgi-core
Python Version:	3.4.3
Python Path:	
['.',
 '',
 '/scratch2/www/signbank/lib/python3.4',
 '/scratch2/www/signbank/lib/python3.4/plat-x86_64-linux-gnu',
 '/scratch2/www/signbank/lib/python3.4/lib-dynload',
 '/usr/lib/python3.4',
 '/usr/lib/python3.4/plat-x86_64-linux-gnu',
 '/scratch2/www/signbank/lib/python3.4/site-packages']
Server time:	Thu, 15 Jun 2017 15:15:10 +0200
Traceback Switch to copy-and-paste view

/scratch2/www/signbank/lib/python3.4/site-packages/django/contrib/sessions/backends/base.py in _get_session
            return self._session_cache ...
▶ Local vars

**Comment by vanlummelhuizen** [comment]
The "Cannot operate on a closed database" error seems to come up rather randomly, which makes it hard to debug. We just restarted the live server for some new functionality (not #330), so now it may be gone for a while. 

My intuition is that it has something to do with the workload of Signbank or the server. Perhaps there are some spawned processes that are not closed correctly and therefore add to the workload.

We will investigate this.

**Comment by Woseseltops** [comment]
> We just restarted the live server for some new functionality (not #330), so now it may be gone for a while.

Indeed, I cannot reproduce. 

Things to check once it pops up again:
* How long did it work (again a week?)
* How often does it give the error (roughly once every 10 times? every 20 times?)
* How are the uwsgi processes doing? Do they have a lot of children?

The final solution if all else fails, is to move to another database system; there's not written a lot about this in the Django context.

**Comment by ocrasborn** [comment]
@Woseseltops, I need some help with the third bullet here :-) I don't need to understand what they are, but how do I find out about them?

**Comment by Woseseltops** [comment]
Don't worry @ocrasborn , I meant 'things to do' FOR MYSELF :).

**Comment by ocrasborn** [comment]
haha!

**Comment by Woseseltops** [comment]
I didn't encounter this anymore, anyone else?

**Comment by ocrasborn** [comment]
Right, me neither. Let's just close it, we can always reopen it later.

**Comment by Woseseltops** [comment]
Our automated check every 15 mins randomly started reporting problems for the ASL Signbank, and today Julie sends me this:

> I'm adding glosses, editing glosses (changing translation equivalents, related signs, notes) or adding movies. To any of those actions, I randomly get "Cannot operate on a closed database." error.

Interesting that this problem now pops up for the ASL Sigbank. I have restarted Apache and UWSGI, let's see what happens.

**Comment by Woseseltops** [comment]
This is an overview of how the problem develops. Nicely shows the randomness, and possibly also the effects of my restart the 19th:

![image](https://user-images.githubusercontent.com/1909317/43193110-72fe16a4-8fff-11e8-8fbe-896fd407e300.png)

**Comment by Woseseltops** [comment]
Restarted a few times at the 25th for unrelated things, and now the problems seems almost gone? Or is it unrelated to the restarting?

![image](https://user-images.githubusercontent.com/1909317/43571180-95a4050e-963c-11e8-8816-4fa7d5d9e18f.png)

**Comment by Woseseltops** [comment]
The problem is not as severe but still there: 

![image](https://user-images.githubusercontent.com/1909317/43899341-e6195cb4-9be1-11e8-844f-7f96ecc2d923.png)

**Comment by Woseseltops** [comment]
Since this is not occurring this much anymore, I'm removing the 'high priority' tag.

**Comment by Woseseltops** [comment]
Okay the issue seems to have disappeared mysteriously again. We'll reopen once it pops up again.
