### ISSUE TITLE
Refinement to display of minimal pairs

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#338]
* In the Minimal Pairs panel, please display two values after the field name: first that of the source sign, second that of the contrasting sign that is listed (which is already there now).
* Same for the minimal pair display in the /gloss_relations/ view
* As values for the various phonology fields can differ between one character and about 20, make sure there are two columns as it were (rather than two values separated by a single space or comma), so that the values for multiple minimal pairs don't look too messy.

**Comment by susanodd** [comment]
![minimal-pairs-panel-two-values](https://user-images.githubusercontent.com/24272544/27285977-cf64fa08-54fe-11e7-8814-9cb6f4e53c40.png)

**Comment by susanodd** [comment]
is the column order okay?

**Comment by ocrasborn** [comment]
Yes it is.

**Comment by susanodd** [comment]
OK, I just pushed this to my branch. I modified the code so it now displays the field names and the values of the fields in correct language. [NL and EN both work.]

[Don't try CN because there is a different issue that the server starts looping if you try Chinese.]

**Comment by susanodd** [comment]
This can probably be closed.
