### ISSUE TITLE
Allow different copyright statements for different datasets

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#339]
* Take both site footer and copyright page into account.
* Add copyright text block(s) as part of the dataset specification?

**Comment by Woseseltops** [comment]
Do I understand correctly that different datasets can have different copyright statements? If so, maybe it makes more sense to mention the copyright statement below each sign, depending on which dataset they belong to, and maybe in the dataset list view? That is, remove it form the footer?

Maybe it also makes sense to mention that the license for the code is different from the license of the content, see #160 .

**Comment by ocrasborn** [comment]
Yes, that's right: different datasets (can) have different copyright statements. My suggestion would be to make this explicit on the Copyright page, where we also make explicit that the content license(s) are different from the software code license, and to find a way to specify a license on the page that lists the datasets a user has access to.

**Comment by Woseseltops** [comment]
Okay, do you want me to write to text, @ocrasborn ? In case you want to do it yourself, you can edit pages again now :) .

**Comment by ocrasborn** [comment]
I'll write it, better you spend your time on ASL SB today (if you have time; issue to come).

**Comment by ocrasborn** [comment]
It'd make sense to refer to the license / usage conditions / copyright on the page "View available datasets". How shall we do this @vanlummelhuizen and @Woseseltops? With hyperlinks to separate pages? Aside from the license, we'll also need to make explicit who is the owner of the data, who is the contact person, and maybe other things like some references. If we add all that as one long list of blocks of text below the table showing available datasets, then it might become long and messy.

**Comment by Woseseltops** [comment]
How about adding an extra column for every piece of information you want to show about the dataset... and once the information becomes too long (for example, we don't want an entire license text in the table), you only put a way words there (like the name of the license), and the rest as an explanation under the table?

**Comment by ocrasborn** [comment]
OK, let's do it like that, but then put an image in this last column then representing the license type: either one of the Creative Commons badges or some other symbol making explicit that it's not open access (red cross perhaps), with the addition of (1), (2), etc. to refer to footnotes below the table. Could you make that editable in the Django admin somehow, this mischmasch of database info and free text?

**Comment by ocrasborn** [comment]
Now that we've started working with different types of datasets, I think we need a solution that allows for a bit more information per dataset. Would it be possible to make the name of the dataset a hyperlink to a separate page, where we display four standard blocks of text, to be edited in the interface by those who have edit-rights for that dataset?
1. Name --> This is already there, can be the title of the page.
2. Owner & Contact person(s) --> free text
3. Description --> free text
4. Copyright statement  --> free text
5. Conditions of use by others  --> free text
Where 2-5 would be the titles of variable-sized text blocks.

**Comment by susanodd** [comment]
I made an example detail view for this (the target of the hyperlink will show this).
The information we already have is filled in (see below).
The new data (empty fields below) needs to be added to the Dataset model.
An Edit button is needed for those with change_dataset permission, in the Dataset Manager group.
Can the details of the dataset (without an Edit button) be visible for those with view_dataset permission, or for logged in users?
That way, people without permission could look up who to contact.

![mockup-dataset-detail-view](https://user-images.githubusercontent.com/24272544/37666657-5b95d766-2c60-11e8-96b4-707f29e44cef.png)

**Comment by ocrasborn** [comment]
Feedback from a quick look & read:
* The copyright field needs to be added
* The Description, Copyright and Conditions of Use fields need a big box for editing, something like 10 lines. Others can be one line.
* All information (the page, that is) should also be visible to anonymous users who are not logged in. So visible to anyone.

**Comment by susanodd** [comment]
Does the acronym field need to be unique?

**Comment by ocrasborn** [comment]
yes!

**Comment by susanodd** [comment]
![navbar-with-datasets](https://user-images.githubusercontent.com/24272544/38308430-5e4cf616-3817-11e8-8c00-91208f089efa.png)
![dataset-detail-view](https://user-images.githubusercontent.com/24272544/38308439-621514d6-3817-11e8-9b8c-6dd546acb0e1.png)
![dataset-detail-edit-copyright](https://user-images.githubusercontent.com/24272544/38308442-653b1214-3817-11e8-8b4a-94d121257f83.png)

**Comment by susanodd** [comment]
There are hyperlinks to the Dataset Detail view on the Dataset Manager page.
The Dataset Detail view has an edit button for when the user is a Dataset Manager and has Change Dataset permission. (Also checked in the python code to prevent others from invoking on the url.)
The text areas for editing become visible when you click on the text you want to edit.

**Comment by susanodd** [comment]
(The example screenshots are on my local database.)

**Comment by ocrasborn** [comment]
Great @susanodd !!
Could you also link to dataset_detail.html from the dataset names on the page _View available datasets_?

**Comment by Woseseltops** [comment]
Happy @ocrasborn ?

**Comment by ocrasborn** [comment]
I have to reopen this again, @susanodd : it seems only superusers can save the info pages. User lindsayf (who has write permission for Norwegian SL and is in the group Dataset_Manager) can see the edit button and edit, but not save the page. Same for user-dataset and NGT.
![errormsg](https://user-images.githubusercontent.com/10242207/40431906-b1409f5a-5ea8-11e8-8af9-32d3aa66d67a.jpg)

**Comment by susanodd** [comment]
I located the error. The permission testing done on update isn't the correct syntax for the permission.

**Comment by susanodd** [comment]
This has been pushed to github.
