### ISSUE TITLE
Set up a moderator-friendly system for accepting new account requests

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#355]
ASL SB expects registrations from many users (100-1000); handling all of these requests manually in Django will be inefficient. We need a way to monitor new registrations, and simple buttons for accepting/rejecting them and assigning a group (default group: Guest).
(Didn't FinSL SB already have an administrator menu with features like these?)

**Comment by henrinie** [comment]
Actually we don't have yet. I think that we will rely on django admin, but
either send email to admins or/and have a page that lists newly registered
users.

We are interested in hearing your ideas concerning this.

14.7.2017 0.06 "ocrasborn" <notifications@github.com> kirjoitti:

**Comment by ocrasborn** [comment]
Suggestion: add a third option (next to logging in and resetting pwd) to the login page, "Request an account", where the user can fill in all the personal data needed (first name - last name - email - user name - password) and select from a list which dataset(s) s/he would like access to. On the basis of this, create a new user in Django, and send an email to the system manager (me for Global ?SB; Julie for ASL) as a notification, upon which the manager can add the checkmark 'Active' in Django, assign the user to a group, and set Dataset permissions as desired. The one field we don't have for this yet is 'Requested data sets', that would need to be added.
We can later refine this as we set up a different data manager for each dataset.
@Woseseltops , @vanlummelhuizen , what do you think?

**Comment by ocrasborn** [comment]
* Workflow:
1.  Prospective user clicks on 'registration' somewhere
2. User goes to page where personal details can be filled in
3. User checks "Accept terms of use" and clicks submit
4. New account is created, but waits for consent from the system manager
5. System manager goes to a page where a list of new request appears, with buttons 'accept' and 'reject'; reject removes the user, accept makes the user 'active'
6. User receives an email saying account is active, with a link to the Conditions of Use page

**Comment by ocrasborn** [comment]
To discuss: how/where to specify who the user manager is for the system, who can have access to the 'new registrations' page and who receives an email notification at interval X about pending account requests.

**Comment by susanodd** [comment]
step (3).
Where can I find the Terms / Conditions of Use that need to be approved by new users?
Is this stored in the database? It would be easiest if this could be retrieved for display.

**Comment by susanodd** [comment]
@ocrasborn , at the moment Signbank does not seem to send any (automated) emails. Is this correct?

**Comment by susanodd** [comment]
In the original (unused code), there are some registration routines that are intended to send the new user an activation code by email.
Under the new registration, this will be done by the admin on a new page (#460).
To avoid the need to send emails, I've made the registration request display the data the user has entered to confirm the request has been received.

Here are some screenshots.
![user-registration-request](https://user-images.githubusercontent.com/24272544/42507830-d4c885fa-8446-11e8-8b5f-966a8dc1a475.png)
![user-registration-complete](https://user-images.githubusercontent.com/24272544/42507839-dac953d0-8446-11e8-9b79-3432655e7d3a.png)

**Comment by susanodd** [comment]
From the screenshots, the Conditions for Use need to appear for the user to accept.

**Comment by susanodd** [comment]
For the requested datasets, these need to somehow be communicated to the Dataset Manager.

The new user is created as an "inactive" user, in the same table as all the users. (as for original Signbank)
The new user is put in Group Guest. (as for original Signbank)

Where would you like the store the Requested datasets?
There is a database table registration_registrationprofile where activation keys are stored.
That would seem the most logical place to store requested datasets.
They could perhaps be fed to the Dataset Manager page? So the manager can grant and revoke permissions, as well as process requests?

**Comment by ocrasborn** [comment]
Hi @susanodd , some responses:
* The only place the system now sends emails is upon resetting a password, I think. We might want to double-check that that is working properly.
* 'Guest' sounds good to me as default, but perhaps we can make new users 'active' without any action on our part. When a Nijmegen SB-manager disapproves, users can be deactivated; and activation is meaningless anyway until the dataset manager for each of the datasets requested has granted access.
* We still need to write up the Terms & Conditions; we can adopt in part what has been created for FinSL Signbank.
* I'm not sure where to store the requested datasets; better discuss this with @vanlummelhuizen and @Woseseltops .

**Comment by susanodd** [comment]
@vanlummelhuizen helped me get the send_mail working for registration. (The mail server had not been set.)

1. Regarding the From address in the new user email, can this be you, @ocrasborn ? Or does Signbank have its own email address?

2. In the emails, it uses the SITE_ID from the settings and looks up the domain and site name in the django_site table. In settings, it had been set to 1, which is example.com. Now it's that of Signbank. But the name of the site is still NGT Signbank.
@ocrasborn , @Woseseltops , or @vanlummelhuizen can somebody update this on the live database?

**Comment by susanodd** [comment]
I pushed the most recent registration code to github.

1. Registration is not available on the "login" page.

2. The user can enter the requested datasets as shown in the screenshots above.
Once the user has submitted, the system sends emails to the owners of each dataset (provided they are also in group Dataset_Manager).

3. There is an activation step for the user. The user receives an email to their submitted email address to activate their account. This doubles to make sure that the email address is valid.

4. For resetting passwords, if an email has multiple usernames, the user will receive a resetting link for each username. The username is shown in the respective emails.

**Comment by ocrasborn** [comment]
@susanodd and @Woseseltops , I just tested it for Global/NGT, and it works OK (some ideas for minor improvements to follow). For ASL, however, there is no menu dataset manager as datasets are not active there, right? If we'd follow the same procedure there, it may be a bit confusing to users: they've been granted access after confirming their account request with the link in the email, but they cannot do anything yet. Requesting access to a specific dataset in the registration process is also a bit odd there, it should always be the one and only existing dataset. We could fill that in by default (or do so and hide the field from the form), but that still leads to the strange user experience of 'I can log in, but I have not been granted access'. What shall we do about this? 
One idea: we can keep accounts inactive until they have been granted view permission for at least one dataset, and send them an email confirmation as soon as that has been done ("Your account is active and you have access to dataset X.")
And shouldn't users be notified of every dataset manager approval, in case they've asked permission for two or more?

**Comment by susanodd** [comment]
I made the is_public field visible for edit on the Dataset Detail View.
I was going to use that field to limit the set of datasets a new user can request.
But at the moment, none of the datasets have is_public set to true.
Do you want the Default Dataset used if there are no public datasets?
(The Default dataset, NGT, is not public.)

**Comment by ocrasborn** [comment]
Hi @susanodd , please set it to true for NGT and for NGT non-signs.
For the other datasets, the dataset managers can "overrule" this, right? In the sense that they can still add permissions for users, even though the users cannot (yet) request access to that particular dataset.

**Comment by susanodd** [comment]
Yes, that's true. The managers can grant and revoke.
Does there need to be a Request access button anywhere for the datasets, maybe in the list view?

**Comment by ocrasborn** [comment]
Yes that would be a good idea at some point. Let's wait a while before we do that, though, until more datasets are actually public.

**Comment by ocrasborn** [comment]
I think this is good for now. I will add a new issue for @susanodd 's last suggestion. -->
