### ISSUE TITLE
Make the translation method more appropriate depending on the type of data

### ISSUE THREAD

**Issue by vanlummelhuizen** [Signbank/Global-signbank#357]
There are several methods to make translations in Signbank:

1. Django standard ugettext method (the 'trans' command, .mo and .po files)
2. Hard-coded as class field, e.g. annotation_idgloss_en, translations of web pages
3. The class Translations (which for now are only translation into Dutch, so also kind of hard coded)

With Multiple Languages / Datasets milestone and Internationalisation label, some data will be labeled with a (spoken) language label. E.g. the hard-coded annotation_idgloss (Dutch) and annotation_idgloss_en (English) will be replaced by a dynamic system.

This issue is for making it so that all things are translated is an appropriate way, also the things that are not touched upon when working on Multiple Languages / Datasets milestone and Internationalisation label, e.g. web pages.

**Comment by vanlummelhuizen** [comment]
Done: translation equivalents (= keywords)

**Comment by vanlummelhuizen** [comment]
@ocrasborn I am transforming the annotation_idgloss (for NGT: Dutch gloss) and annotation_idgloss_en (for NGT: English gloss) to an annotation_idgloss that is dynamic for language so that you can also have French gloss, Farsi gloss etc.

The result of this is that the Search gloss form in the header of the page no longer refers the Dutch/default annotation_idgloss. This search is now done across all languages. The search string is therefore not assigned to any language specific gloss search field in the search form.

**Comment by ocrasborn** [comment]
But not the English gloss, right? Sounds good to me, @vanlummelhuizen

**Comment by ocrasborn** [comment]
Can this be closed, @vanlummelhuizen ?

**Comment by vanlummelhuizen** [comment]
I guess so.
