### ISSUE TITLE
Problems with batch upload videos (2)

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#360]
It still doesn't generate new images on the basis of the newly imported video. I thought we had fixed this before, but maybe the move to the new location broke it?

**Comment by ocrasborn** [comment]
Oh, when you deal with this @vanlummelhuizen , could you re-run the 'generate image' for the whole dataset again?

**Comment by vanlummelhuizen** [comment]
On my local Signbank instance all work well. I think there are some problems with permissions, although I could not find that on the server yet. The logs also do not help. I am going to ask @Woseseltops for his view. 

See also #359.

**Comment by Woseseltops** [comment]
Has this been fixed in the mean time, @ocrasborn ?

**Comment by ocrasborn** [comment]
Looks indeed like it works now :-)
