### ISSUE TITLE
Install Signbank on Yale server

### ISSUE THREAD

**Issue by Woseseltops** [Signbank/Global-signbank#362]
Documented here: https://github.com/Signbank/NGT-signbank/wiki/Installation-report:-RHEL7,-new-VM,-July-2017

**Comment by vanlummelhuizen** [comment]
When doing migrations, please follow the procedure described in https://github.com/Signbank/NGT-signbank/issues/224#issuecomment-319912948.

**Comment by Woseseltops** [comment]
Note to self: think about what user should run Apache.

**Comment by Woseseltops** [comment]
Another note to self:

These are reversion table formats that you have to change in the database yourself:

reversion_revision
* 'comment' text NOT NULL
* 'date_created"datetime NOT NULL
* 'user_id' integer
* 'id' integer (primary)

reversion_version
* 'content_type_id'	integer NOT NULL
* 'format'	varchar(255) NOT NULL
* 'object_repr'	text NOT NULL
* 'object_id'	text NOT NULL
* 'revision_id'	integer NOT NULL
* 'id'	INTEGER NOT NULL AUTOINCREMENT (primary)
* 'serialized_data'	NUMERIC NOT NULL
* 'db' 	varchar(191) NOT NULL

**Comment by Woseseltops** [comment]
I tried to upgrade to the latest version, using the instructions by @vanlummelhuizen , but it failed because of some language settings not being correct. Since it's not really crucial for the American users that these last changes are live right now, I've decided that it's probably the most efficient use of my time to update until commit 7a6028b, and do the rest when @vanlummelhuizen is back.

To do:
* Think about Apache users and writing rights.
* Turn off debug mode (because of upcoming pentest).
* Talk to Kraig about the URL and https.

**Comment by Woseseltops** [comment]
Hurray! With the help of Kraig I today also managed to get Signbank installed on the Yale production server (already had the test server working before): http://spinup-000691.yu.yale.edu/ (you still need VPN to see it). Biggest problems were access for my special non-employee account and the rights to restart Apache.

I'm still on commit 7a6028b, made a branch for the changes I made to get things working here.

I'm currently testing whether everything works; I'm a bit worried about the video serving speed.

**Comment by ocrasborn** [comment]
:-)

**Comment by Woseseltops** [comment]
In the mean time, the server was (1) verified to be secure and (2) upgraded to have more CPU and RAM. Everything is a lot faster, but I'm not 100% satisfied yet.

In progress:
* Arranging HTTPS (Kraig)
* Arranging the URL (Kraig

To do (now that I know that upgrading hardware does not mean a complete reinstall of everything):
* Install a backup mechanism
* #363 
* #364 
* Making stuff even faster
* A number of issues that are marked [after asl migration](https://github.com/Signbank/NGT-signbank/issues?utf8=%E2%9C%93&q=label%3A%22tbc%20after%20asl%20migration%22%20)

At launch day:
* Nijmegen server down
* Take last version of the db
* Upgrade this db structure to work with Signbank until 7a6028b
* Together with Micha, upgrade Sigbank and database to current version
* Nijmegen server redirects to American one

**Comment by Woseseltops** [comment]
Done:
* Arranging HTTPS (Kraig)
* Arranging the URL (Kraig)

In progress:
* Install a backup mechanism
* SVN ( #363 )
* Making stuff even faster

**Comment by Woseseltops** [comment]
( This means you can now see the ASL Signbank at https://aslsignbank.yale.edu )

**Comment by Woseseltops** [comment]
Done, but needs to be verified:
* Install backup mechanism

No longer needed:
* Making stuff even faster

In progress:
* SVN #363 
* Scripts #364

To do:
* A number of issues that are marked after asl migration
* Swap Day: together with @vanlummelhuizen I picked November 15.

**Comment by ocrasborn** [comment]
@Woseseltops , will you let our American colleagues know about Swap Day in time?

**Comment by Woseseltops** [comment]
Of course... who should be informed?

**Comment by Woseseltops** [comment]
(Reminder of this question, @ocrasborn. My email is ready to be sent, I only need recipients!)

**Comment by ocrasborn** [comment]
I'll let you know by mail, @Woseseltops

**Comment by Woseseltops** [comment]
Verified: backup mechanism works
Done: SVN #363
In progress: Scripts #364 

To do:
* Swap day
* A number of issues marked 'after asl migration'

**Comment by Woseseltops** [comment]
Okay, Swap Day was a lot more intensive and had a lot more problems than I thought, but we've got things in a workable state again. 

In progress: Scripts #364

To do:
* Make the ECV file available over HTTP
* #384, remove manual changes needed to make ASL work
* Fix the 'too many SQL variables issue'
* Fix the language problem in the admin
* A number of issues marked 'after asl migration'

**Comment by Woseseltops** [comment]
In progress:
* Scripts #364 
* 'after migration' issue #293
* Make the ECV file available (might be solved by fixing HTTPS at the client side)

Done:
* Fix the 'too many SQL variables issue'
* Fix the language problem in the admin
* All other 'after migration' issues

**Comment by ocrasborn** [comment]
Update:
* #293 is also fixed now.
* Scripts #364 appears OK but remains open for checking that it works well.
* Not sure about the ECV file, @Woseseltops ?

**Comment by Woseseltops** [comment]
Status of the ECV file as far as I know:
* Hard to acquire by Elan because of HTTPS
* Americans are now using a frozen version hosted on Applejack.
* Micha seems to have a workaround to make Elan accept HTTPS; he's in contact with Lee about this.

**Comment by ocrasborn** [comment]
ELAN works with https now also on Mac (cacerts file in Java 1.6 was missing in latest installations of the Mac OS; by moving it back manually from another installation, everything appears OK again).

**Comment by Woseseltops** [comment]
All todo items in this issue are done I believe, and for the problems we are still having we created separate issues.

**Comment by ocrasborn** [comment]
hurrah!

**Comment by ocrasborn** [comment]
(oh, I thought I was to close it)
