### ISSUE TITLE
Create hyperlinks in display of handshape values to handshape details

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#369]
Both in the detail view and the list view

**Comment by susanodd** [comment]
This has been done. (Pushed to master branch on github.)
I made it so for the Detail view, the Handshapes are hyperlinks when you're just viewing, but in Edit mode, you can still modify the selection in the pulldown menu.

**Comment by susanodd** [comment]
I made it so the hyperlinks become hidden during editting, then are either restored or revised when editing is switched off.
This has been uploaded to github, master branch.

**Comment by susanodd** [comment]
Non-existent handshapes in Gloss Detail view are now shown as values in red rather than a hyperlink.
This can happen if a handshape has been deleted.

**Comment by Woseseltops** [comment]
Can this now be closed again, @susanodd ?
