### ISSUE TITLE
Reverse relations involving a gloss not updated on updating the role

### ISSUE THREAD

**Issue by susanodd** [Signbank/Global-signbank#379]
In the Gloss Detail view, Relations to Other Signs can be added, deleted, and existing relations can be modified.
The code differs in what is done.
When a new Relation is added, reverse relations are also automatically added.
When a Relation is deleted, the reverse relations are deleted.
But when the role of an existing Relation is modified, nothing is done to the reverse relations.

**Comment by Woseseltops** [comment]
Hey @susanodd , since you're the one that created this issue, do you also want to be the one to execute it now it has high priority?

**Comment by susanodd** [comment]
Hi, @Woseseltops, you're welcome to do it.
At the time, I wasn't sure what Django automatically does. If it should be the same relation, with a different role value, or if a new relation should replace the previous relation. The user can also select things for the role that are actually computed otherwise.

When we changed to Ajax, I started worrying that things could end up being done eagerly.
The user can stay in Edit mode and keep modifying the gloss.The idea of bumping the user out of Edit mode was to force a commit to be observable to the user.

**Comment by Woseseltops** [comment]
Okay I just tried this out, and the situation is exactly as @susanodd describes: if you add a hypernym relation from sign A to B, sign B automatically gets a hyponym relation to sign A (cool, had no idea), but when you edit the type of relation this automated procedure does not work. 

I see two potential solutions:
* Few minutes: simply remove the functionality to edit relation roles.
* Few hours: when you change a relation type for x to y, go look for the opposite relation type of x in the corresponding sign, and change it to the opposite relation of y. 

I prefer the first one; the functionality is barely used and doesn't save the user much time. What do you think @ocrasborn ?

**Comment by ocrasborn** [comment]
I agree @Woseseltops , let's do this the quick way.

**Comment by Woseseltops** [comment]
Done.
