### ISSUE TITLE
Generate dataset-specific ECVs for all datasets

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#387]
* Also for currently empty datasets (empty ECV), so that as soon as glosses are added, they will appear in the ECV.
* And have these all updated overnight
* And then: #386

**Comment by vanlummelhuizen** [comment]
This is done now. When generated the ECVs should be downloadable using ```/static/ecv/<datasetname>.ecv```.

**Comment by ocrasborn** [comment]
Works! Three requests to optimise this, with decreasing priority:
* The languages in the dataset should depend on the description languages of the data set, and not always English and Dutch like for NGT.
* Remove spaces from data set names with spaces in them (Kata Kolok e.g.). I was actually able to load the URL with a space, didn't know that was possible, but I reckon one day or other it'll bother us, no?
* Please make the feedback page a bit more user-friendly. Suggestion (instead of "OK"): "ECV successfully updated." and auto-redirect that after 3 seconds to where the user came from, namely https://signbank.science.ru.nl//datasets/available

**Comment by ocrasborn** [comment]
Works! Three requests to fine-tune this:
* (most importantly:) the languages in the ECV should match the description languages of the dataset, and not always be Dutch and English like it is now.
* Please remove spaces from ECV file names corresponding to dataset names with spaces (like Kata Kolok). Although I was able to load a url with spaces in safari, I bet it will generate problems sooner or later.
* Generate a bit more user-friendly feedback message (now: "OK"). Suggestion: "ECV successfully updated.", and auto-redirect after three seconds or so to https://signbank.science.ru.nl//datasets/available

**Comment by ocrasborn** [comment]
Open issues:
* (most importantly:) the languages in the ECV should match the description languages of the dataset, and not always be Dutch and English like it is now.
* And what I forgot to specify to this point: make sure the three-character language descriptors match that of the content.

**Comment by susanodd** [comment]
Okay, I'm working to make an automated test for this.

**Comment by ocrasborn** [comment]
@vanlummelhuizen , could you finish the open issues in this issue?

**Comment by vanlummelhuizen** [comment]
> LANG_DEF should be a specific URL for each label

The LANG_DEF is not in the Signbank data so it cannot be added dynamically unless we add a field to the Language model and fill it for each language. Fortunately, this element is optional in ECV. For now, I will leave it out.

**Comment by vanlummelhuizen** [comment]
Update: although LANG_DEF is not required by the XML Schema, ELAN seems to need it. Unfortunately, the cdb.iso.org urls do no longer exist. So I cannot find a method to link a 3 character language code to a cdb.iso.org url. To be continued...

**Comment by vanlummelhuizen** [comment]
Ok, I found the language data file ELAN uses to verify stuff: http://catalog.clarin.eu/ds/ComponentRegistry/rest/registry/components/clarin.eu:cr1:c_1271859438110
I now use this to generate the ECV. Seems to work.

**Comment by vanlummelhuizen** [comment]
My solution is live now. @ocrasborn could you please test?

**Comment by Woseseltops** [comment]
Is this question for @ocrasborn still open?

**Comment by ocrasborn** [comment]
yes, I have yet to test this.
