### ISSUE TITLE
ASL search form has field label "Dutch gloss"

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#389]
@vanlummelhuizen , not sure whether this is related to making the languages more dynamic, if not, and this remains hard-coded for ASL, please just fix this in between the other work.

**Comment by Woseseltops** [comment]
I think this is related to some problem with translating the interface language (with the .po files and stuff). However, in the last version of Signbank (which is not visible yet on the ASL Signbank, they're always a few weeks behind), this part of the page is dynamically created based on available translation languages, so let's wait until the ASL Signbank catches up. If all goes well, this problem will fix itself :) .

**Comment by vanlummelhuizen** [comment]
This seems to be solved. Close?
