### ISSUE TITLE
Change columns that display on pages Proposed new signs and Recently added signs

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#391]
* On both these pages, the Annotation ID Gloss is shown twice, with different headers. Please make the first column display the Lemma Gloss, the second column the Annotation ID Gloss.
* The addition "(English)" to Annotation ID Gloss should be left out. (This may be related to Micha's  languages overhaul, or change again due to it?)

**Comment by Woseseltops** [comment]
The column is always there because there currently is no code to check if the column should be hidden. However, similar to #389, these columns will become dynamic once the ASL Signbank catches up. If all goes well, this problem will be fixed automatically.

**Comment by vanlummelhuizen** [comment]
I have high hopes.

**Comment by susanodd** [comment]
There is currently an error displaying the recently created signs.
This variable is not defined in base.py: RECENTLY_ADDED_SIGNS_PERIOD. The page displays glosses with isNew = True.

**Comment by susanodd** [comment]
I fixed the bug by using a timedelta of 90 days in the code that was using the missing declaration.

**Comment by ocrasborn** [comment]
Current state: only the Creator and Creation Date are displayed, but not the ID Glosses!
