### ISSUE TITLE
Problem with alignment of video in Safari

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#396]
Don't have this problem on Firefox or Chrome on Mac, but the content of the video window in the detail view is moved to the right some 100px, leaving a black rectangle on the left. See screen shot of https://signbank.science.ru.nl//dictionary/gloss/3208/.
Safari also has problems displaying some webcam-uploaded movies, as in https://signbank.science.ru.nl//dictionary/gloss/4720/ Upon first loading the page, the first frame is a minute image in a black video window, then upon clicking it, it plays back alright.

Both are not new, I've had this since a month or two.

<img width="629" alt="screenshot 2018-01-05 12 40 20" src="https://user-images.githubusercontent.com/10242207/34607987-6a92599e-f216-11e7-90cc-6a25f09d071f.png">

**Comment by vanlummelhuizen** [comment]
@susanodd will you also move the video iframe in

* signbank/dictionary/templates/dictionary/word.html
* signbank/dictionary/templates/dictionary/morpheme_detail.html

to a HTML5 video tag?

 There is also a \#videoiframe item in media/css/style.css. After changing all video iframes to video tags, I assume it is no longer necessary. Please check and remove if possible.

**Comment by susanodd** [comment]
The #videoiframe in the css needs to be there because it sets the size of the video frames.
In the <video code I left the identifier id='videoiframe' the same, so that's what it's doing with the css.

**Comment by ocrasborn** [comment]
It works well now on my Safari, but the autoplay has been turned off, which we really liked. Is there a way to turn that back on?

**Comment by vanlummelhuizen** [comment]
Autoplay in now working, also in Safari. Happy @ocrasborn ?
