### ISSUE TITLE
Visualise at all times which data sets are selected

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#397]
* Perhaps by using tags at the bottom of the header? Or is that very ugly? Right below the header?
* Either way, it needs to be a flexible space, so that it could display 10 or more dataset tags.

**Comment by susanodd** [comment]
This has been done. Pushed to github master branch.

**Comment by ocrasborn** [comment]
Great!

**Comment by Woseseltops** [comment]
Hey @susanodd , this is indeed working, well done!

I have an idea for an improvement, though: I noticed you added the dataset information to the context of various views; I think it's also possible to add information of the context of ALL Signbank views at once (don't remember how from the top of my head). Benefit would be that the info really shows up everywhere, and less duplicate code. What's your view on that?

**Comment by ocrasborn** [comment]
A request to make this look nicer: not list the selected datasets as comma-separated text, but as visual objects like our tags are displayed now. I like the way they are displayed in FinSL SB: as small rounded rectangles. For us, the colour should not be purple but the same colour blue as the actual tags.

**Comment by susanodd** [comment]
![menu-bar-tags-selected-datasets](https://user-images.githubusercontent.com/24272544/37410898-da54b3b0-27a1-11e8-9899-1d597ce05623.png)

**Comment by Woseseltops** [comment]
Interesting new look :). 

Suggestion: make it not exactly like the tag visual, because datasets are not tags. Having the triangle on the other side would already be better, or maybe both? Rounded squares could also work, but then you risk that they look like buttons.

**Comment by ocrasborn** [comment]
Good point, about the confusion with buttons. How about we make them rounded rectangles, but then in a light shade of pink? Then it kind of goes with the red of the header, and is clearly distinct from the tags and the buttons. See the Finnish SB, where the small rectangles look nice. They are small though: the spacing below and above the text should be smaller than in the present screen shot.

**Comment by ocrasborn** [comment]
@susanodd , did you already take up @Woseseltops 's suggestion above to move the code to a single place, rather than repeat it for every view? If so, then this can be closed, I think. If not, let's first do that before closing this.

**Comment by Woseseltops** [comment]
Yeah this is what it meant. It won't be long until we are the ones asking you questions about Signbank/Django instead of the other way around @susanodd  :).
