### ISSUE TITLE
Deal with non-Ascii characters in Lemma ID Gloss when saving image/video files

### ISSUE THREAD

**Issue by vanlummelhuizen** [Signbank/Global-signbank#403]
A gloss image or video is saved with the Lemma ID gloss in the filename. If the Lemma ID gloss contains characters that are not allowed in a file name, the file cannot be saved. 

Considerations:

* Django can manage files (https://docs.djangoproject.com/en/1.11/topics/files/), so no need to do that ourselves.
* Django has something called Generic Relations (https://docs.djangoproject.com/en/2.0/ref/contrib/contenttypes/#generic-relations) so that an (image, video, etc.) object can refer to any other object (such as a Gloss object).
* Using these two Django solutions does not include version management. 
* The solution by @stevecassidy (https://github.com/Signbank/signbank-video) does include version management, but deals with handling of the file itself.

**Comment by ocrasborn** [comment]
Two comments:
* Characters not allowed, does that include file names in Chinese characters?
* We discussed informally that video files should really be based on Annotation ID Gloss values, not Lemma ID Gloss values. Perhaps take that into account when working on this?

**Comment by henrinie** [comment]
@vanlummelhuizen What kinds of issues are you facing? I don't think we have had anything like this.
Can you check the LANG environment variable, what is it set for your web server?
I think I had to change that at some point, since our apache defaulted to C, instead of UTF-8, see: https://github.com/Signbank/FinSL-signbank/wiki/Install#apache-envvars

**Comment by vanlummelhuizen** [comment]
@ocrasborn indeed Chinese characters for instance. We agreed that the current method, Lemma ID Gloss and Gloss ID, was sufficiently identifying for now. And the Annotation ID Glosses are now language depentent, how would you like to determine which to use?

@henrinie nice catch. It seems our Apache installation is using ```export LANG=C``` so we could try and change that. @Woseseltops, would that be an option?

**Comment by susanodd** [comment]
Chinese characters are a problem. I think I came across a test sign of @ocrasborn.

![unicode-error-gloss-3698](https://user-images.githubusercontent.com/24272544/35971959-33a78970-0cd0-11e8-8968-130066b10657.png)
![chinese-character-in-video-path](https://user-images.githubusercontent.com/24272544/35972115-d3a596ec-0cd0-11e8-937d-a16f5d45f040.png)

**Comment by ocrasborn** [comment]
If the problem is in the file naming, @susanodd , we can put this problem on hold for later, we're using English movie names right now and for the dataset Shanghainese that is what we will stick to.

**Comment by susanodd** [comment]
Can this be closed now?

**Comment by vanlummelhuizen** [comment]
@susanodd I think so. Closing in 3, 2, 1...
