### ISSUE TITLE
The 'search result scroll bar' doesn't work well for handshapes

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#408]
When clicking on a random handshape from the list of all handshapes (so without having done a search), a bar appears with only three buttons called 'undefined'. It works fine when displaying the results of a search action by the user.
Please make the search result bar in this case display all items.

**Comment by susanodd** [comment]
I'm not able to recreate this error on my local signbank. Can you give a more detailed sequence of commands?

**Comment by susanodd** [comment]
I modified the code so that if no query results have been done for handshapes and the search_type is handshape**, it will show all handshapes in the navbar. Hopefully this will give different behaviour now.

**this should be true when first arriving at the page during a session if no searches have been done

**Comment by ocrasborn** [comment]
@susanodd , it looks like you broke something else while addressing this issue: the hyperlinks on the handshapes names in the default list (so the one that appears when selecting menu item 'Search handshape' from the menu 'Signs') lead to error pages. If I search for a handshape, the links in the list of results work fine.

**Comment by susanodd** [comment]
Okay, I managed to get this undefined error on the live server.
I couldn't duplicate it before, now something to investigate.

**Comment by susanodd** [comment]
It might have something to do with the Reset button.
