### ISSUE TITLE
Revise footer

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#41]
- Use CC picture instead of text for Creative Commons license
- Make hyperlink on CC picture refer to the Copyright page
- Remove the text about feedback from the footer

**Comment by ocrasborn** [comment]
Not sure what my task is here, @Woseseltops . The image can be reused from https://signbank.science.ru.nl//about/copyright/

**Comment by Woseseltops** [comment]
No task for you, @ocrasborn , you self-assigned this one in March :)

**Comment by vanlummelhuizen** [comment]
@ocrasborn @Woseseltops Copyright are now handled per dataset. So, close this issue?

**Comment by Woseseltops** [comment]
Okay for me.

**Comment by ocrasborn** [comment]
yes, good point @vanlummelhuizen ; we'll close this.
