### ISSUE TITLE
Adapt counting of search results

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#412]
The number of search hits (e.g. "Number of matches: 748 out of 6163") now takes the total number of records in the gloss table as the maximum size (6163 in the example). Please adapt so that it adds up the possible maximum number for the number of selected datasets only, not for all datasets.

**Comment by susanodd** [comment]
The code is currently is showing the total of the currently selected datasets. (The datasets you have selected in the Datasets pulldown menu page. See screenshots below.)

![select-datasets](https://user-images.githubusercontent.com/24272544/35615142-8f3ec48e-0671-11e8-99f7-288a4cf57d76.png)
![query-search-signs](https://user-images.githubusercontent.com/24272544/35615145-93323e86-0671-11e8-8e4e-005444fb7e2f.png)

**Comment by susanodd** [comment]
If you have no datasets selected, then the search defaults to all signs in all datasets.
On the Datasets view page, the totals shown there are signs + morphemes.

![select-no-datasets](https://user-images.githubusercontent.com/24272544/35615778-7887dbc0-0673-11e8-8df2-51c82cdf3a29.png)
![dataset-list-view-nothing-selected](https://user-images.githubusercontent.com/24272544/35615785-7d0cec1c-0673-11e8-82c7-93bf486f5ae6.png)

**Comment by susanodd** [comment]
Here are two queries for signs and then signs or morphemes, with no datasets selected.
(Observe all the Annotation ID Gloss columns. The total for the sign or morpheme query is the same as the total of the totals on the Dataset list view page.

![query-view-no-dataset-selected](https://user-images.githubusercontent.com/24272544/35615861-b749a532-0673-11e8-8629-1d55f5926dcf.png)
![query-signs-morphemes-no-dataset-selected](https://user-images.githubusercontent.com/24272544/35615863-baa2701a-0673-11e8-8e9a-35b3ae6144cf.png)

**Comment by ocrasborn** [comment]
@susanodd : Confirmation of what we just thought of over coffee: indeed its with searching signs-by-handshape that the count is not based on the dataset selection.

**Comment by susanodd** [comment]
This has been fixed and pushed to github.
Indeed, the bug was on the Signs with Handshape query page!
