### ISSUE TITLE
Stop new functionality breaking ASL Signbank

### ISSUE THREAD

**Issue by Woseseltops** [Signbank/Global-signbank#415]
We already made some edits in #413 to get the ASL Signbank up and running again, but the users found more places that we accidentally broke:

* Not being able to delete signs (EmptyResultSet error)
* Not being able to use the 'search' item in the 'signs' menu (EmptyResultSet error)
* Missing columns in the proposed new signs (but not the 'recently added!')

The kind of bugfixes are likely to be really similar to what we did in #413 .

**Comment by susanodd** [comment]
Is there a way to relate these errors to the Global sb?
Is it possible to show which committed changes were done between the code working and not working?
Some (recent) changes have been made with permission checks wrt to datasets (in the templates).
Are datasets available in the ASL signbank?

**Comment by susanodd** [comment]
I made some changes yesterday to prevent users without permission from being able to delete things.
The old permissions weren't working anymore (anybody could previously delete anything), the new permissions are at the dataset level to prevent people without permission from deleting things.

**Comment by susanodd** [comment]
Below are some screenshots to show the recent changes in permissions (at the Dataset level)
The user needs to have permission to change the dataset in order for the Edit buttons to be visible.

![susanodd-permissions-ngt-dataset](https://user-images.githubusercontent.com/24272544/35732672-a98ae9b2-081a-11e8-85f4-d2884ebd30df.png)
![dataset-testdatasetmicha-permission-susanodd](https://user-images.githubusercontent.com/24272544/35732675-aea1c380-081a-11e8-9288-a3128791ae66.png)

**Comment by susanodd** [comment]
An NGT sign susanodd has permission to edit. The Add/Delete buttons become visible duing Edit.

![ngt-sign-can-edit](https://user-images.githubusercontent.com/24272544/35732727-d346ec24-081a-11e8-8dc6-e7de09c5c7b6.png)
![ngt-sign-edit-buttons-visible](https://user-images.githubusercontent.com/24272544/35732734-d8b713d2-081a-11e8-8f16-f4e997401615.png)

**Comment by susanodd** [comment]
A TestDatasetMicha sign susanodd does not have permission to edit. The Edit button is not shown and there are no Add/Delete buttons.

![testdatasetmicha-sign-top](https://user-images.githubusercontent.com/24272544/35732805-27f12bc2-081b-11e8-8628-f8dbc4f17073.png)
![testdatasetmicha-sign-rest](https://user-images.githubusercontent.com/24272544/35732810-2bb406a8-081b-11e8-8945-19527e563663.png)

**Comment by susanodd** [comment]
If there aren't any Datasets in ASL then that would be the problem.

**Comment by susanodd** [comment]
I've been using the system setting SHOW_DATASET_INTERFACE_OPTIONS to conditionally hide Dataset things that should not be visible for ASL.

**Comment by Woseseltops** [comment]
> Not being able to delete signs (EmptyResultSet error)
> Not being able to use the 'search' item in the 'signs' menu (EmptyResultSet error)

Turns out this was a print statement added to the Django code (not signbank code) to fix upgrade problems we had two weeks ago. The debug code itself was causing new problem 

![image](https://user-images.githubusercontent.com/1909317/35979078-a86fac80-0ce7-11e8-95a5-c0e608625ecd.png)

As for:

> Missing columns in the proposed new signs (but not the 'recently added!')

Turns out @susanodd already fixed that some time ago in b69fc6e, a commit that didn't make it to the ASL branch yet.

The things Susan mentions are also useful and related, but not what this issue was about ;).
