### ISSUE TITLE
Integrate description languages in search form for glosses

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#417]
* After #405 
* Different fields side by side for each description language (Lemma ID Gloss, Annotation ID Gloss, Translation Equivalents, Annotation Instructions)

**Comment by ocrasborn** [comment]
* Especially when multiple datasets are selected, the search form is now messy (and too big for the template's width), see screenshot below. Proposal: every description language for the sum of the selected datasets in a row, with four fields in columns: Lemma ID Gloss, Annotation ID Gloss, Translation Equivalents, Annotation Instructions.
* Just like now, all should be configured to interpret strings as regular expressions

![screenshot 2018-02-08 17 17 32](https://user-images.githubusercontent.com/10242207/35984270-5d3eb55a-0cf4-11e8-8b14-56f5cb1ec8e3.png)

**Comment by susanodd** [comment]
I'm looking at this issue to see how it's currently working.
I noticed that when a lot of fields appear on one row, as you show above, when you try to type stuff in, it doesn't seem to work. I was trying to enter a translation to search for Norwegian, 'norge'. But the browser swapped the "n" I was typing for an "i". After selecting only one dataset, Norwegian, it worked okay.
I'm going to make the mockup for how you want it to be. (Before issue #405.)

**Comment by susanodd** [comment]
The keyword translations already have the language id stored in the database table, so I could do it analogously to the Annotation ID Gloss fields. Here's what it looks like.

![query-translations-per-language](https://user-images.githubusercontent.com/24272544/36681286-79a0b900-1b18-11e8-8268-0f5a29603586.png)

I can't find any examples of non-empty Annotation Instructions in the database.

**Comment by ocrasborn** [comment]
Yes, that's the type of layout I had in mind (but with the Lemma Gloss in the middle). The annotation instructions will only be used very occasionally for any dataset, but when they are used, they're important to us, and we'd also want to be able to search for them.

**Comment by ocrasborn** [comment]
One last request for refining, @susanodd . Now that we have multiple fields we have six question marks with a help menu for regular expressions. Would it be possible to add just a single one after "Form your query", deleting the present six ones? The pop-up text should then be modified to read: "In many text fields, you can use..." or something like that.

**Comment by susanodd** [comment]
Fixed.

**Comment by ocrasborn** [comment]
Great! We might have to reopen this later after #405 , adding _Lemma ID Gloss_ and _Annotation Instructions_ to the table.
