### ISSUE TITLE
Create a function to generate an ECV for all datasets

### ISSUE THREAD

**Issue by Woseseltops** [Signbank/Global-signbank#418]
As of recently, there is a separate ECV for each dataset. The current situation is that there is a separate button and thus GET request to generate each of these ECVs. 

We want some functionality, to be used by the nightly cronjob, that will automatically look which datasets there are, and generate an ECV for each one.

**Comment by susanodd** [comment]
As a first step, the export_ecv functionality has been moved from adminviews (GlossListView and DatasetListView) to the tools.py file. Buttons attached to these views now check permissions etc before calling the export function in tools.py.
The tools.py file will offer the required function to generate all the ecv's.

**Comment by susanodd** [comment]
The function is write_ecv_files_for_all_datasets().
