### ISSUE TITLE
Several small changes to handshape search page

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#424]
1. The search panel currently collapses in two stages: first the panel itself can expand/collapse, and then the display of the panel bar can be collapsed by clicking on "Form your query". Please remove this latter step, which gives no added functionality, and always display the panel bar/header that the user can click on to show/hide the search fields.
2. Remove pagination: always list all handshapes by default, and any number as the result of a query.
3. Change the default sort order in perhaps a bit of a difficult way: first in two blocks with first handshape names that do not and then handshape names that do contain an arrow >, then within those blocks alphabetically on handshape name.

**Comment by susanodd** [comment]
The first two are done.

**Comment by susanodd** [comment]
@ocrasborn, Do you need the sorting on the other columns to work differently? Should the handshapes always be partitioned?

**Comment by ocrasborn** [comment]
Not sure what you're asking here @susanodd , I'll drop by to discuss it face to face. Thanks for picking up on the other requests so quickly!

**Comment by susanodd** [comment]
The sorting has been adjusted too.
One thing to note, for interface language Chinese, some handshapes don't have a Chinese name.
I just revised it so they show up in the results, but there is no hyperlink (the column is blank).

**Comment by ocrasborn** [comment]
ah thanks for spotting that @susanodd , I'll go fill in the English names as placeholders for now.
