### ISSUE TITLE
Downloading files in Other Media is broken in Safari

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#425]
* Or actually, what is downloaded is a minute file named other_media.jpg, instead of the stored file.
* It seems that this only happens for the Shanghainese dataset, not the NGT one. For the sign https://signbank.science.ru.nl/dictionary/gloss/6535, the file that is stored is .../6535/SHSF177DX59-??????.MP4. So it seems neither the gloss nor the ID number is applied to the file name.
* Have not yet tested what happens when uploading other media to the NGT dataset after the introduction of datasets, might well be broken there too

**Comment by vanlummelhuizen** [comment]
OK, I looked into how the code works for importing other media. It has no similarities to importing videos or images. Instead, it expects a index.csv with the following header: Idgloss,filename,type,alternative_gloss. Per per media file there should be a row in the csv. So, the question now is: what does the index.csv you used for gloss 6535 look like?

**Comment by ocrasborn** [comment]
We've manually uploaded most movies, only once used the import route with the CSV. Just tested for https://signbank.science.ru.nl/dictionary/gloss/6689 that this manual upload still works fine, but the download link leads to the same jpg file as for all the other records.

**Comment by ocrasborn** [comment]
(and now also confirmed that the uploaded file is in the expected place on the server: othermedia/6689/ZWEMMEN-B.mp4)

**Comment by vanlummelhuizen** [comment]
Ok, I need more info. Do you upload to import_other_media/ or directly to othermedia/? If the first, what url do you open to start the import process? What did you upload for the Shanghainese 6535 gloss?

**Comment by ocrasborn** [comment]
I don't upload directly through the server. In the test sign above and in most other cases (incl. all of the other media for Shanghainese), we used the web interface for uploading other media.

**Comment by vanlummelhuizen** [comment]
Fast forward (skipping the face to face conversation with me and @ocrasborn ): when I remove the "download" attribute from the a-tag, Safari displays the video as expected.

(Note that this is only a problem in Safari, not in Chrome or Firefox as far as I can tell.)

**Comment by ocrasborn** [comment]
Any downside to doing that?

**Comment by vanlummelhuizen** [comment]
It is not immediately downloaded, so you have right click the video to download and then the back button to go back to the gloss detail page. Or, right click the link to begin with and select Download linked File.
Not too complicated but a bit less user friendly.

**Comment by ocrasborn** [comment]
let's do it, I say

**Comment by vanlummelhuizen** [comment]
okidoki

**Comment by vanlummelhuizen** [comment]
Ok, I tested one more thing: make the "download" attribute contain the correct file name. That works. It will take some extra effort to implement. Hang on.

**Comment by vanlummelhuizen** [comment]
Let me know what you think @ocrasborn

**Comment by ocrasborn** [comment]
I didn't need to think: my eyes saw it works now. Thanks for your creativity to work around Apple's quirks!
