### ISSUE TITLE
Create copy of database to homedir of @susanodd daily

### ISSUE THREAD

**Issue by Woseseltops** [Signbank/Global-signbank#431]
And set the rights so she can access

**Comment by Woseseltops** [comment]
Added to Onno's crontab that every morning at 400h, the database is copied. Things I did different from the original proposal:
* I don't copy to the homedir of @susanodd but to /vol/tensusers2/seven ; this is because the homedir is not always available if a user is not logged in.
* I don't change the rights; during the copying process this is already done automatically.

I worry about the cronjob process not having access to the database. Let's keep this issue open to see if it works.

**Comment by Woseseltops** [comment]
It's working @susanodd (cc @vanlummelhuizen )! Close if happy.

**Comment by vanlummelhuizen** [comment]
@Woseseltops I am happy! Closing now...
