### ISSUE TITLE
Revise cron job for generating ECV to apply to all datasets

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#433]
Using the output of #418: function write_ecv_files_for_all_datasets()

**Comment by Woseseltops** [comment]
Ha, made it into a oneliner:

```
echo "from signbank.tools import write_ecv_files_for_all_datasets as w; w()" | /scratch2/www/signbank/bin/python /scratch2/www/signbank/repo/bin/develop.py shell
```

Please keep this issue open so I have a reminder to check whether it really works.

PS
Just noticed this issue doesn't have the 'high priority tag'... too bad, I already did it.

**Comment by ocrasborn** [comment]
* The cron job is doing its work well, but the content of the ECVs still need to be adapted for the description languages involved. (plus #112 )
* The old cron job for just NGT can be removed (log message: "Cron <ocrasborn@applejack> /home/ocrasborn/corpusEcvUpdater/corpusEcvUpdater.sh ")

**Comment by Woseseltops** [comment]
> the content of the ECVs still need to be adapted for the description languages involved. (plus #112 )

What I see in the ECV is that for each gloss there is an English and a Dutch description. Do you mean that this should be dynamic, based on the dataset? If yes, isn't that the same as what you say at the end of #387 ? If yes, let's continue the discussion there :) . 

> The old cron job for just NGT can be removed 

It already is; corpusEcvUpdater.sh is something different (a script by Micha that updates eaf files in the corpus-ngt SVN repo).

**Comment by ocrasborn** [comment]
Oh I see, I just didn't get a log email from that before. Good that I do now.

Indeed, the language issue is covered by #387, so I'll close this now.
