### ISSUE TITLE
Change some aspects of the menu bar

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#439]
* Remove "Sign search" button from menu bar (We don't need it, hitting enter has the same effect; it will make space for the user name also when that is a bit longer than John Doe)
* Make the search fields about 30% narrower (so that just the string "Search translation" is visible); we rarely have longer glosses
* Centre-align the flag vertically (it's now higher than the middle)
* The result will be that everything except the list of datasets fits on one row. The second row is then reserved for the list of selected datasets (also to be refined, see #231 )

**Comment by susanodd** [comment]
See the screenshot in #397.
I improved the format, the search fields are narrower and all the fields are on one row.
It didn't work to remove the Search button. Here's why.
If the button gets removed, there needs to be a hidden input field of type "submit". But to make it invisible, the type needs to be set to "hidden" (instead of "submit").
Alternatively, the "hidden" can be put in "style visibility hidden". But doing so causes two lines of menu bar fields! (A new line gets inserted after the invisible submit.)
I wasn't able to solve this weird behaviour. But I did get the flags and formatting to stop jumping.

**Comment by ocrasborn** [comment]
OK, I see. I prefer another solution then: create a square submit button with just an arrow-right-character (→). That will reduce the space taken by search fields and button, so that we can put menus plus login plus search on the first row. The second row can then be for the selected datasets. (They are different types of information: the three of the first row are something the user can interact with, the selected datasets are just a visualisation of something that has been set by the user.)
If that square button doesn't create enough space on the first row, perhaps the menu items could be spaced a bit closer together than they are now.
I'm also wondering whether we should keep Feedback as a menu: some of its items are already elsewhere, and the way it is implemented now it is not linked to the dataset functionality. But let's leave that as a last option for making space for now.

**Comment by susanodd** [comment]
![revised-navbar-search-selected-datasets](https://user-images.githubusercontent.com/24272544/37604679-d167e8be-2b91-11e8-9e4b-1a354e1168c9.png)

**Comment by ocrasborn** [comment]
Ah, of course, a magnifying glass, much better than an arrow! I also like the size and style of the dataset labels like this, but perhaps we need to experiment with the colour a bit together, later this week.

**Comment by susanodd** [comment]
![dataset-buttons-new-style](https://user-images.githubusercontent.com/24272544/37656673-035b543e-2c49-11e8-9b0a-d113182b219f.png)

**Comment by vanlummelhuizen** [comment]
@susanodd To keep the submit button without showing it: style="display: none".

**Comment by susanodd** [comment]
That caused other problems.

**Comment by vanlummelhuizen** [comment]
Such as ... ?

**Comment by ocrasborn** [comment]
I'm fine with the magnifying glass, it's small, immediately clear, and nicely word-less. Could you still finish this issue by changing the location of the various items, more or less cf. the requests above? So:
* Row one: Menu items; search fields; login info; flag
* Row two: dataset tags, left-aligned

See mockup:
![sb_menubar](https://user-images.githubusercontent.com/10242207/38099625-68aeb36a-337b-11e8-952c-99fd9e38eb77.png)

**Comment by susanodd** [comment]
![navbar-with-datasets](https://user-images.githubusercontent.com/24272544/38308342-124e7f96-3817-11e8-9992-fd580617d74a.png)

**Comment by susanodd** [comment]
This has been fixed. When you resize, the elements move to the next line, and if it's really narrow, the menu's also get changed to lists. I also removed some unused code that wasn't diplaying anything.

**Comment by Woseseltops** [comment]
Is the correct issue to talk about the fact that Signbank now uses the full width of the screen instead of only the middle part? If so: I like it better than I thought it would, except that for some views (like the detail view) we now have a large white space on the right side. 

Proposal: if we have no content to fill the full width of the screen, center the content.

**Comment by ocrasborn** [comment]
I support Wessel's proposal.
Some tinkering is still needed for the menu bar:
* on Safari, the top of the page is hidden behind the menu bar + data set selection row. Not so on Chrome/Mac.
* On Safari plus Chrome, the selected dataset list appears to the right of the menu bar when the window is very wide. That is actually not a bad idea to save pixels in height, but a) to make that functional, the empty vertical space below that I see now first row would need to disappear, and b) it should only happen if all selected datasets fit. Do you agree with that, @Woseseltops? Or is it too messy that the location of the dataset list is not always in the same place?
* When two rows are needed, there is too much space above the dataset list.

**Comment by susanodd** [comment]
I worked on the full screen width today, to repair the weird affix bar behaviour I had caused yesterday.
I fixed it so the full width is working now.
The datasets stay on the second row, to the left now, also when you resize.
I had some trouble with the feedback line at the bottom of the page. Sometimes it ends up to the right rather than underneath (when a page is basically just slightly longer that the window, when there's no scrollbar at the side of the window, the browser seems to put it next to the rest rather than make a scroll bar.
If all the datasets are visible, it all fits across.
They stay on the second row now. If you make the window narrower and narrower, it all gets collapsed until it's all in one column with the pull-down menus stacked.

**Comment by susanodd** [comment]
It needs some more tweaking. Helaas. Sometimes the width also gets a scroll, which is probably not the intention.

**Comment by susanodd** [comment]
![wide-window-menu-bar](https://user-images.githubusercontent.com/24272544/38428656-98f2630e-39bc-11e8-9526-ea4d682d520f.png)

**Comment by susanodd** [comment]
![midway-scroll-after-search](https://user-images.githubusercontent.com/24272544/38428787-e8f2d280-39bc-11e8-81d8-2666ce581b7e.png)

**Comment by susanodd** [comment]
The second screenshot shows the affix bar after scrolling a bit inside a search.
Perhaps the column headers also need to be affixed?

**Comment by susanodd** [comment]
![search-with-columns-showing](https://user-images.githubusercontent.com/24272544/38428909-38d676ee-39bd-11e8-9908-3f7948d0769b.png)

**Comment by susanodd** [comment]
When you see how many Annotation ID-Gloss columns there are, the Dataset icons don't look so bad! :)

**Comment by Woseseltops** [comment]
Done, @susanodd ?

**Comment by ocrasborn** [comment]
One small request @Woseseltops  (other than what @susanodd may still be working on): to reduce the vertical white space between the menu bar and the selected dataset labels (by about half of what it is now).

**Comment by Woseseltops** [comment]
You mean just decreasing the height of the menu bar, @ocrasborn ? Just did that, give it a look.

Do note that this area is becoming rather crowded/messy:

![rect8482](https://user-images.githubusercontent.com/1909317/40167162-9071c750-59c0-11e8-943b-013b905561e1.png)

**Comment by Woseseltops** [comment]
Now that I was thinking about the design of the menu bar, one thing that strikes me is that the search icon contains so much more detail than the rest of the layout:

![](https://signbank.science.ru.nl//static/images/rightpointing_magnifying_glass.png)

How about:

![search-button](https://user-images.githubusercontent.com/1909317/40170296-5b8a4f46-59c8-11e8-95d7-b12bd094ecf4.png)

Or even:

![search-no-button](https://user-images.githubusercontent.com/1909317/40170305-61691d20-59c8-11e8-98f8-4495c96b1699.png)

**Comment by ocrasborn** [comment]
Nah, it's fine to do this in the present one. 
How about a yet more minimal one: simply leaving it out and forcing the user to use enter? Or isn't that possible on some browsers? The box already says 'search'.

**Comment by Woseseltops** [comment]
> forcing the user to use enter? Or isn't that possible on some browsers

Definitely possibly on Firefox and Chrome (I've never actually clicked the button, now that I think of it)... maybe if you can verify Safari, we can simply remove the button?

**Comment by ocrasborn** [comment]
No problem in Safari.

**Comment by Woseseltops** [comment]
Aaand it's gone.

**Comment by henrinie** [comment]
I'd strongly advise not going against the standard ways of building interfaces, it is not good for general usability, or assisted technologies for instance.
It might be confusing to mobile users, and even regular desktop users.

I tested it with mobile (android, firefox and chrome), it works if you press the "enter" on the "keyboard".

I noticed however that on mobile your site is a bit broken, the menu bar takes all the space on the screen, and you have like 20px height for the content on the page, which is almost impossible to scroll or view. Maybe the navbar collapse doesn't work currently?

**Comment by ocrasborn** [comment]
Cf. discussion this afternoon, @Woseseltops : please make the button visible again, but use a simpler image for the magnifying glass.

**Comment by Woseseltops** [comment]
Which of the visual suggestions above do we prefer? @vanlummelhuizen , do you have more suggestions?

**Comment by ocrasborn** [comment]
Either above is fine for me. Perhaps the un-button-like second one is a bit more quiet to the eyes.

**Comment by vanlummelhuizen** [comment]
I think the un-button-like one is probably the clearest and the simplest. If we want the user to search for either gloss or translation, we could consider one field and a dropdown-button cf. https://getbootstrap.com/docs/4.0/components/input-group/#buttons-with-dropdowns. But that would force the user to do an extra click.

**Comment by ocrasborn** [comment]
Please let's keep the two separate fields: they have the function of reminding the user that the gloss is not the meaning of the sign.

**Comment by Woseseltops** [comment]
Added the minimalistic search button in commit e01215f2ac6a19d1bfbb467023cdda7279d2a03d .
