### ISSUE TITLE
Recently added signs page doesn't include recently added signs

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#443]
I forgot how the page was generated, on the basis of which criterion that was, but either way: it somehow does not include the recent signs for various datasets (BISINDO, Shanghainese, Norwegian SL). Is there a relation to the introduction of datasets, perhaps?

**Comment by susanodd** [comment]
See these examples. First, the dataset BISINDO is selected, then "all" signs are queried (i.e., no query parameters filled in).
![select-bisindo-dataset](https://user-images.githubusercontent.com/24272544/37591749-c78e5582-2b6c-11e8-8861-04bbd4bff13a.png)
![query-all-signs-selected-dataset-bisindo](https://user-images.githubusercontent.com/24272544/37591756-cdc0159e-2b6c-11e8-9485-7368a6d9daf1.png)

**Comment by susanodd** [comment]
Next, query parameter signlanguage BISINDO is selected.
Now there is only one result.
It looks like it has to do with Dataset versus Sign Language.
![query-select-signlanguage-bisindo](https://user-images.githubusercontent.com/24272544/37591875-35148c48-2b6d-11e8-95a0-08d12f79988a.png)
![query-signlanguage-bisindo-selected-dataset-bisindo](https://user-images.githubusercontent.com/24272544/37591882-390cf63c-2b6d-11e8-94e1-480fdbfa13ed.png)

**Comment by susanodd** [comment]
It looks like maybe the Signlanguage hasn't been set for some signs in dataset BISINDO?

**Comment by susanodd** [comment]
I'll see what the recently added signs is doing. Maybe the order in which things are queried is causing results to be thrown out before checking if they are recently added.

**Comment by ocrasborn** [comment]
Ah, well spotted! I don't understand how it might have come about though. Dataset selection is now enforced through the new sign menu item and button in the search form, but perhaps language is then not set anymore? Likewise for generating dorms through csv import? (Which we didn't do recently)

**Comment by susanodd** [comment]
I found the error. But we fixed this once already, so I don't see how it can be broken again.
The definition of RECENTLY_ADDED_SIGNS_PERIOD is not being imported correctly in the code.
It raises an exception whereby the "isNew" flag is used in the query rather than the creation date.

**Comment by susanodd** [comment]
Believe it or not, datetime.now() stopped working! That's what's causing the exception.

**Comment by susanodd** [comment]
Okay, I fixed it. This is very strange because the code used to work. Based on searching for datetime.now() in the code, it looks like Django defined some pretty printing on top of the original date functions. I imported datetime to a different name, as is done elsewhere in the signbank code.

**Comment by susanodd** [comment]
One other thing, do you want to restrict the list of recently added signs to the selected datasets, if any?

**Comment by ocrasborn** [comment]
Yes, please @susanodd : only recently added signs from the presently selected datasets.

**Comment by Woseseltops** [comment]
Happy @ocrasborn ?
