### ISSUE TITLE
ASL Signbank down

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#445]

**Comment by Woseseltops** [comment]
Up again. Same mysterious problem as last time.

Temporary solution:
* Apache off, wait 30 seconds, Apache on again.
* We now check automatically every 15 mins if ASL Signbank is still up, and send a mail otherwise.

Probably related:
* Weird request every second.

**Comment by Woseseltops** [comment]
The check works. Started to get messages since 1145h, fixed within 2 hours .

**Comment by ocrasborn** [comment]
👍

**Comment by Woseseltops** [comment]
Strangely, this didn't happen since April. We'll reopen this issue if it does.
