### ISSUE TITLE
When editing a Lemma IDGloss the value is a <a href...> if it is in a lemma group

### ISSUE THREAD

**Issue by vanlummelhuizen** [Signbank/Global-signbank#446]
![afbeelding](https://user-images.githubusercontent.com/16682631/37705832-933c60f2-2cfd-11e8-9579-aea4515d5bc0.png)

**Comment by susanodd** [comment]
On which page is this?
Mine showed it okay when I first went to the sign.
Then I deleted the Lemma ID Gloss field to try to get tje error you show.
But the entire field (row) disappeared from the Gloss.

**Comment by susanodd** [comment]
Found it. It's when there is a lemma group. I will fix this.

**Comment by susanodd** [comment]
Question @ocrasborn, do you want to do anything particular if a user tries to delete a Lemma ID Gloss field? I will leave it set to the original value in this case.

(The entire field was disappearing from the Gloss Detail View if the user set it to be empty.)

**Comment by ocrasborn** [comment]
What you propose seems good @susanodd ; it should not be left empty. (And since it must contain unique values, two empty fields should lead to errors as well, I imagine. Not sure how/where that is arranged though.)

**Comment by susanodd** [comment]
Okay, this has been fixed.
I also added code to catch (prevent) setting Lemma ID Gloss and the Annotation ID Gloss fields to empty. If this arises, they are left the original values.
I did this in Morpheme View as well.
However, there are no hyperlinks for Lemma ID Gloss in Morpheme View.
(Not sure how this relates.)

**Comment by susanodd** [comment]
@ocrasborn, this has been fixed. Are you happy with this?

**Comment by susanodd** [comment]
This has been pushed to github. When the user tried to erase the Lemma ID it was temporarily showing up as undefined instead of the original value until the page was reloaded. This has been fixed. The user has to type in a new value if they want to change it.

**Comment by ocrasborn** [comment]
yes, @susanodd !
