### ISSUE TITLE
Update requirements

### ISSUE THREAD

**Issue by henrinie** [Signbank/Global-signbank#449]
Hello, I tried setting up global-signbank, the requirements seem pretty outdated and are missing some stuff.
Getting it to run seems quite complicated as there are many settings files which all are imported to base.py, and the share similar variables.

https://github.com/Signbank/Global-signbank/blob/master/requirements.txt
`django==1.6.1` <-- what version are you really on?
```
ImportError: No module named 'modeltranslation'
ImportError: No module named 'guardian'
```

**Comment by susanodd** [comment]
On my local computer, inside the virtenv, this is what pip list shows:
Django (1.11)
django-bootstrap3 (8.2.1)
django-debug-toolbar (1.9.1)
django-guardian (1.4.9)
django-messages (0.5.3)
django-modeltranslation (0.12.1)
django-reversion (2.0.8)
django-summernote (0.8.6)
django-tagging (0.4.5)
django-versatileimagefield (1.2.2)
olefile (0.44)
Pillow (4.2.1)
pip (9.0.1)
pytz (2017.2)
selenium (3.8.1)
setuptools (36.0.1)
six (1.10.0)
sqlparse (0.2.4)
wheel (0.29.0)

**Comment by Woseseltops** [comment]
This was also mentioned by the Brazilians that tried to install Signbank.

**Comment by Woseseltops** [comment]
Fun fact, for totally unrelated reasons I needed to do this for #448 . What a coincidence.
