### ISSUE TITLE
Use regular expression search for all text fields

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#450]
* Now it's only used in the gloss and translation equivalent fields
* Please add for the Phonology & Semantics fields that consist of text string searches
* And for the Annotation Instructions field
* And for 'Note contains' under Publication Status
* Did I miss any other field?

**Comment by Woseseltops** [comment]
Okay, this seems to work for most fields. For example, when you now search for ```ba.*``` as virtual object, you get banana, basket ball, balie, etc. 

My changes affected the fields: 
* virtual object
* mouth gesture
* mouthing
* phonetic variation
* annotation instructions
* iconic image
* phonology other
* created by

I didn't do notes yet. 

Also, I noticed that if you regex is wrong, you get the general error page... maybe we can tell the user in real time whether what they are typing in is a valid regex (similar to how some websites while creating an account show you in real time that your password is not okay)?

**Comment by Woseseltops** [comment]
> I didn't do notes yet.

It's working for notes now too. 

> maybe we can tell the user in real time whether what they are typing in is a valid regex

I also looked into detail in the differences between different regex engines, and I've come to the conclusion that it's complicated, and probably not worth the time investment.

Happy @ocrasborn ?

**Comment by ocrasborn** [comment]
Happy, @Woseseltops . Let's not invest in the reg exp checking, then.
