### ISSUE TITLE
Errors when creating new glosses

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#451]
* Something apparently was changed recently in such a way that the uniqueness of a new _Annotation ID Gloss (English)_ is no longer enforced within datasets but across datasets. Please address this a.s.a.p. (and perhaps include it in a test?).
* Example: IF-A occurs in NGT, but not in Shanghainese. If I add IF-A to Shanghainese, I get the message "English annotation ID Gloss not unique."
* Other example: adding IF to BISINDO = same error.

**Comment by susanodd** [comment]
I'm having a look at this one.
In the code, this seems to be the constraint causing the problem:

class AnnotationIdglossTranslation(models.Model):
    text = models.CharField(_("Annotation ID Gloss"), ...........)
    gloss = models.ForeignKey("Gloss")
    language = models.ForeignKey("Language")
    class Meta:
               unique_together = (("gloss", "language"),)

The Dataset isn't actually mentioned here. Since English is one of the translation languages for both Dutch and Shanghainese, this is causing the error.

**Comment by susanodd** [comment]
Currently, the database constraint is checked before allowing the new gloss creation. It is the combination above that is checked. To perform the check, a query is done against the objects in AnnotationIdglossTranslation with the proposed combination.
I added an additional check on the found objects to see if the glosses are (not) in the proposed Dataset.
WIth that, it works to create the gloss you describe (IF-A in Shanghainese). Then if you try to create the exact same gloss again, it gives the error: Chinese annotation ID Gloss not unique.
(I did this on my local machine.)
We need to implement tests for this.

**Comment by ocrasborn** [comment]
@vanlummelhuizen : could you think along with @susanodd so that this is addressed in the right way?

**Comment by vanlummelhuizen** [comment]
Susan's solution worked on my computer. I made a small change (that also worked!). It is live now. Please test by hand. We will write a automated test.

**Comment by ocrasborn** [comment]
In fact, it works again, so thanks @susanodd and @vanlummelhuizen .
