### ISSUE TITLE
Fix the video count for glosses, database versus file system storage

### ISSUE THREAD

**Issue by susanodd** [Signbank/Global-signbank#452]
As part of testing video upload (#400), I have been looking at the video routines.
The objects of GlossVideo (glossvideo_set) are searched by the Gloss Detail view (gloss.count_videos) to show how many videos are currently stored for the gloss.
Django does this via the gloss id.
The gloss GEVOEL-B (3356) used to be GELUKKIG-B (3356). All of the old filenames of previous videos for the GELUKKIG-B gloss are still in the database for gloss 3356.
The GlossDetail view, on uploading a new video in Edit mode, incorrectly reports that there are 7 videos for this gloss. Although we can't actually do anything with these.
I discovered that the addvideo function called by Upload Video was not deleting old video urls from the GlossVideo table, nor from the file system. It just keeps adding new data to the table.
The new video file replaces the old one, but only if it's the same ID Gloss (name).

As a first part of correcting this, I have changed the code to remove obsolete filenames from this table.

The old files may or may not still be on disc. If it's a new video for the same gloss, it gets replaced.
In the example of gloss 3356, the Annotation ID Gloss and Lemma ID Gloss were actually changed for this gloss id. This perhaps makes the videos GELUKKIG-B-3356.mp4 a bit dangerous since they could be re-captured if somebody changed the ID Gloss fields back to what it used to be.

@ocrasborn do you want anything done with the old video files?

**Comment by ocrasborn** [comment]
They can all be deleted as far as I'm concerned: we've abandoned an earlier 'revert video' function if I'm not mistaken, and we keep backups of the videos we uploaded so won't be searching on the server for old versions. Cleanup is welcome.

**Comment by vanlummelhuizen** [comment]
I found a problem for the glosses that had their lemma changed (e.g. CHAIRMEN to CHAIRMAN) and I solved it in the code. Next step would be to change the video files by hand.

For the second bit (e.g. ANGRY-B) I haven't found what the problem is. For all I know, someone just deleted the video. For these videos it is also not possible to put them back since they are really gone from the server.

**Comment by vanlummelhuizen** [comment]
Ok, I searched for videos of all Shanghainese glosses with tag 'video:_missing'. Apparently only the CHAIRMEN/CHAIRMAN video is still there. Some of the rest have a _small video (e.g. ANGRY-B) and others do not have a video at all (e.g. AFRICA-B). 

Another thing that I found out: The tag 'video:_mising' was given to the ANGRY-B between september 12 and october 5. Perhaps it is relevant. @ocrasborn

**Comment by Woseseltops** [comment]
Okay to help with this issue a bit I wrote a script that checks:
1. Whether a normal video is present
2. Whether a small video is present
3. Whether there is a video that has the same pk in its name
4. Whether an image is present

These are the cases where 1 and/or 4 is/are false, but one of the others is true:

|Gloss|Normal video present|Small video present|Video with same PK|Image present|
|-|-|-|-|-|
|CHAIRMAN|||x||
|TEASE-A|||x||
|ACROBATICS-B||x||x|
|ACROSS-B||x||x|
|ADMIT-B||x||x|
|AGREE-A||x||x|
|AGRICULTURE-A||x||x|
|AIR-CONDITION-B||x||x|
|ALARM-CLOCK-B||x||x|
|ALWAYS-A||x||x|
|ANGRY-B||x||x|
|ANHUI-A||x||x|
|ONE-TWO-THREE-FOUR-DIME|x||x||
|PACK-B|x||x||

**Comment by Woseseltops** [comment]
Okay, seems like there are two types of glosses with the `video: missing` tag:
* Glosses where there are signs that indeed something went wrong. This is the table above... I guess best fixed manually?
* Glosses where there are no such signs; for all we know, these glosses never had a video. 

Now we know this, is there anything you'd like us to do, @ocrasborn ?

**Comment by ocrasborn** [comment]
Thanks for creating the table @Woseseltops , we'll fix them manually. I think that concludes this issue. Correct, @susanodd ?

**Comment by susanodd** [comment]
When a video gets uploaded, it replaces the previous video as far as the user can see.
The Gloss Detail View shows a "video count" it gets from the database. But this is not accurate.
There is either no video or one video per gloss.
@ocrasborn - is it okay to remove the "We have N videos for this sign."text from the Edit Gloss View?
(See Issue #522.)

**Comment by ocrasborn** [comment]
@susanodd : yes, it's OK to remove that text

**Comment by susanodd** [comment]
This has been pushed to github.
This issue can be closed when live.
