### ISSUE TITLE
Cannot delete a sign

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#453]
The confirm/cancel window that pops up is greyed out as it were. Perhaps related to the layout changes to the menu bar, because part of this window is hidden under the search result scroll bar (which is pushed down by the new menu).

**Comment by susanodd** [comment]
Did you try clicking on Edit first?
Do you want the Delete button visible "not inside of Edit" ?

**Comment by susanodd** [comment]
Oh, I see what you mean, my entire browser goes grey!

**Comment by susanodd** [comment]
I'll put it back outside of Edit. I'm the one who did this.

**Comment by susanodd** [comment]
@ocrasborn, can you recall the last time you were able to delete a sign?
It's not the navigation bar that is messing it up. Yes, it ends up hidden, but even when it's not hidden, it  doesn't work. The entire Delete dialog window is greyed out.

**Comment by ocrasborn** [comment]
@susanodd : Err.... nope. Maybe a few weeks ago?

**Comment by susanodd** [comment]
This has been fixed!

**Comment by Woseseltops** [comment]
This is broken again, both for the Global and ASL Signbank (and also reported by both user groups)

**Comment by susanodd** [comment]
This has been fixed. The Delete Gloss Modal had wandered inside the definitionblock div.

**Comment by Woseseltops** [comment]
It's working, thanks @susanodd  . Also added it to the ASL branch.

**Comment by Woseseltops** [comment]
Deleting notes has the same problem!

**Comment by susanodd** [comment]
This has been fixed! Pushed to github.

**Comment by Woseseltops** [comment]
Works, also added to the ASL branch.
