### ISSUE TITLE
Rotate SB logo 90 deg cw

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#456]
(Don't know why it ended up rotated 90 deg ccw, and initially I didn't care much, but it's actually nicer to use it the way the designer created it.)

**Comment by Woseseltops** [comment]
Funny issue, cool issue number. Done?

**Comment by ocrasborn** [comment]
Done.

**Comment by ocrasborn** [comment]
We need to revert this step -- my mistake! The initial drafts of the logo had the opening on the left, but the final one that we ended up using has the opening at the bottom. For a very specific reason, as one of the designers explains in the video that I will add to the site shortly. So @Woseseltops , could you rotate it 90 dec ccw now? :-)

**Comment by ocrasborn** [comment]
(This is not strictly 'blocking' me from working, but it's a minor thingie to quickly fix that will allow me to post the artist's story about the logo, which has been on the shelff for ages. I'd like to tick off that box.)

**Comment by Woseseltops** [comment]
Done; sorry it took so long :P. I was expecting writing this comment would be the most work for this task, but I ran into a wasp's nest of git problems that needed to be solved before this could be published.
