### ISSUE TITLE
Create alternative detail view where all fields+values are visible on a single screen

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#46]
- Design a new layout without expanding/collapsing panels such that all fields can be read at a glance
- Assume 1920x1080 screen resolution; scrolling on smaller screens
- Permanently display three buttons at the top left of each view: Public view / Detail view / Total view (? better term??), highlight the selected one in blue (just as for the Search/CSV/Clear buttons above search results)

**Comment by susanodd** [comment]
@ocrasborn are you still wanting this?

**Comment by ocrasborn** [comment]
Nah, I think that this has long been addressed with the 'expand all' arrow.
