### ISSUE TITLE
Add help popup about regular expression to the Sign Search button in the menu bar

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#462]
See #301

**Comment by susanodd** [comment]
This has been added.

**Comment by Woseseltops** [comment]
A thought... wouldn't it make more sense to put them inside both text boxes, for example on the right side, so it's just clear that they are instructions about how to use the text? Maybe they can disappear once you start typing.

**Comment by ocrasborn** [comment]
Yes, good idea!

**Comment by susanodd** [comment]
I made it so the tooltips show up when hovering over the text boxes. The question mark has been removed.
It didn't work to put them inside the box since that alters the size of the boxes and messes up the formatting of everything else.

**Comment by Woseseltops** [comment]
I think that's even cleaner, cool! What's your view @ocrasborn ?

**Comment by ocrasborn** [comment]
Yes, very satisfied with this solution!
