### ISSUE TITLE
Create more elegant fix for datasets problem in gloss_detail.html

### ISSUE THREAD

**Issue by Woseseltops** [Signbank/Global-signbank#463]
Because for ASL the dataset variable does not get filled, we got a javascript syntax error and problems with references to this variable from gloss_edit.js . Right now, the lines that are problematic are simply commented out (uncommited). What we want instead:

* A more generic solution: this list should be empty if the dataset functionality is not used.
* The result is a Javascript error. Maybe we can add a unit test that checks whether all Javascript generated by the detail view is valid? https://pypi.org/project/pyjslint/

**Comment by susanodd** [comment]
I added code in the javascript  variable declarations to set the dataset_choices to empty if the SHOW_DATASET_INTERFACE_OPTIONS is false. That way, the gloss_edit.js doesn't generate an error, since the select choices are just empty rather than undefined.

**Comment by Woseseltops** [comment]
Nice solution @susanodd ! Clean and simple

**Comment by Woseseltops** [comment]
Also added the javascript unit test. Turns out a package that does a full Javascript syntax check and is still functioning is not that easy to find (does it even exist?), so I indeed manually defined a two combinations of letters that I do not want to see in the Javascript.
