### ISSUE TITLE
Create more elegant fix field choice retrieval problem

### ISSUE THREAD

**Issue by Woseseltops** [Signbank/Global-signbank#464]
In the homonyms function of the gloss model, it is checked whether the handedness of a gloss is of a particular value; this is done by retrieving a field choice that is assumed to exist. This field choice does not exist of the ASL Signbank. Right now, this is fixed by commenting out the code that needs the field choice, but we rather:
* Change the part of the code that assumes the field choice to exist
* The result was a Django error and the detail view page... Maybe we can add a test that verifies the detail view does not have a Django error ?

**Comment by susanodd** [comment]
Is the Handedness field the only one where this applies? In the code there is a long list of field names.
Do you need the list of field names to be generated instead of hard-coded? (i.e., not just Handedness.)
This may be related to Issue #340.

**Comment by Woseseltops** [comment]
Thank you @susanodd . Your code is now on the ASL branch as well , and I already added a unit tests 2 weeks ago.
