### ISSUE TITLE
ASL site header is still screwed up after update

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#466]
Not sure whether you still had this on your radar @Woseseltops , sorry if you were already on it!

**Comment by Woseseltops** [comment]
Definitely on my radar, but as far as I'm aware, this is the status of this issue:

Me:
> the Dutch version has had quite a number of layout changes (wider screens, more concise rows). The ASL version shares a number of stylesheets (=place where the looks of the site are defined) with the Dutch version, but also has some of its own which are not changed. The result is a strange mix of the old and new layout. Perhaps you can have a look at https://signbank.science.ru.nl/ and let me know if you fully want to move over to the new layout as well?

Lee:
> I suspect we'll be interested in fully following the new stylesheets, if Julie also consents.

That is, we're still waiting for an official 'go' from the ASL team. Seems like a good opportunity for a new tag :) . I didn't send a reminder so far because there's enough other work to do for the ASL SB.

**Comment by ocrasborn** [comment]
The developers agreed today to follow the NGT style sheets, and then can later fine-tune things for ASL when they are not happy with some of the details. --> go ahead, @Woseseltops

**Comment by Woseseltops** [comment]
Moved the ASL Signbank completely to the Dutch layout, and then changed back the header color and the logo (and removed the language picker) . Let's see if new problems pop up.

**Comment by Woseseltops** [comment]
Got now complaints. Let's reopen if they pop up.
