### ISSUE TITLE
Fix access for non-logged in users

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#472]
* For both Global and ASL, the public view works whne someone is not logged in, but it doesn't seem to function for signs that have the checkmark 'In web dictionary' under Publication Status, like it should. An error page results (for ASL, see test item PRODUCE-SIGN, for Global-NGT, RADBOUD).
* See xxx for a related issue.

**Comment by susanodd** [comment]
Search by anonymous users has been fixed. The above error showed up in the results. The hyperlinks were not going to the public pages...
I fixed the hyperlinks, but there's a glitch.
The sign SIGNBANK has a *compound part* SIGN-A (GEBAREN-A).
But SIGN-A (GEBAREN-A) has inWeb set to No, so the error presents if you click on this.

**Comment by ocrasborn** [comment]
Hm, yes. Not quite sure what the preferred behaviour should be here. The same might hold for relations between signs in the panel with that same name (synonyms, homonyms, etc.). [...thinking...] I think just a generic error message 'This sign is not available to anonymous users' would be best.

**Comment by Woseseltops** [comment]
I just tried this to see if this is still an issue, and I discovered that I can no longer reproduce this: when I'm not logged in, I get no compound information. Does that mean this issue can be closed @ocrasborn ?
