### ISSUE TITLE
NoReverseMatch for ASL glosses when logged out

### ISSUE THREAD

**Issue by Woseseltops** [Signbank/Global-signbank#476]
I would expect the public view for glosses in the web dictionary.

This is also a nice opportunity for a unit test: does the public view work when logged out?

**Comment by susanodd** [comment]
This has been fixed for Global. Pushed to github.

**Comment by Woseseltops** [comment]
Added to the ASL branch, it works. Remains: a test that verifies that signs in the web dict are always visible.

**Comment by Woseseltops** [comment]
Test is working!
