### ISSUE TITLE
When creating a new gloss, set the selected dataset to the default dataset

### ISSUE THREAD

**Issue by Woseseltops** [Signbank/Global-signbank#479]
Another usability suggestion from Julie. I see the `DEFAULT_DATASET` setting is already there, let's use it here.

**Comment by ocrasborn** [comment]
Yes, good idea

**Comment by vanlummelhuizen** [comment]
When discussing this with Wessel we came up with two possible implementations/solutions:

1. Use the `DEFAULT_DATASET` only if `SHOW_DATASET_INTERFACE_OPTIONS` is false. This would help the users of ASL signbank, but not annoy the users of Global Signbank not using the default dataset.
2. Use the last used dataset per user. This way everyone benefits. A user has to select a dataset only once if he/she is creating a bunch of new glosses for one dataset.

I also suggested that Julie could use the CSV import for creating a bunch of new glosses.

**Comment by Woseseltops** [comment]
Suggestion by @vanlummelhuizen : this option might be a legacy thing; in the Global Signbank where we have multiple datasets, what is the 'default dataset' differs per person. I might be more useful for more users to just remember what is the latest dataset they used to create a new sign, and have that as the preselected option next time.

**Comment by susanodd** [comment]
I've been working on this.
I made a session variable for the last_used_dataset. The default is None.
There are two ways into gloss creation. One is the pull-down menu; the other is a button on the Search page.
The pull-down menu for Add new sign makes use of the last_used_dataset.
I let the button on the Search page be the ---------- default. (By setting last_used_dataset to None).
Any preferences?

**Comment by ocrasborn** [comment]
Hi @susanodd ; on the Search page, there is currently no dataset button, right? What people select is a language, to narrow down results from the selected datasets. I think that can stay, although we do need to cut down the options of Language and Dialect there to the selected datasets. I'll make an issue for that.

**Comment by ocrasborn** [comment]
Can we close this issue, @susanodd ?

**Comment by susanodd** [comment]
Yes.

**Comment by Woseseltops** [comment]
This does not work anymore, both for global and ASL Signbank

**Comment by susanodd** [comment]
There are some other things messed up with gloss creation. I'm working on the permissions as part of #623.

**Comment by susanodd** [comment]
This may be ambiguous if the user has multiple datasets selected.

**Comment by susanodd** [comment]
In the gloss creation template, there is a pull-down menu to choose the dataset from among the selected datasets. (For Global there many be many. For ASL there is one.)

Write permission on the chosen dataset is checked during a gloss creation (in add_gloss in update.py)

It's a bit of chicken or egg.

At the moment (live Signbank), the "New Gloss" menu or button is only made available to users who have "add_gloss" permission. (Which is independent from the datasets. In #623 @ocrasborn has been granting users this permission by making them Editors.)
If the user has add_gloss permission (to be able to do stuff in the interface) additional checks are done in python to check permission for the dataset.

This bug may be related to (not having) the add_gloss permission.

**Comment by susanodd** [comment]
Okay, I can make it the default dataset.
This is actually already implemented that the last_used_dataset is set based on what the user is doing. Such as looking at Gloss Detail. So conceivably, if the user has two windows open to compare glosses in different datasets, it could keep being reset to the "last used".
The last_used_dataset is a session variable.

Indeed, the last_used_dataset is already passed as context to the GlossCreateForm.

@Woseseltops can you check on getting the error if the last_used_dataset is None?

**Comment by ocrasborn** [comment]
In the most typical situations, people will just select one at a time when adding/editing data, or if they have more, just work on one for a time. If needed though, it might be an idea to add a radio button option on the Select Database page for 'Default dataset'?

**Comment by susanodd** [comment]
The last_used_dataset code has been refined with additional cases.
It's set to:
(1) a single dataset (e.g., ASL or if only one has been been selected),
(2) the last used dataset based on user activity (original code),
(3) otherwise it sets it to the default dataset.
Previously, the last_used_dataset was only dependent on prior user activity before creating a sign. 
For example, if the user was searching for glosses and did a Gloss Detail View on a result, then the last_used_dataset was set to the dataset of that gloss.
If the user is looking at stuff in many datasets this will still be the case.

**Comment by vanlummelhuizen** [comment]
Changes are live.

**Comment by Woseseltops** [comment]
To do for me: add changes to the ASL branch.

**Comment by Woseseltops** [comment]
Now that I have looked at the (amount of) code changes, I think it's not practical that I will copypaste these to the ASL branch; let's wait for the next ASL upgrade instead.

**Comment by Woseseltops** [comment]
Julie asked about this again (and rightfully so). I don't want to upgrade the ASL Signbank without @vanlummelhuizen , so temporarily fixed this by hardcoding that the first dataset is preselected.

**Comment by susanodd** [comment]
This issue seems to have been subsumed by #859.
