### ISSUE TITLE
Make it possible to set a default data language per dataset

### ISSUE THREAD

**Issue by vanlummelhuizen** [Signbank/Global-signbank#480]
Instead of an application global default data language.

**Comment by ocrasborn** [comment]
Do you mean default in the sense of default-for-this-user? And where would this have effect? 
For the promotion of exchanging data and thus accessibility, we should take care to promote the use of English as the general default, for fields that are not mandatory.

**Comment by vanlummelhuizen** [comment]
It would for instance be used for the naming of video files. NGT video files now have Dutch names. Are you suggesting they should be changed to English?

**Comment by ocrasborn** [comment]
Ah I see. Nah, would prefer to keep them in Dutch.

**Comment by vanlummelhuizen** [comment]
Ok, I will go ahead with this then.

**Comment by susanodd** [comment]
This is needed for Homonyms List when the selected dataset is Shanghainese. (All the glosses are invisible, get_annotation_idgloss_translation sets this to an empty string.)

**Comment by susanodd** [comment]
I see what's happening. The default language is being set to Nederlands, but Shanghainese glosses only have English or Chinese translations.

**Comment by ocrasborn** [comment]
(Homonyms: see #495 )

**Comment by susanodd** [comment]
It's now possible for Dataset Managers to set the default language in the Dataset Detail View.

**Comment by ocrasborn** [comment]
Somehow in this process (or while revising the menu bar?) this page has been partly hidden under the menu bar again. The other two Dataset pages are fine. Could you look into this, @susanodd ?

**Comment by susanodd** [comment]
For which dataset does it do this? It's okay on my machine (for NGT).

**Comment by susanodd** [comment]
I'm up to date with github. Perhaps @Woseseltops modified the menu bar on the live server and didn't put it on github yet.

**Comment by vanlummelhuizen** [comment]
Solved. `dataset_edit.js` needed a variable `language_choices` which wasn't passed from the context into the template.

**Comment by vanlummelhuizen** [comment]
I believe this issue is done. Agreed, @ocrasborn, @susanodd ?

**Comment by vanlummelhuizen** [comment]
@susanodd  Lemma (Idgloss) translations should use the Dataset languages and also the Dataset default language. Does that answer this old question?

**Comment by vanlummelhuizen** [comment]
I am closing this issue because the whole discussion seems to have ended.
