### ISSUE TITLE
Add frequency of field values in brackets in detail view

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#487]
* In the pull-down menus for phonology and semantics in the Detail View, it would be nice to have between (square or round] brackets the frequency of that value in all the selected datasets.
* This will give users creating new entries a bit of help in seeing how frequent forms are typically coded.
* We could extend this to the search form.

**Comment by susanodd** [comment]
![pull-down-phonology-gloss-detail-with-frequency](https://user-images.githubusercontent.com/24272544/44722904-d5b20a00-aace-11e8-8568-9acb2764c864.png)

**Comment by susanodd** [comment]
(The screenshot only worked if it's the entire screen, not just the window.)

**Comment by ocrasborn** [comment]
Way cool, @susanodd ! Exactly what I was hoping to have. Will you be able to change the style sheet so that the drop-down list is white again?

**Comment by susanodd** [comment]
I added this for all the phonology fields that are lists, that are for glosses in the selected datasets.
Does this look okay?

**Comment by susanodd** [comment]
OH, was it white? Okay...

**Comment by ocrasborn** [comment]
Can you also do it for the field values under Semantics?

**Comment by susanodd** [comment]
It might be my computer. It looks like it's the same display (on my computer) for the real site.

**Comment by susanodd** [comment]
Okay, now that I figured out how to do it.

**Comment by susanodd** [comment]
This has been pushed to github.

**Comment by ocrasborn** [comment]
Great to see the frequencies 'live' in the system now, @susanodd . Did you notice though that the lists of values in the pull-down menus have become unsorted? Or at least, I don't see what the current sort order is. Please make sure they get re-sorted alphabetically again.

**Comment by susanodd** [comment]
This has been fixed! Pushed to github.

**Comment by ocrasborn** [comment]
Very happy, @susanodd and @Woseseltops , this really is a big step in more control over and insight in the data.
