### ISSUE TITLE
Add a 'Request access' button for datasets

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#488]
* In the list view?
* Only display for datasets that are set for public access

**Comment by susanodd** [comment]
Is it sufficient to have a button to request View access (for public access datasets)?
Or is a button also needed to request Change access (If the user already has View access)?

**Comment by ocrasborn** [comment]
View access is sufficient; Change access will not be frequent, and will need to be discussed (like in email) before anyway.

**Comment by susanodd** [comment]
Slight glitch. The dataset NGT non-signs, neither of the owners is a Dataset Manager.
(On my local machine, it's not working to send a -- print to command line simulation -- email to an owner.)

**Comment by susanodd** [comment]
I have this working now. Shall I push it?

**Comment by susanodd** [comment]
This is on the live server now. It's under View available datasets. A button shows up if you currently don't have view access and may request view access (public dataset).

**Comment by susanodd** [comment]
Maybe somebody can confirm that the email is still being sent to the intended dataset manager?
DEFAULT_FROM_EMAIL
EMAIL_HOST
I thought that these settings had gone missing when the lemma translations were added.
The settings have since been modified to make use of links so local settings can be different.

**Comment by Woseseltops** [comment]
![image](https://user-images.githubusercontent.com/1909317/50295381-35fefa00-0478-11e9-9c98-bba310c1eeea.png)

**Comment by susanodd** [comment]
I removed the first and last name fields from the email text template, in case they are empty as above.

**Comment by ocrasborn** [comment]
@susanodd , I think we should prevent them from being empty in the first place: if they are not obligatory yet, please make them so (create separate issue?).
A different request on this access: add a field where the requesting user can motivate the request, with the guidelines as follows: "Please explain why you would like to get access to this dataset. What are the purposes for which you wish to use it?"

**Comment by susanodd** [comment]
This has been pushed to github.

**Comment by ocrasborn** [comment]
Oh, what I forgot, @susanodd : if you didn't already, please also make the motivation field obligatory (adding a star to the field names for obligatory fields)

**Comment by susanodd** [comment]
It's now the case that all fields are obligatory.
With the except of selecting the requested datasets, which defaults to the default dataset if nothing is selected.
Do you want a star on every field?

**Comment by susanodd** [comment]
One thing that's still missing is the Gebruikersvoorwaarden that one supposedly approves.
Do these exist somewhere?

**Comment by susanodd** [comment]
I should clarify. The Motivation is on the New User Registration page.
It's not yet on the Available Datasets page. (One needs to be logged in to view that list.)
I'm working on this part now.

**Comment by susanodd** [comment]
The Motivation has been added to the Access request on the Available Datasets page.
(This only shows for users who do not currently have permission, such as user-dataset.)

**Comment by susanodd** [comment]
A hyperlink has been added for Terms of Service. (Pushed to github.)

**Comment by susanodd** [comment]
Are you happy with this @ocrasborn ?

**Comment by ocrasborn** [comment]
yes, @susanodd !
