### ISSUE TITLE
The Search Morpheme page is partly hidden under the header

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#489]

**Comment by susanodd** [comment]
I'm revising the Morpheme Search so it has multiple select fields.

**Comment by ocrasborn** [comment]
Hi @susanodd: both should at some point be addressed, but are low priority, as morphemes are not used for many signs  yet. That should change in the future though. Could you make new issues for both of these?

**Comment by Woseseltops** [comment]
What's the status of this issue, @susanodd ?

**Comment by susanodd** [comment]
Oops, the newly created concConcSet isn't found in the morpheme search form.

**Comment by susanodd** [comment]
This has been fixed and pushed to github. Sorry for the long delay.
Once it's live, the issue can be closed.
