### ISSUE TITLE
Change formatting of headers of Dataset pages

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#490]
On all three Dataset pages, the header (title of the page) is now only in boldface. Please adjust the formatting so that it mirrors that of other pages, like the Feedback pages. (The About pages I have edited myself in the menu and are a bit smaller (Header level 3), will adjust this myself, OC.)

**Comment by Woseseltops** [comment]
Looks done to me. Happy @ocrasborn ?

**Comment by ocrasborn** [comment]
indeed
