### ISSUE TITLE
Add the newly translatable Lemma ID Gloss implementation to the New Sign methods

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#491]
* It's now only present in the search form I think (after #357 ); please add it in the following places:
* On page Signs > Add new sign
* On panel in Signs > Search signs
* In Detail view
* In List view

**Comment by Woseseltops** [comment]
I guess it would be most efficient if @vanlummelhuizen did this one?

**Comment by vanlummelhuizen** [comment]
I am actually doing this (mostly done) in #405. It is not live yet because there are some (hopefully) minor things to do.

**Comment by Woseseltops** [comment]
I guess this is done, right @vanlummelhuizen ?

**Comment by vanlummelhuizen** [comment]
Yes.
