### ISSUE TITLE
Search by Phonology for Morphemes

### ISSUE THREAD

**Issue by susanodd** [Signbank/Global-signbank#492]
The search morpheme query page currently resembles that for signs.
The main difference is the Search by morphology panel, since it's morphemes we're looking for rather than morphology of a gloss.
Check whether e.g., the phonology search fields are relevant, or should be hidden for morphemes.

**Comment by ocrasborn** [comment]
The search fields are relevant, but the list of fields needs to be adapted: #638 and #639

**Comment by susanodd** [comment]
I'm looking at this issue now.

On the normal Search page, you can do either Sign or else Sign or Morpheme.

When searching on Morpheme Type (Hands: Handedness) via the Search Morpheme page, this returns five morphemes.

But the same query (Morpheme Type: Hands: Handedness) on the normal Search (using Sign or Morpheme) does not return any results.

**Comment by susanodd** [comment]
Here is the revised signs/search on morpheme type, sign or morpheme (#689):


![search-sign-or-morpheme-type-handedness](https://user-images.githubusercontent.com/24272544/110640462-22532180-81b1-11eb-928b-b6050e91dc18.png)

![search-sign-or-morpheme-type-results](https://user-images.githubusercontent.com/24272544/110640484-27b06c00-81b1-11eb-934f-4141ebeb86a0.png)

**Comment by susanodd** [comment]
This has been pushed to theoddbranch.

**Comment by Woseseltops** [comment]
Hey @susanodd are you introducing a new setting MORPHEME_DISPLAY_FIELDS here? If so, it should be added to `settings/server_specific/default.py` . Other than that nothing to complain ;)

**Comment by susanodd** [comment]
Check!

**Comment by susanodd** [comment]
The morpheme lookahead in the Search by Morphology was broken. I just fixed this.

**Comment by susanodd** [comment]
This has been pushed to branch `search_by_morphology`.

**Comment by susanodd** [comment]
This has been awaiting in a pull request for quite a while.

**Comment by susanodd** [comment]
This is live now.
