### ISSUE TITLE
Hide empty phonology fields in Morpheme Detail View

### ISSUE THREAD

**Issue by susanodd** [Signbank/Global-signbank#493]
Everything is visible now.
Related to Issue #492

**Comment by ocrasborn** [comment]
See #262 !

**Comment by susanodd** [comment]
Phonology fields that are empty are hidden on Global.
However Semantics fields that are empty are not hidden.

**Comment by susanodd** [comment]
A new issue has been created for hiding empty semantics fields. (#807).
