### ISSUE TITLE
Create menu Analysis

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#500]
* See #497 
* Please create a menu Analysis, to the right of Signs
* And move the analysis-functions that are now under Signs there: Homonym List, Minimal Pair List, Frequencies
* Hide the menu for people in group "Guest" and for anonymous users (not logged in)

**Comment by susanodd** [comment]
This is live now.
I made the Analysis menu and the pages underneath it visible to group Editor.
This works that when I wasn't logged in, I was not able to see the new menu.
This should also hold for Guests, assuming they're not in group Editor.

I looked to see what groups can see which pages. It's not very consistent.
The site also makes use of object permissions and these are tested in the code.
The four different test users are probably the best way to test who can see what.
Some of the groups have an empty set of pages for that group. But the the users get permissions via other group membership or as a user.
Maybe @ocrasborn you can browse the pages in the admin and select different groups to see what they can see, to see if things make sense?
I did the permission for the Analysis menu via the Editor group.
For the Dataset Manager group (for granting permissions), you need to be in the Dataset Manager group. (Or logged in as test user user-dataset).

**Comment by susanodd** [comment]
Oops, forgot to make the point. It's not clear what group should have permission for the Analysis, maybe group Researcher?
I wasn't able to set a "everybody except" permission. You have to grant permissions, not withhold permissions. It didn't seem wise to add a permission for all groups except Guest. Users can be in more than one group. I don't know if they get removed from Guest. If it's analogous to unix permissions then that would be like public or '-rw-r--r--' or something. But people who are superuser can also see public stuff.

**Comment by ocrasborn** [comment]
Yes, group 'Researcher' seems the way to go I'd say.

**Comment by susanodd** [comment]
Group Researcher now has permission for the analysis pages.
