### ISSUE TITLE
Efficiency of minimal pairs and homonyms

### ISSUE THREAD

**Issue by susanodd** [Signbank/Global-signbank#501]
A subset of phonology fields is to used when computing the minimal pairs.
This is hard-coded in the code and can be moved to settings. There are 14 fields compared:
`['handedness', 'domhndsh', 'subhndsh', 'handCh', 'relatArtic', 'locprim',
                      'relOriMov', 'relOriLoc', 'oriCh', 'contType', 'movSh', 'movDir', 'repeat', 'altern', ]`

_[Handedness, Strong Hand, Weak Hand, Handshape Change, Relation between Articulators, Location, Relative Orientation: Movement, Relative Orientation: Location, Orientation Change, Contact Type, Movement Shape, Movement Direction, Repeated Movement, Alternating Movement]_

Q: Is this list up to date? Can this be put in settings? (Along with the number of fields, 14.)

Because it is costly to compute dynamically, the set of glosses over which to compute is narrowed in the template query set. For example, if Handedness or Strong Hand is empty. At the moment, if Weak Hand is empty the glosses are also ignored. But there are one-handed signs that don't have a Weak Hand value. These are currently not displayed.

But......... when the empty Weak Hand signs are displayed, there are also many signs of the form # ..... showing up in the Minimal Pairs List. Indeed these signs seem to only have the fields Handedness and Strong Hand.

Q: Because of sparse data in some glosses too many results are found for minimal pairs. What is the best way to filter away which glosses to ignore?

**Comment by susanodd** [comment]
I revised the code to show 1 handed signs in the Minimal Pairs.
Filtering of the results to make sure that the considered signs have non-empty handedness and strong hand fields. If no other fields are set, the glosses are ignored. This to prevent some incomplete gloss specifications from being shown.

**Comment by susanodd** [comment]
@ocrasborn, can signs with # at the start be omitted from the Minimal Pairs List?

As it is, #A is a minimal pair with all the other letters of the alphabet, etc. etc.

**Comment by ocrasborn** [comment]
Yes, @susanodd , two-character signs starting with # can be omitted from the minimal pair list.

**Comment by susanodd** [comment]
Everything in the analysis menu is considerably faster now!
