### ISSUE TITLE
Settings for field names

### ISSUE THREAD

**Issue by susanodd** [Signbank/Global-signbank#503]
Q @ocrasborn : Are there any identifiable names that make sense for the settings with which these lists can be called? (See explanation and examples below.)

In the models.py file there are many iterations over field names. These are being moved to the settings file to make the code more maintainable.
From the settings, the existing phonology and semantics settings, and the new setting for minimal pairs:

`FIELDS['phonology'] = ['handedness','domhndsh','subhndsh','handCh', 'relatArtic','locprim','locVirtObj',
          'relOriMov','relOriLoc','oriCh','contType','movSh','movDir','repeat','altern','phonOth', 'mouthG',
          'mouthing', 'phonetVar', 'domhndsh_letter','domhndsh_number','subhndsh_letter','subhndsh_number','weakdrop','weakprop',]`

`FIELDS['semantics'] = ['iconImg','namEnt','semField','valence']`

`MINIMAL_PAIRS_FIELDS = ['handedness', 'domhndsh', 'subhndsh', 'handCh', 'relatArtic', 'locprim',
                      'relOriMov', 'relOriLoc', 'oriCh', 'contType', 'movSh', 'movDir', 'repeat', 'altern']`

Because different phonology fields are used in different ways based on the type of data used for the field and based on the actual phonology data itself, sometimes exceptions are used in the iterations. For example, to identify whether the field is represented as a list or a Boolean, or whether the field is used for computing minimal pairs, or whether the field is an extra property such as weak drop or letter or number.
It will make the code more readable to also include this information in the settings rather than using exceptions (if field not in [.....]).

Here are examples, what can these be called in the settings file?

- `        for field in FIELDS['phonology']:
            if field not in ['weakprop', 'weakdrop', 'domhndsh_number', 'domhndsh_letter', 'subhndsh_number',
                             'subhndsh_letter']:`

The above code identifies the attribute type data on handshapes.

`for field in ['handedness','domhndsh','subhndsh','handCh','relatArtic','locprim',     'relOriMov','relOriLoc','oriCh','contType','movSh','movDir']:`
``for field in ['repeat', 'altern']:``

The above code separates the Booleans from the other fields used for minimal pairs.

- `elif fieldname in ['locVirtObj', 'phonOth', 'mouthG', 'mouthing', 'phonetVar', 'iconImg', 'useInstr']:
`

The above fields are text fields rather than choice lists or Booleans.

**Comment by susanodd** [comment]
Not directly.
There are some places in the code that still make use of field name lists rather than using the settings.
These are gradually being worked away.
Issue #340 may offer alternatives for the field choice specifications.

**Comment by susanodd** [comment]
I recently looked at the (server specific) settings file again to get one of the tests done (#570).
The lists of field names for minimal pairs and homonyms computations are hard coded in a few places in the models. [Note to self.]

**Comment by susanodd** [comment]
@Woseseltops, I have one test for Minimal Pairs now. It's focused on the 'repeat' phonology field, since there had been a bug displaying that field (Issue #578).
There is a list of Minimal Pairs Fields in the settings.
Ideally, the test should cover all of these fields in some modular way.
(Question follows.)

Regarding Settings for field names, there are tests for field choices (to make sure they can't be deleted if they are in use). Those tests are done in a modular way, although the first, second, or third choice from a Choices list is used. (Representative, but not exhaustive.)

Q: Do we want a general test for Minimal Pairs?
Q: Is a test sufficient that looks at "field type"? E.g., if we check one field that is Boolean, do we assume that other fields that are Boolean are also okay?
This is related to the lists in the Settings file. Ideally the tests would be as generic as possible.
But they should also be as effective as possible rather than cumbersome, or excessive.
Q: How to tell the difference?

**Comment by susanodd** [comment]
Example. If you look at the setting for Minimal Pairs Fields, then a test should probably construct glosses that differ on at least one, possible more fields and confirm whether they show up as minimal pairs.

The bug mentioned in Issue #578 didn't show up until glosses existed that differed in only the repeat field. So it's possible some bugs can show up as more data gets filled in for the glosses.

How to construct a test that works to avoid such potential bugs?

**Comment by Woseseltops** [comment]
Hey @susanodd , let me try to summarize what you just asked:
1. There is a setting `MINIMAL_PAIRS_FIELDS` that lists all the fields that are compared to discover minimal pairs. 
2. In the unit test for minimal pairs, do we compare all fields in this list or just a few?

My answer is: why not all fields in the list, dynamically? So the test would, for each field in the gloss, create two glosses that differ on this field, and then see if the minimal pair functionality agrees that this is a minimal pair. If not, the test fails.

**Comment by susanodd** [comment]
There are two additonal settings for field names:
HANDSHAPE_ETYMOLOGY_FIELDS
HANDEDNESS_ARTICULATION_FIELDS
These are used in places in the code that were previously hard-coded.

**Comment by susanodd** [comment]
This is all live now, so it can be closed.
