### ISSUE TITLE
Signbank is slow

### ISSUE THREAD

**Issue by Woseseltops** [Signbank/Global-signbank#504]
Every page seems to loading slower than it used to, but I notice quite some differences between pages (for example detail view vs public view). I suspect we accidentally added something resource intensive without realizing it.

I think the debug toolbar that we installed but never used might be useful here.

@ocrasborn ... high priority okay?

**Comment by ocrasborn** [comment]
yes please!

**Comment by vanlummelhuizen** [comment]
I identified two pieces of code that take about 4 of 5 seconds:

The first is in the Gloss list view (search page). It evaluates the queryset and puts annotationidglosstranslations in a list that is used in the gloss detail view at the top:
https://github.com/Signbank/Global-signbank/blob/272a62abb8ba08ee946be272de974023029c6fce/signbank/dictionary/adminviews.py#L844-L864

The second is in the Gloss detail view and calculates frequency_lists_phonology_fields:
https://github.com/Signbank/Global-signbank/blob/272a62abb8ba08ee946be272de974023029c6fce/signbank/dictionary/adminviews.py#L1058-L1083

Next steps: 

* find a solution for each
* find more bottlenecks

**Comment by Woseseltops** [comment]
> The second is in the Gloss detail view and calculates frequency_lists_phonology_fields:

Oh so that's the choice list counts are recalculated each time we load a fresh page? That's (of course in retrospect) a likely cause, and I think something that can easily be cached in some form. I see two solutions:
* Update the numbers each time a gloss is edited (so if you set a choice from option a to option b, option a goes `-= 1` and option b goes `+= 1`). Con: if we make a small mistake somewhere this will go out of sync with reality quickly.
* We update the counts every night. Con: if the cron job fails, it will take long before we notice.

**Comment by vanlummelhuizen** [comment]
Another possibility is to do it after page load using ajax calls.

**Comment by vanlummelhuizen** [comment]
I have investigated whether it is possible to reduce the number of queries in the frequency_lists_phonology_fields code using annotate/subquery etc. This seems very hard or even impossible, so perhaps we could make a start on overhauling the FieldChoice setup (https://github.com/Signbank/Global-signbank/issues/340#issuecomment-369260007).

**Comment by susanodd** [comment]
My changes have finally been pushed to github.
There are big improvements to Homonyms and Minimal Pairs.

**Comment by Woseseltops** [comment]
Okay I spend some time trying to understand what already has been done to the detail view, and I think it's this:
* During page generation, some information about the field choices is preloaded and stored in memory, so we're not continuously making queries to the database.
* Both the finding of homonyms and minimal pairs has been sped up.
* We no longer wait with showing the page until all minimal pairs are found; instead, the page is already shown and the info about the minimal pairs is added later.

Still, it takes >3 seconds to load the detail view. As discovered by @vanlummelhuizen, if I take out the code that counts how often each list is used (to be added to the dropdowns), it only takes 1 second. Can we ajaxify this next? 

PS
The commits also seem to suggest that the homonym info is also added later, but this is not what I see happening on the site.

**Comment by susanodd** [comment]
The homonyms in Detail View isn't an ajax call. The Homonyms section is just the stored homonyms. The duplicate phonology homonyms could be an ajax call.

**Comment by susanodd** [comment]
Yes, the frequency can probably be an ajax call. The counts are for the machine value, not the translation, so the counts could be concatenated to the choices in javascript. But there are lots of fields and choices....
Or perhaps something analogous to the pre-computed field choice translations table. And figure out how often this needs to be regenerated.

**Comment by susanodd** [comment]
I'm working on CSV at the moment. You're welcome to take it up.

I'm looking at a Gloss Detail to see what the Debug stuff looks like now. (After all the revisions.)
It looks like "next gloss" navigation stuff uses a lot of database computation. These same calls are doing a join with Morphemes.
That's one thing I wasn't able to reduce. It seems like extra SQL stuff is added to ignore Morphemes.
(Also in Gloss Detail View, because of whatever was searched and has search results in the banner.)

**Comment by Woseseltops** [comment]
Okay, I created a new page that gives as a JSON all choice lists: https://signbank.science.ru.nl/dictionary/ajax/choice_lists/include_frequencies . Although I cleaned up the code that generates the choice lists (removed a few unneccessary loops etc), it still takes a few seconds to load. You can also request the version without the frequencies (just https://signbank.science.ru.nl/dictionary/ajax/choice_lists/ ), which is near instant.

Next step would be to take out this code when generating the detail view and adding it later with AJAX.

**Comment by Woseseltops** [comment]
The original choice list code is now replaced by code loading in the ajax page. The detail view is much much faster now! It takes quite a few seconds before the field choice info is also there, but this doesn't matter because clicking the edit button and navigating to the field also takes a while.

**Comment by Woseseltops** [comment]
Addition: and if you also think so, we can maybe also close #252 ?

**Comment by vanlummelhuizen** [comment]
A problem that arose at the VGT Signbank guys: when loading the choice_lists is rather slow, clicking on a red field to edit it, the user will only see the field disappearing. On the console there is a error. 

I think the solution is to include choice_lists without counts in the context/template and load choice_lists with counts using Ajax. What do you think, @Woseseltops ?

**Comment by Woseseltops** [comment]
Great idea @vanlummelhuizen

**Comment by ocrasborn** [comment]
Currently slow: loading of images in list view. See also #624 which I just closed, which seems related. @Woseseltops , are you still working on this?

**Comment by susanodd** [comment]
Can this be closed?

**Comment by vanlummelhuizen** [comment]
@susanodd I think so. If we encounter slow parts, we just open new, *more specific*, issues.
