### ISSUE TITLE
Add a way to identify finger spelling glosses

### ISSUE THREAD

**Issue by Woseseltops** [Signbank/Global-signbank#506]
@susanodd is working on minimal pairs, and discovered that it's probably better to exclude finger spelling from it (because every letter is a minimal pair with every other letter). Problem is: we don't have a general way to identify finger spelling glosses. One way could be to add an extra Boolean field 'finger spelling', or maybe we can use the fact that the glosses all seem to start with a hashtag (but is that also the case for the ASL Signbank or other datasets) ? Any ideas, preferences, @ocrasborn and @vanlummelhuizen ?

**Comment by ocrasborn** [comment]
Indeed @Woseseltops , hashtag is what unites them.

**Comment by Woseseltops** [comment]
> Indeed @Woseseltops , hashtag is what unites them.

Also in other datasets, and in the ASL Signbank?

**Comment by ocrasborn** [comment]
In other datasets: yes.
In ASL: no. There, they indicate in the field Derivation History whether there is a connection to fingerspelling, and (thus far) they haven't entered letters as lemmas like we have with #A #B etc.

**Comment by Woseseltops** [comment]
> They indicate in the field Derivation History whether there is a connection to fingerspelling, and (thus far) they haven't entered letters as lemmas like we have with #A #B etc.

I see. The problem we're trying to solve is finding an easy way for @susanodd to quickly exclude any fingerspelling glosses, and if I understand everything correctly using the hashtag would suffice: in ASL apparently they don't use Signbank is this way, so we don't have this problem.

**Comment by vanlummelhuizen** [comment]
Perhaps also use a setting to turn it on or off (off by default). If someone else installs Global Signbank, and they  use a hashtag for something other than finger spelling, this won't be a problem.

**Comment by Woseseltops** [comment]
@susanodd , I think your question is answered, right? If so, please close this issue :)

**Comment by susanodd** [comment]
Yes!
