### ISSUE TITLE
The words 'dataset bar' appear where the dataset bar used to be

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#507]
Please remove :-)

**Comment by susanodd** [comment]
This has been removed.

**Comment by Woseseltops** [comment]
Sorry, forgot to clean this up for over 2 weeks. It was there to verify that the dataset indicators were really gone, not just hiding behind some other element on the page.

![](https://media1.tenor.com/images/57e5b99257ddc933c97a007325daad15/tenor.gif)
