### ISSUE TITLE
Menu bar translation is broken

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#508]
I think both Datasets and Analysis still require translation in both Chinese and Dutch, but the others had long been translated, but don't appear anymore. Or have we changed them all to new strings in the meantime, and is it just a translation problem?

**Comment by susanodd** [comment]
These seem to be using a function get_current_language that is not defined anywhere.

**Comment by susanodd** [comment]
I found the problem. There is some Django template code inside of a javascript window-ready function.
So the code to set the language wasn't getting executed in the template.
This has been fixed.

**Comment by Woseseltops** [comment]
Happy @ocrasborn ?
