### ISSUE TITLE
Some newer unit tests fail when there is only one language (as with the ASL Signbank)

### ISSUE THREAD

**Issue by Woseseltops** [Signbank/Global-signbank#510]
They have been disabled for now. The problematic unit tests are:

* `test_import_csv_update_gloss_for_lemma` contains hardcoded references to the `en` language.
* The situation that is tested in the very last part of `test_Import_csv_new_gloss_for_lemma` does not apply when there is only one language. In that case, I guess this part should not executed?

**Comment by vanlummelhuizen** [comment]
@susanodd Is this something you can look at, since you are working on Import CSV quite a lot lately?

**Comment by susanodd** [comment]
@Woseseltops is this still broken? It could be that the solution to #537 fixed this?
The hard-coded uses of name_en make use of a setting instead.
