### ISSUE TITLE
Create a new field under semantics

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#516]
* Please add a text field "Concepticon Concept Set" under Semantics, and add it to the detail view and search form.
* In the detail view, add a help pop up with the text "Concepticon website", linking to http://www.concepticon.clid.org 
* (I made this 'blocking' as we're going to be using it shortly for a study with a deadline that is near)

**Comment by Woseseltops** [comment]
Done. I've named it 'concConcSet' :) .

Question for @ocrasborn : 
* I've added the tooltip, but it goes away once you try to click the link. Why not make the whole fieldname a link?

Questions for @vanlummelhuizen and @susanodd : 
* There's a new migration file. That's no problem for you guys, right?
* I've solved the special instructions for this field like this: 8adc75718d9dc4d83f6d5169a8a528ffcd46edb8 . That is, hardcoded in the template... can you think of a prettier solution?

**Comment by ocrasborn** [comment]
@Woseseltops : good idea, let's put the link on the fieldname (and have it open in a new tab).

**Comment by Woseseltops** [comment]
Done. Happy @ocrasborn ?

**Comment by vanlummelhuizen** [comment]
@Woseseltops No problem processing the migration.

About the special instructions, I am OK with your solution.

**Comment by ocrasborn** [comment]
Happy, @Woseseltops !
@susanodd , could you also add this to the CSV import/export routines?

**Comment by susanodd** [comment]
Yes. It got added automatically because it's in the FIELDS settings. Need to check if extra processing is needed on the values.

**Comment by Woseseltops** [comment]
Did you do this, @susanodd , and if yes: can this be closed?
