### ISSUE TITLE
Field choice translations, also in MESSAGES ?

### ISSUE THREAD

**Issue by susanodd** [Signbank/Global-signbank#517]
In the new efficient code for Homonyms and Minimal Pairs, the code makes use of Ajax calls to reduce the number of database queries during generation.
In the Minimal Pairs code, it now generates minimal pairs for each particular gloss and adds the rows to the table, using an Ajax call.
Because of this, the field choices need to be translated in the python code rather than inside the template.
The translations of field choices are stored in the FieldChoice database table.
The question is: are these also in the Messages file? Can they be put in the Messages file too?
Then the translation could be incorporated into the python code using Django's gettext() rather than needing a database lookup for every value.

**Comment by vanlummelhuizen** [comment]
I believe this is possible in one way or another, but I don't know how though. Be aware that the mechanism for making translations first finds all things in the code that need translation and than determines which translation are new and which translations are deleted. More about this on https://docs.djangoproject.com/en/2.1/topics/i18n/translation/#message-files.

Another (better?) possibility is to retrieve the translation at the point where you retrieve the other field choice data.

**Comment by susanodd** [comment]
Yes, I forgot I was already doing that in a big table. But it's not yet done in all the views.
