### ISSUE TITLE
Two cron jobs give errors

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#518]
* backup-ngt-signbank.sh: not sure what the issue is here
* corpusEcvUpdater.sh: refers to path as it was on old applejack?

**Comment by Woseseltops** [comment]
> backup-ngt-signbank.sh

Hmm I think we confused you here by turning on the old Applejack again for a few days. I also got a daily error in my mailbox, but this was about a missing `/vol/customopt/config/scripts/admin/cron/backup-ngt-signbank.sh` which is only missing on the old Applejack. I no longer got this error after the old Applejack was turned off again.

By the way, I also used this as an opportunity to check the backups and they look okay. :) 

> corpusEcvUpdater.sh: refers to path as it was on old applejack?

Possibly here too it was the old Applejack that confused you. In the logs for corpusEcvUpdater.sh for the new Applejack I see no old paths.

I do see other errors, though. They seem to be about some XML format not matching a predefined schema? Two example errors from `/scratch/signbank-logs/corpusEcvUpdater.java_2018-11-19_03-00-01.log` : 

```
Error:     cvc-complex-type.3.2.2: Attribute 'CVE_REF' is not allowed to appear in element 'ALIGNABLE_ANNOTATION'.
System id: file:///home/ocrasborn/corpusEcvUpdater/corpus-ngt/corpus-ngt/eaf/./CNGT1700-CNGT1799/CNGT1799.eaf
Public id: null
Line:      1075
Column:    111
```
```
Error:     cvc-complex-type.2.4.a: Invalid content was found starting with element 'DESCRIPTION'. One of '{CV_ENTRY}' is expected.
System id: file:///home/ocrasborn/corpusEcvUpdater/corpus-ngt/corpus-ngt/eaf/./CNGT0600-CNGT0699/CNGT0600.eaf
Public id: null
Line:      359
Column:    37
```

@vanlummelhuizen , as you wrote this script, could you have a look?

**Comment by vanlummelhuizen** [comment]
I changed corpusEcvUpdater.sh last monday and planned to test it the same day. I didn't so the change went on to be used last few nigths. Fortunately, it now does give errors. @ocrasborn do you know of a recent gloss change in Signbank that is reflected in one or more EAFs, so we can test whether it works correctly now?

**Comment by ocrasborn** [comment]
Nope, @vanlummelhuizen , we'll have to create a test item in an EAF. Can you do that?

**Comment by vanlummelhuizen** [comment]
I search the corpusEcvUpdate logs of this month for 'error' and found nothing. This seems all solved to me. Agreed, @ocrasborn ?

**Comment by ocrasborn** [comment]
I'm afraid not, @vanlummelhuizen . Here's the log mail I got this morning:
Updating '.':
svn: E170013: Unable to connect to a repository at URL 'svn+ssh://ocrasborn@applejack.science.ru.nl/scratch2/svnrepos/signlang/corpus-ngt/corpus-ngt'
svn: E210005: No repository found in 'svn+ssh://ocrasborn@applejack.science.ru.nl/scratch2/svnrepos/signlang/corpus-ngt/corpus-ngt'

**Comment by ocrasborn** [comment]
Has the path changed?

**Comment by vanlummelhuizen** [comment]
@ocrasborn I sent you an email with some instruction for you to solve this.

**Comment by vanlummelhuizen** [comment]
@ocrasborn when reviewing our email conversation of 21 feb I think this issue can be closed. Agreed?

**Comment by ocrasborn** [comment]
I still see error messages in the log of the backup script: 

rsync: chgrp "/vol/archive/backups/ngt-signbank/current/." failed: Operation not permitted (1)
rsync: chgrp "/vol/archive/backups/ngt-signbank/current/manual_backups" failed: Operation not permitted (1)

and:

rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1183) [sender=3.1.1]

Action needed?

Also, now we're at it anyway, let's rename the script to replace 'ngt' by 'global'.

**Comment by vanlummelhuizen** [comment]
First of all, the backups themselves look as they should. The only thing that is not completely right, is the owner/group of the files and directories.

I believe the problem is that on the original directories there is a [sticky bit](https://en.wikipedia.org/wiki/Sticky_bit) on the group. That makes it impossible for the user that runs the backup-cronjob (you, @ocrasborn) to change the group of the directories because those directories have a different owner (you, @Woseseltops). Perhaps removing the sticky bit is the solution. Or we should try to tell rsync not to `chgrp`.

As for the renaming of the script: I cannot become you on the system and that is needed to change the cronjob call. @Woseseltops is able to do that. @Woseseltops, can you do this?

**Comment by Woseseltops** [comment]
>  Perhaps removing the sticky bit is the solution. 

I tried removing the sticky bit, but cannot do it because I am not the owner of the folder above which also has a sticky bit :).

> As for the renaming of the script: I cannot become you on the system and that is needed to change the cronjob call

Done.

**Comment by Woseseltops** [comment]
Over a month later, but the sticky bit has been removed. Curious to know if the error goes away.
