### ISSUE TITLE
Unify video management systems

### ISSUE THREAD

**Issue by susanodd** [Signbank/Global-signbank#522]
There are two video management systems in Signbank: one on the file system, and one in the database.
When a new video is uploaded, Django creates a new record in the GlossVideo table as well as adds data to the GlossVideoHistory table. Unfortunately, these entries all have the same filename. Whereas on the filesystem, the old versions get version numbers.
There used to be functionality to revert back to a previous video if the video was deleted.
This doesn't work anymore because only one filename is known to the database.
The python/Django database code could be revised to reflect what is being done in the file system.

**Comment by vanlummelhuizen** [comment]
I will try to make things work in a more Django like way. In process I hope to fulfill @ocrasborn 's wished from #426 .

**Comment by susanodd** [comment]
@vanlummelhuizen, can you give an indication of per when your branch for this issue was created?

As part of testing videos, the tests are built in such a way. The video tests were crashing on my machine. Also, the small video, nor the still image file for the video were being deleted with the video, because the paths were computed incorrectly. (The test was only checking the normal video file.)

I split the get_image_path method of Gloss into two separate methods. The method was overloaded (by using an extra parameter in the header) and it specifically looked at the file system, whereas the analogous method for get_video_path merely creates a path.

I split the functionality of the get_image_path into two separate methods so that the existence check is true for one, and not used for the other (analogous to the get_video_path).

I just double-checked on your branch for this issue and noticed it doesn't match at all. I'm wondering when your branch branched off so I can see how this code evolved. It looks like it was primarily used in the template for related signs.

**Comment by susanodd** [comment]
The revised get image path functionality has been pushed to github master branch.

**Comment by vanlummelhuizen** [comment]
@susanodd It seems this interfere with the unify_video_management_systems branch quite a lot, unfortunately. At best your efforts will proof to be obsolete when merging unify_video_management_systems into master. 

I will first merge master into unify_video_management_systems and see what happens.

**Comment by susanodd** [comment]
The unit tests were broken.

**Comment by susanodd** [comment]
I've been going through code to (finish) removing hard-coded field choices (#503).

As part of this, I'm checking hard-coded things for which there are settings.
/glossvideo/ was hard-coded into the model functions. That was changed to the setting.

The image method was checking the file system using an os.path.exists call, which was supposed to be returning false (None) or a path. But file system lookup was crashing instead if there wasn't anything and Django wasn't finishing the code.
So I split the functionality into separate calls, so there is a Boolean function and a path function.
The path function computes the path where the thing is supposed to be, or is to be put. (As is done in the video path methods.)

**Comment by vanlummelhuizen** [comment]
This is running on the live server for a week now. I have had no complaints so I believe it is working quite well. 

@ocrasborn It also means that videos and images are now save on the server under a directory named by the dataset acronym. Also, it is possible to revert to an older video (discarding the current video completely).

@Woseseltops When applying https://github.com/Signbank/Global-signbank/commit/e68f1f594700501d712cebf248c1e6c471a508ad to the ASL Signbank, run this command

```
python bin/develop.py makeglossvideos
```

It solves *most* problems arisen from the non unified video systems.

**Comment by Woseseltops** [comment]
Live at both servers and no major problems.
