### ISSUE TITLE
Change layout of page Select Datasets

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#525]
It's now a bit too hard to quickly select and deselect, as the checkboxes are so far away from the dataset names (even with the lines). Suggested solution: change order of the columns, making sure the checkbox column is only as wide as the word Selected in the header.

**Comment by Woseseltops** [comment]
Good solution, done. Happy @ocrasborn ?

**Comment by ocrasborn** [comment]
Thanks for the quick action @Woseseltops . Happy. But then to top it off in terms of usability (not so much aesthetics), let's align the confirm button to the left instead of the right.

**Comment by Woseseltops** [comment]
Done.
