### ISSUE TITLE
CSV export broken for ASL Signbank

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#532]

**Comment by Woseseltops** [comment]
Might be related to #535 , which is about the fact that the unit test about importing CSVs fails. Interestingly, this unit test has an extra error message for the ASL Signbank:

```
======================================================================
ERROR: test_Import_csv_update_gloss_for_lemma (signbank.dictionary.tests.ImportExportTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/www/signbank/repo/signbank/dictionary/tests.py", line 386, in test_Import_csv_update_gloss_for_lemma
    form_name = '{}.Lemma ID Gloss ({})'.format(gloss.id, language.name_en)
AttributeError: 'Language' object has no attribute 'name_en'

======================================================================
FAIL: test_Import_csv_new_gloss_for_lemma (signbank.dictionary.tests.ImportExportTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/www/signbank/repo/signbank/dictionary/tests.py", line 502, in test_Import_csv_new_gloss_for_lemma
    "up a completely new Lemma ID gloss.".format(dataset_name))
  File "/var/www/signbank/lib/python3.4/site-packages/django/test/testcases.py", line 393, in assertContains
    self.assertTrue(real_count != 0, msg_prefix + "Couldn't find %s in response" % text_repr)
AssertionError: False is not true : Couldn't find 'To create glosses in dataset ASL, the combination of Lemma ID Gloss translations should either refer to an existing Lemma ID Gloss or make up a completely new Lemma ID gloss.' in response
```

**Comment by Woseseltops** [comment]
To do list for this issue:
* Fix the CSV export for ASL Sigbank
* Fix all unit tests related to the CSV for the ASL Signbank
  * Possibly, it might be needed to do #535 first.

**Comment by ocrasborn** [comment]
From Julie's mail: "For now, there is a bit of an urgency for this one request. We do need a fix of the CSV link that you can click on when you see "all signs". I get this error when I try clicking on the CSV link."

<img width="1332" alt="screen shot 2019-01-28 at 4 16 22 pm" src="https://user-images.githubusercontent.com/10242207/52051796-df93d980-2554-11e9-9d1b-37f4947dff93.png">

**Comment by Woseseltops** [comment]
For completeness, the ASL Signbank has been upgraded since Julie's message. We no longer get an error; instead, we only get 2-3 signs instead of everything.

**Comment by Woseseltops** [comment]
> there is a bit of an urgency for this one request

Just realized I completed missed the urgency :( .

Anyway, I just did a deep dive into this problem, and discovered that:
* We're back to the error again.
* If you search via the topbar, this information is lost when you create the CSV.
* As a result, ALL glosses are included in the CSV
* Putting all glosses in a CSV takes too long; the internal server error is probably a time-out.
* You can avoid the error by searching via the search page

Suggested remedy:
* Sending info about this workaround to Julie (agreed @ocrasborn ?)
* Micha recently added functionality to automatically fill the search page in #548 . @vanlummelhuizen can I 
* Check if I can find any timeout settings.

**Comment by Woseseltops** [comment]
Found the setting (simply called Timeout in the Apache config). Made it longer, now it works.

**Comment by susanodd** [comment]
Related to the timeout, do we need to be doing calls to google-analytics.com ?

**Comment by vanlummelhuizen** [comment]
@Woseseltops I don't see any obstacles for merging the auto fill functionality with the ASL branch. Note that it is not a complete solution because searching with auto filled form fields could give different results that searching with the top bar search field (AND vs OR). I am working on a better solution, but I am not there yet.

**Comment by vanlummelhuizen** [comment]
@Woseseltops I made a new solution for #548: https://github.com/Signbank/Global-signbank/commit/d639e7023caa59560a4c6a9ef349f254e6cf64de. Please review and if ok, use it for ASL Signbank.

**Comment by vanlummelhuizen** [comment]
@Woseseltops any news on this front?

**Comment by Woseseltops** [comment]
Hey @vanlummelhuizen , I finally investigated this. It does not work yet for ASL, because this code

```javascript
         // Empty menu_bar_search_mirror
         $("#adminsearch :input").change(function() {
            $("#menu_bar_search_mirror").val("");
         });
```

keeps getting called. I'm not sure why this is (in the Global Signbank it's only called when change your search query, but my best guess is that is something related to the fact that the code on the ASL Signbank is a bit older. Perhaps just a general upgrade would fix it?

**Comment by ocrasborn** [comment]
@woseseltops, are you sure it isn't yet working for ASL? I managed to export something just 2-3 weeks ago

**Comment by vanlummelhuizen** [comment]
@Woseseltops I think a general upgrade would fix this: the element with class 'menu_bar_search_mirror' is not in the html so the piece of code you posted is not working properly. Although I think it also shouldn't give any problems.

**Comment by ocrasborn** [comment]
@Woseseltops , just checked again after your ASL update of this morning, still works for me.

**Comment by Woseseltops** [comment]
It works!
