### ISSUE TITLE
Unit test Import_csv_update_gloss_for_lemma fails

### ISSUE THREAD

**Issue by Woseseltops** [Signbank/Global-signbank#535]
You probably know most about this @susanodd

**Comment by Woseseltops** [comment]
Might be related to #532

**Comment by Woseseltops** [comment]
Error message is

```
======================================================================
FAIL: test_Import_csv_update_gloss_for_lemma (signbank.dictionary.tests.ImportExportTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/www/signbank/live/repo/signbank/dictionary/tests.py", line 416, in test_Import_csv_update_gloss_for_lemma
    self.assertContains(response, "The following lemma idgloss translations refer to several lemma idglosses "
  File "/var/www/signbank/live/sb-env/lib/python3.5/site-packages/django/test/testcases.py", line 393, in assertContains
    self.assertTrue(real_count != 0, msg_prefix + "Couldn't find %s in response" % text_repr)
AssertionError: False is not true : Couldn't find 'The following lemma idgloss translations refer to several lemma idglosses instead of 0 or 1: ' in response

----------------------------------------------------------------------
```

**Comment by susanodd** [comment]
Yes, I didn't revise the tests yet!

**Comment by susanodd** [comment]
It looks like Annotation ID Gloss is not being set for the Gloss that's created for this test.

**Comment by susanodd** [comment]
This is not the only test that fails.
The test for `testSearchForGlosses` also fails.
The test `test_DatasetListView_ECV_export_permission_change_dataset` also fails.
The test `VideoTests` also fails.
I've commented out these other test that are broken so I can work on the test of this issue.

**Comment by susanodd** [comment]
@Woseseltops : Can you specify a commit in the history for when the tests were all working last?

**Comment by Woseseltops** [comment]
> Can you specify a commit in the history for when the tests were all working last?

Unfortunately, no. The test must have worked in November when we last used them for the ASL upgrade.

**Comment by susanodd** [comment]
This has been fixed. Additional human feedback was added to the refractored CSV import so that the tests have something to test for.

**Comment by susanodd** [comment]
@Woseseltops can you check if this works for you now?
All of the tests work on my local machine, with the most recent database and the most recent code.
No errors.

One warning is generated:
`WARNINGS:
dictionary.Dataset.exclude_choices: (fields.W340) null has no effect on ManyToManyField.`

(It was generating that warning yesterday when I tried to do migrations. Today I have a copy of the real database so the migrations aren't needed.)

**Comment by Woseseltops** [comment]
I just tried testing this, but the unit tests are giving me all kinds of unrelated errors. Will come back to this (even) later.

**Comment by susanodd** [comment]
I fixed that in one of the migrations.
There should not be a null setting.

**Comment by susanodd** [comment]
Remember to comment out the FieldChoiceTests for making sure field choices that are in use can't be deleted. Those rely on Issue #381 and the migration for choice lists that were missing in _meta.

**Comment by susanodd** [comment]
The implementation of preventing field choice deletion when in use has been totally rewritten (#381).
The tests related to this have also been rewritten.
All tests run successfully for Global on the most recent github version.

**Comment by Woseseltops** [comment]
> I just tried testing this, but the unit tests are giving me all kinds of unrelated errors. Will come back to this (even) later.

Okay I figured this out: the test database I was still using on the live server was way too old. Now it just crashes on the FieldChoiceTests like you mention @susanodd . Since that's another issue, this one can be closed as far as I'm concerned.
