### ISSUE TITLE
Hardcoded reference to English language in tools.py

### ISSUE THREAD

**Issue by Woseseltops** [Signbank/Global-signbank#537]
It's about this piece of code, which occurs outside of a function in `tools.py`

```
table_column_name_lemma_id_gloss_translations = {}
for language in Language.objects.all():
    lemmaidgloss_comumn_name = "Lemma ID Gloss (%s)" % language.name_en
    table_column_name_lemma_id_gloss_translations[language.language_code_2char] = lemmaidgloss_comumn_name
```

It was added by @susanodd in 99a76532d . 

Current solution: put the problematic line inside a try
Best solution: make the used language dynamic

**Comment by susanodd** [comment]
This is also confusing to me.
I "replaced" the big import functions with two separate functions to separate the functionality of update and create.
I that that export / import always use the English names for things.
But now I see somebody added this to adminviews.py:
`lang_attr_name = 'name_' + DEFAULT_KEYWORDS_LANGUAGE['language_code_2char']`
It looks like a new settings didn't get added everywhere.

**Comment by susanodd** [comment]
In this function of adminview.py
`render_to_csv_response` of GlossListView
there is a (in English) hardcoded list of fields:
`for extra_column in ['SignLanguages','Dialects','Keywords','Sequential Morphology', 'Simultaneous Morphology', 'Blend Morphology',
                             'Relations to other signs','Relations to foreign signs', 'Tags', 'Notes']:`

This code has always been this way.
But are we now using language translations for CSV headers?

**Comment by susanodd** [comment]
I see something in the database that is maybe related to the wish to code orthogonally.
In the dictionary_languages table, there are fields for: name, name_en, name_nl, name_zh_hans, language_code_2char
But if you work backwards from the language_code_2char, there aren't columns for every combination "name_" plus language_code_2char.

The code above that's causing the problem can probably be changed to just "name" instead of "name_en". And just assume that field is the default?

**Comment by vanlummelhuizen** [comment]
@susanodd A short explanation of the name, name_en, name_nl, name_zh_hans vs language_code_2char stuff:

The database columns name_en, name_nl, name_zh_hans were generated by the Django module [modeltranslation](https://django-modeltranslation.readthedocs.io/en/latest/). It used LANGUAGES from the settings. These languages are the interface languages. So users can view the interface in English, Dutch and Chinese.

The languages in the dictionary_language table are the language for which there might be some data. A subset of these languages are linked to a Dataset and are used to determine for what languages a annotation/lemma idgloss translation should be made.

I hope this helps.

(Perhaps we should make a wiki page about all the different kinds of languages and translation.)

**Comment by susanodd** [comment]
This issue is related to CSV import. The places where field "name_en" is hardcoded are all in code related to CSV import.

**Comment by susanodd** [comment]
All of the hardcoded references to name_en have been revised to make use of to setting.

**Comment by susanodd** [comment]
@Woseseltops can you see if you are happy with the solution? It makes use of settings now, so it's not hard coded.

**Comment by Woseseltops** [comment]
I didn't check in detail, but I see `_en` references removed and Signbank still works, so looks like our goal has been reached.
