### ISSUE TITLE
Javascript fails on ASL list view

### ISSUE THREAD

**Issue by Woseseltops** [Signbank/Global-signbank#538]
This piece of code

```

function makeMultipleSelect(fieldId,fieldVar) {
  var target_pulldown = document.getElementById(fieldId);
   
 target_pulldown.setAttribute('multiple','multiple');
 target_pulldown.setAttribute('class',"js-example-basic-multiple form-control");
 target_pulldown.setAttribute('name',fieldVar);
 target_pulldown.style.width = '100%';
 }
```

fails because target_pulldown is null. Not sure for how long this has been the case; I only noticed it because some newly introduced Javascript didn't work.

**Comment by Woseseltops** [comment]
What I figured out so far: 
* This function is called multiple times, iterating over the Javascript variable `multiple_select_fields`.
* The problem is that for the ASL Signbank, this variable is filled with `['handedness', 'domhndsh', 'subhndsh', 'locprim', 'relatArtic', 'relOriMov', 'relOriLoc', 'oriCh', 'handCh', 'movSh', 'movDir', 'contType', 'namEnt', 'semField', 'wordClass']`, containing various fields that the ASL Signbank does not have. This leads to null ref exceptions.
* This Javascript variable is filled with a list of strings taken directly from the settings variable `MULTIPLE_SELECT_GLOSS_FIELDS` .

Strangely, for the ASL Signbank this settings variable is not set. So it's not only weird that this settings variable is set with the global fields, it is weird that there is content at all.

**Comment by Woseseltops** [comment]
Hint to self: check the ASL branch.

**Comment by susanodd** [comment]
I've revised the references to the settings MULTIPLE_SELECT_GLOSS_FIELDS and MULTIPLE_SELECT_MORPHEME_FIELDS to be computed from the Gloss._meta and Morpheme._meta field information for those fields with choices that are in the settings for FIELDS['phonology'] etc.
This should solve the problem for ASL.

**Comment by susanodd** [comment]
It's not quite as generic as you'd expect. Using the above generated settings, the morphology search fields on Gloss List View do not end up Multiple Select because they are relations, not fields in the Gloss or Morpheme model.

**Comment by susanodd** [comment]
This has been pushed to github.

**Comment by Woseseltops** [comment]
Wow, beautiful solution @susanodd ! So now the setting is not needed anymore at all, we just infer the multiple select fields automatically?

**Comment by susanodd** [comment]
Yes
