### ISSUE TITLE
Dataset menu: 2 items not showing

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#546]
User lori alerted me, same for user-editor I tested: the menu items Dataset > Select and Dataset > Manager are no longer showing. For me (superuser) they are. We get access to them by typing in the url, and in Django the two pages are 'published'. What might be going on?

**Comment by vanlummelhuizen** [comment]
@ocrasborn When editing a page near the end of the form there is a section called Advanced options and in there you will find Group required. Does changing the selection in that list make the menu items show up? If not, can you tell which pages this is about?

**Comment by susanodd** [comment]
Permissions for the pages are controlled before Django will show them in the menu.

**Comment by susanodd** [comment]
Try it now? It's difficult to do a multiselect in the Group permissions of the page.
(On Firefox it is the control key, not the shift key.)
I just changed it to be permissions for groups Researcher, Editor, Dataset_Manager, and Publisher.

**Comment by susanodd** [comment]
That's in the admin btw. It doesn't work to sequentially select permissions and keep saving. They all have to be selected at the same time before saving. Hence the multiselect. You can see if the control key works to choose groups that are not adjacent in the list. The pages should be visible now.

**Comment by susanodd** [comment]
This has been fixed.

**Comment by vanlummelhuizen** [comment]
@ocrasborn close this issue?
