### ISSUE TITLE
Impossible to edit page content in Admin

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#547]
Had forgotten about this earlier, but now having created a new page I run into the same problem: I can no longer edit page content in the Django Admin.

**Comment by vanlummelhuizen** [comment]
@ocrasborn I fixed it by copying the static folder of django_summernote in the virtualenv to the static folder of Signbank, which is called 'media'. @Woseseltops can you think of a better and more sustainable solution? A symbolic link gave permission denied.

**Comment by ocrasborn** [comment]
Thanks @vanlummelhuizen, works for me

**Comment by Woseseltops** [comment]
> @Woseseltops can you think of a better and more sustainable solution?

Nope, that's how I've been doing it in the past as well. Weird that the folder was moved. I believe the official recommended way of doing this also works this way (but automatically instead of having to manually copy folders).

**Comment by Woseseltops** [comment]
Onno seems happy this can be closed.
