### ISSUE TITLE
Let the search query from the menu bar be reflected in the search query form in the results page

### ISSUE THREAD

**Issue by vanlummelhuizen** [Signbank/Global-signbank#548]
When you search using the fields in the menu bar, the search form in the resulting page does not reflect the search query used. The consequence is that when the results are sorted, the original search query is not used and all glosses are shown. See also #544.

**Comment by vanlummelhuizen** [comment]
@ocrasborn This is done. Please confirm.

**Comment by ocrasborn** [comment]
Confirm! However, the issue from which this originated, #544 , raises its ugly head: when I now click sort, search results turn to zero. For a different reason, I think: it looks like the query is interpreted as X AND Y AND Z, instead of X OR WHY OR Z. Am I right? Should we want to change this? I'm not sure.

**Comment by vanlummelhuizen** [comment]
@ocrasborn One way to solve this is to use a hidden search field that is the same as the search field in the menu bar. That way the sorting uses the same search constraints. Downside: when the user fill in the search form, the hidden search field should be emptied. Perhaps this could be done when the search form is submitted.

**Comment by susanodd** [comment]
Can you provide an example of X and Y and Z that is causing this problem.

Based on #544, I tried English mother and Dutch oma and it finds four glosses for the selected datasets.

**Comment by ocrasborn** [comment]
Hm. It no longer occurs now, and I can see why: unlike when I tested, the query 'moeder' is now only copied to the Dutch gloss field. Before, it was copied to the gloss field for all languages. Then sorting resulted in zero hits, as 'moeder' was not found in the English gloss field. (In fact, I tried with NGT + LSFB selected, and then 'moeder' was in three gloss fields, not resulting in any hits for either French or English.)

**Comment by vanlummelhuizen** [comment]
OK, I made a better solution: a hidden input field in the search form that shadows the search input field in the menu bar. It is emptied when you change another field in the form, so that it does not interfere. There is not really anything to see unless you know how to test it, but nevertheless: happy @ocrasborn ?

**Comment by ocrasborn** [comment]
yes, @vanlummelhuizen
