### ISSUE TITLE
Copy ASL videos to Ponyland

### ISSUE THREAD

**Issue by Woseseltops** [Signbank/Global-signbank#549]
Currently on hold until access to the American server is restored. Request by @ocrasborn

**Comment by Woseseltops** [comment]
Okay the videos are copied to `/var/www/signbank/live/writable/asl-videos/glossvideo` , a total of 3.2G . Strangely, I also found a directory called `glossvideo_save`, of 14G, created in january 2018, so I am copying that as well. I can't remember what this directory is, or why it is so much larger than the current video directory.

What's the next step, @ocrasborn ? I can't just merge them with our own video directory, because the PKs in the filename of course don't match.

**Comment by ocrasborn** [comment]
Thanks @Woseseltops

**Comment by ocrasborn** [comment]
Ah, small issue: some files are not readable to me because of permissions. Not all, but still a few hundred it seems. E.g. /CO/COLORADO-3181.mp4. could you fix that for me, @Woseseltops ?

**Comment by Woseseltops** [comment]
Done!

**Comment by ocrasborn** [comment]
thanks @Woseseltops !
