### ISSUE TITLE
Display of handshape images has changed

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#551]
See https://signbank.science.ru.nl/signs/search_handshape/: the images have different aspect ratios (intentionally), and are now cropped and/or resized so that most images are not fully visible.

**Comment by susanodd** [comment]
Can you make a screenshot? They look okay on the live server on my computer. At least they are different sizes and shapes.

**Comment by ocrasborn** [comment]
<img width="147" alt="screenshot 2019-02-19 18 15 15" src="https://user-images.githubusercontent.com/10242207/53033869-59432700-3472-11e9-94d7-6ed503ead816.png">
<img width="159" alt="screenshot 2019-02-19 18 15 08" src="https://user-images.githubusercontent.com/10242207/53033871-59432700-3472-11e9-818a-8d795e4c518e.png">
<img width="152" alt="screenshot 2019-02-19 18 14 58" src="https://user-images.githubusercontent.com/10242207/53033872-59432700-3472-11e9-8e0d-d0cb940f1e05.png">

**Comment by susanodd** [comment]
This has been fixed. Pushed to github.

**Comment by susanodd** [comment]
Are you happy with this @ocrasborn ?

**Comment by susanodd** [comment]
(Remember to reload the page.)

**Comment by ocrasborn** [comment]
Yes, thanks @susanodd
