### ISSUE TITLE
CSV import-create broken again

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#553]
AttributeError at /signs/import_csv_create/
'Settings' object has no attribute 'DEFAULT_DATASET_ACRONYM'

**Comment by vanlummelhuizen** [comment]
I cannot reproduce this problem. Does it still exist?

**Comment by ocrasborn** [comment]
Ah! No! It doesn't! A temporary hiccup yesterday, apparently. Same file works fine now.
