### ISSUE TITLE
Google Analytics causes massive delays in displaying view

### ISSUE THREAD

**Issue by susanodd** [Signbank/Global-signbank#557]
Importing @ocrasborn's mega CSV file for VGT (ca. 17,000 glosses to create).
The CSV import shows feedback to the user in the form of a giant table of glosses to create.
This is causing massive delays because of all the "gegevens overbrengen van www.google-analytics.com".
Can we remove these calls to google? They are bogging down the website.

**Comment by susanodd** [comment]
From the google analytics instructions:

> Move the code to the very bottom of the page, if you haven't already

The table is being generated and it's extremely long.

**Comment by Woseseltops** [comment]
Just an idea: if >500 signs are imported, maybe we can create a log file you can download instead of generating a table on the fly?

**Comment by susanodd** [comment]
Hmm. The table that is generated has id's in the elements that are used by the python code to actually create the glosses. (e.g, lemma_id_gloss_en ...)

**Comment by susanodd** [comment]
I'll see if it improves if the import code stores the rows in a table, instead of processing all the data as read. Maybe it can be processed column-wise to check all the data is okay.
One reason for doing all the signs at once is so that we don't have to keep checking whether the lemma translations, annotation translations, already exist in the dataset. As soon as some glosses have been created, it has to check every row with the existing stored glosses (to avoid runtime errors).

**Comment by susanodd** [comment]
Not sure if this is relevant anymore.
