### ISSUE TITLE
Cannot include pictures on page

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#559]
Created a new page About/Acknowledgments. When I try to include a picture, I get an error message (png or jpg both fail):

Got an error uploading an image: AttributeError at /summernote/upload_attachment/
This QueryDict instance is immutable
Request Method: POST
Request URL: https://signbank.cls.ru.nl/summernote/upload_attachment/
Django Version: 1.11
Python Executable: /usr/bin/uwsgi
Python Version: 3.5.2

**Comment by susanodd** [comment]
I'm not exactly sure how to use summernote.
I found some legacy code for uploading attachments and I modified that so it works now.
There is a directory "attachments" in the writable folder. That's where it puts them.
 But the links shown in the upload attachments page seem to be intended for use as references.
The plot thickens.

**Comment by Woseseltops** [comment]
A quick Google search showed we simply needed to upgrade Summernote: https://github.com/summernote/django-summernote/issues/187

Did that, gave some problems, fixed those, now it works. Happy @ocrasborn ?

**Comment by ocrasborn** [comment]
Happy! Could I ask for a small favour (doesn't belong in this issue, too small to make a new one): the three logos I've added to /about/acknowledgments/, could you all bottom-align them and distribute them equally over the width of the frame? My css is a bit rusty... :-)

**Comment by Woseseltops** [comment]
You sure you want that, @ocrasborn ? Because that would mean the logos would end up at completely different places depending on the height and width of the monitor. As an alternative solution, I now made it so the logos are now (sort of) evenly spaced... how do you like that?

**Comment by Woseseltops** [comment]
I now also edited the whitespace around the logos to be similar.

**Comment by ocrasborn** [comment]
Indeed! I noticed, thanks @Woseseltops
