### ISSUE TITLE
ProgrammingError: column dictionary_signlanguage.id does not exist

### ISSUE THREAD

**Issue by FabricioRojas** [Signbank/Global-signbank#562]
We are trying to install GlobalSignbank for Spain, we took the [Finnish SignBank guide](https://github.com/Signbank/FinSL-signbank) as exemple for this installation. 

We followed all the steps without problem until we found this error after executing the second command on the [Databse migration](https://finsl-signbank.readthedocs.io/en/latest/installation.html#database-migration) step  **python bin/develop.py makemigrations**:

![image](https://user-images.githubusercontent.com/6605072/54424835-bd70a800-470b-11e9-85ce-dd9e2d9afa47.png)

`/var/www/Global-signbank/venv/lib/python3.5/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
Traceback (most recent call last):
  File "/var/www/Global-signbank/venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: column dictionary_signlanguage.id does not exist
LINE 1: SELECT "dictionary_signlanguage"."id", "dictionary_signlangu...`

We also tried with SQLite DB but we got the same error. Before getting this error we got another one because it couldn't find the 'dictionary_signlanguage' table that is why we create that table and now it is showing this error.

### This is our set up config:
- Ubuntu 16.04.5 LTS
- PostgreSQL 9.5.14
- Django 1.11
- Python 3.5.2
- SQlite 3.11.0

**Comment by vanlummelhuizen** [comment]
Apparently, this is not easily fixable. We will look into this (#564). 

We are also looking into a work around by providing an SQLite database that has all tables but no data. I hope to come back on this soon.

**Comment by vanlummelhuizen** [comment]
Because this is not a easy thing to fix, I made a **_workaround_** so that you can at least use SQLite:

Download and unpack [schema.sql.gz](https://github.com/Signbank/Global-signbank/files/2987805/schema.sql.gz).

Assuming you are on Linux, changing paths for you situation, do the following:
1. Apply the SQL schema. Run `sqlite3 writable/database/signbank.db < schema.sql`
2. Make Django think all migrations were applied. Run `python bin/develop.py migrate --fake`
3. Create a super user. Run `python bin/develop.py createsuperuser`
4. Add two Sites (https://docs.djangoproject.com/en/1.11/ref/contrib/sites/). Run `python bin/develop.py shell` and enter
    `from django.contrib.sites.models import Site`
    `Site.objects.create(name='example.com', domain='example.com')`
    `Site.objects.create(name='Signbank', domain='your-domain.com')`
5. Apply the following git diff:

```
diff --git a/signbank/tools.py b/signbank/tools.py
index 56d067d..f14f59c 100755
--- a/signbank/tools.py
+++ b/signbank/tools.py
@@ -1412,7 +1412,10 @@ def get_selected_datasets_for_user(user):
         if public_datasets:
             selected_datasets = public_datasets
         else:
-            selected_datasets = [ Dataset.objects.get(acronym=settings.DEFAULT_DATASET_ACRONYM) ]
+            try:
+                selected_datasets = [ Dataset.objects.get(acronym=settings.DEFAULT_DATASET_ACRONYM) ]
+            except:
+                selected_datasets = []
         return selected_datasets
```

**Comment by FabricioRojas** [comment]
Thanks for the fast replying.

We started over with a fresh installation and following these steps. At least we could finish the installation, but we found with another error when we tried to start the service.

After executing the command `python bin/develop.py runserver localhost:8000` and opening the url we get this on the browser.


![OnPaste 20190325-170108](https://user-images.githubusercontent.com/6605072/54939130-b1f95a00-4f1f-11e9-9daf-205c6ddacdd0.png)

**Comment by vanlummelhuizen** [comment]
I think there are some migrations you need to apply:

1. activate the virtual environment for your Signbank instance
2. run `python bin/develop.py migrate` 

Otherwise use this schema:
[signbank_schema_2019-03-27.sql.gz](https://github.com/Signbank/Global-signbank/files/3012152/signbank_schema_2019-03-27.sql.gz)

**Comment by FabricioRojas** [comment]
After executing this command `python bin/develop.py migrate` we got this message

```
System check identified some issues:

WARNINGS:
dictionary.Dataset.exclude_choices: (fields.W340) null has no effect on ManyToManyField.
Operations to perform:
  Apply all migrations: admin, attachments, auth, contenttypes, dictionary, django_summernote, feedback, guardian, pages, reversion, sessions, sites, tagging, video
Running migrations:
  No migrations to apply.
  Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
```

So we executed this one `python bin/develop.py makemigrations` and then we tried again with the previous one.  Unfortunately we got the [same error](https://github.com/Signbank/Global-signbank/issues/562#issuecomment-476292796) when trying to start the service.

We tried with the other schema, when executing we got this error: `Error: near line 78: object name reserved for internal use: sqlite_sequence` in the line 78 there was this sentence `CREATE TABLE sqlite_sequence(name,seq);` we simply remove it from the sql file and re-import the DB.

After that we made some changes more and finally we could start the service.

![image](https://user-images.githubusercontent.com/6605072/55071870-a1f98b80-5081-11e9-8bc1-35b21fcbe268.png)


The problem now is when trying to navigate to any page on the site, for example this is trying to access admin/login:

![OnPaste 20190327-111802](https://user-images.githubusercontent.com/6605072/55072049-01579b80-5082-11e9-93eb-4f9dad7a4780.png)


This is the full traceback from the error:

```
Environment:


Request Method: GET
Request URL: http://51.83.45.165:8000/admin/login/?next=/admin/

Django Version: 1.11
Python Version: 3.5.2
Installed Applications:
('modeltranslation',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.admin',
 'django.contrib.admindocs',
 'django.contrib.staticfiles',
 'bootstrap3',
 'django_summernote',
 'signbank.dictionary',
 'signbank.feedback',
 'signbank.pages',
 'signbank.attachments',
 'signbank.video',
 'reversion',
 'tagging',
 'guardian')
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'signbank.pages.middleware.PageFallbackMiddleware',
 'reversion.middleware.RevisionMiddleware')



Traceback:

File "/var/www/Global-signbank/venv/lib/python3.5/site-packages/django/core/handlers/exception.py" in inner
  41.             response = get_response(request)

File "/var/www/Global-signbank/venv/lib/python3.5/site-packages/django/core/handlers/base.py" in _legacy_get_response
  249.             response = self._get_response(request)

File "/var/www/Global-signbank/venv/lib/python3.5/site-packages/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "/var/www/Global-signbank/venv/lib/python3.5/site-packages/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/var/www/Global-signbank/venv/lib/python3.5/site-packages/django/views/decorators/cache.py" in _wrapped_view_func
  57.         response = view_func(request, *args, **kwargs)

File "/var/www/Global-signbank/venv/lib/python3.5/site-packages/django/contrib/admin/sites.py" in login
  393.         return LoginView.as_view(**defaults)(request)

File "/var/www/Global-signbank/venv/lib/python3.5/site-packages/django/views/generic/base.py" in view
  68.             return self.dispatch(request, *args, **kwargs)

File "/var/www/Global-signbank/venv/lib/python3.5/site-packages/django/utils/decorators.py" in _wrapper
  67.             return bound_func(*args, **kwargs)

File "/var/www/Global-signbank/venv/lib/python3.5/site-packages/django/views/decorators/debug.py" in sensitive_post_parameters_wrapper
  76.             return view(request, *args, **kwargs)

File "/var/www/Global-signbank/venv/lib/python3.5/site-packages/django/utils/decorators.py" in bound_func
  63.                 return func.__get__(self, type(self))(*args2, **kwargs2)

File "/var/www/Global-signbank/venv/lib/python3.5/site-packages/django/utils/decorators.py" in _wrapper
  67.             return bound_func(*args, **kwargs)

File "/var/www/Global-signbank/venv/lib/python3.5/site-packages/django/utils/decorators.py" in _wrapped_view
  149.                     response = view_func(request, *args, **kwargs)

File "/var/www/Global-signbank/venv/lib/python3.5/site-packages/django/utils/decorators.py" in bound_func
  63.                 return func.__get__(self, type(self))(*args2, **kwargs2)

File "/var/www/Global-signbank/venv/lib/python3.5/site-packages/django/utils/decorators.py" in _wrapper
  67.             return bound_func(*args, **kwargs)

File "/var/www/Global-signbank/venv/lib/python3.5/site-packages/django/views/decorators/cache.py" in _wrapped_view_func
  57.         response = view_func(request, *args, **kwargs)

File "/var/www/Global-signbank/venv/lib/python3.5/site-packages/django/utils/decorators.py" in bound_func
  63.                 return func.__get__(self, type(self))(*args2, **kwargs2)

File "/var/www/Global-signbank/venv/lib/python3.5/site-packages/django/contrib/auth/views.py" in dispatch
  90.         return super(LoginView, self).dispatch(request, *args, **kwargs)

File "/var/www/Global-signbank/venv/lib/python3.5/site-packages/django/views/generic/base.py" in dispatch
  88.         return handler(request, *args, **kwargs)

File "/var/www/Global-signbank/venv/lib/python3.5/site-packages/django/views/generic/edit.py" in get
  174.         return self.render_to_response(self.get_context_data())

File "/var/www/Global-signbank/venv/lib/python3.5/site-packages/django/contrib/auth/views.py" in get_context_data
  122.         current_site = get_current_site(self.request)

File "/var/www/Global-signbank/venv/lib/python3.5/site-packages/django/contrib/sites/shortcuts.py" in get_current_site
  15.         return Site.objects.get_current(request)

File "/var/www/Global-signbank/venv/lib/python3.5/site-packages/django/contrib/sites/models.py" in get_current
  63.             return self._get_site_by_id(site_id)

File "/var/www/Global-signbank/venv/lib/python3.5/site-packages/django/contrib/sites/models.py" in _get_site_by_id
  35.             site = self.get(pk=site_id)

File "/var/www/Global-signbank/venv/lib/python3.5/site-packages/django/db/models/manager.py" in manager_method
  85.                 return getattr(self.get_queryset(), name)(*args, **kwargs)

File "/var/www/Global-signbank/venv/lib/python3.5/site-packages/django/db/models/query.py" in get
  379.                 self.model._meta.object_name

Exception Type: DoesNotExist at /admin/login/
Exception Value: Site matching query does not exist.
```

We hope this to be a simple error and that we finally could make this work.
Thanks you!

**Comment by vanlummelhuizen** [comment]
For now remove or comment out the following line in signbank/settings/base.py:

`STATICFILES_STORAGE = ( os.path.join(PROJECT_DIR, "static"), )`

**Comment by FabricioRojas** [comment]
We get the same error after removing that line.

**Comment by vanlummelhuizen** [comment]
Did you do points 2 - 5 of the workaround above again after you made a (new) database with the sqlite3 command?

**Comment by FabricioRojas** [comment]
Doing again points 2-5 finally worked. Thanks!
