### ISSUE TITLE
Create unit test to check if there are glosses in all ECVs

### ISSUE THREAD

**Issue by Woseseltops** [Signbank/Global-signbank#563]
ECVs that are empty for some mysterious reason are a recurring problem for the ASL Signbank. Clicking the button to generate the ECV fixes it. This test should fail if the button should be clicked again.

**Comment by susanodd** [comment]
I've implemented a test for this.
One thing that comes up, because we use a test database, which is empty, it's not possible to test whether empty ecv's for a dataset are rightly so, because for the test database all datasets are empty.
Whereas on the server a dataset may be empty, and hence correctly have an empty ecv.

**Comment by susanodd** [comment]
Other than run such a test on the real database, a coded solution would be to output an ecv only if there are actually glosses in the dataset.
Another possibility is to modify the create_test_db code to put a token gloss in each non-empty dataset.

**Comment by susanodd** [comment]
Design: The new test fails if any of the ecv files does not contain glosses.
Observation: The test is run against the test database, so the datasets have no glosses unless created by the test.
Q: What to do about (real) empty datasets? The test fails for these. It's not possible to determine which datasets are empty on the test database, so it's not possible to determine if an ecv is correctly empty.
Possible solution: Don't save any file for empty datasets.
Q: If that's done, does any other code rely on there being an ecv file? Or can it not exist? Can an empty dataset correspond to no ecv file?

**Comment by susanodd** [comment]
To assist in this issue, I revised the Dataset List View.

The interface (template) and the code no longer offer exporting an empty dataset to ecv. This is to prevent empty ecv files from purposefully being created.
The ECV button is no longer shown for empty datasets. And the url action for exporting an ecv returns an information message to the user that the dataset is empty and nothing was done. (e.g., if the user attempts to circumvent the absence of the button by typing in the url with parameters.)

The test (this issue) checks for empty ecv files and reports back.

**Comment by ocrasborn** [comment]
:-)

**Comment by susanodd** [comment]
I'm working on this issue again.
One of the tests is broken:
`test_DatasetListView_ECV_export_permission_change_dataset`
The test database is actually empty, and ECV export is not offered for empty datasets.
A gloss needs to be created so there is something to export.

**Comment by susanodd** [comment]
Revised the tests to cover empty datasets. Added an additional test and more feedback for the tester.

**Comment by Woseseltops** [comment]
Just checked this, and looks perfect. It didn't work on the live server initially, but that turned out to be because of old ECV files still lying around. The test passed after I removed those.

This issue can be closed as far as I am concerned, @susanodd
