### ISSUE TITLE
Migrating fails for a new install of Global Signbank

### ISSUE THREAD

**Issue by vanlummelhuizen** [Signbank/Global-signbank#564]
For new installs of Global Signbank the initial migration fails because it tries to find things in the database.

We now think there are unnecessary imports in the migration process that end up in places where the code tries to get stuff from the database.

**Comment by Woseseltops** [comment]
Okay on several I places I added exceptions for OperationalErrors, the error you get when the code tries to to use a table that does not exist yet. This means that the code now no longer requires a particular database to be there. 

Next up: changing the migrations so that some required initial data is already there.

**Comment by Woseseltops** [comment]
Done... you think we can close this, @vanlummelhuizen ?

**Comment by vanlummelhuizen** [comment]
Yes!

**Comment by Woseseltops** [comment]
Now that I'm working with MySQL, I get `django.db.utils.ProgrammingError` instead of an `OperationalError`, so the `try except` clause needs to know about this as well. Furthermore, a new one in `models.py`: 

```
translated_choice_lists_table = generate_translated_choice_list_table()
```

**Comment by susanodd** [comment]
Does this table generation give an error?
It's possible we can recode to remove this.
This dates to before we started using Ajax to generate the field choices.

**Comment by Woseseltops** [comment]
Yeah it's always 'OperationalError/ProgrammingError: x does not exist'. In the new case, x is dictionary_fieldchoice . You get it when you try to do `develop.py migrate` on an empty database.

**Comment by susanodd** [comment]
The exception in tools.py relies on:
        ` for language in Language.objects.all():`

The exception in forms.py relies on:
        ` for tag in Tag.objects.all()`

The exception in models.py relies on:
          `Handshape.objects.all()`
and
          `FieldChoice.objects.filter(field__iexact=f_category)`

plus there's a test:
          `if f_category == 'Handshape':`


The exception in registration/forms.py relies on:
         `for ds in Dataset.objects.filter(...)`


There could be a problem with the Handshape versus FieldChoice Table in MySQL.
The queries/code deliberately abuse the fact that Handshape objects contain all the fields of FieldChoice objects.

**Comment by Woseseltops** [comment]
Just tried this, it works now! Thanks @susanodd
