### ISSUE TITLE
Problem with referring to lemma in new gloss

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#565]
From Julie:
"I've instructed people who have editor access to ASL Signbank to use ~NEED-ID-GLOSS as the Lemma ID whenever suggesting new ID glosses. I use the Lemma ID to group together all proposed ID glosses. And the suggesters put their actual proposed ID gloss in the "Annotation ID Gloss" field. They reported issues with being able to do this. Specifically, they got an error message saying that the Lemma ID doesn't exist when it does. The "drop-down menu" showing existing lemma ids after starting to type wasn't showing up (and they didn't know that this had to happen - that they had to actually select something from the menu instead of just typing it in). 

I re-produced their issue (video here: 
https://www.dropbox.com/s/ycz776hnl826abp/190312_SuggestingWhenLemmaIDisknown.mov?dl=0) and it turns out that for the "add new sign" form, you need to "reset" the form by "un-selecting" the dataset. If it says "ASL", you need to pick ---- then back to ASL. See video at link above - it's a bit long but you should get the idea."

**Comment by vanlummelhuizen** [comment]
I already solved this for Global Signbank: a6a6d2acfbfa7f1bd4621cb9957a2c3166d42668. I asked @Woseseltops to put this solution on the ASL instance.

**Comment by Woseseltops** [comment]
Which I have done indeed, a month ago already. Happy @ocrasborn ?
