### ISSUE TITLE
Double-check working of ASL registration process

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#566]
Julie: "By the way, I just got an email from someone who tried to register for the ASL Signbank and still hadn't gotten access. That was one of my questions before too. I see that feature is up but I am not getting any alerts anywhere about this. How do I see and process those requests?"

**Comment by Woseseltops** [comment]
Looks like this is not working correctly. I tried and did get an activation email, but it linked to the Global Signbank. When I manually fixed the URL, the account got created, but of course with no permissions so far. Can you refresh my memory on what is supposed to happen next, @ocrasborn ?

**Comment by ocrasborn** [comment]
Julie requested a kind of 'digest mail' to her as admin, say once a week to start with, where she would see all new registrations and could act upon those. Background: possibly many new registrations for the ASL Signbank in the future.
As the ASL SB doesn't use the dataset feature, giving access to the one active dataset should be done automatically, so that all that happens is activating new accounts. It'd be fine to do that in the admin (ideally as an action that could be applied to all users that she check-marked), as long as she could filter the users there to see the new ones easily. Alternatives are also welcome.

**Comment by Woseseltops** [comment]
Current working in Global Signbank:
* During account registration, users can request access to datasets
* After confirming their email, users can log in, but cannot see any datasets yet
* The managers of the requested datasets get an email when access to a dataset is requested
* In the dataset manager page, users can search for the users they want to give access

What I propose is to keep this functionality the same for ASL Signbank, but with the following extra things so it makes more sense for Julie:
* If the (existing) setting SHOW_DATASET_INTERFACE_OPTIONS is false, a new user automatically requests access to the main dataset (and does not see this option).
* A new setting REQUEST_NOTIFICATIONS, where you can turn off getting an email every time a new user requests access.
* A new command line function that gives you an overview of active users with access to no datasets. I will configure that the output of this function will be emailed to Julie every week if not null.
* A new view that uses this same functionality. If SHOW_DATASET_INTERFACE_OPTIONS is false, it adds a checkbox behind each name. If you click the checkbox, the user will be given access to the main dataset.

@susanodd feel free to take up some of these things if you like them :)

**Comment by Woseseltops** [comment]
Before I start, do you you agree with this @ocrasborn ?

**Comment by ocrasborn** [comment]
Hi @Woseseltops : all sounds perfectly sensible to me. One request and one question:
* The request (maybe you already had this in mind): in the email to Julie, please add first name - last name - email address to the user name, to help her decide whether or not immediate action is needed
* The question: where does the email address for the destination go? It would be handy if this is something users can configure in the Django admin somehow, along perhaps with the frequency of the email?

**Comment by Woseseltops** [comment]
Already did this:

> A new command line function that gives you an overview of active users with access to no datasets. 
> A new view that uses this same functionality.

And I also created a Signbank function under tools to do this:

> I will configure that the output of this function will be emailed to Julie every week if not null.

**Comment by Woseseltops** [comment]
Got the view working where you get an overview of all users without a dataset, and you can give them access. 

![image](https://user-images.githubusercontent.com/1909317/60959451-805aa200-a308-11e9-87de-f71e794083c8.png)

**Comment by Woseseltops** [comment]
I've now also made the registration email more dynamic, so it says the name of the correct Signbank at the correct places etc.

Current flow:
1. User registers. If the Signbank installation uses datasets, the user can request access to one or more datasets automatically.
2a. If the user requested a dataset, the dataset owner will get an email, and can go to the manage dataset page.
2b. If not, s/he will show up in the list of users without dataset (both as a view and as a recurring email), where s/he can be given access to the default dataset.

An extra thing I proposed above is to let users automatically request access to the main dataset when there is only one, and then turn off the email notification... but given the fact that this flow already does what we want I think this isn't needed.

**Comment by ocrasborn** [comment]
Hi @Woseseltops , I'm sitting here next to the person who would receive the weekly emails for ASL registrations, and she isn't getting any ;-). Did you still need to take up this issue after the ASL update? I take it that this update has long since been executed, no?
And to remind me: can the ASL user configure somewhere who is getting this email and with which frequency? A field (even if in the admin) saying 'every X days' would be just perfect for this, but perhaps this is already there?

**Comment by Woseseltops** [comment]
I was thinking it would be easy to configure the weekly mail, but it turns out I never wrote the code that (1) composes the mail (using existing functionality that compiles a list of users), (2) sends the mail. After I've got that, I have to create a cronjob that actually runs this code.

**Comment by Woseseltops** [comment]
> it turns out I never wrote the code that (1) composes the mail (using existing functionality that compiles a list of users), (2) sends the mail. 

Ah no I actually, as a management command even. I love it when I discover a solution cooked up by my past self that is better than the solution by my current self :) . Put the command in cron, will reopen this issue based on what Julie thinks of it.
