### ISSUE TITLE
Enable Homonym List for ASL

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#567]
Menu items is there, but not linked to function it seems: "all I see is this - "<generate overviews to be put here>" meaning this is still under construction? (I recently wanted to be able to see all of our homonyms at the same time in a list somehow and remembered you and I talking about that possibility and wondered if this was it)" (Julie)

**Comment by Woseseltops** [comment]
I see that this URL works: https://aslsignbank.haskins.yale.edu/analysis/homonyms/ , so I made a menu item pointing this sign. Happy @ocrasborn ?
