### ISSUE TITLE
Revise the Public View

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#568]
* Please move the field 'Translation equivalents' which is now below the movie to appear below the gloss(es), and make the translations appear there as well (if any).
* The Notes in SB have a property 'published' (a checkmark in the edit mode). We were never bothered about this, but now would like to use this feature to make notes appear to anonymous users. Please add them to the 'public view' below the glosses and the translation equivalents. 
* Use format "<Note type>: <note value>" in the second column, and the generic label "Note(s)" as the field name in the first column

**Comment by susanodd** [comment]
This has been done and pushed to github.

**Comment by susanodd** [comment]
This has been fixed. Published notes are displayed on the Public View.
Additionally, there was a subtle error in adding new notes in Gloss Detail View.
The name of the selection field for Note Type had also been used elsewhere in the template for a different field and new notes were being ignored. That has been fixed.

**Comment by vanlummelhuizen** [comment]
@ocrasborn this is live. Happy?

**Comment by ocrasborn** [comment]
happy
