### ISSUE TITLE
Unit test: all settings files have all settings

### ISSUE THREAD

**Issue by Woseseltops** [Signbank/Global-signbank#570]
A problem I've had multiple times is errors because the ASL settings file is not up to date. Ideally, when creating a new setting, we should add it to (1) the global settings file, (2) the ASL settings file and (3) the empty template. This new unit test should check whether that has been done indeed.

This issue might also be a nice opportunity to remove unused settings files.

**Comment by susanodd** [comment]
Okay, this has been done. I made a simple test that reads in the server specific settings for global and asl and compares what's been set. It gives feedback.
Based on that, I modified a couple of names for Global, removed an unused setting, and added (empty) settings that were missing for ASL.

**Comment by susanodd** [comment]
@Woseseltops this has been fixed. The settings for ASL are on the Global branch.

**Comment by Woseseltops** [comment]
Looks good, thanks @susanodd ! 

One extra request: right now, it is hardcoded to only check the global and ASL settings files, but I would also like (1) to check the empty template and (2) this to work in the use case that if people add new settings files (for example, a new installation of Signbank somewhere), these are also automatically checked... so maybe dynamically compare ALL settings files with each other? Feel free to remove older unused settings files to make the unit test not fail.

**Comment by susanodd** [comment]
Okay, @Woseseltops, what should actually be in the other settings files?
Should they all be identical? What is the relation between the empty_template and the others?
You want something like a Venn diagram?

I'm now iterating over all settings files that are in server_specific and constructing a dict of the settings.
But what should be tested for the other files?
(Yes, this is very relevant to #579, for a new Signbank.)

When is the test successful?

**Comment by susanodd** [comment]
I made the test just do printouts after each comparison.
This has been pushed to github.

**Comment by vanlummelhuizen** [comment]
Perhaps we should think about default settings that may or may not be overridden, and comments to guide the developer.

**Comment by susanodd** [comment]
That's a good idea. Is that what empty_template is supposed to be?
I made some comments in Issue #579 related to the settings for languages. (Waiting to see if that is causing a problem.)
Yes, there needs to be a guide for this.

**Comment by Woseseltops** [comment]
![](https://media.giphy.com/media/xT0xem7ZlZ2DOYqpG0/giphy.gif)

#586

**Comment by Woseseltops** [comment]
> Should they all be identical? What is the relation between the empty_template and the others?

Right now, the test should fail if one settings file has settings that are not in all other settings files. After #586 is implemented, the test should only file if a settings file uses a setting which is not in the default settings file.

**Comment by Woseseltops** [comment]
(#586 is implemented)

**Comment by susanodd** [comment]
This has been done.
Incidentally, the `default.py` filename is now hard-coded in the test.
