### ISSUE TITLE
ASL search unit test fails while search works

### ISSUE THREAD

**Issue by Woseseltops** [Signbank/Global-signbank#571]
In the search unit test, three glosses are created: two with handedness 4, and one with handedness 5. When searching for glosses with handedness 4, indeed two glosses are found... but when searching for handedness 5 nothing is returned. Huh? Even weirder is that we do not have this problem when running tests on the Global Signbank server.

**Comment by susanodd** [comment]
Does ASL have the same version of (normal) code now?

**Comment by susanodd** [comment]
Did you use the new version of create_test_db ? I modified this yesterday because it was not clearing the lemmaidgloss and lemmaidglosstranslation tables. That was causing some problems with the import csv tests.

**Comment by susanodd** [comment]
It looks like there aren't any annotation translations created in that test.

**Comment by susanodd** [comment]
I revised the other testSearchForGlosses test as well.
I also revised code to remove hard-coded "_nl" from other tests. (See #510.)

**Comment by Woseseltops** [comment]
Issue solved!
