### ISSUE TITLE
Don't show tags to anonymous users in list view

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#572]
When a user that is not logged in searches for signs, getting hits from what has checkmark 'Publish in dictionary' under Publication Status, they also see the workflow tags of the editors. Please hide tags altogether from the list view when a user is not logged in.

**Comment by ocrasborn** [comment]
Oh, for both ASL and Global, please. Nice 'n simple ;-)

**Comment by susanodd** [comment]
Tags have been hidden for anonymous users. Pushed to github.

**Comment by vanlummelhuizen** [comment]
@ocrasborn, this is live. Happy?
