### ISSUE TITLE
Datasets not shown in header for all pages

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#573]
For the home page and the pages in the About menu, the available and selected datasets are not shown in the site header. I didn't check all the analysis pages yet, as they take a long time to load, please do check.

**Comment by susanodd** [comment]
This has been fixed and pushed to github. For logged in users, datasets are now shown on the Home page and in the About pages.

(Recall, if a user is not logged in, datasets are not shown in the headers.)
