### ISSUE TITLE
ASL video upload problem

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#576]
From mail by Julie, May 11 2019: Just got on ASL Signbank myself today to add some new signs (SIM-COM, COOKING). When I add a video, I get this error message. When I close the page and go back to the ASL Signbank entry in a new webpage, the video is there so it looks like the "error" doesn't disrupt the video upload process. But I wanted to report it anyway because the error message keeps popping up every time I add a video to a new entry, thought you would like to know. 

<img width="1186" alt="Screen Shot 2019-05-11 at 12 26 18 PM" src="https://user-images.githubusercontent.com/10242207/57628580-81868180-759a-11e9-889a-1fbcc21de894.png">

**Comment by Woseseltops** [comment]
Looks like uwsgi had to be restarted. Did that, now the error message is gone as well.

**Comment by Woseseltops** [comment]
Julie was happy.
