### ISSUE TITLE
Uploaded video not shown

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#581]
This may be related to #426 or #522 , I imagine.
Lori is changing the videos for dataset IS, and finds that the videos don't display. In fact, I can't seem to find them in glossvideo/ either. But the image of the video is correctly processed, stored, and displayed. E.g. https://signbank.science.ru.nl/dictionary/gloss/8719

**Comment by vanlummelhuizen** [comment]
The lemma for this gloss contains parentheses. The lemma is used for constructing the filenames of the video and image, but apparently is not done in the same way for the video and the image: EXPLAIN%28WFD%29-8719.mp4 and EXPLAIN(WFD)-8719.png. The %28 and %29 are the URL-encodings of ( and ). I quickly fixed it by renaming the video file. I will also look into a semi-permanent solution (until the code for #522 is put live). 

Any other glosses I need to fix right away?

**Comment by Woseseltops** [comment]
Lee is also reporting this problem for the ASL Signbank, it looks like it's no longer possible to upload videos to glosses starting with a ~ . This is the uwsgi error log:

```Error resizing video:  b'/var/www/signbank/writable/glossvideo/~W/%7EWESSELTEST-3306.mp4'
Video file: /var/www/signbank/writable/glossvideo/~W/%7EWESSELTEST-3306_small.mp4
avconv -v quiet -i /var/www/signbank/writable/glossvideo/~W/%7EWESSELTEST-3306_small.mp4 -filter:v scale='iw*max(1,sar)':'ih*max(1,1/sar)' /tmp/signbank-extractMiddleFrame/%7EWESSELTEST-3306_small.mp4-frames/all/frame-%5d.png
error with small video destination inside of video/views.py:addvideo
[pid: 4542|app: 0|req: 25992/127879] 130.132.35.237 () {70 vars in 1683 bytes} [Wed Jun  5 11:20:18 2019] POST /video/upload/ => generated 0 bytes in 6677 msecs (HTTP/1.1 302) 6 headers in 205 bytes (471 switches on core 3)```

**Comment by vanlummelhuizen** [comment]
@Woseseltops I made a fix for Global-SB. Can you apply is on ASL-DB?

**Comment by Woseseltops** [comment]
Ah sorry @vanlummelhuizen , missed the commit attached to this issue. I copied the fix and it works!

Two things:
* I see you commented out the original code... maybe it's good to add *why* the original code is commented out, in case we encounter it again in a few years and can't remember.
* I think this problem was introduced recently by accident. Maybe 'uploading videos with weird chars' should be something we check for in the unit tests?

**Comment by vanlummelhuizen** [comment]
> I see you commented out the original code... maybe it's good to add why the original code is commented out, in case we encounter it again in a few years and can't remember.

Perhaps it was better to remove the old code. With `git log -L` someone could see in what commit the changes were made, and also find this discussion.

> I think this problem was introduced recently by accident. Maybe 'uploading videos with weird chars' should be something we check for in the unit tests?

Agreed. I will make something in my #522 work.

**Comment by susanodd** [comment]
Although it's sometimes good to have comments as @Woseseltops suggests so you can still see that something used to be there. Otherwise, it's possible that the wheel gets reinvented if nobody first does a git log -L to see if something used to exist.

**Comment by vanlummelhuizen** [comment]
@susanodd, where to draw the line between commenting and removing? If there is a lot of commented out code, it becomes unreadable. And who is to say any commented out code will end up being used again in the future. Some commented out code may sit there forever.

**Comment by vanlummelhuizen** [comment]
I believe this issue can be closed.
