### ISSUE TITLE
Change setting mechanism: default with overrides, comments

### ISSUE THREAD

**Issue by Woseseltops** [Signbank/Global-signbank#586]
Idea by @vanlummelhuizen: 

> Perhaps we should think about default settings that may or may not be overridden, and comments to guide the developer.

That is, instead of an empty template file that nobody uses, there is a 'default' file that everybody uses and the individual server specific files will be much smaller.

Maybe this would also be a good moment to rethink what settings belong in this default server specific file (= things that might be different for each SB installation) and what settings belong to the base.py file (=things that Django need to know but will be the same for every Signbank installation).

**Comment by Woseseltops** [comment]
Implemented this already and is in use for the Global Signbank. Next up: clean up the rest of the settings file.

**Comment by Woseseltops** [comment]
Forgot to label commit 14c41417bda7ec40bf1f9046d181542e69d4aa79

**Comment by Woseseltops** [comment]
One change I had to make that slightly complicates things: some settings are made of other settings, like:

```python
ROOT = '/my/root/'
WRITABLE_FOLDER = ROOT+'writable/'
VIDEO_FOLDER = WRITABLE_FOLDER+'glossvideo/'
```

But what if you want to override the first setting in a separate file? Do you copy over all other settings that include this setting as well? To avoid this I opted for a system that makes including other settings in `default.py` impossible. Instead, combinations like the ones above are done at the end, in the `__init__.py`. So for the example above, `default.py` would look like 

```python
ROOT = '/my/root/'
WRITABLE_FOLDER = 'writable/'
VIDEO_FOLDER = 'glossvideo/'
```

and `__init__.py` would look like

```python
from default import *
from server_specific import *

WRITABLE_FOLDER = ROOT+WRITABLE_FOLDER
VIDEO_FOLDER = WRITABLE_FOLDER+VIDEO_FOLDER
```

**Comment by susanodd** [comment]
@Woseseltops: Is it possible that the changes for this issue are causing the column order problem shown at the demo? (See #580.)
I have the most recent database on my machine, but I have not pulled the code of this issue.

**Comment by Woseseltops** [comment]
Nope @susanodd , see my response in #580 .
