### ISSUE TITLE
Order gloss typeahead results by length

### ISSUE THREAD

**Issue by Woseseltops** [Signbank/Global-signbank#592]
When creating a new gloss, Julie wants to search for and select the lemma 'WE'. However, it is not in the list of 5 suggestions, because longer words like 'jewelry' and 'next-week' apparently go first, and the actual thing she is looking does not 'make the list'. 

A solution could be to simply sort the list of matches by length; for long words you can simply continue typing if your match is not in the list, while this is not possible for short words like WE.

**Comment by Woseseltops** [comment]
Still working on this @susanodd ?

**Comment by susanodd** [comment]
Yes! It's 99 percent finished.
I'm working on the morpheme pages which also make use of the ajax calls. There is a weird CSS formatting glitch. It seems the pages haven't been updated for some time. They also make use of the updated javascript and ajax calls.

**Comment by susanodd** [comment]
This has been pushed to github.

**Comment by vanlummelhuizen** [comment]
The solution from @susanodd is live. Please confirm, @ocrasborn .
