### ISSUE TITLE
Backups have stopped working in July

### ISSUE THREAD

**Issue by Woseseltops** [Signbank/Global-signbank#593]
When run by hand, the backup script still works, so unclear why the script is not executed anymore.

**Comment by vanlummelhuizen** [comment]
@Woseseltops Unless you ran the backup script a 5 this morning, it is working again.

**Comment by Woseseltops** [comment]
Weird, because I did not change anything. My best guess right now is that Onno's crontab file was ignored because he didn't log in for a long time, but I don't really believe it myself.

**Comment by ocrasborn** [comment]
I hadn't logged in for min. 5 to possibly even 8 weeks
