### ISSUE TITLE
Display of images broken

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#596]
Also in ASL?
Images don't display anymore in neither the list view nor the detail view.

**Comment by vanlummelhuizen** [comment]
This has probably to do with the unification of video systems. It is love now but not everything worked as I hoped. I am working on it but it takes quite some time.

**Comment by vanlummelhuizen** [comment]
I ironed out all things I could find. I also brought back the images + hover video on the gloss list view. Please verify and check @ocrasborn .
