### ISSUE TITLE
Create a central crontab file for Signbank

### ISSUE THREAD

**Issue by Woseseltops** [Signbank/Global-signbank#597]
Right now, we are using the account of Onno on Applejack, but only Onno and Wessel can edit.

https://superuser.com/questions/1078301/how-to-allow-multiple-users-to-access-to-the-same-crontab-in-debian-linux-v8-4

Idea by @vanlummelhuizen

**Comment by vanlummelhuizen** [comment]
Also interesting: http://wiki.networksecuritytoolkit.org/index.php/HowTo_Share_A_Terminal_Session_Using_Screen

**Comment by susanodd** [comment]
This is too old.
