### ISSUE TITLE
Populate the NGT GlossFrequency objects in a cron job

### ISSUE THREAD

**Issue by susanodd** [Signbank/Global-signbank#602]
The new dataset frequency model of #354 needs to be populated in a cron job.
To process all the NGT eaf documents, it takes about 1.25 hours on my local server. This ought to be done at night.
The configure_speakers and configure_corpus_documents_ngt functions are available in tools.py.

**Comment by susanodd** [comment]
There are also urls for the configuration in dictionary urls. You need to be logged in.
dictionary / configure_speakers /
dictionary / configure_corpus_documents_ngt /

**Comment by Woseseltops** [comment]
Aha so @vanlummelhuizen accepted your pull request? Nice.

To make it quick for me to test whether this works, could you add an optional argument to the function so I can make it only process part of data (like the first file or something like that)?

This is the relevant line in the crontab file at the moment:

`echo "from signbank.tools import update_cngt_counts as w; w()" | /var/www/signbank/live/sb-env/bin/python /var/www/signbank/live/repo/bin/develop.py shell`

**Comment by vanlummelhuizen** [comment]
@Woseseltops: I talked to @susanodd : unfortunately she did not have time to implement your optional argument request because she is leaving to go on vacation. She says it has been tested intensively.

**Comment by Woseseltops** [comment]
I just changed the Cronjob to:

```echo "from signbank.tools import configure_corpus_documents as w; w()" | /var/www/signbank/live/sb-env/bin/python /var/www/signbank/live/repo/bin/develop.py shell``` 

Some thing I noticed:
* I had to install numpy and pympi-ling to make it work.
* There is also a `configure_speakers`... but that one only has to be run once, right?

**Comment by susanodd** [comment]
yes, configure_speakers only needs to be run once.

**Comment by susanodd** [comment]
yes, numpy and pympi-ling needed to be installed to parse the eaf files to obtain the date.

**Comment by Woseseltops** [comment]
Okay I think it's working. We'll reopen when (not if) it breaks.

**Comment by susanodd** [comment]
@Woseseltops is this cron job still being run?

I ask because the code in question is (being) extended to also work for other datasets with their own EAF files. (#756).
(There is separate python code for the new functionality, but now there are new urls that mirror the functionality of this issue,but for other datasets.)
I noticed the extra file index argument mentioned above is in the url.
That's why I reopened this issue, because it's not clear to me now what the relation is between doing this for CNGT and doing this for other datasets.

So far this new functionality is only on my local server. I am working on tests now.

I was looking to see what to do about the CNGT specific functionality.
The Frequency View for a Gloss now uses the actual GlossFrequency objects rather than the frequency fields hard coded in the Gloss model. (This is on my local server.)

For the "other" datasets using EAF files, there is now (will be) a button for updating the corpus.
The files are then scanned again and the GlossFrequency objects updated.
This overlaps with what this cron job of this issue is doing (for CNGT).

Any idea what to do? Will this cron job become obsolete? Will there need to be cron jobs for all datasets?

**Comment by ocrasborn** [comment]
It seems all cron jobs have stopped since the server update, @Woseseltops

**Comment by susanodd** [comment]
This issue is subsumed by #769.

**Comment by susanodd** [comment]
GlossFrequency objects and corpora are on Global.
