### ISSUE TITLE
Odd error upon mass importing videos

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#603]
When I import videos for dataset EmblemsNL using the video import script, I get this message for a seemingly random 62 out of 107 files. All 107 uploaded correctly though. After import, the files are correctly removed from the import directory (EmblemsNL/nld/).

OSError: [Errno 2] No such file or directory: '/var/www/signbank/live/writable/import_videos/EmblemsNL/nld/STINKEN-B.mp4'
OSError: [Errno 2] No such file or directory: '/var/www/signbank/live/writable/import_videos/EmblemsNL/nld/BESPOTTEN-B.mp4'
OSError: [Errno 2] No such file or directory: '/var/www/signbank/live/writable/import_videos/EmblemsNL/nld/WARM-B.mp4'
OSError: [Errno 2] No such file or directory: '/var/www/signbank/live/writable/import_videos/EmblemsNL/nld/DOM-B.mp4'
OSError: [Errno 2] No such file or directory: '/var/www/signbank/live/writable/import_videos/EmblemsNL/nld/GEK-C.mp4'
OSError: [Errno 2] No such file or directory: '/var/www/signbank/live/writable/import_videos/EmblemsNL/nld/STERK-A.mp4'
OSError: [Errno 2] No such file or directory: '/var/www/signbank/live/writable/import_videos/EmblemsNL/nld/ROCK-ON.mp4'
OSError: [Errno 2] No such file or directory: '/var/www/signbank/live/writable/import_videos/EmblemsNL/nld/GOED-A.mp4'
OSError: [Errno 2] No such file or directory: '/var/www/signbank/live/writable/import_videos/EmblemsNL/nld/VERDRIETIG-A.mp4'
OSError: [Errno 2] No such file or directory: '/var/www/signbank/live/writable/import_videos/EmblemsNL/nld/JAMMER-A.mp4'
OSError: [Errno 2] No such file or directory: '/var/www/signbank/live/writable/import_videos/EmblemsNL/nld/RUSTIG-A.mp4'
OSError: [Errno 2] No such file or directory: '/var/www/signbank/live/writable/import_videos/EmblemsNL/nld/DODEN-A.mp4'
OSError: [Errno 2] No such file or directory: '/var/www/signbank/live/writable/import_videos/EmblemsNL/nld/SCHRIJVEN.mp4'
OSError: [Errno 2] No such file or directory: '/var/www/signbank/live/writable/import_videos/EmblemsNL/nld/STOPPEN.mp4'
OSError: [Errno 2] No such file or directory: '/var/www/signbank/live/writable/import_videos/EmblemsNL/nld/DOM-A.mp4'
OSError: [Errno 2] No such file or directory: '/var/www/signbank/live/writable/import_videos/EmblemsNL/nld/LIFTEN-B.mp4'
OSError: [Errno 2] No such file or directory: '/var/www/signbank/live/writable/import_videos/EmblemsNL/nld/SUCCES.mp4'
OSError: [Errno 2] No such file or directory: '/var/www/signbank/live/writable/import_videos/EmblemsNL/nld/VOL.mp4'
OSError: [Errno 2] No such file or directory: '/var/www/signbank/live/writable/import_videos/EmblemsNL/nld/ROKEN.mp4'
OSError: [Errno 2] No such file or directory: '/var/www/signbank/live/writable/import_videos/EmblemsNL/nld/PRACHTIG.mp4'
OSError: [Errno 2] No such file or directory: '/var/www/signbank/live/writable/import_videos/EmblemsNL/nld/DOOR-DE-VINGERS-ZIEN.mp4'
OSError: [Errno 2] No such file or directory: '/var/www/signbank/live/writable/import_videos/EmblemsNL/nld/AANSTEKER.mp4'
OSError: [Errno 2] No such file or directory: '/var/www/signbank/live/writable/import_videos/EmblemsNL/nld/BESPOTTEN-A.mp4'
OSError: [Errno 2] No such file or directory: '/var/www/signbank/live/writable/import_videos/EmblemsNL/nld/KOMEN-A.mp4'
OSError: [Errno 2] No such file or directory: '/var/www/signbank/live/writable/import_videos/EmblemsNL/nld/ALSTUBLIEFT-B.mp4'
OSError: [Errno 2] No such file or directory: '/var/www/signbank/live/writable/import_videos/EmblemsNL/nld/NEE-A.mp4'
OSError: [Errno 2] No such file or directory: '/var/www/signbank/live/writable/import_videos/EmblemsNL/nld/LUISTEREN-B.mp4'
OSError: [Errno 2] No such file or directory: '/var/www/signbank/live/writable/import_videos/EmblemsNL/nld/ERGERNIS-A.mp4'
OSError: [Errno 2] No such file or directory: '/var/www/signbank/live/writable/import_videos/EmblemsNL/nld/OPGELUCHT.mp4'
OSError: [Errno 2] No such file or directory: '/var/www/signbank/live/writable/import_videos/EmblemsNL/nld/ZIEZO.mp4'
OSError: [Errno 2] No such file or directory: '/var/www/signbank/live/writable/import_videos/EmblemsNL/nld/HONGER.mp4'
OSError: [Errno 2] No such file or directory: '/var/www/signbank/live/writable/import_videos/EmblemsNL/nld/KOMEN-B.mp4'
OSError: [Errno 2] No such file or directory: '/var/www/signbank/live/writable/import_videos/EmblemsNL/nld/ZIN-IN-A.mp4'
OSError: [Errno 2] No such file or directory: '/var/www/signbank/live/writable/import_videos/EmblemsNL/nld/DOM-C.mp4'
OSError: [Errno 2] No such file or directory: '/var/www/signbank/live/writable/import_videos/EmblemsNL/nld/PEACE.mp4'
OSError: [Errno 2] No such file or directory: '/var/www/signbank/live/writable/import_videos/EmblemsNL/nld/TIJD.mp4'
OSError: [Errno 2] No such file or directory: '/var/www/signbank/live/writable/import_videos/EmblemsNL/nld/GA-DOOR.mp4'
OSError: [Errno 2] No such file or directory: '/var/www/signbank/live/writable/import_videos/EmblemsNL/nld/GELD.mp4'
OSError: [Errno 2] No such file or directory: '/var/www/signbank/live/writable/import_videos/EmblemsNL/nld/STINKEN-A.mp4'
OSError: [Errno 2] No such file or directory: '/var/www/signbank/live/writable/import_videos/EmblemsNL/nld/BEDELEN.mp4'
OSError: [Errno 2] No such file or directory: '/var/www/signbank/live/writable/import_videos/EmblemsNL/nld/GEK-A.mp4'
OSError: [Errno 2] No such file or directory: '/var/www/signbank/live/writable/import_videos/EmblemsNL/nld/EVEN-DENKEN.mp4'
OSError: [Errno 2] No such file or directory: '/var/www/signbank/live/writable/import_videos/EmblemsNL/nld/TIME-OUT.mp4'
OSError: [Errno 2] No such file or directory: '/var/www/signbank/live/writable/import_videos/EmblemsNL/nld/STIL.mp4'
OSError: [Errno 2] No such file or directory: '/var/www/signbank/live/writable/import_videos/EmblemsNL/nld/DRINKEN.mp4'
OSError: [Errno 2] No such file or directory: '/var/www/signbank/live/writable/import_videos/EmblemsNL/nld/RUSTIG-B.mp4'
OSError: [Errno 2] No such file or directory: '/var/www/signbank/live/writable/import_videos/EmblemsNL/nld/HOERA.mp4'
OSError: [Errno 2] No such file or directory: '/var/www/signbank/live/writable/import_videos/EmblemsNL/nld/ERUIT.mp4'
OSError: [Errno 2] No such file or directory: '/var/www/signbank/live/writable/import_videos/EmblemsNL/nld/STELEN.mp4'
OSError: [Errno 2] No such file or directory: '/var/www/signbank/live/writable/import_videos/EmblemsNL/nld/KOUD-B.mp4'
OSError: [Errno 2] No such file or directory: '/var/www/signbank/live/writable/import_videos/EmblemsNL/nld/HALLO.mp4'
OSError: [Errno 2] No such file or directory: '/var/www/signbank/live/writable/import_videos/EmblemsNL/nld/OEPS.mp4'
OSError: [Errno 2] No such file or directory: '/var/www/signbank/live/writable/import_videos/EmblemsNL/nld/PRATEN.mp4'
OSError: [Errno 2] No such file or directory: '/var/www/signbank/live/writable/import_videos/EmblemsNL/nld/TWIJFEL-A.mp4'
OSError: [Errno 2] No such file or directory: '/var/www/signbank/live/writable/import_videos/EmblemsNL/nld/GOED-C.mp4'
OSError: [Errno 2] No such file or directory: '/var/www/signbank/live/writable/import_videos/EmblemsNL/nld/WARM-A.mp4'
OSError: [Errno 2] No such file or directory: '/var/www/signbank/live/writable/import_videos/EmblemsNL/nld/ZIN-IN-B.mp4'
OSError: [Errno 2] No such file or directory: '/var/www/signbank/live/writable/import_videos/EmblemsNL/nld/SLAPEN.mp4'
OSError: [Errno 2] No such file or directory: '/var/www/signbank/live/writable/import_videos/EmblemsNL/nld/SEKS.mp4'
OSError: [Errno 2] No such file or directory: '/var/www/signbank/live/writable/import_videos/EmblemsNL/nld/NADENKEN-A.mp4'
OSError: [Errno 2] No such file or directory: '/var/www/signbank/live/writable/import_videos/EmblemsNL/nld/HOOFDPIJN.mp4'
OSError: [Errno 2] No such file or directory: '/var/www/signbank/live/writable/import_videos/EmblemsNL/nld/LUISTEREN-NIET-A.mp4'

**Comment by vanlummelhuizen** [comment]
@ocrasborn After digging in some log files, my assessment of this is that the process of importing videos was started twice and the two processes overlapped. First, both processes listed all files. Then one process handled one file and deleted/moved them. By the time they were gone, the other process could not find them anymore.

**Comment by vanlummelhuizen** [comment]
@ocrasborn Let's see what happens with the next time an import videos process is started. If problems keep arising, we could think of a solution of a method to run multiple processes after each instead of in parallel.

**Comment by susanodd** [comment]
This issue is kind of old.
