### ISSUE TITLE
Still image not always from the middle of the video

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#604]
When batch uploading videos recently to dataset EmblemsNL, we found that for quite a few videos, the auto-generated still image is not from exactly the middle of the video, leading to the impression of a rest position of the signer in the list view. What might be wrong here?
The signs in question:

KOMEN-B 
WETEN-NIET-A
WEGGAAN 
BESPOTTEN-B 
GELD 
ERUIT 
PEACE
ALSTUBLIEFT-B
SEKS 
SLAPEN
ROKEN
BUIKPIJN
VOL
DOM-A
DOM-C
NADENKEN-A

**Comment by vanlummelhuizen** [comment]
@ocrasborn this is probably caused by the same thing as described in https://github.com/Signbank/Global-signbank/issues/603#issuecomment-558994736: two simultaneous video import processes. The question is now, who is going to solve this. I guess uploading only the videos for the signs listed above and then importing them again, should do the trick.

**Comment by ocrasborn** [comment]
Hi @vanlummelhuizen , was just trying to batch import again, videos are in the right place, but I get the following error, which is similar to what I get in the interface when I try to remove a video with the delete button, or try to re-upload a video in the interface:
[Errno 2] No such file or directory: '/var/www/signbank/live/writable/glossvideo/EmblemsNL/KO/KOMEN-B-36633.mp4' -> '/var/www/signbank/live/writable/glossvideo/EmblemsNL/KO/KOMEN-B-36633.mp4.bak11226'

**Comment by vanlummelhuizen** [comment]
Hi @ocrasborn apparently, there was a GlossVideo that had 'glossvideo/EmblemsNL/KO/KOMEN-B-36633.mp4' as videofile, but that file does not exist for some reason. In my development setup, when I delete this GlossVideo, importing videos seems to work again. So, I deleted this particular GlossVideo in the live database. Can you try to import again?

**Comment by ocrasborn** [comment]
@vanlummelhuizen : works! No image is generated, however.
See #635 btw, was trying to play with this option too, but couldn't -- or did you do something else to delete it from the live database?

**Comment by vanlummelhuizen** [comment]
@ocrasborn I deleted this one GlossVideo in the so called Django Shell, which is for us developers, but it is also possible to do it in the Admin.

**Comment by ocrasborn** [comment]
Seems to be OK now
