### ISSUE TITLE
Don't setup lemma typeahead when you cannot create new glosses.

### ISSUE THREAD

**Issue by Woseseltops** [Signbank/Global-signbank#606]
Right now, this lemma-typeahead Javascript on the list view takes information from the dataset dropdown when creating new glosses. 

```
$(document).ready(function() {
    gloss_dataset_id = $('#id_dataset').find(":selected").attr('value');

    if (gloss_dataset_id == null)
    {
        $('.lemmatypeahead').prop("disabled", true);
        return;
    }
    gloss_dataset_languages = $('#id_dataset').find(":selected").attr('dataset_languages');
    languages = gloss_dataset_languages.split(",");

    lemma_bloodhound.remote.url = url+'/dictionary/ajax/lemma/'+gloss_dataset_id+'/'+language_code+'/%QUERY'
    if($("#id_dataset").val() == "") {  // No dataset selected
        $('.lemmatypeahead').prop("disabled", true);
    }
    $("#id_dataset").change(function() {
        if(this.value) {
            $('.lemmatypeahead').prop("disabled", false);
            gloss_dataset_id = this.value;
            gloss_dataset_languages = $(this).find(":selected").attr('dataset_languages');
            languages = gloss_dataset_languages.split(",");
            if (languages.length > 1) {
                lemma_bloodhound.remote.url = url+'/dictionary/ajax/lemma/'+gloss_dataset_id+'/'+languages[0]+'/%QUERY'
            } else {
                lemma_bloodhound.remote.url = url+'/dictionary/ajax/lemma/'+gloss_dataset_id+'/'+languages+'/%QUERY'
            }
        } else {
            $('.lemmatypeahead').prop("disabled", true);
            gloss_dataset_id = null;
        }
    });
});
```

This leads to problem when a user does not have permission to create new glosses. I would like to use this issue for two things:
* Figuring out what this type-ahead code is for in the first place.
* If we still need it, make sure it's not dependent on other (unrelated?) functionality

**Comment by Woseseltops** [comment]
See also #605

**Comment by susanodd** [comment]
The typeahead needs to restrict the pull-down to the selected datasets.

**Comment by susanodd** [comment]
Is there a reason why the document ready function is inside the lemma_typeahead.js file rather than inside the template?

**Comment by susanodd** [comment]
I moved the javascript variable "user_can_add_gloss" to above the import of lemma_typeahead.js so the check is done to avoid executing the problem causing code.

**Comment by susanodd** [comment]
@Woseseltops's tempfix has been replace with a permissions check, if the use can't add a new gloss, don't set up anything:
`    if (!user_can_add_gloss) {
        return;
    }`

**Comment by vanlummelhuizen** [comment]
> Is there a reason why the document ready function is inside the lemma_typeahead.js file rather than inside the template?

@susanodd It is possible to have multiple 'document ready' functions (https://www.quora.com/Can-we-have-multiple-document-ready-functions-in-jQuery-If-yes-then-what-is-the-main-advantage), so since this one has to do with the lemma typeahead, I put it in lemma_typeahead.js.

Above you implemented one of my suggestions in https://github.com/Signbank/Global-signbank/issues/605#issuecomment-563155719. Good!

**Comment by Woseseltops** [comment]
@vanlummelhuizen explained to me that there is in fact a relation between the lemma typeahead and the option to create new glosses: you use this typeahead only when you are creating a new gloss. That makes this issue name weird, so I changed it. And if understand everything correctly I'll close the issue too.
