### ISSUE TITLE
How to reload SB to make new tags/field values available?

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#607]
Just something quick: I used to run https://signbank.science.ru.nl/reload_signbank/ to make new tags available to the user, but now get an error when I do this. (The new tag that is not available yet is "Project: Phonological Spread".)

Is the function broken, or does it work in another way now?

**Comment by Woseseltops** [comment]
I had a quick look at the code, and this is how we used to run things long ago, still on the old Applejack... so this must have been broken for years already ;). 

@vanlummelhuizen perhaps this is good time to move away from the setup with GNU screen and start using a UWSGI .ini file that we touch to restart? I didn't want to use this approach for Signbank initially because I thought restarting took to long and wasn't reliable, but I have been using it for a few other projects and it works perfectly everytime.

**Comment by ocrasborn** [comment]
Haha, @Woseseltops , well, can't be too many years, but more than one I would easily believe.
It's still referred to on the wiki, please adjust there as well: https://github.com/Signbank/Global-signbank/wiki/How-to-add-new-field-choices-to-Signbank

**Comment by ocrasborn** [comment]
In the meantime, @Woseseltops , and that could change the tag from 'blocking' to 'high priority', could you do something quick today such that Hannah can see the new tag value?

**Comment by Woseseltops** [comment]
Sorry missed your question yesterday @ocrasborn , but just reloaded Signbank manually... now it's visible!

**Comment by vanlummelhuizen** [comment]
I made the Tag choice list dynamic so that is not necessary to restart the application when a Tag is added: https://github.com/Signbank/Global-signbank/commit/e8ffbab648dc2b8ae96d3bddd6e338565511d0d6

**Comment by Woseseltops** [comment]
@vanlummelhuizen , the Signbank UWSGI process is now a vassal of the emperor; in case you need to restart all you need to do is touch it. In some cases git pull causes small permission problems for UWSGI, we'll see.

Is the reload functionality, the original cause for this change, still needed?

**Comment by vanlummelhuizen** [comment]
@Woseseltops Since the tag choice list is now dynamically generated, the original reload functionality should not be necessary for this purpose.

**Comment by ocrasborn** [comment]
@Woseseltops @vanlummelhuizen It's good that it's no longer needed for the tags, but are there not other reasons why the system needs to be reloaded? In my memory, we did this now and then when there was a database error or other issues for the user.

**Comment by vanlummelhuizen** [comment]
@Woseseltops I got the permission problems. For now I made them readable for all/others. Let's try to find a better solution.

**Comment by Woseseltops** [comment]
> For now I made them readable for all/others. Let's try to find a better solution.

How about some kind of shortcut that fixes all permissions and then touches the ini that is always available when you're inside the virtualenv, @vanlummelhuizen ?

**Comment by susanodd** [comment]
Some of this should have disappeared with the new Field Choice model? These are all retrieved dynamically.

**Comment by vanlummelhuizen** [comment]
@susanodd  You could try it out, of course. If you don't feel like doing that, just close this because I believe there is no need to reload Signbank to make things show up, that is everything is retrieved dynamically.

**Comment by susanodd** [comment]
Yes, I agree. That was the whole point of the new field choice model!
