### ISSUE TITLE
Make the dataset labels in the header link to each dataset's info page

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#609]
Just a thought: the dataset labels in the header now function to 1) indicate what the user has access to and 2) what is selected and what not. It'd be nice to turn these into hyperlinks that point to the info page for each dataset. E.g. for NGT: https://signbank.science.ru.nl/datasets/detail/5

**Comment by susanodd** [comment]
This has been added.

**Comment by vanlummelhuizen** [comment]
I noticed that the center of the dataset acronym in the label/ribbon was not clickable. I changed it so that the whole label/ribbon is now clickable.
