### ISSUE TITLE
Searching for frequency data

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#61]
Copied from comment in #56:
Done for the detail view, but not for the search page, as we don't have the option to search for frequency (yet?). If we want that, maybe:
1) We should wait for #19 first, as having real data will make testing easier :).
2) We should agree on how it should work first. Searching for signs with exact frequency x doesn't seem that useful to me, so maybe some functionality where you can select 'more than' and 'less than'?

**Comment by vanlummelhuizen** [comment]
@ocrasborn Is this still relevant?

**Comment by ocrasborn** [comment]
Hm. Let's rather make sure that the new way of displaying frequency data dynamically (e.g. #620 ) can be exported, so for any dataset and regardless of the metadata categories involved. I'll close this.
