### ISSUE TITLE
Gloss count on dataset info page is not correct

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#610]
On the info page for each dataset, the gloss count now says "45 public glosses, 31952 total". Please make a count specific for each dataset (listing both public and total glosses like now).

**Comment by susanodd** [comment]
This has been fixed.

**Comment by susanodd** [comment]
@ocrasborn, on the Available datasets page, do you want only the publicly available shown to anonymous users? (i.e., is it private information to know how many total glosses there are?)

**Comment by ocrasborn** [comment]
Hi @susanodd : No, it's not private how many glosses there are, so the way it currently is after your fix of Feb 7 is just fine. I think we can therefore close this issue, right?

**Comment by susanodd** [comment]
Okay.
