### ISSUE TITLE
Add columns to the page Select Dataset

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#611]
On the Select Dataset page, there's now the Acronym and Name of each dataset. Let's use this page to remind users of what the dataset is and what the copyright conditions are, by adding the fields Description and Copyright in two more columns.

**Comment by susanodd** [comment]
This has been pushed to github.

**Comment by ocrasborn** [comment]
Thanks @susanodd !

**Comment by Woseseltops** [comment]
I'm interpreting Onno's gratitude as satisfaction.
