### ISSUE TITLE
Add a USE_HANDSHAPE setting

### ISSUE THREAD

**Issue by Woseseltops** [Signbank/Global-signbank#616]
The ASL Signbank doesn't use our handshape functionality. We might as well encode this is a setting, just as wel do with datasets. When this setting is set to False:
* All handshape related tests should automatically be skipped (or at least not fail) somehow.
* The handshape UI should be hidden in the detail view. Right now, the UI is already hidden for the ASL users... figure out how this works and rewire.

**Comment by ocrasborn** [comment]
Let me ask Julie whether or not she would like to start using the handshapes, OK? Will come back to this.

**Comment by ocrasborn** [comment]
That's good!
After our meeting two weeks again, in fact the ASL users got excited about the handshapes functionality again :-), so could you set the setting to True now for ASL, and include it in the next update? After that, issue can be closed.

**Comment by susanodd** [comment]
This might be obsolete now?
