### ISSUE TITLE
Unit test test_frequency_sorting takes language name from the settings

### ISSUE THREAD

**Issue by Woseseltops** [Signbank/Global-signbank#618]
The test test_frequency_sorting queries field choices for a field that is generated by taking the adjective form of default language (as specified in the settings), and glueing '_name' to it. If the default is English, it will query for the 'english_name' field. However, the default language does not necessarily have to have a corresponding field in the FieldChoice object, and this test will end in an error if this is the case.

**Comment by susanodd** [comment]
This has been fixed.

**Comment by Woseseltops** [comment]
But how about this setting FALLBACK_FIELDCHOICE_HUMAN_LANGUAGE ... should it be added to default settings?

**Comment by susanodd** [comment]
This was already in the default settings, that's why I used it.

**Comment by Woseseltops** [comment]
Ah okay thanks.
