### ISSUE TITLE
Allow for Dataset Managers to upload EAF files (and upload updates)

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#619]
* This is extracted from #354 , which has focused on the visualisation
* We still need a way for Dataset Managers of each dataset to provide the source annotations from which frequencies can be calculated. Annotations will be in EAF format, in the tiers that have 'gloss' or 'Gloss' as Type
* My suggestion would be to keep this simple, in the sense of allowing an upload functionality, but not a whole interface for viewing which EAF files are already there, selecting ones to delete, selecting ones to update, etc. New uploads should simply replace EAF files with the same name.
* Store these on the server in subfolders similarly to how the videos and images are now organised.

**Comment by susanodd** [comment]
This has been pushed to github.

**Comment by susanodd** [comment]
I revised the layout of the Dataset Manager page (#632) so that the Metadata (#620) and EAF files management is in columns to the right of user management. This has been pushed to github.

**Comment by ocrasborn** [comment]
Great @susanodd , what a difference to the eye!
