### ISSUE TITLE
Adapt the script that calculates frequencies on the basis of EAF files

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#621]
* For the Corpus NGT, we distinguish GlossL from GlossR in tier names, depending on whether the sign is made with the right hand or the left hand. Two-handed signs get two glosses, and the current script has a metric for deciding when a sign is counted as one-handed and when as two-handed: it's not a raw count of all annotations on Tiers with Type = gloss.
* Most other datasets will only have one tier for both one-handed and two-handed glosses.
* We can be prescriptive to Dataset Managers on the naming of their EAF files, but would still like to allow for one-tier and two-tier annotations of a signer. So, proposal: adapt the script in such a way that iff the file contains tier names starting with GlossL and GlossR, the present method for calculating frequencies is used, and otherwise use raw frequencies of all tiers with Type = gloss.

**Comment by vanlummelhuizen** [comment]
@ocrasborn Do you have an example EAF for me to test?

**Comment by ocrasborn** [comment]
@vanlummelhuizen I'll email a zip

**Comment by vanlummelhuizen** [comment]
@ocrasborn I cannot find any email with a zip in my email. What do we do with this issue?

**Comment by ocrasborn** [comment]
Coming up shortly in your inbox @vanlummelhuizen !

**Comment by vanlummelhuizen** [comment]
@ocrasborn From our email correspondence on June 16 2022 I conclude that the script already did what you wanted. Therefore, it seems this issue can be closed. Agreed?
