### ISSUE TITLE
Registration is broken

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#622]
When I try to register a new account, I get a django error page:

Request Method: | POST
-- | --
https://signbank.science.ru.nl/accounts/register/
1.11
SMTPServerDisconnected
Connection unexpectedly closed
/usr/lib/python3.5/smtplib.py in getreply, line 393
/usr/bin/uwsgi
3.5.2
['.',  '',  '/var/www/signbank/live/sb-env/lib/python35.zip',  '/var/www/signbank/live/sb-env/lib/python3.5',  '/var/www/signbank/live/sb-env/lib/python3.5/plat-x86_64-linux-gnu',  '/var/www/signbank/live/sb-env/lib/python3.5/lib-dynload',  '/usr/lib/python3.5',  '/usr/lib/python3.5/plat-x86_64-linux-gnu',  '/var/www/signbank/live/sb-env/lib/python3.5/site-packages',  '/var/www/signbank/live/sb-env/lib/python3.5/site-packages/CNGT_scripts/python']
Thu, 13 Feb 2020 14:47:20 +0100

**Comment by ocrasborn** [comment]
Addition: reset password also seems broken; likely related? If not, please create a separate issue.

**Comment by susanodd** [comment]
should that be signbank.cls.ru.nl ?

**Comment by ocrasborn** [comment]
Both work, until now; I'm now putting links on webpages and in emails I send out to signbank.cls.ru.nl.

**Comment by Woseseltops** [comment]
We also need a test to check if this functionality is still working.

**Comment by vanlummelhuizen** [comment]
Perhaps the config of the Postfix (smtp mail) server changed recently, as another user of the server suggested, causing this. Let's await what comes out of his question/complaint to the administrators.

**Comment by vanlummelhuizen** [comment]
I got a reply from the administrators that they restarted Postfix. I just tested whether registration works and I correctly got an email asking me to confirm my registration. So, this is fixed.
