### ISSUE TITLE
Show frequencies in 'Exclude field choices for datasets'

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#625]
In the list of field choices to hide (under Dataset > Dataset Management > button Exclude...), the machine values are shown between brackets after the values. These have little value (sorry for the pun) for the Dataset Manager, but showing the frequencies for the datasets that the manager has management rights over would be really helpful here! Please show those, perhaps best between square brackets just like for the field value frequencies in the pull-down menus in the detail view.

**Comment by susanodd** [comment]
The code showing the machine value is actually in the default display __str__ method of class FieldChoice.

**Comment by susanodd** [comment]
I've got this working now. I've added panels per field choice category to reduce the length of the display.

**Comment by vanlummelhuizen** [comment]
@ocrasborn This is live now.

**Comment by ocrasborn** [comment]
@vanlummelhuizen : not sure if related, but I can't load the dataset pages at all right now, get an error.

**Comment by vanlummelhuizen** [comment]
It should work again. Let me know if not.

Explanation: when putting new code live, the file permission are not correct anymore. I forgot some template files.

**Comment by ocrasborn** [comment]
It works, and it's cool @susanodd ! I like the visual effect upon clicking the buttons, they have a subtle flashy way of displaying the fields.
One visual thing though: the content of the columns are not aligned with the headers of the columns (on Mac/Safari; all good on Mac/Chrome and Mac/Firefox)...

**Comment by susanodd** [comment]
Okay, I'll need to see what that is.
See if you need the frequencies split across the managed (selected) datasets.

**Comment by vanlummelhuizen** [comment]
@ocrasborn Just don't Safari. ;)

**Comment by ocrasborn** [comment]
@susanodd : no need to split the frequencies! Just fine like it is.
@vanlummelhuizen : I know I know...

**Comment by ocrasborn** [comment]
I see that also in Safari columns are now nicely aligned, well-done @susanodd and/or @vanlummelhuizen
