### ISSUE TITLE
Allow .mov file format in the video upload dialog

### ISSUE THREAD

**Issue by Woseseltops** [Signbank/Global-signbank#627]
Right now it only allows mp4:

```html
<input type="file" name="videofile" accept="video/mp4" required="" id="id_videofile">
```

This causes .mov files to not be selectable by default, as seen in these screenshots by Julie:

![image](https://user-images.githubusercontent.com/1909317/75329871-bab98500-5880-11ea-9de7-a3d75d9d723b.png)
![image](https://user-images.githubusercontent.com/1909317/75329883-bee5a280-5880-11ea-8db4-ca714aea0498.png)
![image](https://user-images.githubusercontent.com/1909317/75329890-c147fc80-5880-11ea-9336-5750f2fd9bae.png)

If I'm not mistaken, .mov files are converted to mp4 automatically by Signbank.

**Comment by ocrasborn** [comment]
Ah, that would be nice for Global Signbank as well @Woseseltops

**Comment by vanlummelhuizen** [comment]
I have looked into this. There is some unused code for this purpose, but I could not make it work yet.

**Comment by vanlummelhuizen** [comment]
Uploaded .mov files are now also accepted and automatically converted to .mp4.

**Comment by Woseseltops** [comment]
Looks like they are no longer accepted agian. @Jetske , can you look into this?

**Comment by susanodd** [comment]
There is a problem with the encoding (CNGT script) that does not work correctly for QuickTime files. That has been broken for a long time. (See the other video upload issues.)

**Comment by Jetske** [comment]
There is still the same problem that sporadically random characters are added behind the name the video is supposed to have, in which case an error occurs as it cannot find the video

**Comment by Jetske** [comment]
I think this may be why it adds the characters: it tries to save a video with a name that already exists in the file location. So I hope first making the history (convert old video to .bak file) before saving the new video helps to make that work better.

**Comment by vanlummelhuizen** [comment]
I tested this (branch allow_mov_627) and it all seems to work. Shall we deploy and test on the live server?

**Comment by Jetske** [comment]
@vanlummelhuizen thanks, yes then I agree we can deploy it!

**Comment by vanlummelhuizen** [comment]
@Jetske I deployed just now. I also tested what happens if you add another video to a example sentence and that also seems to work. 

The only thing  is that the browser loads the video from cache, so that  the new video is not shown. This is probably caused by the fact that the new video gets the same name (e.g. 14.mp4) as the old video. 

We might need to reconsider this method of replacing video files on the system.

**Comment by susanodd** [comment]
@vanlummelhuizen Is this issue completed, or do you want to rename the issue as per reloading as you describe? 
(I think this happens more places when reloading.)

**Comment by susanodd** [comment]
On the live server there are sentence videos existing not inside the subdirectories for datasets. They were created before the subdirectory structure was added.
But they exist inside the video data structure so exist with the original pathname as such without the dataset in the pathname.
I.e. sensevideos/1.mp4
These need to be creatively moved and the links to them creatively fixed.

**Comment by susanodd** [comment]
See #1022

**Comment by vanlummelhuizen** [comment]
> @vanlummelhuizen Is this issue completed, or do you want to rename the issue as per reloading as you describe?
> (I think this happens more places when reloading.)

Probably better to make a new, clean issue for that. I will do so later today.

**Comment by vanlummelhuizen** [comment]
> On the live server there are sentence videos existing not inside the subdirectories for datasets. They were created before the subdirectory structure was added.
> But they exist inside the video data structure so exist with the original pathname as such without the dataset in the pathname.
> I.e. sensevideo/1.mp4
> These need to be creatively moved and the links to them creatively fixed. (Recall that Django stores paths inside File data…)

There are 4 files in `sensevideo/` that are also in an ExampleVideo object. We probably can fix this by hand. Use `ExampleVideo.objects.filter(videofile="sensevideo/1.mp4").first().examplesentence.senseexamplesentence_set.first().sense.glosssense_set.first().gloss.dataset.acronym` to get the dataset acronym. 

I will also do this later today.

**Comment by vanlummelhuizen** [comment]
> Probably better to make a new, clean issue for that. I will do so later today.

Done: #1065

**Comment by vanlummelhuizen** [comment]
> I will also do this later today.

Done.
