### ISSUE TITLE
Reduce the number of clicks necessary for entering new (phonology) data

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#628]
E.g., could we have the 'OK' buttons also respond to return on the keyboard?

**Comment by vanlummelhuizen** [comment]
@ocrasborn Where exactly do you want this? 

I added a new Gloss and then edited some phonology field. All fields other than the dropdown lists were listening to enter as if the user was clicking the OK button.

**Comment by ocrasborn** [comment]
Can confirm that on my computer, we clearly didn't test enough.
What doesn't work on my mac what would really help, is moving to the next field in the same panel. Would that be possible to set up?

**Comment by vanlummelhuizen** [comment]
It should be feasible.

**Comment by ocrasborn** [comment]
:-) :-)

**Comment by susanodd** [comment]
@vanlummelhuizen what do you mean by "listening"?
It opens in Edit mode after a gloss is created. Should it not open in Edit mode?

**Comment by vanlummelhuizen** [comment]
@susanodd What I meant was that if you are editing e.g. a phonology field (one that is not a dropdown list) pressing enter has the same effect as clicking OK.

**Comment by Woseseltops** [comment]
This issue is similar to #140

**Comment by susanodd** [comment]
To my surprise, the arrow keys step through the menu lists.
But yeah, return doesn't seem to do anything.
Could we make it so horizontal arrows stay on the choices of the same field and vertical arrows go up and down between fields?

**Comment by susanodd** [comment]
Oh, I googled. It looks like perhaps we can put numbers on the identifiers to coerce navigation to iterate through them as sequenced.
Then the point of @vanlummelhuizen relates to that, since we want to keep shifting the focus on the next active in sequence, based on what arrow the user touches. (Instead of having them all be active at once.)

**Comment by vanlummelhuizen** [comment]
@susanodd Perhaps good to know: the default way to navigate to the next field in a form is by hitting the Tab key. And Shift-Tab for navigating to the previous field.

**Comment by ocrasborn** [comment]
The arrows to move in a pull-down menu and the enter to confirm and save are very useful. What would still be nice is if tab (or any other key) would jump to (=activate, select) the next pull-downmenu (esp. in phonology, which is what is edited most and contains most fields). Using tab now just jumps to the next text field in the whole window.

**Comment by susanodd** [comment]
This is kind of working now!

I can walked through all of the phonology fields, with it automatically going to the next after hitting OK.
However, once in a while it stops and I have to do another field modification to get it going again.

I've been working on it for the Morpheme view so as now to mess up other interfaces.

**Comment by susanodd** [comment]
I implemented this for Morpheme Detail View.
As usual, you can press arrow keys to go through the lists.
When you type OK or Return, you jump to the next list / phonology field.

**Comment by susanodd** [comment]
If you notice some glitches using this, I'm revising the javascript so it works with the other fields. Also related to #669.

**Comment by susanodd** [comment]
This still hasn't been put on the live server.

**Comment by Woseseltops** [comment]
Did a pull this morning!

**Comment by susanodd** [comment]
Thanks!

**Comment by Woseseltops** [comment]
The Norwegian users (of the Global Signbank) report that tabbing no longer works, can this be fixed?

**Comment by susanodd** [comment]
I hadn't realised it was the Tab key. It's implemented using the Return key. So when a phonology field is in focus, hitting Return advances to the next phonology field.

**Comment by ocrasborn** [comment]
Thanks @susanodd , not a bug then, but a feature that needs more attention in the manual :-)

**Comment by Woseseltops** [comment]
I'm guessing this can be closed then :)
