### ISSUE TITLE
For some NTS signs, no images are generated

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#629]
e.g. https://signbank.science.ru.nl/dictionary/gloss/36422/

**Comment by vanlummelhuizen** [comment]
@ocrasborn The video of example you gave was uploaded on may 30, 2019. I don't think I can find what happened back then. 

Can you give a more recently uploaded example? Or describe what you or someone else did recently that resulted in images not being generated?

**Comment by ocrasborn** [comment]
Hm. Just created onnotest with the movie I downloaded from the link below, and it works. They thought it was related to the format of the movies perhaps, coming from another site. Perhaps we had an issue on the day they created those. I'll have them test some more.

**Comment by ocrasborn** [comment]
Can't reproduce, going fine now.
