### ISSUE TITLE
On the Select Dataset page, add 'Select all' and 'Select none' buttons

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#631]
to the left or to the right of the button at the bottom of the page, I'd suggest.

**Comment by susanodd** [comment]
@ocrasborn, do you want this to merely be in the interface?

At the moment, the (legacy) logic is that if the user does not select any datasets, then this defaults to the user being shown all "viewable" datasets the user has permission to view.
(For yourself, you can check this out: if you deselect everything and then "Save selection", all the datasets become highlighted in the header.)

(In the legacy code, we has some reason for doing it this way when datasets were introduced.)

Q: Do you want this functionality to remain, or you actually want "no datasets selected"?


For anonymous users, no datasets are shown in the header. The selected dataset functionality reduces to any public datasets, or if there aren't any, the default dataset. (Elsewhere the anonymous user can only see public glosses.)


Q: The question is, What does nothing selected mean? Should it be the same behaviour as now? Or do you want nothing selected to be nothing selected. (Then some other functionality will require the user to select datasets first.)

**Comment by ocrasborn** [comment]
I remember the earlier logic, yes; this can stay as far as I'm concerned. (So if nothing is selected, all are shown that the user has access to.) The reason to ask for these extra buttons: It's just that for me, having access to many datasets (and expecting more in the future), it's a lot of clicking now to select or unselect all. In practice, I will never "Select none" and then confirm, but I first clear the list where multiple would be selected, and then go on to select one or a few by selecting the checkboxes in the list.

**Comment by susanodd** [comment]
This has been pushed to github.

**Comment by vanlummelhuizen** [comment]
@ocrasborn it's live.

**Comment by ocrasborn** [comment]
Thank you!
