### ISSUE TITLE
Uploading images to a gloss without a video leads to error

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#633]
Donovan: Has anyone had issues trying to upload images to ASL Signbank lately? When adding in new sign entries today and trying to upload an image, an error message comes up (attached here). There does not appear to be any issues uploading videos, just images (tried in several different browsers and image formats, all with the same result).

**Comment by ocrasborn** [comment]
Onno: Just tested it myself. Uploading an image for wesseltest3 leads to the same error, but when I first upload a video, I can then upload the same test image without a glitch. I’ll add it to the to-do list for next week, but please let us know how urgent it is (i.e. would you want an immediate system update to fix this, or can it wait until some other things have also been completed?).

**Comment by ocrasborn** [comment]
Wessel in an email to Julie, 26 Feb: 3. Uploading images does not work for the 'BIT' gloss. 
I just tried and it worked for me. However, the error page you included suggests that there was a problem related to the video not being found, and we indeed changed the video system under te hood. Could it be the case that you tried to upload the image when the video was not yet there?

**Comment by vanlummelhuizen** [comment]
@ocrasborn @Woseseltops I fixed this. See https://signbank.science.ru.nl/dictionary/gloss/37052.

**Comment by ocrasborn** [comment]
Great! Should we keep this issue open until we've updated ASL signbank? Is that what the 'tbc ...' tag is for, which i've just added? Just checking, @Woseseltops

**Comment by Woseseltops** [comment]
> Is that what the 'tbc ...' tag is for, which i've just added?

Correct... but I've just manually added the fix by @vanlummelhuizen because already two team members mentioned it now :) .
