### ISSUE TITLE
Error in admin when searching in Glossvideo

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#635]
When I try to search for a gloss in https://signbank.science.ru.nl/admin/video/glossvideo/, whatever substring I type in, I get an error
(I'm trying to find out why I cannot upload a video to https://signbank.science.ru.nl/dictionary/gloss/36546/, get an error there. Deleted the media in writable, now seeing whether it helps to delete the record in glossvideo, but can't because of this bug)

**Comment by vanlummelhuizen** [comment]
@ocrasborn It works again.

**Comment by ocrasborn** [comment]
thanks @vanlummelhuizen
