### ISSUE TITLE
Add menu item Show all morphemes

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#637]
To make the Signs menu more consistent. It should display the list view for morphemes with all morphemes there (of course).

**Comment by susanodd** [comment]
At the moment, this menu item is unpublished on Global, until the code to support is put on the live server.

**Comment by susanodd** [comment]
This is live now.

**Comment by susanodd** [comment]
This is live except for the repair to count.

(At the time of writing, the count on the live server is not restricted to selected datasets. That has been fixed.)
