### ISSUE TITLE
Change the list of phonological fields for Morphemes

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#638]
For Morphemes, we need a subset of the fields that we are using for Signs. In the detail and list view for morphemes, please hide the following: [list needs to be double-checked by Inge before I make it high-priority, OC]
- Strong hand
- Weak hand
- Mouth gesture
- Mouthing
- Phonetic variation
- Strong hand letter
- Strong hand number
- Weak hand letter
- Weak hand number
- Weak drop
- Weak prop

**Comment by susanodd** [comment]
This is best done with a separate setting for morpheme phonology. As it is, the phonology fields are retrieved from the setting for phonology.

**Comment by susanodd** [comment]
Since the objects overlap with Gloss objects, and we also have users hiding fields, I'll make a new display setting.

**Comment by susanodd** [comment]
I also hid the empty fields from display. They appear when you edit the morpheme.

**Comment by susanodd** [comment]
It's not clear to me what I should do with ASL for this setting. I made an empty setting.

**Comment by susanodd** [comment]
@ocrasborn, regarding the hiding of Strong Hand and Weak Hand, ...
On the main Search page, one can choose "Sign or morpheme" for the search.
The fields Strong Hand and Weak Hand are in the results table.
Shall the search option "Sign or morpheme" be removed?

Furthuremore, Morpheme is a subclass of Gloss in the model.
Should they diverge?

I've used a settings for the morpheme phonology, so they are hidden in the Detail View.
(@Woseseltops, @vanlummelhuizen, your input is welcome.)

**Comment by Woseseltops** [comment]
I think your solution, with a separate setting for which phonology fields to use for morphemes (as opposed to glosses), is the best one, @susanodd .

> Furthuremore, Morpheme is a subclass of Gloss in the model.
Should they diverge?

I think the number of similarities between glosses and morphemes is still greater than the number of differences... right?

**Comment by susanodd** [comment]
Yes. But now some fields of Gloss will not be used. And there are additional fields for the subclass Morpheme.
So these extra fields will show up as empty columns for glosses in the Gloss table.

**Comment by vanlummelhuizen** [comment]
Sounds like the concept of abstract base classes would apply here (https://docs.djangoproject.com/en/3.0/topics/db/models/#abstract-base-classes).

**Comment by Woseseltops** [comment]
Agreed @vanlummelhuizen , good suggestion. What would be a good name for such an abstract base class? Sign?

**Comment by susanodd** [comment]
Are you proposing Sign as an Abstract model above Gloss and above Morpheme, with the common fields they share?
The morpheme phonology will include some handshape fields (#639).

**Comment by vanlummelhuizen** [comment]
Perhaps AbstractSign? Sign sounds very concrete to me. Or is that to much my developer mind speaking? Is the user ever going to deal with this abstract model directly?

**Comment by susanodd** [comment]
Q (still not answered): Do we (still) want morphemes and glosses displayed in the same (Gloss) list?
Since e.g., fields Strong hand, Weak hand are not available for Morpheme editing, any data that gets displayed for these (because of sub classing) is legacy data.

**Comment by susanodd** [comment]
This is live. (Except still waiting for #669 to be put live.)

**Comment by susanodd** [comment]
This is live.
