### ISSUE TITLE
Enable handshape features in the phonological specification of a morpheme

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#639]
* This is part 2 of changing the Morpheme phonology; #638 is part 1
* Rather than having a specific strong hand or weak hand, Morphemes may include sub-features of handshapes in their phonological specification. We now have a separate handshape table where some of these features are used. We need the following fields (field values to be edited in the admin like for other fields), which partly overlap with handshape features, partly not:
- Selected Fingers [list of values]
- Aperture [list of values]
- Finger Configuration
- Finger Spreading
- Internal movement

[Field list yet to be finalised with Inge, OC]

**Comment by susanodd** [comment]
I can work on this if the field list is available.

**Comment by susanodd** [comment]
This has been silent for a long time awaiting input. I'll close it for now.
