### ISSUE TITLE
Add Django command that prefills the database 

### ISSUE THREAD

**Issue by Woseseltops** [Signbank/Global-signbank#641]
I want to go 'python bin/develop.py prefill-db' or something like that, and then a process will check if the database is in the correct place (and if not: give instructions on what is probably going wrong), and if so start an interactive process that will guide me through the creation of things like:
* Translation languages
* The first dataset (link to translation languages and also adjust settings file)
* A dataset manager group, and perhaps some other logical groups like 'guest' and 'editor'
* Initial pages (adding a new gloss, searching, showing all signs)
* A superuser
* Interface languages; run the sync_translation_fields command so Django-model-translation makes the database aware of them.

**Comment by ocrasborn** [comment]
Good idea @Woseseltops !

**Comment by Woseseltops** [comment]
Made a start with the dialogue. Not finished yet, and it does nothing yet.

**Comment by Woseseltops** [comment]
@ocrasborn mentioned in another issue that we also want to use this tool to include field choices. How would that work, @ocrasborn ? Are current field choices in Global Signbank a good set to start with for everybody, or would there be something of a basic set of choices that everybody wants, and then we ask 'do you also want field choices for this, field choices for that, etc'? 

And perhaps the same for hand shapes?

**Comment by Woseseltops** [comment]
Okay the dialogue is finished (minus the question for @ocrasborn , which is still open). Will actually implement the functionality once I can go back to my desk at the RU again, because I can more easily install new versions of Signbank there.

**Comment by ocrasborn** [comment]
Ah, right, missed that @Woseseltops . My idea was to include all of Global Signbank's field choices for a new database, as that will speed up the learning curve for new managers of a new system, and it will be much less work for them deleting values (or fields) than creating them on the basis of our system or the user manual we've created.

**Comment by Woseseltops** [comment]
To do:
* Ask user to prefill field choices
* Ask user to set up a writable folder, which contains a glossvideo folder, a glossimage folder, an ecv folder, a logs folder, an othermedia folder and a packages folder.

**Comment by ocrasborn** [comment]
@Woseseltops , please also include #656 here: pre-fill database with groups and related permissions from Global

**Comment by Woseseltops** [comment]
This is what I currently have in the category user management, @ocrasborn : 

```
Name of the superuser: wessel
Password of the superuser:
Superuser wessel created

Create a user group for users that can edit the content in Signbank? [y/n]: y
Name of this group (leave blank for 'Editor'):
Group Editor created

Create a user group for users with only reading permissions? [y/n]: y
Name of this group (leave blank for 'Guest'):
Group Guest created
``` 

Is this what you mean? Do you want to extend this?

**Comment by ocrasborn** [comment]
Exactly what I mean, yes @Woseseltops . We do have a distinction between Guests and Researchers though, but to be honest I forgot what the difference in permissions is. Possibly only the CSV export button? It'd be good to create that distinction between Guest/Researcher at least for this one permission.
The distinction between Editor and Publisher is also small, but it would be good I think to create a distinction between people who can edit content in the web interface (Editors), and people who in addition can access the Django admin (Publishers). So please add that distinction as well.

**Comment by Woseseltops** [comment]
Note to self, we also need to ask if the user wants to use the registration options, and then do `CREATE TABLE "registration_registrationprofile" ("id" integer NOT NULL PRIMARY KEY, "user_id" integer NOT NULL UNIQUE, "activation_key" varchar(40) NOT NULL);`

**Comment by Woseseltops** [comment]
What I have right now

```Name of the superuser: wessel
Password of the superuser:
Superuser wessel created

Create a user group for users that can edit the pages and signs in Signbank? [y/n]: y
Name of this group (leave blank for 'Publisher'):
Group Publisher created

Create a user group for users that can edit signs but not pages in Signbank? [y/n]: y
Name of this group (leave blank for 'Editor'):
Group Editor created

Create a user group for users with only reading permissions? [y/n]: y
Name of this group (leave blank for 'Guest'):
Group Guest created

Create a user group for users with reading and export permissions? [y/n]: y
Name of this group (leave blank for 'Researcher'):
Group Researcher created

The registration functionality requires an extra table in the database. Do want to add this table? [y/n]: y
Registration profile table created
```

**Comment by Woseseltops** [comment]
Also good to add here: check if postfix is installed, check if ImageMagick is installed.

**Comment by susanodd** [comment]
This can probably be closed. This is not actually possible since the migrations can't be applied starting from 0 after the field choices were done since original fields were deleted.
