### ISSUE TITLE
Problem with linking videos

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#642]
We started working with dataset ZEI, which has Farsi and English as description languages. Some problems, possibly related:
* I can batch upload videos, but they do not the preview image & cannot be played
* If I look in glossvideo/ZEI/, the subfolders are all named ????; which I reckon is Ponyland's way of telling me they are all in Farsi script? But why would that be, doesn't the system always take the (default/obligatory) English glosses to create subfolder names?
* No images are generated from the batch upload either

**Comment by ocrasborn** [comment]
Not sure if you're working on it at the moment, but now my videos do play back :-) I do constantly get 'closed database' errors though, in the last fifteen minutes

**Comment by Woseseltops** [comment]
So the problem fixed itself? Weird.

About the closed database: we've had that before and didn't solve it #335 #441 . I've restarted apache and uwsgi to be sure, but in the past that did not help.

**Comment by ocrasborn** [comment]
@Woseseltops : practically, uploading work now it seems, but could you double-check what the situation is with the file and folder names for ZEI? If I rsync the uploaded videos back to my mac, I can see interesting file names that are mix of Farsi script (right-to-left) and alphanumeric (left-to-right). Could this be related to why images are not generated for these new videos (as that is one issue noted above that is not yet addressed).

**Comment by ocrasborn** [comment]
@Woseseltops I tested creating a new sign in dataset NGT (TESTIMAGECREATE), uploaded a ZEI movie, but likewise no image is generated.

**Comment by Woseseltops** [comment]
Outcome of my investigation:
* Indeed, the Farsi characters are treated as normal characters, and the whole mechanic where the video files are divided into folders named after the first two characters still works:

```
drwxrws---+  2 wapsignbank wwwsignbank 4.0K Apr  7 11:00 ار
drwxrws---+  2 wapsignbank wwwsignbank 4.0K Apr  7 11:00 ان
drwxrws---+  2 wapsignbank wwwsignbank 4.0K Apr  7 11:00 جو
drwxrws---+  2 wapsignbank wwwsignbank 4.0K Apr  7 11:00 خی
drwxrws---+  2 wapsignbank wwwsignbank 4.0K Apr  7 11:00 خر
drwxrws---+  2 wapsignbank wwwsignbank 4.0K Apr  7 11:00 سی
drwxrws---+  2 wapsignbank wwwsignbank 4.0K Apr  7 11:00 سگ
drwxrws---+  2 wapsignbank wwwsignbank 4.0K Apr  7 11:00 شی
drwxrws---+  2 wapsignbank wwwsignbank 4.0K Apr  7 11:00 گا
drwxrws---+  2 wapsignbank wwwsignbank 4.0K Apr  7 11:00 گر
drwxrws---+  2 wapsignbank wwwsignbank 4.0K Apr  7 11:00 گل
drwxrws---+  2 wapsignbank wwwsignbank 4.0K Apr  7 11:00 گو
drwxrws---+  2 wapsignbank wwwsignbank 4.0K Apr  7 11:14 می
drwxrws---+  2 wapsignbank wwwsignbank 4.0K Apr  7 11:00 مر
drwxrws---+  2 wapsignbank wwwsignbank 4.0K Apr  7 11:00 مو
```

* When these characters are there, operating systems try to display (part of) the names from right to left, which on the Linux command line leads to things like: `small.mv4_گوسفند-37110' where I would have expected `37110-گوسفند_small.mv4` . I believe this is only a matter of displaying things, though, not of the underlying system. Even weirder is that Farsi is written from left to right, if I'm not mistaken, so perhaps the operating systems are thinking that this is Arabic?

* I get no images for any video whatsoever, unrelated to the previous two points. I found a permission problem with the tmp dir in the logs... next time I have time to work on this I'm going to try changing the TMP_DIR setting:

```IOError:  [Errno 13] Permission denied: '/tmp/signbank-ExtractMiddleFrame/wesseltest6-37005.m
p4-frames'```

**Comment by ocrasborn** [comment]
@Woseseltops No, Farsi (=Persian) is written right-to-left, so that explains part of it. See also https://www.w3.org/International/questions/qa-html-dir

**Comment by Woseseltops** [comment]
> No, Farsi (=Persian) is written right-to-left

Looked it up, you are right :)

> next time I have time to work on this I'm going to try changing the TMP_DIR setting:

Done that, that seems to fix it.

**Comment by vanlummelhuizen** [comment]
@ocrasborn I created a new button in the Edit mode of the Detail view. It creates a citation form image from the current video. Useful if creating an image failed for some reason. Could you please try it and comment? You will find it somewhere below the video in Edit mode.
