### ISSUE TITLE
Catalan: "attempt to write a readonly database"

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#644]
The Dataset Selection page loads OK, but when I try to confirm changes the error includes "attempt to write a readonly database"

**Comment by ocrasborn** [comment]
Addition: same error when I try to create a new sign. Page loads OK, but clicking to confirm leads to this message.

**Comment by Woseseltops** [comment]
Ai yeah sorry, when creating a backup for the issue with the interface languages, I apparently messed up the permissions. Fixed now!
