### ISSUE TITLE
Catalan: list view for handshapes doesn't list much

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#646]
On the Search Handshape page (which is the way to get to the list view for all handshapes), the phonology columns 3-9) don't list any value, whereas in the detail page for handshapes, there's almost always something there (at least for column 3-4-7).

**Comment by ocrasborn** [comment]
Also, the images don't display, presumably because they are not there. Could you copy these for the remaining records (I deleted some) from Global SB?

**Comment by Woseseltops** [comment]
> Also, the images don't display, presumably because they are not there. Could you copy these for the remaining records (I deleted some) from Global SB? (Yeah sorry I know, putting two issues in one...)

This is done already. Sorry, didn't notice there were images!

**Comment by Woseseltops** [comment]
> On the Search Handshape page (which is the way to get to the list view for all handshapes), the phonology columns 3-9) don't list any value, whereas in the detail page for handshapes, there's almost always something there (at least for column 3-4-7).

This was caused by the lack of handshapes, so #647
