### ISSUE TITLE
Catalan: cannot upload video

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#649]
* Error: ImportError at /video/upload/. No module named 'CNGT_scripts'
* Wasn't there already a test for this? Or is the test not complete?

**Comment by ocrasborn** [comment]
Adding an image works fine

**Comment by vanlummelhuizen** [comment]
I installed the CNGT_scripts module, ffmpeg and ImageMagick. I also added `FFMPEG_PROGRAM = "ffmpeg"` to server_specific.py. Now it all works again.
