### ISSUE TITLE
Catalan: Some problems with adding morphology

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#653]
When editing the Morphology for a sign:
1. I can successfully add blend glosses. Yeah!
2. I cannot add morphemes: the one morpheme I created (niks/nada) is not read from the list of morphemes, I cannot select it. Simply typing it in and clicking add leads to an error (like I would expect)
3. I can select a gloss for adding as a Compound part, but then clicking add leads to an error.

**Comment by vanlummelhuizen** [comment]
I pulled the latest code from Git. Now it seems to work again.

**Comment by ocrasborn** [comment]
ah good!
