### ISSUE TITLE
Create more readable URLs for dataset info pages

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#662]
We find that dataset managers start to want to refer to their dataset in publications. It'd be good to have URLs for this that are a bit more descriptive, linking to the dataset info pages. Right now we have things like https://signbank.science.ru.nl/datasets/detail/2, it'd be nice if we could have instead https://signbank.science.ru.nl/datasets/[acronym], so in this example https://signbank.science.ru.nl/datasets/Kata_Kolok.

**Comment by vanlummelhuizen** [comment]
https://github.com/Signbank/Global-signbank/commit/963ae53d261dfd9ef2ff89672a6f7bed6eaca3bf

I added another view that calls the DatasetDetailView. This way the old url setup is still active, so nothing breaks. I did change the url in the links of the datasets in the top bar. I can do that in other places too if you want, e.g. https://signbank.science.ru.nl/datasets/available.

**Comment by ocrasborn** [comment]
Excellent @vanlummelhuizen ! Yes, please do refer to that new view on the three pages under the Dataset menu as well, to make things consistent for the user.

**Comment by vanlummelhuizen** [comment]
OK, done. See also #666

**Comment by ocrasborn** [comment]
:-)
