### ISSUE TITLE
"Permission error" when trying to open any detail view

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#663]
Got two reports of this, same on my computer, also with all datasets selected.

**Comment by vanlummelhuizen** [comment]
Yesterday, @Woseseltops put some new stuff live, but in the process some files turned out not to be readable by the server user that runs the web app. Unfortunately, Wessel does not work today and I don't have permission to solve the problem. There are two options:

1. Wait until tomorrow when Wessel works
2. Ask the big guns to flex their muscles and help us out. That is ask C&CZ.

**Comment by ocrasborn** [comment]
Hi @vanlummelhuizen , we can wait until tomorrow, but thanks for thinking along. For the future, could something be done to give you the same rights as @Woseseltops in this matter?

**Comment by ocrasborn** [comment]
oh, @vanlummelhuizen , for today, could we put up a temporary page instead of the site saying 'Under maintenance, back up again in the course of June 26"? I can add that to the home page, but then not everyone will see it.

**Comment by vanlummelhuizen** [comment]
I rather ask C&CZ. If I give them a command they can copy and paste, they probably won't mind.

**Comment by ocrasborn** [comment]
OK!

**Comment by vanlummelhuizen** [comment]
Solved. @Woseseltops we need to fix this for the future.

**Comment by ocrasborn** [comment]
So should we leave this issue open for now, @vanlummelhuizen ?

**Comment by ocrasborn** [comment]
Thanks for addressing it now!

**Comment by Woseseltops** [comment]
Apologies for not checking if the website worked after the pull! I have seen this problem before, but not at Signbank, so it didn't cross my mind to verify. Thanks for cleaning up my mess again @vanlummelhuizen :/

![image](https://i.imgur.com/OkHv4Ds.gif )

> Solved. @Woseseltops we need to fix this for the future.

Agreed. How about using a post-merge hook that does something like this, to make sure we can all write all all files, and Apache can read?

```
chmod -r g+rw /var/www/signbank/live/repo
setfacl -R -m user:wapsignbank:rx /var/www/signbank/live/repo/

**Comment by vanlummelhuizen** [comment]
@Woseseltops No need for apologies. You are allowed to make mistakes. As am I, hopefully.

Looks like a nice post-merge hook to me. Do you have experience with git hooks? Or a better question: who is going to set it up?

**Comment by vanlummelhuizen** [comment]
@Woseseltops Ok, I created a post-merge hook in /var/www/signbank/live/repo/. Next time one of us does a merge or pull, we will see what happens. If I do it, I expect to see many permission denied messages because I do not own everything. Perhaps a pip to /dev/null is a good idea.

**Comment by Woseseltops** [comment]
> Next time one of us does a merge or pull, we will see what happens.

I did it today, and this problem showed up again, so our hook is not working yet. I now made it like this:

```
#!/bin/sh

echo 'Fixing permissions'
chmod -R g=rw /var/www/signbank/live/repo
setfacl -R -m user:wapsignbank:rx /var/www/signbank/live/repo/
```

So if we don't see the message, it's not working yet.
