### ISSUE TITLE
Show horizontal search result scroll bar for all view 

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#665]
Just noticed for the first time that the horizontal scroll bar we have above the Detail View is not present in the Public View and the Relation View; please add it for all views/tabs.

**Comment by Woseseltops** [comment]
I always thought this was by design :P . Anyway, it's on all tabs now!

**Comment by susanodd** [comment]
This needs some revision for Morpheme detail view. The links end up going to morphemes because there is also a Morpheme search page. But this gives errors if the previous search results are glosses.

**Comment by susanodd** [comment]
In the various classes in adminviews, the information needed to display the results in the ribbon is collected.
Some of the older code has hard-coded languages, or an idgloss field.
I'll make the code consistent.
I'll add an is_morpheme flag in order to make the appropriate links in the ribbon.

**Comment by susanodd** [comment]
This has been fixed. The search results bar is also shown in Morpheme Detail View.
The links in the search results are now to Gloss Detail View or to Morpheme Detail View..
Additionally, if you search on "Gloss or Morpheme", the morphemes link to Morpheme Detail View.

**Comment by susanodd** [comment]
This is on github but not live yet.

**Comment by susanodd** [comment]
Regarding the scroll bar for Public View.
If one is already logged in and goes to Public View, then the scroll bar is visible.
But if one is not logged in, the scroll bar is not visible.
If one is logged in and views Public View, clicking on a different gloss in the scroll bar shows the Detail View for the newly clicked on gloss.

**Comment by susanodd** [comment]
This is nearly done. I did extensive code improvement so the different data in the various scroll bars can share routines.

**Comment by susanodd** [comment]
Scroll bar for lemmas. Lemma search results (#708) shown in scroll bar in Lemma Update View (#722).

**Comment by ocrasborn** [comment]
@susanodd This is a great improvement to the interface, thanks!
