### ISSUE TITLE
Replace the /datasets/detail/123 url by /datasets/<dataset acronym> globally.

### ISSUE THREAD

**Issue by vanlummelhuizen** [Signbank/Global-signbank#666]
See also #662 Note that we also need to make the acronym field unique for Dataset.

**Comment by vanlummelhuizen** [comment]
@ocrasborn Why did you tag this issue with 'high priority'? Both urls work exactly the same way. Technically there is no reason to do this very soon. The only reason to remove the longer ones soon is that users may not encounter the longer ones at all, anywhere. Is that what you want?

**Comment by ocrasborn** [comment]
eh.... not sure! I think I intended to make #662 high priority, as we don't want to let that disappear from our memory

**Comment by susanodd** [comment]
Oh, I see what the issue is. I just did a grep on "datasets/detail/". I'll do this.

**Comment by susanodd** [comment]
Pushed to github.

**Comment by susanodd** [comment]
See previous.
