### ISSUE TITLE
Phonology fields with > character not previewed in Detail views

### ISSUE THREAD

**Issue by susanodd** [Signbank/Global-signbank#669]
I found this error when working on issue #629.
This is fixed.
This issue supports the commit of the javascript code.

**Comment by susanodd** [comment]
This is waiting to be put on the live server. (@Woseseltops )

Note that the media/js files also need to be put on the live server.

jquery.jeditable.mini.js
gloss_edit.js
morpheme_edit.js

**Comment by susanodd** [comment]
This is live in Morpheme View. But it's not on the server for Gloss View.

**Comment by Woseseltops** [comment]
Did a pull this morning! Can check if it's working like you intended @susanodd  , and if so close the issue?

**Comment by susanodd** [comment]
Yes, it works!
