### ISSUE TITLE
CSV Update glitches

### ISSUE THREAD

**Issue by susanodd** [Signbank/Global-signbank#670]
There are some glitches with None values (not yet been set) in field choice fields in import/export and display.
These need to be made consistent.

**Comment by susanodd** [comment]
@Woseseltops, can you let us know when this is on the live server?

**Comment by susanodd** [comment]
More revisions to make display of empty fields consistent.
During debugging with a test file from @ocrasborn to update Named Entities, I noticed that it wasn't possible to update this field in the Detail View. This was caused by the old syntax described below. That's been fixed.

@Woseseltops :
Also fixed code bug in update.py caused by old syntax:
Old syntax:
`setattr(gloss,field,value)`
New syntax:
`gloss.__setattr__(field,value)`
The old syntax was causing fields not to be updated.
Maybe this evolved with new versions of Python and Django.

**Comment by susanodd** [comment]
This is waiting to be put on the live server. (@Woseseltops )

**Comment by susanodd** [comment]
This still isn't on the live server.

**Comment by Woseseltops** [comment]
Sorry for the long delay, did a pull this morning! Can check if it's working like you intended @susanodd , and if so close the issue?

**Comment by susanodd** [comment]
Yes, it's working!

**Comment by susanodd** [comment]
Some redundant messages appear when updating.
Changes are live.
No changes found.

**Comment by susanodd** [comment]
This has been fixed and pushed to github.

**Comment by Woseseltops** [comment]
Just pulled... could you check if things work again and if so close this issue!

**Comment by susanodd** [comment]
Thanks, just confirmed it's working.
