### ISSUE TITLE
Checkbox fields in Detail views don't initialise properly

### ISSUE THREAD

**Issue by susanodd** [Signbank/Global-signbank#672]
When you click on a field that's set to Yes, the checkbox on some fields isn't set in Edit mode.

I fixed this, it was caused by too many spaces in the Django template.

**Comment by susanodd** [comment]
![edit-sign-yes-pre-click](https://user-images.githubusercontent.com/24272544/88171292-5cba7f00-cc1f-11ea-8818-41130d471891.png)
![edit-sign-yes-click](https://user-images.githubusercontent.com/24272544/88171299-62b06000-cc1f-11ea-8f2a-4d04526cc172.png)

**Comment by susanodd** [comment]
The above screenshots show the issue.
The screenshots below show the fix.

**Comment by susanodd** [comment]
![edit-sign-yes-preclick-fixed](https://user-images.githubusercontent.com/24272544/88171569-d94d5d80-cc1f-11ea-88fa-625ac5401e51.png)

![edit-sign-click-fixed](https://user-images.githubusercontent.com/24272544/88171584-df433e80-cc1f-11ea-9199-737827a55368.png)

**Comment by susanodd** [comment]
The bug was caused by "pretty printing" formatting of if-else code in the Django template.
This was fixed by putting all the code together with no spaces.
It's really ugly that way, but it needs to be that way.

**Comment by susanodd** [comment]
This is waiting to be put on the live server. (@Woseseltops )

**Comment by Woseseltops** [comment]
Did a pull this morning! Can check if it's working like you intended @susanodd , and if so close the issue?

**Comment by susanodd** [comment]
Yes, it works now!
