### ISSUE TITLE
Enable drag and drop uploading

### ISSUE THREAD

**Issue by Woseseltops** [Signbank/Global-signbank#675]
For example like this (but you can pick another solution): https://www.smashingmagazine.com/2018/01/drag-drop-file-uploader-vanilla-js/

![uploader-preview](https://user-images.githubusercontent.com/1909317/86451841-c1b73f00-bd1b-11ea-8267-8191eb15e5b0.gif)

Can you help us prioritize this, @ocrasborn ?

**Comment by Jetske** [comment]
It seems to work fine now in the gloss detail view for uploading 'new video' and 'new citation form image'. I can also add it to upload 'other media'. 

Is there any other place where this could be nice to add?

**Comment by susanodd** [comment]
This is completed.
