### ISSUE TITLE
Live server not same as github

### ISSUE THREAD

**Issue by susanodd** [Signbank/Global-signbank#676]
The Gloss Detail view is not getting context variables that are set up in the most recent adminviews.

@vanlummelhuizen , @Woseseltops , Please check whether adminviews on the server is the one on github.
This works on my local server, and mine is the same code as on github. Thanks.

**Comment by Woseseltops** [comment]
Hi @susanodd , sorry for the long radio silence. It might have been the case that I did not do a pull on the live server for a long time, but I did one this morning. Your latest commit b2d583 is on there. Also the latest change to adminviews.py is visible.

Can you check if this fixes it?
