### ISSUE TITLE
Link to lemma edit pages directly from the gloss detail view

### ISSUE THREAD

**Issue by Woseseltops** [Signbank/Global-signbank#677]
Right now, the only way to find lemma edit pages is from the 'show all lemmas' list view. 

Current behavior: if you click the lemma in edit mode, it shows (1) a form to choose another existing lemma and (2) a link create a new lemma. If you click the link, the row changes into a lemma creation area.

Desired behavior: three options, in the form of links: Edit existing lemma   Choose other lemma    Create new lemma . Clicking each of these should show a form, like is currently happening when you click 'create new'.

**Comment by susanodd** [comment]
Yes, that is annoying.
It's a bit weird now. The Lemma is where the Dataset is stored.
It's not clear to me how we can keep users from choosing a different Lemma and thereby also modifying the Dataset the gloss is in. (Do we do this?)
Are you proposing to go to a different page rather than do this inside Gloss view?
Like a Lemma View?
It should probably be only allowing you to choose / create lemmas in the same Dataset.
The Dialects were messed up like this. ( #671.)

**Comment by susanodd** [comment]
To illustrate the different accesses to Lemmas. Here are those for Lemma Carry (in the Lemma List you see there are 10 glosses associated with it, and Update Lemma where it can be updated), plus the list of 10 glosses with Lemma Carry, and the Gloss Detail View for Carry-A.)

![lemma-list-carry](https://user-images.githubusercontent.com/24272544/89532709-844e4180-d7f2-11ea-9cd0-04cf4ae67998.png)
![update-lemma-carry](https://user-images.githubusercontent.com/24272544/89532738-8e704000-d7f2-11ea-96dd-14d59a080f86.png)
![10-glosses-carry](https://user-images.githubusercontent.com/24272544/89532757-94662100-d7f2-11ea-90de-b13b46242786.png)
![gloss-carry-A](https://user-images.githubusercontent.com/24272544/89532764-97f9a800-d7f2-11ea-88e6-085930a57bc3.png)

**Comment by susanodd** [comment]
Considering that many glosses can be linked to a Lemma. And that the Dataset (of the Gloss) is obtained via the Lemma (of the Gloss), it seems potentially dangerous that the user can change a Lemma in this way.
To do so via the Gloss Detail View would more or less be breaking the link to the Lemma and possibly remove the Gloss from the Dataset it's in.
Likewise, it seems dangerous to be able to Update a Lemma in this way, and other Glosses associated with the Lemma will also be changed. (The Lemma object is updated so the new English or Nederlands would be seen in glosses that are associated with it. Very useful for typo's. But not sure about other changes.) Of course the user must have permission.

**Comment by susanodd** [comment]
Probably @Woseseltops you suggest to revise the Update Lemma into a Lemma View?
Then the associated glosses for this lemma could be shown there.
And we'd probably need a Lemma Search so as to avoid going through the entire Lemma List.
If we expand the Update Lemma view, then it would suffice to show the Dataset and the Glosses associated with it.
But the Dataset probably can't be modified.

There could be something to assign a gloss to this Lemma (group). Add glosses to the Glosses associated with it.
So move the Lemma Edit functionality of the Gloss Detail View to the Lemma (Update) View.

**Comment by Woseseltops** [comment]
> It's not clear to me how we can keep users from choosing a different Lemma and thereby also modifying the Dataset the gloss is in. (Do we do this?)

Hmmm I didn't know it worked that way. Let's map the options:

 Action in gloss detail page|Will change dataset (danger)?|Possible at the moment|Desirable
---|---|---|---
1 Change lemma to other lemma within dataset|no|yes|yes
2 Change lemma to other other lemma outside of dataset|yes|no|no
3 Add new lemma inside same dataset|no|yes|yes
4 Add new lemma in other dataset|yes|no|no
5 Edit text field of current lemma|no|no|yes
6 Edit dataset of current lemma|yes|no|no

As you can see, none of the dangerous options are possible at the moment (2, 4), and we have to make sure we do not accidentally add 6... but as changing the dataset of a lemma is currently not possible on the edit page of lemmas, I don't think that will happen? In other words, nothing to worry about, right?

> Are you proposing to go to a different page rather than do this inside Gloss view?

Yes, because that way it is clearer that a lemma is a separate entity, so if lemma X is used in gloss a and gloss b, if you change it in gloss a it will also change gloss b.

> Like a Lemma View?

I don't think that's necessary; just the current lemma editing view is fine. Perhaps some minor extensions (from the end user perspective, at least), like you mention here:

> If we expand the Update Lemma view, then it would suffice to show the Dataset and the Glosses associated with it.

>But the Dataset probably can't be modified.

Yes so this is indeed important as discussed above.

> There could be something to assign a gloss to this Lemma (group). Add glosses to the Glosses associated with it.
So move the Lemma Edit functionality of the Gloss Detail View to the Lemma (Update) View.

Could be interesting, but I guess outside of the scope of this issue. This is just about helping a Japanese user who made a typo in a lemma ;).

**Comment by susanodd** [comment]
![revised-update-lemma](https://user-images.githubusercontent.com/24272544/89771377-8240f700-db00-11ea-927c-f19beaf23176.png)

**Comment by Woseseltops** [comment]
![image](https://media1.tenor.com/images/8403dcb5e7e7178d2c2ede12a6bf62f1/tenor.gif)

**Comment by susanodd** [comment]
![gloss-detail-edit-lemma](https://user-images.githubusercontent.com/24272544/90004904-b77f4d80-dc96-11ea-9b0f-705e0327d275.png)

**Comment by susanodd** [comment]
You see the Edit Lemma button now, which gets you to the Update Lemma Page.
If you actually click on the existing lemma, it's as it was.
On the Update Lemma Page, it's context sensitive so you either get back to the Lemma List or the Gloss Detail View.

**Comment by susanodd** [comment]
Hmmm. I pushed a commit, but I put the wrong Issue number! I put #667 instead of 677.

**Comment by Woseseltops** [comment]
Great @susanodd ! So now we have the option to create and change, but also to edit the current lemma. For the first two, you have to click the lemma, for the last one, you have click a button. Is there a special reason for these two different approaches @susanodd ?

**Comment by susanodd** [comment]
That's how @vanlummelhuizen once set it up. I made the new button separate because of the way the rest works.
When you click on the original lemma, it disappears.
That interferes with wanting to jump to the Update View. So I made a new button.
I think the original behaviour is a bit weird. But I left it so.

**Comment by susanodd** [comment]
The original Lemma is the original Annotation ID Gloss (the text was copied).
So when you first edit a gloss's lemma, you're editing something like itself derived from itself.
We were assuming that users would then group together glosses by creating a lemma and assigning that lemma to all the glosses in its group.
I guess with the use of the Update Lemma View, I put the list of Glosses there thinking we wanted to facilitate associating glosses with the Lemma. (This can be done.)
As it is now, if a "new" Lemma has already been created (instead of the original Annotation ID Gloss that was used to make the gloss's original Lemma), then the idea of the interface (if you click on the red Lemma) is that the user can select a different (or new) Lemma there.

The current (click on the Lemma part of the) interface uses Ajax calls to stay inside the Edit.
The new button goes to another page. Because I couldn't get it to "ajaxify" back into the Gloss Edit, I made the button separate.

**Comment by susanodd** [comment]
![gloss-view-click-on-red-lemma](https://user-images.githubusercontent.com/24272544/90134566-a7886c00-dd71-11ea-82d0-20da2e94ad0f.png)

**Comment by susanodd** [comment]
See above. Having clicked on the red Lemma, the Edit Lemma button disappears and the original options for choosing a different or a new lemma are shown.

**Comment by susanodd** [comment]
The implementation is also dependent on a Lemma Group being a hyperlink when not in Edit mode.
That's why it disappears if you are in Edit mode and click on it.

![lemma-group-hyperlink-carry](https://user-images.githubusercontent.com/24272544/90135182-92600d00-dd72-11ea-99d6-1eccd387fd6d.png)

**Comment by susanodd** [comment]
![lemma-group-carry-hyperlink](https://user-images.githubusercontent.com/24272544/90135560-216d2500-dd73-11ea-8620-24dd48a5f209.png)

**Comment by Woseseltops** [comment]
Okay, so if I understand you correctly, the reasons for it being a separate button are mostly technical, right? Just to be sure we're on the same page, if we would only have to worry about user experience, would you agree something like this would be cleanest?

![image](https://user-images.githubusercontent.com/1909317/90230087-4d42e600-de19-11ea-8b33-d4137f478111.png)

If yes, we can try to think about a technical solution :)

**Comment by susanodd** [comment]
Yes, that's much better!
It's also much better if the current Lemma stays visible.
I will revise it!

**Comment by ocrasborn** [comment]
Yes @Woseseltops, I like those three buttons a lot, they help make the whole issue of what's a lemma gloss more transparent for the user, too. Thanks for implementing @susanodd

**Comment by susanodd** [comment]
This has been implemented and pushed to github.
