### ISSUE TITLE
Search Gloss via Menu bar gives duplicates

### ISSUE THREAD

**Issue by susanodd** [Signbank/Global-signbank#678]
![search-duplicates-menu-bar](https://user-images.githubusercontent.com/24272544/89772107-bf59b900-db01-11ea-86ff-701e633d4833.png)

**Comment by susanodd** [comment]
![search-query-field](https://user-images.githubusercontent.com/24272544/89772401-3b540100-db02-11ea-92bf-b1f8bb8911be.png)

**Comment by susanodd** [comment]
This is trickier than expected.
The order_queryset_by_sort_order is giving back more glosses after sorting when its input comes via the menu bar!

**Comment by susanodd** [comment]
I fixed this.
I removed the order_by part from these statements in adminviews.py:
```
            ordered = list(qs_letters) #.order_by(sort_key))
            ordered += list(qs_special) #.order_by(sort_key))
```
This was somehow duplicating some of the glosses.
Now the results (when you query via the menu bar) are no longer sorted.
However, you can click the sort on the column to achieve the same.

**Comment by susanodd** [comment]
I'm revising this again.
The implicit language for searching via the menu bar can be either the (default) language of the last used dataset (provided it is still selected), or it can be the interface language (provided it is also one of the languages of the selected datasets).

**Comment by ocrasborn** [comment]
Hi @susanodd : That's all understandable for me, but I doubt that it will be transparent for the user what happens when, if we would have a if-if-if type of scenario. Is it not easier to search across all gloss resp. translation fields for all of the datasets? Or is that where the duplicates started coming from?
In terms of the user interface, these two menu bar fields suggest 'wide' searching, in contrast to the language-specific fields in the search form (simply because nothing is specified in the labels other than 'search gloss' resp. 'search translation'

**Comment by susanodd** [comment]
Yes, it's that multiple languages are being used. That's what's causing the problem.
Okay, "wide" searching makes sense. I had thought it was a shortcut.
It seems to be causing problems because more languages are getting filled in.
I tried using French and there are numerous Unicode errors popping up.
I revised the parameters to sorting so that all the active dataset languages (their 2 char codes) are passed to the sorting routine.
Next, I need to revise the query to account for this to avoid duplicates. And get rid of the unicode messages to the error log.

**Comment by susanodd** [comment]
I removed the default sorting. There aren't any duplicates anymore, but the results aren't sorted.
Because of multiple datasets and multiple translations, it's not clear what language should be used for default sorting.
It was putting glosses that start with symbols after glosses that start with letters, and empty translations at the end.
But which language should be the default?

**Comment by ocrasborn** [comment]
@susanodd , how about just sorting by the English Annotation ID Gloss? That's an obligatory field for all datasets, and in that way signs for the same concept are close together. Which is what people will typically want when searching across languages. (Note to my linguist friends: no, I know, the gloss does not encode the concept, that's what the translation equivalents and the Concepticon link does.)

**Comment by susanodd** [comment]
I made the sort use English if available.
The code relies on the Languages of all the selected datasets, plus the setting for Default Keywords.
It is English by default. Although this might not be true in other Signbanks.
I had to explicitly check if there are duplicates in the sorted list and not include them in the results.

**Comment by susanodd** [comment]
@ocrasborn, you can check this now. English is used for the default sorting for the Menu bar search. No duplicates now.
