### ISSUE TITLE
SB down, "Internal Server Error"

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#679]

**Comment by susanodd** [comment]
It was working okay on Friday.
I can't find any extra details in the logs.

This is the access log from yesterday:

![screenshot-access-log-20200816](https://user-images.githubusercontent.com/24272544/90378169-4ca88a80-e079-11ea-9d2a-5d3c3c2a1cc7.png)

**Comment by susanodd** [comment]
And the one from this morning before a new log was created.

![screenshot-access-log-20200817](https://user-images.githubusercontent.com/24272544/90379538-2388f980-e07b-11ea-9e97-a56f13c72d36.png)

**Comment by susanodd** [comment]
What's this:

`"GET /robots.txt HTTP/1.1"`

**Comment by susanodd** [comment]
What's this:

`"GET /dns-query?dns=AAABAAABAAAAAAAAA3d3dwdleGFtcGxlA2NvbQAAAQAB HTTP/1.1"`

**Comment by susanodd** [comment]
What's this:

`"GET /robots.txt HTTP/1.1" 500 4674 "-" "Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)"`

**Comment by susanodd** [comment]
What's this:

`"GET / HTTP/1.1" 500 4679 "-" "TLS tester from https://testssl.sh/"`

**Comment by susanodd** [comment]
I'm not going to ping the associated IP addresses because then my computer will be in their logs.

**Comment by vanlummelhuizen** [comment]
@susanodd All those GET entries are not the problem. The problem is that the UWSGI process is not running because of conflicting port numbers. I am looking into this at the moment. Not found a solution yet.

**Comment by susanodd** [comment]
Okay, I was comparing my own access log with the Signbank one. Mine only has pages I access.
I found this information:

Bots, spiders, and other crawlers hitting your dynamic pages can cause extensive resource (memory and CPU) usage. This can lead to high load on the server and slow down your site(s).
```
# go away Googlebot
User-agent: Googlebot
Disallow: /
```

**Comment by vanlummelhuizen** [comment]
My assessment: because of some work by @Woseseltops on Friday, some file permissions are incorrect. I contacted the administrators to correct the permissions. I keep you posted.

**Comment by susanodd** [comment]
Great!

**Comment by vanlummelhuizen** [comment]
@ocrasborn @susanodd @Woseseltops Thanks to the quick response of the administrators, the site is up and running again.

**Comment by ocrasborn** [comment]
And thanks to your quick action, too, @vanlummelhuizen !

**Comment by Woseseltops** [comment]
Thanks for this @vanlummelhuizen ! Do you have some more details for me on what went wrong? I'm quite sure I checked if everything was still online when I stopped working.

**Comment by vanlummelhuizen** [comment]
I turned out some file permissions were incorrect. I had the admin fix them. See also my mail correspondence with them. These problems makes me very hesitant to put new stuff live. Perhaps move to a container solution soon?

**Comment by Woseseltops** [comment]
> I turned out some file permissions were incorrect

Yeah sorry, I meant: do you know which files had what problems? Because the post merge hook ran, and should have corrected everything my account has permissions to screw up ;)... so I really wouldn't know what could have gone wrong there.

**Comment by vanlummelhuizen** [comment]
> do you know which files had what problems?

All I remember is that is was an __init__.py somewhere. Perhaps also other files. Not sure.

> You mean so we can fix file permissions ourselves?

Yes, if they need to be fixed in that context.
