### ISSUE TITLE
Make Handshape (search) page accessible to anonymous users

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#681]
https://signbank.science.ru.nl/signs/search_handshape/, that is, listing all handshapes when no query is performed

**Comment by susanodd** [comment]
This has been pushed to github.

**Comment by ocrasborn** [comment]
@susanodd Hm, was this live yet? In the Django admin, I've removed all group requirements under 'advanced' for this page, so as to allow anyone to access, but while the menu item is now visible if I'm not logged in, when I select the menu item, i'm prompted to log in.

**Comment by susanodd** [comment]
It seems to not be live for some reason. It's on github, but not on the live server.

**Comment by susanodd** [comment]
@vanlummelhuizen, could you put this code on the live server.
