### ISSUE TITLE
Enrich email confirmation upon getting access to a dataset

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#684]
When a user gets permission to see a dataset, they currently get the following message (ex. for NGT):

 - - - - - - - - - -
You have been granted access to dataset Nederlandse Gebarentaal at Global SignBank.

Global SignBank Webmaster
 - - - - - - - - - -

Please enrich this as follows:

 - - - - - - - - - -
You have been granted access to dataset [DATASET] at Global SignBank.

For more information on the type of information Global Signbank stores about signs, see the manual on this page: https://signbank.science.ru.nl/about/manual/
Note that handshapes are described in terms of phonological features separately from signs; see this page: https://signbank.science.ru.nl/signs/search_handshape/

The Release Notes page describes the latest changes and additions to the functionalities of the website: https://signbank.science.ru.nl/about/release/

Global SignBank Webmaster
 - - - - - - - - - -

**Comment by susanodd** [comment]
This has been pushed to github.
