### ISSUE TITLE
User names with spaces allowed but not really?

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#685]
Just tried to assign a user with username of the kind 'Firstname Lastname' to different group in the admin. When I save the change, I get an alert saying that spaces are not allowed, and only a limited set of special characters like _ are allowed. There were at least two other users who had created an account with a user name containing a space, so apparently when this happens in the user interface there's nothing blocking this. Should we actively prevent people creating such a user name in the registration dialogue? Now, I'm forced to remove the space and/or change it to something like an underscore in order to make changes to the user's properties.

**Comment by susanodd** [comment]
This could have arisen with upgrades to newer versions of Python/Django, or possibly increased usage of utf-8.

**Comment by susanodd** [comment]
Do you have more examples of this?
I looked through the database but I can't find any usernames with spaces.

It's possible that Django is doing this when it displays an object.
The __str__(self) method gives a display recipe for an object.
But if this has not been explicitly defined, Django does whatever.

In the Admin code there are references to __str__ 
E.g.,
class RegistrationProfile(models.Model):
 class Admin:
        list_display = ('__str__', 'activation_key_expired')
        search_fields = ('user__username', 'user__first_name')
    def __str__(self):
        return u"Registration information for %s" % self.user

But user is an object (not a string).

The search fields (above) could be that a user_username is the same as a user_last_name, so it just looks like there is a space.

The display of the object (with spaces) might not match with identifying the object.
(There needs to be a lookup of the object using the names. But it should be looking up username, not username first_name.)

**Comment by susanodd** [comment]
I see what it may be that you are seeing. Some users have "." in their user names.

**Comment by susanodd** [comment]
This has been pushed to github.

**Comment by ocrasborn** [comment]
@susanodd , could you give me a short debrief on what the situation is now? Will spaces continue to be allowed, and have you fixed the problem of editing such profiles? Or are they automatically changed to full stops now?

**Comment by susanodd** [comment]
Yes this is fixed. Spaces are not allowed.
The spaces are caught when the user is filling in the form to enter their data.
It gives the user an error message: Usernames should not have special characters.

The other special characters besides space are '|', '+' (to me these look dangerous because of regular expressions)
and the '@'. (a couple of users have an email address, but we don't do anything to check user names as being valid email addresses, so that seems misleading).

**Comment by ocrasborn** [comment]
Thanks @susanodd , all clear.
