### ISSUE TITLE
Field value is not displayed after exiting edit view

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#686]
Just created a test sign in a new dataset, and enjoyed the new keyboard navigation when adding the phonology. Possibly related to that: one of the four values I filled in is not displaying (for the field 'Relative Orientation: Movement'; value 'Back' is visible when in edit mode, but is not displayed when exiting edit mode).

**Comment by ocrasborn** [comment]
Hm, reloading the page makes it appear. And then I cannot replicate it.

**Comment by ocrasborn** [comment]
Ah, there's a pattern of some sort: added another sign, added more phonology with the keyboard and exited edit mode: all good, all values appear. Then I go back into edit mode and specify another value for another field, exit edit mode: value not displayed. Reloading displays it.

**Comment by ocrasborn** [comment]
Oh, hm: perhaps the issue is that either I didn't notice the red 'reload' alert at the top, or it didn't display...

**Comment by susanodd** [comment]
It's true it needs to be reloaded.

I suspect the ajax call that loads the field choices. sometimes its results are not displayed right away..

**Comment by ocrasborn** [comment]
ah ok, I'll close this for now then, and keep an eye out on it
