### ISSUE TITLE
Handshapes search_type not defined

### ISSUE THREAD

**Issue by susanodd** [Signbank/Global-signbank#688]
There is a missing session variable for HandshapeDetailView.

This arises if the first thing you do after logging in is something with handshapes.
This should be a session variable.

https://github.com/Signbank/Global-signbank/blob/da7326de971f8b68c39237bfc178424bcef96110/signbank/dictionary/adminviews.py#L2433

**Comment by vanlummelhuizen** [comment]
@susanodd I try to replicate this bug but don't see any problem. Perhaps I misunderstand. Can you explain a bit more?

**Comment by susanodd** [comment]
![handshape-search_type-error](https://user-images.githubusercontent.com/24272544/94693627-3f4b1500-0334-11eb-9bc6-fd2bf8c92ee8.png)

**Comment by vanlummelhuizen** [comment]
To replicate: 

1. open a incognito browser window
2. go to https://signbank.science.ru.nl/dictionary/handshape/190 or the same page on dev instance. 
3. You might see a error already. If not, log in and again go to https://signbank.science.ru.nl/dictionary/handshape/190

**Comment by susanodd** [comment]
Okay, so it needs to be a new browser window. Thanks.
