### ISSUE TITLE
Dataset manager view: manage buttons do not work for dataset "International Sign (Whynot 2016)"

### ISSUE THREAD

**Issue by Woseseltops** [Signbank/Global-signbank#695]
All of the grey 'manage' buttons in this screenshot were clicked, but nothing happens for the 'International Sign' one:

![image](https://user-images.githubusercontent.com/1909317/99061167-6d617d00-25a1-11eb-94e8-084960de059e.png)

Instead, I get an error in the console:

`Uncaught Error: Syntax error, unrecognized expression: #dataset_InternationalSign(Whynot2016)_manage_change` . 

I'm guessing the problem is with the parentheses... @ocrasborn , would it be okay to remove them?

**Comment by ocrasborn** [comment]
@Woseseltops : yes, parentheses may be removed here in the name

**Comment by susanodd** [comment]
It looks like that dataset_ .... _manage_change
should be the acronymn, not the dataset name.

**Comment by susanodd** [comment]
In the template for manage datasets, those used in identifiers may ought to be acronym instead of name.
There's code for removing spaces, but not parentheses.
Probably jquery can't deal with special characters.

`href="#dataset_{{dataset.name|cut:' '}}_manage_change"`

**Comment by ocrasborn** [comment]
(Background: we started out with just short names, and later decided that we'd better separate names from acronyms. For the initial datasets, the names were short.)

**Comment by vanlummelhuizen** [comment]
Solved it by using `slugify` template tag instead of `cut:" "`.
