### ISSUE TITLE
Create another two interface translations (Hebrew & Arabic)

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#696]
This is of course not 'blocking' in the sense of us not being able to work anymore, but @Woseseltops or @vanlummelhuizen , it'd be good if you could do this before continuing with other things. I'm not quite sure what is required, but we'll need to have another interface element to allow for selecting the new language, the admin needs to display new fields for page translation e.g., and a .po file needs to be generated for Hebrew.
What all is not covered by either 1) pasting hebrew texts in the appropriate box in the Pages on Admin, or 2) the .po file? Is everything included in the .po file by new, or are some things still hard-coded?

**Comment by susanodd** [comment]
The pull-down language setting (with the flags), that's hard coded. And a few other places that explicitly look at the interface language.

**Comment by susanodd** [comment]
Some of the places where that interface language code is used is in determining e.g., what field choice language to show.
And similarly for handshapes.
(I searched in the code on "zh-hans" to see where it's explicitly tested for.)

**Comment by Woseseltops** [comment]
The current flag icons are from an icon set that is no longer available, and thus can no longer be extended. Proposed new icons (UK one already being used by the Catalans): 

![image](https://user-images.githubusercontent.com/1909317/100349379-a27dbe80-2fe8-11eb-9af5-425bff670e75.png)

**Comment by Woseseltops** [comment]
Created a branch for this, added a .po: https://github.com/Signbank/Global-signbank/blob/506156d37dfc3b6f5b8cb40d3d2ce78913fe78cf/conf/locale/he/LC_MESSAGES/django.po

**Comment by Woseseltops** [comment]
To do:
* Adding the new interface language to the settings
* Integrating it in the menu dropdown (@susanodd already located where)

If I'm not mistaken, model-translation should handle the rest of it from here automagically (like an extra field to translate pages, etc). The only place where it does not work is field choices : https://github.com/Signbank/Global-signbank/issues/658

**Comment by ocrasborn** [comment]
Hi @Woseseltops , thanks for taking this up! Could you adapt the permissions so that I can access the .po file?

**Comment by ocrasborn** [comment]
Sorry @Woseseltops , my bad! typo in the rsync command. All good.

**Comment by Woseseltops** [comment]
By chance, I discover today (a day later), that this is not true:

> If I'm not mistaken, model-translation should handle the rest of it from here automagically (like an extra field to translate pages, etc) ...

See #702 .

**Comment by ocrasborn** [comment]
@Woseseltops : see my change to the title of the issue: I wasn't sure first, but we'd like to add not only Hebrew but also Arabic. I've asked the Israeli team which flag they'd like to use for that (or, if too difficult, suggested we might switch from flags to a text menu).

**Comment by Woseseltops** [comment]
https://www.quora.com/Which-flag-represents-the-Arabic-language . I looked up it up and Duolingo goes for option 1. I think this is also a serious option, although the source is a bit unclear: https://commons.wikimedia.org/wiki/File:Flag_of_the_Arabic_language.svg

**Comment by ocrasborn** [comment]
@Woseseltops , the Israeli team would really like to avoid any flags, for political reasons, and I can understand them. We had already made a choice for the flags representing English (well, and Dutch!) which was political in a sense, of course. But let's use this occasion to steer away from the flags (sorry for the effort you put into it finding a new icon set!), and move to a menu with language names in the original language (so Nederlands, English, עברית, etc. There's space on my large screen for the full words, but we could also consider a two- or three-character ISO code that would make the whole menu bar look better for smaller screens. Oh, @Woseseltops , and do feel free to move this to a separate issue, if that makes your life more organised. :-)

**Comment by Woseseltops** [comment]
Too bad but I understand @ocrasborn ! Made a start with switching to text this morning. 

To do: 
* Remove the animations... they don't really add anything and it looks messy with overlapping text
* Things look weird when choosing the longer name 'Nederlands'.
* The language picker still needs to be cleaned up... I think it mentions 'flags' here and there in the code still.
* The input for the language picker is still hardcoded... should come from the settings dynamically.

**Comment by ocrasborn** [comment]
@Woseseltops : yes, the longer language names will be ugly in the interface. How about two-letter ISO codes? EN-CN-NL-HE-AR? (not sure about Arabic)

**Comment by Woseseltops** [comment]
Done:
* Remove the animations... they don't really add anything and it looks messy with overlapping text
* Language code instead of language names

**Comment by Woseseltops** [comment]
Today I cleaned up the language picker and rewired everything so it now gets its info from the settings directly; changes to the settings are visible in the language picker directly.

The idea of @ocrasborn to use language codes turned out to have 2 downsides: language code are not always short (ZH-hans), and languages codes are not necessarily understandable for users of that language. I therefore added this setting, which populates how the languages are called in the language picker:

```
#Short (abbreviated) version of how language users call their language, to be used in the language picker
INTERFACE_LANGUAGE_SHORT_NAMES = ['EN','NL','官话','עִברִית','عربى'] 
```

A prettier solution, I think, would be to add this to the language objects in the Django admin, as this is where we specify how languages are called in other languages anyway. However, because this would require an extra database migration, which is inconvenient as there are already migrations going on at at least one other branch, I've postponed it for now.

Todo:
* There is still a weird flickering glitch if the cursor approaches the language picker from below.
* Preparing the pull request so this branch can be merged into master.

**Comment by susanodd** [comment]
This looks really nice|

The migration on my branch is awaiting a pull to master.

**Comment by susanodd** [comment]
@Woseseltops, what's the best way to "fix" currently hard-coded language code references?

In #716 I have modified the Relations View.

As an aside, the template has numerous hard-coded language usages.
request.LANGUAGE_CODE == 'nl'
request.LANGUAGE_CODE == 'zh-hans'

These then get fed into translation functions in the templatetags (https://github.com/Signbank/Global-signbank/blob/bfe09051b1006ca103defab053c30e655ce01565/signbank/dictionary/templatetags/field_choice.py#L33) code as
translate_to_dutch
translate_to_chinese
translate_to_english (default)

What do you propose?

**Comment by Woseseltops** [comment]
Hey @susanodd I propose to discuss this in @vanlummelhuizen s issue #658 which is about removing these hardcoded language references. This issue is really about new interface languages and the language picker.

**Comment by susanodd** [comment]
Okay. The hard coding won't crash it. It will just drop through to English.

**Comment by susanodd** [comment]
I guess what my question was, is the LANGUAGE_CODE still the same?

**Comment by ocrasborn** [comment]
er... @Woseseltops , am I supposed to see anything yet in the interface? Or did you assign me to answer any open questions? (I still see the three flags in the interface, also after reloading, and in the admin I only see three language fields in a Page, for instance, not five.)

**Comment by Woseseltops** [comment]
Sorry @ocrasborn I didn't expect you to be this quick :) . I wasn't finished putting it online yet, it is now!

**Comment by ocrasborn** [comment]
Oh haha! I'll be more patient next time. Anyway:
1. Everything looks OK (in the user interface) for Mac/Firefox and Mac/Chrome, but on Mac/Safari I get question marks for missing images.
2. I don't yet see anything in the admin under pages, text boxes for Hebrew and Arabic that is.

**Comment by susanodd** [comment]
@Woseseltops how does this issue relate to the file system on right-to-left languages?

Django is putting the extension part of the filename at the start sometimes. Here is what the file properties look like in Ubuntu.

![right-to-left-filename](https://user-images.githubusercontent.com/24272544/111300447-616df080-8651-11eb-8437-c7105f3fed0d.png)

**Comment by susanodd** [comment]
@ocrasborn what is the best way to introduce new "feedback messages" that will need to be translated?

I'm using the Python/Django syntax: _("Some text that will be translated")

E.g., _("Upload other media failed: The file has an unknown type.")

**Comment by ocrasborn** [comment]
Hi @susanodd , @Woseseltops and @vanlummelhuizen can best advise here, but as long as you're consistent with how it's been done elsewhere, it should be OK, I'd say. (Note that the actual translations can take many months up to over a year, we don't review new to-translate-strings all that often.)

**Comment by ocrasborn** [comment]
Hi @Woseseltops : of the two open points above (11 Mar 2021), the Safari issue is solved now, could you still take care of this:
**I don't yet see anything in the admin under pages, text boxes for Hebrew and Arabic that is.

**Comment by susanodd** [comment]
I implemented the Semantic Fields in such a way that translations can be added in the Admin.
I just checked and they may be added on the page for the specific semantic field. The English name is the "name" of the field.
The other languages are all translations.
I have yet to actually display the translations in the templates depending on the interface. 
At the moment, they are only visible under Settings in the list of semantic fields.

![semanticfields_translations](https://user-images.githubusercontent.com/24272544/176161697-a48a5fc4-a22c-4d7e-bb21-58e1e792fa7c.png)

**Comment by susanodd** [comment]
The page titles are all in the .po files.

**Comment by susanodd** [comment]
There are numerous texts that appear in "trans" blocks within the templates. These also appear for translation in the .po file.

I see what you mean, if you look at` /about/acknowledgements/` versus `/feedback/overview`

The feedback pages all have the translations that appear in the templates in the .po file.
In Admin, it shows the url to the template in the window. 
Whereas the acknowledgements page shows the actual text in the Admin.

**Comment by susanodd** [comment]
Shall I generate new .po files for the other languages?

In looking up what the difference was in the Admin pages versus the templates, I noticed I had forgot the trans blocks in the bootstrap titles for the Feedback pages. #703.

**Comment by susanodd** [comment]
The page content that shows up in the Admin is actually (hard-coded) fields in the Page model.

https://github.com/Signbank/Global-signbank/blob/5c654c984fe1ba12b116e2be0c18faea47b5110c/signbank/pages/models.py#L9-L18

Do we want all the languages hard-coded in Pages?

**Comment by susanodd** [comment]
I went ahead and added to two languages to the Pages model. It's just (language specific) fields for the title and content.
I modified the context processor so if either of these are empty, it serves up the English.
Because pages are separate from the dictionary, this migration is under the pages folder. The scope of these changes is thus limited.

**Comment by susanodd** [comment]
![admin-pages-other-languages](https://user-images.githubusercontent.com/24272544/176709457-5c539e7a-8a4c-4387-8629-3d1b72285edd.png)

**Comment by vanlummelhuizen** [comment]
Revisiting. Hebrew and Arabic are now two additional interface languages. It seems a number of pages (all?) are already translated. The `.po` files however only have empty `msgstr`'s, so they need work. 

Hebrew and Arabic are not used for ModelTranslation. So FieldChoice etc. are not translatable to those languages (yet).

@ocrasborn Please tell us how to proceed.

**Comment by ocrasborn** [comment]
@vanlummelhuizen Indeed, @susanodd pasted in the page translations that were made; the .po files are in the making in Israel. Of course we'd also like to translate the field choices, don't they end up in the .po file?

**Comment by susanodd** [comment]
The field choices are not in the .po files. They can be changed in the Admin Field Choice.
The new languages are available on Global Admin now. (No screenshot.)
