### ISSUE TITLE
Create CSV export function for all media links and gloss-number links

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#699]
For some purposes, it'd be really helpful to have a list of what the gloss number in the database, the annotation ID gloss, and the media links are. It's fine to keep the URLs as they are. We could add these as extra columns to the CSV export of search results, but perhaps we don't want all users (but only dataset managers) to have access to this. Proposal:
* Create an extra column ("All links") with buttons ("Download") on the Dataset Management page (https://signbank.science.ru.nl/datasets/manager);
* Clicking the button downloads a CSV with the following columns: Annotation ID Gloss (multiple for multiple languages), ID number (or whatever it's called in SQL speak), glossvideo url, glossimage url.

(So for video's, e.g. this url: https://aslsignbank.haskins.yale.edu/dictionary/protected_media/glossvideo/ASL/AB/ABHOR-2040.mp4)

**Comment by susanodd** [comment]
@ocrasborn, do you definitely want the entire url of the image/video? Including the https and the domain name?

Is it correct that you wish to be able to use the file locations in the generated CSV as hyperlinks?

(The part before the "glossvideo/..." needs to be "constructed". The "protected_media" part isn't a physical folder. The files are located in the writable folder of the server.)

**Comment by susanodd** [comment]
@vanlummelhuizen @Woseseltops @ocrasborn 
This issue needs hyperlinks.
To construct them, I would like to use the setting URL
In the example given by @ocrasborn, for ASL, the URL setting gives the correct domain.
https://github.com/Signbank/Global-signbank/blob/affb3fa53a43b3adc8f0c1a53052423d2defe3a1/signbank/settings/server_specific/asl_yale.py#L8
But for Global, the same setting shows science:
https://github.com/Signbank/Global-signbank/blob/affb3fa53a43b3adc8f0c1a53052423d2defe3a1/signbank/settings/server_specific/global_sb_new_aj.py#L7

rather than cls (which is what the protected_media serves):

https://signbank.cls.ru.nl/dictionary/protected_media/glossvideo/NGT/BL/BLAASTEST-2922.mp4

Any qualms about switching the URL setting to cls instead of science?

**Comment by susanodd** [comment]
@vanlummelhuizen you have done a lot with filenames with special characters.

I found there's a method for this in the Gloss model.

**Comment by susanodd** [comment]
Here's what it looks like. It generates the columns described above in the output CSV. Here shown with a test video having been added to the #A gloss to test that the correct hyperlink has been made. On Global, this will use the URL setting, as shown above.


![dataset-hyperlinks-csv](https://user-images.githubusercontent.com/24272544/110467863-cf596b80-80d7-11eb-9eb8-045bebb7484f.png)

![csv-hyperlinks](https://user-images.githubusercontent.com/24272544/110468343-73dbad80-80d8-11eb-8f00-13b5f0d2b14c.png)

**Comment by susanodd** [comment]
This has been pushed to github on theoddbranch.

**Comment by Woseseltops** [comment]
Reviewed the code. I like it.

**Comment by Woseseltops** [comment]
Okay, I do have a minor code style thing that caught my eye, about this:

            gloss_image_path = gloss.get_image_url()
            gloss_video_path = gloss.get_video_url()
            if gloss_image_path:
                gloss_image_path = gloss_image_path.encode('utf-8')
                gloss_image_path = os.path.join(protected_media_url,gloss_image_path)
                gloss_image_path = hyperlink_domain + gloss_image_path.decode()
            if gloss_video_path:
                gloss_video_path = gloss_video_path.encode('utf-8')
                gloss_video_path = os.path.join(protected_media_url,gloss_video_path)
                gloss_video_path = hyperlink_domain + gloss_video_path.decode()

            row.append(gloss_video_path)
            row.append(gloss_image_path)

Somethign along the lines of this might be a little more descriptive:

```
def form_full_url(path):
    return hyperlink_domain + os.path.join(protected_media_url,gloss_image_path.encode('utf-8')).decode()				

gloss_video_path = gloss.get_video_url()
if gloss_video_path:
    full_url = form_full_url(gloss_video_path)
    row.append(full_url)			
else:
    row.append(gloss_video_path)

gloss_image_path = gloss.get_image_url()
if gloss_image_path:				
    full_url = form_full_url(gloss_image_path)
    row.append(full_url)
else:
    row.append(gloss_image_path)

```
