### ISSUE TITLE
Replace FieldChoices with category 'Handshape' with  Handshape objects

### ISSUE THREAD

**Issue by vanlummelhuizen** [Signbank/Global-signbank#700]
Handshape objects are now linked to 'Handshape' FieldChoices using the machine_value (which is used as the primary key in Handshape). 

Do this after #658 and #661.

**Comment by susanodd** [comment]
This was originally done so that queries could work on sets containing objects of type Handshape as well as FieldChoice, hence the overlapping field names.

**Comment by vanlummelhuizen** [comment]
> This was originally done so that queries could work on sets containing objects of type Handshape as well as FieldChoice, hence the overlapping field names.

@susanodd Can you point me to code that does that?

**Comment by susanodd** [comment]
https://github.com/Signbank/Global-signbank/blob/ef6d3cb7e44f253b901e85edd80ec73f0cd9fca5/signbank/dictionary/models.py#L1906-L1924

**Comment by susanodd** [comment]
https://github.com/Signbank/Global-signbank/blob/ef6d3cb7e44f253b901e85edd80ec73f0cd9fca5/signbank/dictionary/adminviews.py#L5311-L5329

**Comment by susanodd** [comment]
There's some of initialization code for setting up Handshapes as well. Originally they were only in FieldChoice until they became objects with additional fields. When first using Handshapes, if there aren't any Handshape objects, they are created. There should also be code for maintaining the two representations.

**Comment by susanodd** [comment]
There may also be some raw queries using fields. I'm not sure any more.
(That may have been intermittent when doing minimal pairs, if any handshape attributes can be included.)

**Comment by susanodd** [comment]
This can probably be closed now.

**Comment by susanodd** [comment]
I fixed an error in CSV export related to this. It was using the `__str__` method instead of name because it's not longer caught by the attribute field_choice_category. (Fixed for the semantic fields and derivation history exports too.)
This is part of #851 and awaiting deployment.

**Comment by susanodd** [comment]
This can probably be closed. However,

There are some weird constructions, when a handshape is not found.

https://github.com/Signbank/Global-signbank/blob/fbb7c25da6f0629cdcdac5e9bce1f2021e33fec4/signbank/dictionary/update.py#L467-L472

@vanlummelhuizen what do you think?

**Comment by vanlummelhuizen** [comment]
@susanodd This piece of code is yours. What exactly is weird about it?

**Comment by susanodd** [comment]
It seems weird because in the template where a new handshape is chosen, only existing handshapes are offered in the choice list.
I know it's safe this way. But it shouldn't be possible to choose a non-existent handshape.
(Unless in some very weird scenario, a non-used handshape was removed in the time between the user choosing it and pressing return...)

**Comment by vanlummelhuizen** [comment]
> Unless in some very weird scenario, a non-used handshape was removed in the time between the user choosing it and pressing return...

I don't think it is weird. Perhaps very unlikely. Also, if someone want to tinker with the app by constructing malformed requests, this is an extra safety measure. So, kudos! 

So, if you are happy, you may close this issue.
