### ISSUE TITLE
Problem batch importing images

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#704]
I don't thing this is particularly new, we just don't do it normally: try to batch import images like we batch import videos. We now have a number of paper dictionaries that we want to digitise as SB datasets with images but not videos. Currently, I'm working on IS_WFD1975. Here's what I did:
* Upload images to writable/import_images/IS_WFD1975/eng/. (Here I noticed there were no subdirectories for datasets, just a bunch of old PNG and JPEG files, which I moved to OLDSTUFF/, and I created IS_WFD1975/eng/, just like I do for import_videos/ when I have a new dataset)
* Run https://signbank.science.ru.nl/dictionary/import_images/. I then first get the message that I didn't save, about the target directory IS_WFD1975/MA/ not existing.
* I created IS_WFD1975/ in the right place, ran the command again, and now I get this: DoesNotExist at /dictionary/import_images/, Dataset matching query does not exist. See screenshot.
I see three options: 1) I am doing something wrong (please instruct me if so); 2) We hadn't yet created the batch import for images per dataset yet, with a subdirectory to select the language of the gloss that should match the file names; 3) There's a bug somewhere, but we did create the functionality.

**Comment by susanodd** [comment]
The owner / group might need to be www-data ?

**Comment by ocrasborn** [comment]
Not sure what's changed, but everything correctly imports now. The group of the files is wwwsignbank, not wwwdata. However, I do still get this error page at the end of the process:

DoesNotExist at /dictionary/import_images/
Dataset matching query does not exist.

**Comment by vanlummelhuizen** [comment]
@ocrasborn Those error messages without context are too general to find where they happen in the code. When you run into the same problem, please add more context. I am going to close this issue for now.
