### ISSUE TITLE
Cannot add items under Related Signs

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#706]
When I try to add a homonym (under Related Signs), I can select the Type of relation, but typing in the gloss field does not deliver any suggestions. Filling in an existing gloss and saving leads to an error.
(This is a symptom we've recently had elsewhere, but I can't find the issue, sorry. Feel free to merge these / please refer to it if you can find it.)

**Comment by vanlummelhuizen** [comment]
@ocrasborn Can you tell what the gloss is you tried to do this for? I just tried it for wesseltest3trala (id 3117) and I could add wesseltest6 as a homonym without any problem.

**Comment by ocrasborn** [comment]
@vanlummelhuizen Hm, for any gloss I tried just now (in two datasets), all is fine... I'll close this for now, and remember to include more details for the next bug report :-)
