### ISSUE TITLE
Make the list of lemmas searchable

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#708]
See #707 . Judging from the problem there, not being able to see a Lemma ID Gloss that is not actually 'in use', that is being linked to an Annotation ID Gloss, it'd be best to add a search functionality to the admin. Downside: that would not help non-admin users. Only me, essentially. So, could we make unlinked Lemma ID Glosses appear in the regular lemma search on the sign search page, and then list them as 'unlinked' somehow? Or perhaps to keep things organised for the user, create a separate search page for lemma search, that returns a list of lemmas with the annotation glosses linked to them?
Actually, the page "Show all lemmas" is already a step towards that goal; adding a search field on top there might also do the trick. And/or a button 'Search unlinked lemmas'?
Anyway, as you understand, please do think along and advise!

**Comment by susanodd** [comment]
I want to implement this, but I'm still working on #693 and still need to merge it.

**Comment by susanodd** [comment]
I'm working on this, it's nearly done.

**Comment by susanodd** [comment]
I'm not sure what to do about sorting.
For the Gloss List, sorting presented some problems due to blank fields.

**Comment by susanodd** [comment]
![lemmalist-query](https://user-images.githubusercontent.com/24272544/106459419-1e393300-6492-11eb-9cae-7bb84ec097e0.png)

**Comment by susanodd** [comment]
![lemma-query-English-test](https://user-images.githubusercontent.com/24272544/106468986-eedcf300-649e-11eb-9d29-064cf433a544.png)

**Comment by susanodd** [comment]
I thought I was going crazy. The second example has NGT and CSL_Shanghai selected.
Now when I search for test in English, the Protest glosses don't show up for NGT because it's not filled in for English.

The querying is working. But I'm not sure if "empty" needs to somehow be a search term to add functionality.
We don't have the notion of "published" for Lemmas, so the test lemmas also show up with Lemma Search.

**Comment by susanodd** [comment]
To compare, on the live server, here is a search on Lemma English test with datasets NGT and CSL_Shanghai.
The test glosses are not shown. And you see Chinese in the Annotations.

![gloss-search-lemma-test-english](https://user-images.githubusercontent.com/24272544/106470229-8abb2e80-64a0-11eb-8f64-3bb2af1eeb26.png)

**Comment by ocrasborn** [comment]
Yes, I understand @susanodd . We should really make all translations obligatory also for Lemma Glosses, just like Annotation Glosses. Perhaps you can create a separate issue for that?

**Comment by susanodd** [comment]
Searching has been put on github.
The Export CSV has revised to the results.

**Comment by susanodd** [comment]
I'm adding a scroll bar for Lemma results on the Update Lemma page, to be shown when the user has done a search on lemmas.

**Comment by susanodd** [comment]
![lemma-search-wrijven](https://user-images.githubusercontent.com/24272544/109503259-54ba9b80-7a9a-11eb-831b-543e975d6a62.png)


![lemma-update-handen-wrijven-b](https://user-images.githubusercontent.com/24272544/109503277-5ab07c80-7a9a-11eb-99c2-1da5323a27b9.png)

**Comment by Woseseltops** [comment]
Reviewed this. Nice touch add a scroll bar as well!
