### ISSUE TITLE
People get an error in trying to create an account

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#711]
See also #710 . No need to deal with this before Christmas, but it'd be good to take it up first in the new year.
<img width="803" alt="Screen Shot 2020-12-13 at 4 44 05 PM" src="https://user-images.githubusercontent.com/10242207/102688546-b2f41400-41f7-11eb-91d4-af3a32a78008.png">

**Comment by Woseseltops** [comment]
Looks like I forgot to restart the server after I removed some debugging stuff, sorry!
