### ISSUE TITLE
Are some fields of MissingSignFeedback not used?

### ISSUE THREAD

**Issue by vanlummelhuizen** [Signbank/Global-signbank#712]
In the model MissingSignFeedback there are some fields that are never in a form (or at least I couldn't find them):

https://github.com/Signbank/Global-signbank/blob/435071fbdd35c8bd2e6a897bacc867ea1358c063/signbank/feedback/models.py#L233-L252

Are they still used (other that display) and if yes, where?

**Comment by susanodd** [comment]
Those look like maybe legacy fields?

**Comment by ocrasborn** [comment]
Well, the fields largely (perhaps not all) are still in use, but we don't use them for this form, where people can suggest new signs to be added. In fact, this function we don't use at all at the moment, as it's more relevant to uses of Signbank as a dictionary. As that is still something we do want to pick up in the not too far future, I'd suggest to leave this issue low-priority but open for a while. OK @vanlummelhuizen ?

**Comment by vanlummelhuizen** [comment]
OK.

**Comment by susanodd** [comment]
This has been subsumed by #873
