### ISSUE TITLE
Make ALL text translatable

### ISSUE THREAD

**Issue by Woseseltops** [Signbank/Global-signbank#715]
The Catalan users discovered that there still are quite a lot of string that are not translatable at all.

* Most search box labels on the search page, and a few table headers
* Available dataset page
* Add new sign page 
* All of the recently added sign page
* All of the CSV import page

![image](https://user-images.githubusercontent.com/1909317/104748493-19664680-5752-11eb-8442-b328776c0ca6.png)

![image](https://user-images.githubusercontent.com/1909317/104748515-1ec39100-5752-11eb-9691-2d28d48ee031.png)

![image](https://user-images.githubusercontent.com/1909317/104748567-2aaf5300-5752-11eb-9fda-df956645d058.png)

![image](https://user-images.githubusercontent.com/1909317/104748584-2daa4380-5752-11eb-99c7-2ad0088b2cc0.png)

![image](https://user-images.githubusercontent.com/1909317/104748607-3438bb00-5752-11eb-913d-889e5d5bf452.png)

![image](https://user-images.githubusercontent.com/1909317/104748617-38fd6f00-5752-11eb-8fef-d41ccebaca2f.png)

![image](https://user-images.githubusercontent.com/1909317/104748634-3e5ab980-5752-11eb-8440-0461bd967048.png)

![image](https://user-images.githubusercontent.com/1909317/104748665-461a5e00-5752-11eb-82c1-db5f707408d7.png)

![image](https://user-images.githubusercontent.com/1909317/104748677-4adf1200-5752-11eb-886a-903166802875.png)

![image](https://user-images.githubusercontent.com/1909317/104748704-503c5c80-5752-11eb-900e-864b70fef935.png)

![image](https://user-images.githubusercontent.com/1909317/104748718-55011080-5752-11eb-9aac-6d4bc4cee48e.png)

**Comment by susanodd** [comment]
Quite a few of those are my fault.

**Comment by Woseseltops** [comment]
Don't worry about it. I promised Jaime I will fix this tomorrow. You can also work on it if you like, but please make sure all of your progress is somehow available for me tomorrow before lunch so I can pick up from there and make it available for the Catalans.

**Comment by susanodd** [comment]
Okay, I'm not that fast.

**Comment by Woseseltops** [comment]
Turns out my assumption that we simply forgot to make these texts translatable was wrong! The Catalans still had a number of `#fuzzy` strings in their .po file.
