### ISSUE TITLE
List compounds in which the selected sign appears under Relations to other signs

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#716]

**Comment by susanodd** [comment]
Okay, I'm going to start on this now.

**Comment by susanodd** [comment]
In the Relations View, what columns would you like for the compounds?

**Comment by susanodd** [comment]
Here's what it looks like. First a gloss with sequential morphology. Then the relation view of one of those compounds.

![gloss-sequential-morphology](https://user-images.githubusercontent.com/24272544/107032408-0b856d80-67b4-11eb-9aa6-6fe4782fc9dc.png)


![relations-view-compounds](https://user-images.githubusercontent.com/24272544/107032432-150ed580-67b4-11eb-9789-24ed8a3fa004.png)

**Comment by susanodd** [comment]
@ocrasborn, I'm not exactly sure what to call the compounds. In the wesseltest10 gloss (which I edited it myself making it be in Lemma WEBCAM), it looks like the Relations view is calling it WEBCAM all over the place, instead of wesseltest10.

(That has something to do with idgloss which is a property of model Gloss. Django uses that to print out glosses if you haven't specifically coded how to print them in a template.)

The Relations view shown above is for Gloss BRABANT-A (which is Compound part 2 of wesseltest10 aka WEBCAM.)

**Comment by susanodd** [comment]
@ocrasborn, do you (also) need it the other direction? In this example, the Relations view of wesseltest10 shows no Compounds.

**Comment by ocrasborn** [comment]
Hi @susanodd , in response to your two questions:
* Better use the Annotation ID Gloss than the Lemma ID gloss, if that's what you're asking.
* We don't need it in the other direction (this is already under the Morphology panel, that suffices).
In the mockup/screenshot above, I think spelling out the compound part is superfluous, better leave that out to keep it clean. Users can see at a glance in this example that it's the second part of the compound. One suggestion though to highlight that: make the BRABANT-A in this example appear in boldface, to strengthen the 'at a glance'.

**Comment by susanodd** [comment]
Point 2 has been pushed to github.

**Comment by susanodd** [comment]
Point 1 has been pushed to github.

**Comment by ocrasborn** [comment]
@vanlummelhuizen @Woseseltops , can this already be made live? @susanodd , were you done with the whole issue?

**Comment by susanodd** [comment]
Yes, this issue has been done for a while.

**Comment by vanlummelhuizen** [comment]
@ocrasborn I am discussing part of the way @susanodd implemented field choice colors. When this we are done, and all other things Susan built are also ok, I will put it live.

In a gereral sense, we are trying to find a workflow that will allow us to work on things separately but also make the code maintainable. Git can help us with that, but we are still finding out how we best apply it's features. Susan, @Woseseltops and I planned a video meeting next week to discuss this.

**Comment by ocrasborn** [comment]
Thanks for the update @vanlummelhuizen

**Comment by susanodd** [comment]
Issue #727 has been put on github. Kindly put theoddbranch live @vanlummelhuizen .
