### ISSUE TITLE
Errors in loading search results in recent days

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#719]
Several users have indicated, and I have now experienced it myself, that often search results don't all load. In my case, I should have one hit (searching for annotation gloss #X in NGT), but the hit doesn't display. In other reported cases, of the four reported hits, only three load. Reloading the page solved the issue for me, which leads me to think that it may be related to the 'closed database' issue #335 , which is also rearing its head in recent days.

**Comment by vanlummelhuizen** [comment]
I can confirm that the problem is caused by the "Cannot operate on a closed database" problem. After the page is loaded, some additional data is retrieved. A request is done for each individual Gloss and some of them fail due to the "Cannot operate on a closed database" problem.

The "Cannot operate on a closed database" problem should be tackled when @Woseseltops has finished #673 .

**Comment by susanodd** [comment]
I had the "Cannot operate...." earlier today. It was because I had the page open for a long time and was only comparing the Gloss template to that on my local server, but not updating the online page. It ended up giving an error when I reloaded, so I had to login again.
Maybe locks on Edit pages expire?

**Comment by susanodd** [comment]
Oh, I just realised. Because I keep pages open and just leave them, maybe I'm causing problems?
I don't seem to ever get automatically logged out. Eventually Firefox crashes.

**Comment by ocrasborn** [comment]
@susanodd , I do that all the time too, leave page open without logging out, can't imagine that's an issue

**Comment by vanlummelhuizen** [comment]
@susanodd I am not immediately dismissing the idea that leaving a Signbank page open for a while causes these problems, but I think it is not the case. It would mean something continues to run on the server for the whole time the page is open and  I cannot think of anything  doing that.

**Comment by susanodd** [comment]
I just got the "closed database" again.
In my only window I had a gloss in NGT showing with only NGT selected.

Then I opened a new tab window to check out the error in #721.
So I selected (in that new window) only the Dataset IS_WFD1975, so I could view the gloss Jam.
But it gave a "closed database" error.
So I shut the tab that was using NGT. Then reloaded the new page and it worked fine, no error.

**Comment by vanlummelhuizen** [comment]
@susanodd Are you able to replicate that situation and end up with the same results every time? In other words does this happen exactly the same way every time? If so, we may be able to find a problem there. If not, we are still dealing with a irregular problem.

**Comment by susanodd** [comment]
Not exactly. But a different error (on the live server just now, with two tabs open).

![sign-jam-is_wfd1975](https://user-images.githubusercontent.com/24272544/106885990-abbf9180-66e3-11eb-9863-6adb88b7be41.png)

![search-test-NGT](https://user-images.githubusercontent.com/24272544/106886005-af531880-66e3-11eb-8dcd-05c1b66993a0.png)

**Comment by susanodd** [comment]
When I first opened the search tab, it was still the same selected dataset. Then I changed the dataset in that tab and searched and went to PROTEST-A and got the error that it wasn't in my selected datasets, with a link to continue, which brought me back to the search page (shown). Then reloading the Jam sign (in a completely different selected dataset) did not give an error.

**Comment by susanodd** [comment]
Okay, and in the mean time (after working on something else), the Sorting results on reload now turns up empty, and the selected dataset is now IS_WFD1975.

**Comment by susanodd** [comment]
However, after resetting the dataset to NGT in the second tab, again, and repeating the previous, I can show the PROTEST-A gloss okay.
And on going beck to the JAM sign again, on reload, it shows an error, with a link backwards, which brings me to a previous query of jam. (With the previous dataset selected again in the header.)

As I'm deliberately trying to get errors, it looks like the two tabs are working independently, although I'm the same user. And my chosen dataset is different in each tab.

Perhaps it has to do with when the permission is checked and when the page is generated?

**Comment by susanodd** [comment]
This seems related to Sqlite.
