### ISSUE TITLE
Sorting is broken for the handshape search results

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#720]
In the list view of Handshapes, I can click the sort arrows at the top of the columns, something appears to happen, but sorting is not correctly executed.
https://signbank.science.ru.nl/handshapes/show_all/

**Comment by susanodd** [comment]
It works okay on the search_handshape page. 

So it's the show_all page (where no search form is shown). You're right, it looks like it thinks it's doing something, but isn't.

**Comment by susanodd** [comment]
Oh dear! There's some hardcoded languages in the template!

**Comment by vanlummelhuizen** [comment]
I am still working on removing hard coded language references. See alse https://github.com/Signbank/Global-signbank/issues/661#issuecomment-769074729

**Comment by susanodd** [comment]
I'm a bit confused actually.
On my local server, I don't have the "Show all handshapes" page. Only the "Zoek handvorm".

**Comment by ocrasborn** [comment]
Sorry @susanodd , you're right: there's only the search page. But since opening it from the menu shows all handshapes, I always think of it as such.

**Comment by susanodd** [comment]
Okay, I fixed this, now the show_all page can be sorted too.

**Comment by susanodd** [comment]
This issue is complete on github theoddbranch. It's waiting to be put live.

**Comment by Woseseltops** [comment]
Reviewed this. Solution / code style looks okay to me, but this might clash with #661 as said before.

**Comment by susanodd** [comment]
Yes, this needs revision after #661 has been completed.
