### ISSUE TITLE
Make translations for Lemma Glosses obligatory

### ISSUE THREAD

**Issue by susanodd** [Signbank/Global-signbank#722]

**Comment by vanlummelhuizen** [comment]
See also https://github.com/Signbank/Global-signbank/issues/708#issuecomment-770934925

**Comment by susanodd** [comment]
Okay, this was just changing required False to True for the form fields.

Issue #708 hasn't been put on the live server yet. It's on theoddbranch.

Here's the search and the Update. The required field is shown red when you try to do Update with it empty.
(The message to fill it in doesn't get captured by the screenshot)

![lemma-search-test](https://user-images.githubusercontent.com/24272544/109287322-b58c6e80-7823-11eb-8587-121a2dc95bb8.png)

![update-lemma-required](https://user-images.githubusercontent.com/24272544/109287343-bb824f80-7823-11eb-85a2-90e4e66df264.png)

**Comment by susanodd** [comment]
If you don't want to fill it in, you can go back to the list.

However, at the moment this goes back to the entire lemma list rather than the search results.
I'll revise this because it is unexpected.

@ocrasborn would you like the lemma search results in a scroll bar on the update page?

This to show up if you get to this page via the lemma search, not via a gloss detail edit.

**Comment by susanodd** [comment]
Okay (to self), I'm making a scroll bar on the Lemma Update page if the previous thing to get to the page was a Lemma Search.
That makes the most sense.
