### ISSUE TITLE
Create a script to automate deployments

### ISSUE THREAD

**Issue by Woseseltops** [Signbank/Global-signbank#724]
1. Store the hash from the current commit in a temp file
2. Pull from master branch 
3. Backup database
4. pip install -r requirements
5. Fix all permissions
6. Database migrations
7. Run all unit tests

In later phases, we could add:
* A rollback script, that checkouts the commit from the temp file and grabs the database you backed up.
* Automated rollback if the tests fail.
* A cronjob that runs the automated deployment script every x hours.

**Comment by susanodd** [comment]
Step 7 will fail at the moment.
There is an error in the test_Settings test, to do with the SWITCH_TO_MYSQL setting.
This test is still broken. I couldn't figure out how to fix it. If you comment it out, all the tests work.

**Comment by susanodd** [comment]
Okay, I sucessfully deployed the newest master branch.
I revised the tests, but only got rid of 2 of the failures.
There remain 3 failures.
One is the Settings test. (This also fails on my local server.)
One is the Documents, as shown above, because the create_test_db has not been applied.
The other is something to do with field choice lists. (There is a failure because one list has a length of zero.)
I suspect this also has something to do with create_test_db.

**Comment by susanodd** [comment]
One thing that is not working are the translations.
I successfully compiled them for NL. But they are not showing up on the Global website.
Does it need to be restarted?
I followed the instructions in the wiki and also touched the ini file.
This is slightly annoying because they work on my local server.

**Comment by vanlummelhuizen** [comment]
> I noticed in some of the Django sites that "trans" is now "translate".

`trans` seem the correct one for Django 1.11: https://docs.djangoproject.com/en/1.11/topics/i18n/translation/#trans-template-tag



> And here, https://stackoverflow.com/questions/12826101/django-translation-template-trans-something it says that this should have a comma after it: `LOCALE_PATHS = ( '/path/to/my/project/locale/', ) `
> 
> https://github.com/Signbank/Global-signbank/blob/713bd4722536a7610a6b81fd131442be062ecda0/signbank/settings/base.py#L14

For Django 1.11 it seems the default is a list: https://docs.djangoproject.com/en/1.11/ref/settings/#locale-paths

**Comment by susanodd** [comment]
Does the test database need to be generated separately from the deploy script?

**Comment by susanodd** [comment]
Success! The translations weren't visible because I hadn't restarted Global.

**Comment by susanodd** [comment]
There's a new test database now.

**Comment by susanodd** [comment]
Awesome! I just deployed all the newest translations!

Now the only thing is the tests. Some tests fail because they no longer match the feedback strings on the site because the of revised messages for translations.

**Comment by susanodd** [comment]
Okay, we're down to one test failure and one error arising during a test.
--- Failure in `test_Settings`:
https://github.com/Signbank/Global-signbank/blob/fab1b69bcc1a9a618599b3c6f331a1e2516ee2c2/signbank/dictionary/tests.py#L2460

`AssertionError: Lists differ: ['MODELTRANSLATION_LANGUAGES', 'SWITCH_TO_MYSQL'] != []`

--- And one error during `test_DatasetListView_ECV_export_permission_change_dataset` that a temp directory` glossvideos/temp_NGT ` can't be renamed.

https://github.com/Signbank/Global-signbank/blob/fab1b69bcc1a9a618599b3c6f331a1e2516ee2c2/signbank/video/models.py#L440-L444

**Comment by susanodd** [comment]
The test error related to the failed attempt to rename a video path (see previous comment directly above this one), I suspect it's related to this:

https://github.com/Signbank/Global-signbank/commit/791cf981bb1d43461bdbeac8a35707ed6d5267e4

https://github.com/Signbank/Global-signbank/blob/791cf981bb1d43461bdbeac8a35707ed6d5267e4/signbank/video/models.py#L380

https://github.com/Signbank/Global-signbank/blob/791cf981bb1d43461bdbeac8a35707ed6d5267e4/signbank/video/models.py#L438

**Comment by susanodd** [comment]
On the master branch, that is set to True:

https://github.com/Signbank/Global-signbank/blob/d20d2adcda09095b7e21a72d8b03477058d94674/signbank/video/models.py#L380

https://github.com/Signbank/Global-signbank/blob/d20d2adcda09095b7e21a72d8b03477058d94674/signbank/video/models.py#L460

**Comment by susanodd** [comment]
On my local server I hardly have any videos stored, so testing doesn't generate that error. But it used to, hence there was once a pull request for that setting, which was never merged because it couldn't be shown why it was needed.

**Comment by susanodd** [comment]
Now the only test error is for `test_Settings`

**Comment by susanodd** [comment]
I modified the Admin to allow removal of field choices with duplicate machine values.

That was one of the errors being generated in the tests:

`Duplicate machine value for  Location :  [('Location', '2', 'Neutral space > head'), ('Location', '2', 'Bottom')]`

**Comment by susanodd** [comment]
Now there's only the one machine_value 2 for Location and delete isn't offered because it's in use.

![field_choice_location_no_duplicate](https://user-images.githubusercontent.com/24272544/172648723-5deb6c9d-e66a-4696-a685-5129c56dcf3e.png)

**Comment by susanodd** [comment]
I generated a new test database so the test that was generating the message about the duplicate runs fine now.

**Comment by vanlummelhuizen** [comment]
@Woseseltops About the deploy script, we should also include `collectstatic` I guess. Agreed?

**Comment by vanlummelhuizen** [comment]
Perhaps take a look at https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

**Comment by Woseseltops** [comment]
Hey @vanlummelhuizen , I think this is a case of 'baat het niet dan schaadt het niet', but from the documentation you provided it is not clear to me what actual use case you have in mind?

**Comment by vanlummelhuizen** [comment]
@Woseseltops Are we talking about the `collectstatic` thing or the  deployment-checklist?

If about `collectstatic`, when deploying things with assets like images, css or javascript they should be in the static root, unless you have DEBUG set to... oh wait...

If about deployment set up, in general I find it refreshing to visit the Django docs once in a while. In this particular case it mentions several security issues that we did not use yet, e.g. [CSRF_COOKIE_SECURE](https://docs.djangoproject.com/en/1.11/ref/settings/#std:setting-CSRF_COOKIE_SECURE) and [SESSION_COOKIE_SECURE](https://docs.djangoproject.com/en/1.11/ref/settings/#std:setting-SESSION_COOKIE_SECURE), among others. Also, running `bin/develop.py check --deploy` gives some insight into what could be improved.

**Comment by susanodd** [comment]
@Woseseltops Create test dataset needs to be added to the deployment to accommodate testing after migrations.

**Comment by susanodd** [comment]
@Woseseltops please check the deploy.sh script again.

I had trouble with it earlier. It was complaining about the last line:
python "$ROOT"repo/bin/develop.py -k test

I added the flag --keepdb
(It seems the newest Django uses that instead of -k for keep)
I also removed the -k from it.
But it still complained about the -k
Then it started working okay.
But now the -k is there again.

I think it had problems because running "deploy.sh" was pulling another "deploy.sh" from GitHub master.
Now I have no idea what the correct form of the last line should be.

**Comment by vanlummelhuizen** [comment]
@Woseseltops For my understanding: this `deploy.sh` is only for deploying code changes, not full installs from scratch? The reason I ask is that we do not have a description of a full install, including the software requirements `ffmpeg` and `imagemagick`, as far as I know.  Perhaps time to write up a nice, complete README?

**Comment by susanodd** [comment]
@Woseseltops There seems to be something wrong with create_test_db

On deployment, it did not create a new test database, whereby the tests started failing with this:

`sqlite3.DatabaseError: database disk image is malformed`
 
SO I created a new test database by running:

`python bin/develop.py create_test_db`

(again, not sure if it was run or what).
And now the tests work!

It seems like it must have conked out while it was supposed to be creating it.
Is this possible?
Literally every single test was generating that message. So something was messed up with the test database.

But it's okay now. (Were you working on the server_specific settings or something? Or working on copying for backups?
I can't explain the error.)

**Comment by susanodd** [comment]
This seems to be working fine. Just don't deploy things end of the afternoon on Fridays. (The previous comment was related to attempt at deployment while backup was being done.)
