### ISSUE TITLE
Hide Settings menu for anonymous users

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#725]
The new Settings menu (#693) should only be accessible to Admin users. It is, but Anonymous users (people who are not logged in) still see it. I haven't tested it yet, but I assume non-admin users cannot access it anyway, right?

**Comment by vanlummelhuizen** [comment]
Just tested it and anonymous users cannot access any of the settings pages.

**Comment by ocrasborn** [comment]
I saw that too, @vanlummelhuizen , the request was to hide the menu altogether from their view. Not clear enough in my formulation perhaps. And in fact, please hide it from all non-admin users, while you're at it - or anyone else of course 😊

**Comment by vanlummelhuizen** [comment]
If you open a page in admin, there are advanced options where you can select one or more "Group required". The page will then only be shown to users in those groups. The only things is that there is no "admin" group. So either choose one of the existing group which cover the users you want, or add a new group for "admin" users.

**Comment by susanodd** [comment]
I coded it so that you have to be in Superuser to Manage Colors.
But there isn't a group as @vanlummelhuizen pointed out.

**Comment by ocrasborn** [comment]
No worries, @susanodd & @vanlummelhuizen : I restricted the display of the menu item to the group Publisher (which in practice now is only used for admins). Thanks @vanlummelhuizen for reminding me how this works.
