### ISSUE TITLE
Lookup of users in Manage Dataset fails

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#728]
I can no longer use the dataset management page, as the lookup of user names seems to be broken. When I type in the correct user name to revoke permissions and click the Revoke button, I get the error: "Username must be non-empty. Please make a selection using the drop-down list."

**Comment by susanodd** [comment]
Did you scroll in the dropdown to select the user, rather than type the name?

**Comment by ocrasborn** [comment]
That's the issue, @susanodd , the dropdown no longer appears.

**Comment by susanodd** [comment]
This is very weird!

**Comment by susanodd** [comment]
This might have to do with file permissions on dataset_edit.js
The usertypeahead function that's in that file isn't being loaded.

There was an issue with file permissions a while back (#663).
@vanlummelhuizen @Woseseltops ?

**Comment by vanlummelhuizen** [comment]
This problem occurs when you use signbank.cls.ru.nl. If you use signbank.science.ru.nl it works. I will try to  fix this now.

**Comment by vanlummelhuizen** [comment]
I decided that signbank.CLS.ru.nl is THE global signbank url and not signbank.SCIENCE.ru.nl (which still works for most things). So now the problem of this issue will occur on signbank.SCIENCE.ru.nl and not signbank.CLS.ru.nl. See also #718.

**Comment by Woseseltops** [comment]
Quick question @vanlummelhuizen , wouldn't it be more logical to just make the url relative here: https://github.com/Signbank/Global-signbank/blob/87a408187d87d068f073b074900ee18d4e42c89c/media/js/dataset_edit.js#L195 , that is just make the call to '/dictionary/ajax/user/' instead of 'https://signbank.cls.ru.nl//dictionary/ajax/user/'

**Comment by vanlummelhuizen** [comment]
@Woseseltops I think relative urls are better where possible. This was the first and simplest solution I thought of. I think the  URL and PREFIX_URL could and should have a more elegant solution. See also #505.

**Comment by susanodd** [comment]
Is this issue solved?
It works on my local server.

**Comment by ocrasborn** [comment]
It works @susanodd if users remember to go to signbank.cls.ru.nl, but since we've been at science.ru.nl for so long, this will keep us scratching our heads for a while I expect. If there's a technical solution to get around this, that'd be good, but I would not qualify it as 'high priority'.

**Comment by vanlummelhuizen** [comment]
Best solution I can think of right now is redirecting signbank.science.ru.nl to signbank.cls.ru.nl. I think this can be done in the Apache configuration. @Woseseltops, do you agree?

**Comment by susanodd** [comment]
These files contain hardcoded "science.ru" references:
https://github.com/Signbank/Global-signbank/blob/e145fc9b10c46e137447c9827957aad48274ad94/signbank/registration/templates/registration/dataset_access_granted_email.txt#L3-L6

AND

https://github.com/Signbank/Global-signbank/blob/e145fc9b10c46e137447c9827957aad48274ad94/signbank/dictionary/migration_readme.txt#L10

**Comment by susanodd** [comment]
This is working on Global. Perhaps it can be closed?

**Comment by susanodd** [comment]
I checked it again and it's still working okay.
