### ISSUE TITLE
Display refinement to Admin Gloss

### ISSUE THREAD

**Issue by susanodd** [Signbank/Global-signbank#739]
There are some large text areas inside of the Gloss Edit of Admin.
I noticed this when checking the Other Media display there to see what paths are shown.
This issue is meant to refine the display there. Some of the code is legacy.

**Comment by susanodd** [comment]
Okay, this is not exactly related to this issue, but it is something weird with a test gloss (on the live server).

Here, the url has a circular path. (@Woseseltops @vanlummelhuizen ):

![weird-url](https://user-images.githubusercontent.com/24272544/114181321-a8de5880-9941-11eb-9f8b-db06a89719cf.png)

**Comment by susanodd** [comment]
I removed all the duplicate stuff at the end of the path and reloaded it. Now it's disappeared from the url.

https://signbank.cls.ru.nl/dictionary/gloss/8822/dictionary/gloss/dictionary/gloss/dictionary/gloss/dictionary/gloss/37052

https://signbank.cls.ru.nl/dictionary/gloss/8822/

**Comment by susanodd** [comment]
THIS ISSUE

Here is a screenshot of the Glosses section of Admin on the live server.
Observe that it looks empty.

![admin-glosses-top-signbank](https://user-images.githubusercontent.com/24272544/114182691-34a4b480-9943-11eb-8c48-e9ccf7aa8ce1.png)

**Comment by susanodd** [comment]
THIS ISSUE STEP TWO

The above prompted me to investigate this on my local server. I modified the display of glosses to also show the ID, the Lemma (the same as above), followed by the is_public toggle.

Here is the same "top" rows, followed by the rows where Lemma's start to be shown.

![admin-glosses-top-local](https://user-images.githubusercontent.com/24272544/114182872-759cc900-9943-11eb-944e-2f18d84cf4f0.png)


![admin- glosses-mid-local](https://user-images.githubusercontent.com/24272544/114182894-7df50400-9943-11eb-8b5a-9bbbb552e222.png)

**Comment by susanodd** [comment]
In the database, there's a rather large number of totally empty glosses. They don't have a Lemma so they're not in a dataset. The database is all but empty for those rows. It's not possible to access them except for in the Admin.

I'm working on making the Glosses Admin less cumbersome. I revised it to show the ID because all of those empty glosses cause problems trying to search for anything.

**Comment by ocrasborn** [comment]
Ah, that'll be very helpful @susanodd ! thanks

**Comment by susanodd** [comment]
Update. The cause of the extremely slow Gloss Admin was the Lemma field. I changed it to be read only. Now it's much faster.

What it was doing before was "getting ready" a big pull-down of ALL the existing Lemma objects with all the translations.
I noticed that if I tried to click on the Lemma to see what it was, my browser and indeed my computer would freeze up.
Then a very very long time later, I noticed there would be a pull-down for lemma's where even combinations with Farsi were being listed. (Lemma's for totally different Datasets and languages not used in the Dataset of the current gloss.)

I made all the Gloss fields be read only. Including the Lemma field.
Now it's superfast to browse a single gloss's content.
Indeed, all of those "empty" glosses actually have some data in them!! (See screenshot above.)
Now it's possible to look inside them.

I'll try to get this finished and put onto github. I need to keep checking some of the classes. I'm kind of doing it by trial and error since I had no idea what was wrong with it.

**Comment by susanodd** [comment]
Here are a couple of screenshots of a gloss that shows up "empty" looking area of the Glosses list (see above).
It looks empty because there was no lemma fields filled in when it was created.
But as you can see, there are fields filled in.

![admin-gloss-38188-blank-lemmas](https://user-images.githubusercontent.com/24272544/114700446-cdf81000-9d21-11eb-9746-023ba5b02d32.png)

![admin-gloss-38188-details](https://user-images.githubusercontent.com/24272544/114700476-d3edf100-9d21-11eb-808d-320b62053ab9.png)

**Comment by susanodd** [comment]
So it would seem that for creating new glosses, some additional "interface" is needed so that "empty" glosses aren't "invisible".
I can see this gloss inside of Admin.

But an "error message" is generated when trying to view the above gloss on Signbank.

An error message is shown (to prevent crashing) when a requested Gloss does not have a Lemma.
This is because the Dataset is stored inside of Lemma, not inside of Gloss.

So for this example, although we can see that English and Japanese are filled in for Annotations, the "Dataset" is undefined because there is no Lemma.

![dictionary-gloss-38188-missing-lemma](https://user-images.githubusercontent.com/24272544/114701343-fc2a1f80-9d22-11eb-8d86-4296c8eb751a.png)

**Comment by susanodd** [comment]
I can revise the new "read-only" Gloss Admin to allow adding a Lemma if this is not defined.
Possibly together with choosing a Dataset (that the user has access to), and restricting Lemma's to that.
I guess if the user is a Dataset Manager that the user ought to be able to edit a gloss even if it hasn't got a Lemma (instead of showing the error message) ?
@ocrasborn what do you suggest?

It seems possibly very annoying if it looks like glosses have disappeared.
We have a method (url) for finding glosses that don't have a Dataset. But when I tried searching for Glosses that don't have a Lemma, it doesn't work really because everything is protected by allowing users access to Datasets they have permission for, so with guardian checks, it's unclear if a user should have access to a Gloss without a dataset.

However, the Admin can look at these Gloss objects. So probably just add Lemma update there?

**Comment by susanodd** [comment]
Here are some additional screenshots for a test sign.
It shows the new compact read-only tabular inline display.
Note that for these sections where other "objects" are shown, the ID of that object is shown in the left column.
I did that to facilitate debugging so that we can locate an object in the database table if necessary.

Qua formatting, I added a box outline on the "Delete row" column. (Delete happens if you save the gloss, you can click and unclick on things before you want to save. This is as before. But now you can only delete, not alter rows.)

![admin-glosses-revised-search](https://user-images.githubusercontent.com/24272544/114704153-917ae300-9d26-11eb-85bb-53917063bbd8.png)


![admin-gloss-change-inlinetabular](https://user-images.githubusercontent.com/24272544/114704177-9770c400-9d26-11eb-9078-2eaac1898c45.png)


![admin-gloss-change-translations-othermedia](https://user-images.githubusercontent.com/24272544/114704196-9cce0e80-9d26-11eb-9b03-6d5488b1b7b8.png)

**Comment by ocrasborn** [comment]
Hi @susanodd , I think being able to search allows admins sufficient means of digging into individual glosses. We shouldn't need to do large-scale maintenance in the admin, but rather let dataset managers do that through CSV export/import in the interface. So please don't invest too much time in making the admin very 'useful' here.

**Comment by susanodd** [comment]
Hi @ocrasborn, I am adding some minimal functionality to help repair things.
Mostly, I've removed editing functionality. (Admin Glosses)

That fields are read-only now forces users to update things on the site, rather than in the admin. I was concerned that because it was so slow it would be possible to inadvertently modify something just by clicking around wondering why nothing was happening.

This is akin to dangling pointers. To be able to see what objects there are that are not connected to anything. Because there were all those duplicate field choices before, then it seems that if there is data stored that's not connected to anything this could potentially slow the system down. It will also help us track down glitches. Seeing that there are glosses without datasets, then we can use the admin to assist to see if the interface doesn't catch something.

**Comment by ocrasborn** [comment]
OK @susanodd !

**Comment by susanodd** [comment]
This has been pushed to github branch admin_issues_739_682.

**Comment by susanodd** [comment]
LemmaIdgloss Admin, can filter on Dataset

![admin-lemmaidgloss-1](https://user-images.githubusercontent.com/24272544/116527682-3f67bf00-a8db-11eb-946f-2fd405e8cace.png)

Example LemmaIdgloss with unknown Dataset, it shows the ID in the header

![lemma-idgloss-unknown-dataset](https://user-images.githubusercontent.com/24272544/116527704-47276380-a8db-11eb-936c-fe285d4f395e.png)

LemmaIdgloss ASL single translation language, it's not possible to add additional translations, only edit the existing

![admin-le mmaidgloss-ASL-single-translation](https://user-images.githubusercontent.com/24272544/116527747-51e1f880-a8db-11eb-916b-f47005b3d78a.png)

**Comment by susanodd** [comment]
LemmaIdgloss Filter Kata Kolok

![admin-lemmaidgloss-filter-katakolok](https://user-images.githubusercontent.com/24272544/116528241-e3516a80-a8db-11eb-8050-017aa2d30650.png)

LemmaIdgloss Kata Kolok example with only one translation, additional translations can be added in the appropriate languages

![admin-lemmaidgloss-katakolok-translations](https://user-images.githubusercontent.com/24272544/116528368-0c71fb00-a8dc-11eb-8e3f-ee6494b8e380.png)

![admin-lemmaidgloss-katakolok-translations2](https://user-images.githubusercontent.com/24272544/116528466-27446f80-a8dc-11eb-8d3c-d17f3326d32f.png)


![admin-lemmaidgloss-katakolok3](https://user-images.githubusercontent.com/24272544/116528385-1267dc00-a8dc-11eb-86e4-c3567904c6d1.png)

**Comment by susanodd** [comment]
LemmaIdgloss filter on Hebrew

![admin-lemmaidglosstranslation-filter-hebrew](https://user-images.githubusercontent.com/24272544/116528532-3aefd600-a8dc-11eb-96a2-9c5eec399938.png)

**Comment by susanodd** [comment]
I'm of the opinion that a most useful usage of Admin LemmaIdgloss would be to tackle type errors in translations. One can now filter on translation languages at the LemmaIdglossTranslation level, and on dataset at the LemmaIdgloss level.

**Comment by susanodd** [comment]
I know I'm the one who opened this issue.
Has anybody got any feedback on the new Admin, or is it all right? @ocrasborn ?

**Comment by susanodd** [comment]
This is on Global.
