### ISSUE TITLE
Small interface improvement on Select Datasets page

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#740]
There are three buttons now on the Select Datasets page, two at the top, one at the bottom. There's a natural order, the 'save selection' at the bottom follows after having put checkmarks in the list. Now that the list is getting longer, it'd be helpful to have all three buttons both at the top and at the bottom, so that I'll have to scroll less often.

**Comment by Woseseltops** [comment]
Duplicated them, so you have three buttons above and below! Gave them a similar appearance as well.

Also, because this is so small, did it on the master branch directly instead of creating a seperate branch and pull request for this!

**Comment by ocrasborn** [comment]
Such small things that make me happy :-)
