### ISSUE TITLE
Replace h by H in the name of the tab "Revision history"

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#741]
cf. capitalisation of the tabs Frequency View and Relations View, e.g.
(Yes, how small can an issue be!)

And while your at it, it might pay off to go through the English interface for 15 minutes to spot other inconsistencies (Menu item names?)

**Comment by susanodd** [comment]
This is done. It's in a queue of updates now.

**Comment by susanodd** [comment]
This has been pushed to master branch.

**Comment by susanodd** [comment]
This is live on Global. (Already for quite some time.)

**Comment by susanodd** [comment]
I revised all the English page titles in Admin.

**Comment by susanodd** [comment]
This issue has been subsumed by #746.

**Comment by susanodd** [comment]
The capitalisation has been included in #703.
