### ISSUE TITLE
Make capitalisation of interface words more systematic

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#746]
Sometimes we use initial caps for content words in English, sometimes not. It'd be good to make this systematic at some point. Possibly there are guidelines for this (W3 consortium? accessibility guidelines?).

**Comment by susanodd** [comment]
Yes, indeed there is a W3 page.
https://www.w3.org/WAI/tips/designing/#tocheading

**Comment by susanodd** [comment]
I've changed nearly all of the labels in the forms to caps.
There are some long phrases where it may be nicer to change it to a shorter phrase, such as these from `GlossSearchForm`:

- Search for gloss of related signs
- Search for gloss of foreign signs
- Search for gloss with this as morpheme

**Comment by susanodd** [comment]
One thing about the translations, when working on #748, one of the labels wouldn't translate if caps were used, so I left it in lowercase. 

https://github.com/Signbank/Global-signbank/blob/e590a23c03a796a2094acc047fd66c39be2027bf/signbank/dictionary/templates/dictionary/glosstags.html#L22

It would seem that the translations are also dependent on capitalisation?

**Comment by susanodd** [comment]
Some of the capitalisations will require a migration to change the label in the model.

**Comment by susanodd** [comment]
Here is a strange quirk.
Observe the heading text `"Search by Language and Basic Properties"` in the Gloss List View template code (master branch):

https://github.com/Signbank/Global-signbank/blob/e590a23c03a796a2094acc047fd66c39be2027bf/signbank/dictionary/templates/dictionary/admin_gloss_list.html#L471


This should be translated to whatever language is set. But this is not being done on Global.
Here is the page with NL set, as viewed on Global:


![global_zoek_op_taal_nl](https://user-images.githubusercontent.com/24272544/167388826-6bf68004-174f-4100-848c-f01964ec3cd7.png)


Here is the same page with NL set, as viewed on my local server:

![local_zoek_op_taal_nl](https://user-images.githubusercontent.com/24272544/167388925-73ac6b13-4819-45de-8873-d94b42960909.png)


For some reason, Global isn't using the translations!
(@Woseseltops maybe some translations didn't get ported to lightning?)

**Comment by susanodd** [comment]
The majority of changes have been made.
Those that remain are 

- verbose names in models.py (requires migration), and 
- some lengthy labels in search forms (as shown above).

Aside from those, this has been pushed to branch `title_caps`.

**Comment by susanodd** [comment]
This is live now.
