### ISSUE TITLE
Dialog button UI: make the 'nevermind' option a neutral color instead of green

### ISSUE THREAD

**Issue by Woseseltops** [Signbank/Global-signbank#749]
Encountered in #733, following this discussion: https://ux.stackexchange.com/questions/49991/should-yes-delete-it-be-red-or-green

We have in at least two locations:
* Lemma view: delete row
* Lemma view: delete all

Perhaps more?

**Comment by susanodd** [comment]
This has been pushed.

**Comment by susanodd** [comment]
This is in the commits:
https://github.com/Signbank/Global-signbank/commit/c419f836e32ee3c5d84901346ad5dd4f5e121a25

**Comment by susanodd** [comment]
This can be closed.
