### ISSUE TITLE
Add favicon to signbank website

### ISSUE THREAD

**Issue by richardbank** [Signbank/Global-signbank#75]
Please add attached favicon to the signbank website. (Rename favicon.png to favicon.ico; I had to rename due to github restrictions.)

![favicon](https://cloud.githubusercontent.com/assets/10399929/8744386/1ad86fa4-2c77-11e5-80a6-769b03180368.png)

**Comment by Woseseltops** [comment]
Ah, that's an easy one :).

Two remarks:
* I kept the png extension; let me know if there's a reason to switch to .ico .
* In the browser, the icon is even smaller, making the text hard to read. We could consider to create a very minimalistic logo for Signbank one day, which is recognizable even when the logo is small. Something along the lines of this:

![](https://t2.ftcdn.net/jpg/00/91/18/53/500_F_91185304_OM3svaeisjQskJkH3j64OsjxDY3oj4dy.jpg)
![](https://s-media-cache-ak0.pinimg.com/736x/13/83/74/138374d6c0e39bcbd1d0a8a863879d53.jpg)
![](https://stocklogos-pd.s3.amazonaws.com/styles/logo-medium-alt/logos/image/1426070801-f762cbcc1e7c0c6c5835dc51ff567b59.png?itok=lrOStnvJ)

**Comment by ocrasborn** [comment]
Good idea. We might have to reconsider the name altogether, if we'd be housing multiple languages with one system, "Universal Signbank" wouldn't be the most catchy name, and Signbank is already in use by others, too.

**Comment by Woseseltops** [comment]
Already done in other issue.
