### ISSUE TITLE
Change order of columns on Manage Datasets page

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#752]
The new column to download a CSV file with the links was put between the two upload columns for the frequency functionality; please put those two back together again. I have no preference for where to put the download CSV column.

**Comment by susanodd** [comment]
Okay, this has been done. It's awaiting other changes to be merged.

**Comment by susanodd** [comment]
This is live.
The Hyperlink download button for CSV is before the two columns for EAF.
Perhaps the headers are not clear because the Metadata header has CSV in it?

**Comment by ocrasborn** [comment]
Thanks @susanodd ; I think the headers are fine like this, explaining users what is what will be something we take up in the manual.
