### ISSUE TITLE
Escape translations that will be sent to Javascript

### ISSUE THREAD

**Issue by Woseseltops** [Signbank/Global-signbank#754]
When Catalan Signbank is set to Catalan, we get a Javascript crash:

![image](https://user-images.githubusercontent.com/1909317/121702325-0faef800-cad2-11eb-9a9d-4e8b25757c7d.png)

**Comment by susanodd** [comment]
I did a search of "turn_off_edit_mode_str" and I find it with:

`var turn_off_edit_mode_str =  '{% trans "Turn off edit mode" %}'`

Is there a reason not to let Django do this in `trans`?

**Comment by vanlummelhuizen** [comment]
@susanodd I think the problem here is that there is a quotation mark in the translation: "... d' ...". that ends the Javascript string prematurely.

**Comment by susanodd** [comment]
@vanlummelhuizen yes, I can see that. But why is the code in this form? Have we not been getting rid of hard-coded languages?

What are the implications of this issue? Do the independent javascript routines need to escape the variables they receive?
Or is this a syntax error? How did this variable get filled in (the right half)? Did Django generate that?

**Comment by vanlummelhuizen** [comment]
> Have we not been getting rid of hard-coded languages?

@susanodd This is not a hard-coded language as far as I can see. The code `{% trans "Turn off edit mode" %}` replaces itself with a translation for "Turn off edit mode" in the current language. The current language is variable, not hard-coded (see also https://docs.djangoproject.com/en/1.11/topics/i18n/translation/#trans-template-tag). 

The replacement is done inside two single quotes denoting a Javascript string. If the translated string contains a single quote that is not escaped, as is the case here, the Javascript string is ended prematurely, resulting in an error. 

So, the translated string needs to be escaped along with the translation before it is placed between the two single quotes.

**Comment by Woseseltops** [comment]
This could be a solution: https://stackoverflow.com/questions/22469235/complicated-quote-escaping-in-django-template-translations

**Comment by Woseseltops** [comment]
Turned out to be a relatively simple fix, could all be done inside the template. Did not do an exhaustive search for all translations that end up in Javascript strings, so we might need to reopen this issue if more is discovered.
