### ISSUE TITLE
Add another relation between signs

### ISSUE THREAD

**Issue by Woseseltops** [Signbank/Global-signbank#764]
Requested by Julie:

> Add a new relation under "relations to signs" - our current "see also" is overused so I'd like to add one relationship in particular "handshape paradigm" which we will use to capture relationships between signs where they have the same phonological form but different handshapes (e.g., numeral incorporation sets, initialized sets eg GROUP, CLASS, FAMILY, etc).

Should be a small task.

@ocrasborn , do we want this for the Global Signbank as well?

**Comment by susanodd** [comment]
The relation choices are defined by a constant in models.py

https://github.com/Signbank/Global-signbank/blob/94dbe93ee7552b7d9cd19416ee29b86d5d18dd61/signbank/dictionary/models.py#L1723-L1730

**Comment by susanodd** [comment]
Related to this, I've made improvements to Gloss Relations View.

**Comment by ocrasborn** [comment]
@susanodd , yes, let's add this for Global SB as well.

**Comment by susanodd** [comment]
Okay, on the live server something got messed up with the display of minimal pairs in the Related Signs View. The contrasting field values are not displayed anymore.
This could have something to do with the space of time between this branch first being created and the numerous updates via other branches in the between time.

**Comment by susanodd** [comment]
@Woseseltops  is there any reason why on MY SERVER the minimal pairs show up correctly, but on the live server they do not? (Compare the screenshots below)

https://signbank.cls.ru.nl/dictionary/gloss_relations/349

(screenshot)

![relations_view_349_live_server](https://user-images.githubusercontent.com/24272544/151545143-740cb44a-7c35-43a3-b59c-8d96c691e43b.png)


This is the same page on my server:

![relations_view_349](https://user-images.githubusercontent.com/24272544/151544909-5d792fec-9390-4378-a40d-55bb5b47c199.png)

**Comment by susanodd** [comment]
@Woseseltops 
I'm on branch relations_between_signs for this issue.
I merged it with the most recent master.
It's only one commit ahead of the master, (code for adding the new relation).

I'm not able to fix the issue of the minimal pairs (screenshot) on the live server because it doesn't show up on my server!
Is there some file missing on the live server?

**Comment by susanodd** [comment]
@Woseseltops , it's fixed now! Thanks!!

**Comment by susanodd** [comment]
I added the code for displaying the new Handshape Paradigm relation to the Related Signs View.

Here's a silly example.


![relationsview_paradigm](https://user-images.githubusercontent.com/24272544/151553380-a74b2d76-04e2-4adf-9829-0cce597a3a8f.png)

**Comment by susanodd** [comment]
@Woseseltops does this look alright? It's implemented now.

**Comment by susanodd** [comment]
@Woseseltops this has been in the pull requests for a while now. Any chance of merging it?

**Comment by Woseseltops** [comment]
Sorry this one took me so long to review!

**Comment by ocrasborn** [comment]
@Woseseltops , did you reopen this to implement it on Global SB following ASL SB? Because I don't see the option yet in Global. Or for another reason?

**Comment by susanodd** [comment]
I have the newest version of master branch (Global SB) on my local server. It's working fine there.
Perhaps it's not on the live server yet?

**Comment by susanodd** [comment]
This is on the live server now, @ocrasborn.
