### ISSUE TITLE
User registration is broken

### ISSUE THREAD

**Issue by DoorSpruijt** [Signbank/Global-signbank#776]
An intern trying to register encountered this error, and I was able to replicate it myself. 

![PrtScrnError](https://user-images.githubusercontent.com/91131283/136376137-2cbdb0bb-adfc-4935-b110-97cd6f10c86a.png)

**Comment by ocrasborn** [comment]
This issue is identical to #755 , the error message may help @Woseseltops fixing this

**Comment by Woseseltops** [comment]
Forgot the Postfix installation, so it crashed when trying to send an email. After installing it works!
