### ISSUE TITLE
Display available and selected datasets in the header for anonymous users

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#781]
See #780 . For the same reason, we need to display available (public) and selected datasets for anonymous users in the header, like we do for logged-in users. Now, anonymous users see a red header with just the logos and name, but not the datasets.
* To not confuse these users, let's only display the datasets that are actually available to them.
* Note: these are not so much datasets that logged-in users can apply for access to (these get a checkmark under 'Is public' for that dataset in the admin), but datasets that have any glosses that have the checkmark 'In dictionary' under Publication Status set to true.

**Comment by susanodd** [comment]
I've implemented this using a session variable, since anonymous users do not have an account. For users with an account, the selected datasets is stored in the database and retrieved when the user logs in again.

**Comment by susanodd** [comment]
Regarding the display of datasets  for which there are public glosses, would this also be for logged in users?

**Comment by susanodd** [comment]
Here is what this currently looks like for test user_dataset. This user only has access to two datasets.

![available_datasets_test_user_dataset](https://user-images.githubusercontent.com/24272544/146002397-f7d78f79-751d-4864-b599-4c1978ed03e5.png)

![select_datasets_test_user_dataset](https://user-images.githubusercontent.com/24272544/146002418-340beaf3-3418-424a-bf9c-bb05d2a727eb.png)

**Comment by susanodd** [comment]
See #780 for screenshots of the menu bar with (public) datasets for anonymous users.

**Comment by susanodd** [comment]
![anonymous_menu_EmblemsNL](https://user-images.githubusercontent.com/24272544/146010066-becabdd8-830b-442d-ab00-3805f366205a.png)

**Comment by ocrasborn** [comment]
> Regarding the display of datasets for which there are public glosses, would this also be for logged in users?
No, logged in users should always see all datasets.

**Comment by susanodd** [comment]
@Woseseltops I can't figure out how to put the Select Datasets in the Menu for Anonymous Users.
I gave group Guest permission to view this page, but that did not suceed in putting it into the header menu.

**Comment by susanodd** [comment]
Okay, this is fixed now! i had to remove all the allowed groups, since everybody can view it now in the menu.

**Comment by susanodd** [comment]
This is live now.
