### ISSUE TITLE
Problems with Signbank Lexicon Service in ELAN

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#784]
This is an older problem that was already on @vanlummelhuizen's plate. I was not able to log in in Signbank from ELAN, for an EAF file for which a connection to the Signbank lexicon service was specified. I asked Han Sloetjes, lead ELAN developer, to test the current state, and he returned the following report:
-----------------
Inloggen bij Signbank lukt en ik heb inmiddels wat naar de ELAN extensie gekeken.
Bij de eerste poging om vanuit ELAN in te loggen bij de webservice, resulterend in een popup met foutmelding, zag ik een melding in de log, beginnend met
WARNING: Invalid cookie header: "Set-Cookie:...

Hoewel het hier gaat om een 'warning', ben ik toch even gaan zoeken hoe dit te verhelpen, heb een kleine aanpassing gedaan in de bron code en een nieuwe jar gebouwd. Echter, opnieuw resulterend in een foutmelding over het niet kunnen verbinden met de Lexicon Service. Na wat zoeken (sommige fouten werden nog niet gelogd) bleek de oorzaak van het probleem een '404 Not Found' te zijn (ook in de oorspronkelijke situatie).

De url van de webservice is 
https://github.com/Signbank/accounts/login/?api=yes

en ook als ik via curl verbinding probeer te leggen:
curl -v https://github.com/Signbank/accounts/login/?api=yes
bevat het resultaat o.a.
< HTTP/1.1 404 Not Found 

Het lijkt er dus op dat de webservice offline is, of igg niet normaal functioneerd. Dat kan ik verder niet nakijken, maar dit probleem lijkt niet aan de extensie te liggen. Misschien is er ook een probleem met de extensie, maar dat kan pas verder onderzocht worden als de service weer functioneert.

**Comment by Woseseltops** [comment]
Hi @ocrasborn , I would be surprised if that Github URL is correct... perhaps some copy/paste error? 

The term 'Lexicon service' is not used in the code, so not 100% sure what functionality you are referring to, but my best is the package functionality. This is available via https://signbank.cls.ru.nl/dictionary/package/ (but it requires an authenticated user) .

**Comment by vanlummelhuizen** [comment]
@ocrasborn Is this still an issue? As @Woseseltops pointed out, you should not use github.com in your url. Instead, use https://signbank.cls.ru.nl.

The term 'lexicon service' is the term I use in the Elan extension code because this extension is not limited to Signbank.

**Comment by DSRU** [comment]
@ocrasborn @vanlummelhuizen can I check if there is anything we need to do on the newly established https://signbank.nzsl.nz/ end to enable a lexicon connection? When I try to add the above URL as a Signbank lexicon service, I can't click 'next'. Any changes to the url cause an error. ECV is working.

**Comment by vanlummelhuizen** [comment]
I am closing this issue because it seems there is no problem anymore.
