### ISSUE TITLE
'Multiple objects found' error when trying to log in with email address

### ISSUE THREAD

**Issue by Woseseltops** [Signbank/Global-signbank#788]
Reported by ASL Signbank users
[MultipleObjectsReturned at _accounts_login_.pdf](https://github.com/Signbank/Global-signbank/files/8047332/MultipleObjectsReturned.at._accounts_login_.pdf)

**Comment by ocrasborn** [comment]
@Woseseltops I added the ASL label so I can filter myself for things that they reported (although they might be relevant for Global as well)

**Comment by susanodd** [comment]
For Global, I'm unable to replicate this error on my local server. (With send_mail changed to print statements, etc.)

I double checked that it's not raised by using an email as a login. That's actually not possible because @ is a special character.

**Comment by susanodd** [comment]
It looks like ASL might have older code for registration/forms.py.
Global is from 8 months ago, whereas the ASL branch is from 3 years ago.

**Comment by susanodd** [comment]
Okay, I found the place where the error arises. It's some Django supplied code for authentication.

It's looking at the email address.
However, we are not allowing to create accounts with the username being an email address, because @ocrasborn was using his own email for many accounts.

**Comment by susanodd** [comment]
I made a simple change to the authentication so that the username is looked up.
Now an error message is shown if one has entered e.g., an email (i.e., not a username).

![fouteusername](https://user-images.githubusercontent.com/24272544/154258835-fe89dd2d-1ddc-4baf-89e0-fb9563c9a46c.png)

**Comment by Woseseltops** [comment]
Wow good find @susanodd ! So the error probably was not referring to the individual account entered, but to the fact that there were multiple accounts with the same email address in general.

Fix still needs to be confirmed once live.

**Comment by susanodd** [comment]
This works correctly on the live server.
