### ISSUE TITLE
Remove obsolete frequency fields from settings

### ISSUE THREAD

**Issue by susanodd** [Signbank/Global-signbank#798]
With the introduction of the GlossFrequency model, the dynamic calculation of frequencies, and the dynamic calculation of regions from the data, the initial hard coded regional frequency fields are no longer needed. These can be removed from the settings.

For example, of the following, only the first two fields are used now.

```
FIELDS['frequency'] = ['tokNo','tokNoSgnr','tokNoA','tokNoSgnrA','tokNoV','tokNoSgnrV','tokNoR','tokNoSgnrR','tokNoGe',
                       'tokNoSgnrGe','tokNoGr','tokNoSgnrGr','tokNoO','tokNoSgnrO']
```

**Comment by Woseseltops** [comment]
I indeed think these fields can be removed, they don't seem to be used in the code anywhere. Weird that these were in the default settings by the way (as opposed to the installation specific one).

Two questions for @susanodd :
* I think that, by extension, the gloss fields these settings refer to can also be removed, right? Would cause a migration file of course.
* In the Global SB specific settings file, I also see 

https://github.com/Signbank/Global-signbank/blob/06efaaa896092c452d16ca8e793c4c088f1226ff/signbank/settings/server_specific/global_sb_new_aj.py#L64-L95

Looking for references to this in the code, I encounter this

https://github.com/Signbank/Global-signbank/blob/7c18b0ce544ec70bcbca3ce772ad8344a1ddd42f/signbank/dictionary/adminviews.py#L3532-L3542

and this

https://github.com/Signbank/Global-signbank/blob/8f7d25b73a30153f23cf4be5af5b38265da39698/signbank/dictionary/templates/dictionary/gloss_frequency.html#L59-L61

Any idea what this is?

**Comment by susanodd** [comment]
The only Gloss frequency fields that are still used are the two that overlap with ASL:
https://github.com/Signbank/Global-signbank/blob/e590a23c03a796a2094acc047fd66c39be2027bf/signbank/dictionary/models.py#L709-L710
(These are computed dynamically when the corpus is updated.)

The hard coded `**settings**` for **regions** in Global SB can be removed.
These Gloss frequency fields are tied to regions specifically for CNGT (incorrect for other datasets).
https://github.com/Signbank/Global-signbank/blob/e590a23c03a796a2094acc047fd66c39be2027bf/signbank/dictionary/models.py#L711-L723

Regions are now computed dynamically from the Speaker objects (field `location`) via the `frequency_regions` method of Dataset.
https://github.com/Signbank/Global-signbank/blob/e590a23c03a796a2094acc047fd66c39be2027bf/signbank/dictionary/models.py#L2290-L2296

**Comment by susanodd** [comment]
I tested the dynamic generation of regions on the tstMH dataset with a bogus meta data file with totally different locations than for CNGT.
One caveat is that if desired locations for a dataset don't have any speakers, then the locations aren't shown in the frequency table. We don't have any Location objects.

**Comment by susanodd** [comment]
Once there are corpora for datasets other than NGT, then all the frequency info should just show up in the Gloss Frequency template.

**Comment by susanodd** [comment]
This can be closed now.
