### ISSUE TITLE
Cannot change values for Weak Drop/Weak Prop

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#800]
Once a value is selected in the pull-down menu for Weak Drop or Weak Prop (Panel Phonology), this cannot be undone: an error pops up. (Setting the initial value works fine, it's saved correctly after leaving the edit mode.)

**Comment by susanodd** [comment]
Good find! Indeed, it gives an error if you want to set it back to Neutral.
What's weird is it gives a constraint violation of NOT NULL.
However, in the model, this is allowed to be NULL, so it's very strange it gives this error.

**Comment by susanodd** [comment]
In the error log, it's giving this error from model GlossRevision (which is where the history of changes is stored).

**Comment by susanodd** [comment]
Fixed! Here it's visible in the Revision History.

![setting_weakdrop_to_Neutral](https://user-images.githubusercontent.com/24272544/164705958-a310a7b9-9509-4840-87ef-c13cc61693e3.png)

**Comment by susanodd** [comment]
@ocrasborn does the Revision History need to show the "pretty" values in the Old value column?
I'm not sure what else is done with Revision History.
I don't think we allow undo's using the values stored there or use history items for anything. (?)

**Comment by susanodd** [comment]
I pushed the fix as shown above.

**Comment by susanodd** [comment]
This has been awaiting in a pull request for quite a while.

**Comment by susanodd** [comment]
This is live now!
