### ISSUE TITLE
Hide empty semantics fields in gloss and morpheme detail view

### ISSUE THREAD

**Issue by susanodd** [Signbank/Global-signbank#807]
Empty Phonology fields have been hidden in other issues. (#493, #262)
Since there are more Semantics fields now, these can be hidden when empty.

**Comment by susanodd** [comment]
This has been pushed to branch `hide_empty`.

**Comment by Woseseltops** [comment]
Up to you, @susanodd , but I personally would not have made a pull request for this, as these are not the kind of changes that are hard to reverse, bug prone, or might slow others down in the future (which is what we try to prevent with code reviews). :)

**Comment by susanodd** [comment]
Oh, you mean just put on master?

**Comment by susanodd** [comment]
This is live now.
