### ISSUE TITLE
Videos not displayed

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#818]
Most if not all videos for NGT are not displayed -- perhaps also other datasets? I see on the server that most have been moved to temp_NGT, which must be the cause. (Why?!)

**Comment by susanodd** [comment]
Oh, this has to do with a failed test probably.

**Comment by susanodd** [comment]
I moved them back to NGT.

**Comment by susanodd** [comment]
I moved the image folders back too.

**Comment by susanodd** [comment]
I'm not entirely sure how to best solve this problem.
The safest solution to prevent it from happening is to turn this off
https://github.com/Signbank/Global-signbank/blob/d20d2adcda09095b7e21a72d8b03477058d94674/signbank/video/models.py#L494

**Comment by ocrasborn** [comment]
Not sure whether this is related or not, but recently uploaded videos disappeared after a day or two, an assistant noticed. When we uploaded a test video to replicate this, I did notice it had different file permissions. Check out PUBER-A-2799.MP4, for instance, uploaded on June 1 through the interface.

**Comment by susanodd** [comment]
Yes, I see it has totally different permissions!

`-rw-r--r-- 1 ubuntu signbank-writable 1877285 Jun  1 13:01 PUBER-A-2799.MP4`

**Comment by susanodd** [comment]
@ocrasborn were the videos that originally went missing also in NGT?
That video for PUBER-A hasn't got a still image from the video.

**Comment by susanodd** [comment]
I used the dictionary/get_unused_videos to see if there is anything else for PUBER-A.
There are only two .bak files.

There numerous .bak files.

Perhaps a similar command for images would be of use.

I tried to see if the missing files are visible as being unused. I selected all the datasets, but there don't seem to be any weird locations.
Perhaps the command should also look for "non-dataset" folders and report those as well.

**Comment by susanodd** [comment]
The folder writable/tmp is used to store the "extract middle frame" temp files.
It appears it leaves behind a folder with the name of the gloss.
Here you can see remnants of what has been uploaded in the form of a folder name like this:
writable/tmp/PUBER-A-2799.MP4-frames
This is empty, of course.

**Comment by susanodd** [comment]
The folder writable/othermedia has some files uploaded on Jun 1:

`-rw-r--r-- 1 ubuntu signbank-writable   345930 Jun  1 09:01 OVERMORGEN_MM.mp4`
`-rw-r--r-- 1 ubuntu signbank-writable 32268931 Jun  1 09:01 OVERMORGEN_ZM.mov`
`-rw-r--r-- 1 ubuntu signbank-writable   275555 Jun  1 09:15 PAN_MM_2.mp4`
`-rw-r--r-- 1 ubuntu signbank-writable 28913036 Jun  1 09:15 PAN_ZM_2.mov`
`-rw-r--r-- 1 ubuntu signbank-writable   316327 Jun  1 09:33 PAPRIKA_MM_2.mp4`
`-rw-r--r-- 1 ubuntu signbank-writable 28622913 Jun  1 09:34 PAPRIKA_ZM_2.mov`
`-rw-r--r-- 1 ubuntu signbank-writable   318546 Jun  1 09:54 PERZIK_MM.mp4`
`-rw-r--r-- 1 ubuntu signbank-writable 30670851 Jun  1 09:55 PERZIK_ZM.mov`
`-rw-r--r-- 1 ubuntu signbank-writable   315020 Jun  1 09:27 PANTY_MM.mp4`
`-rw-r--r-- 1 ubuntu signbank-writable 32848495 Jun  1 09:27 PANTY_ZM.mov`
`-rw-r--r-- 1 ubuntu signbank-writable   315852 Jun  1 09:35 PARAPLU_MM.mp4`
`-rw-r--r-- 1 ubuntu signbank-writable 32768907 Jun  1 09:36 PARAPLU_ZM.mov`
`-rw-r--r-- 1 ubuntu signbank-writable   292027 Jun  1 09:52 PER ONGELUK_MM.mp4`
`-rw-r--r-- 1 ubuntu signbank-writable 32180007 Jun  1 09:52 PER ONGELUK_ZM.mov`
`-rw-r--r-- 1 ubuntu signbank-writable   298068 Jun  1 09:38 PAUZE_MM.mp4`
`-rw-r--r-- 1 ubuntu signbank-writable 31665187 Jun  1 09:38 PAUZE_ZM.mov`
`-rw-r--r-- 1 ubuntu signbank-writable   344063 Jun  1 10:49 AANTREKKELIJK_MM.mp4`
`-rw-r--r-- 1 ubuntu signbank-writable 36023000 Jun  1 10:49 AANTREKKELIJK_ZM.mov`
`-rw-r--r-- 1 ubuntu signbank-writable 340272 Jun  1 09:58 PESTEN_MM.mp4`
`-rw-r--r-- 1 ubuntu signbank-writable   286637 Jun  1 09:06 PAARS_MM.mp4`
`-rw-r--r-- 1 ubuntu signbank-writable 30932691 Jun  1 09:07 PAARS_ZM.mov`

**Comment by susanodd** [comment]
The first two are here under other media:
https://signbank.cls.ru.nl/dictionary/gloss/1116/

**Comment by susanodd** [comment]
writable/othermedia maintains folders with the gloss id which contain its media files.
These folders were changed on Jun 1:
`drwxr-sr-x 2 ubuntu signbank-writable  4 Jun  1 09:01 1116`
`drwxr-sr-x 2 ubuntu signbank-writable  4 Jun  1 09:15 1189`
`drwxr-sr-x 2 ubuntu signbank-writable  4 Jun  1 09:34 1340`
`drwxr-sr-x 2 ubuntu signbank-writable  4 Jun  1 09:55 1483`
`drwxr-sr-x 2 ubuntu signbank-writable  5 Jun  1 09:27 1506`
`drwxr-sr-x 2 ubuntu signbank-writable  4 Jun  1 09:36 1608`
`drwxr-sr-x 2 ubuntu signbank-writable  4 Jun  1 09:52 2979`
`drwxr-sr-x 2 ubuntu signbank-writable  4 Jun  1 09:38 578`
`drwxr-sr-x 2 ubuntu signbank-writable  4 Jun  1 10:49 72`
`drwxr-sr-x 2 ubuntu signbank-writable  3 Jun  1 09:58 724`
`drwxr-sr-x 2 ubuntu signbank-writable  4 Jun  1 09:07 998`

**Comment by susanodd** [comment]
@ocrasborn can you check if these are the missing videos?
If so, they were uploaded to Other Media for the respective glosses.
