### ISSUE TITLE
Cannot set a name for a new 'sign language'

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#821]
When creating a new dataset, I have the option of adding a sign language (the one that I need for the new dataset). The create-sign language page I then go to does not enable me to specify the Name of the language. There are now three languages without a name (one being a duplicate of one of the other two). In the admin, I cannot edit Sign Languages at all, so there I cannot correct it either. To do:
- enable editing of all text fields in a new sign language page (and perhaps check for other fields in admin?)
- enable editing of sign languages (and perhaps other fields?) in admin

**Comment by ocrasborn** [comment]
Ah, this may be a bigger issue: I can also not change the text fields in the admin for page Release Notes! I'm upping the urgency to blocking! :-)

**Comment by vanlummelhuizen** [comment]
@susanodd Are you working on this yet? I found that removing `'name'` from https://github.com/Signbank/Global-signbank/blob/4cff04a9b315414d2c4f5c98affecc6bed4f9df4/signbank/dictionary/admin.py#L622 solves the issue of the SignLanguage name.

**Comment by susanodd** [comment]
I've been working on #816 still. That's taking longer.

**Comment by vanlummelhuizen** [comment]
@ocrasborn I have added the name field for SignLanguage in the admin.

**Comment by ocrasborn** [comment]
Thanks @vanlummelhuizen, I was able to edit that field again :-)
