### ISSUE TITLE
Setup automated backups on Lightning

### ISSUE THREAD

**Issue by vanlummelhuizen** [Signbank/Global-signbank#822]

**Comment by vanlummelhuizen** [comment]
@Woseseltops 

Proposal: 
1. `scp`  the database from the Signbank container to Applejack, let's say around 3 am. 
2. At around 4 am run a script on Applejack to prune the backups to our liking.

Both can be done as a cronjob. The only issue I can think of is what account to use for both.

**Comment by vanlummelhuizen** [comment]
@ocrasborn That were emails from the old instance. They were useless because nothing changed since the move to Lightning. Do you still want to receive email logs?

**Comment by ocrasborn** [comment]
yes, please @vanlummelhuizen

**Comment by Woseseltops** [comment]
Looks an okay to me @vanlummelhuizen . I like the pruning solution `cometbackup` we use on Applejack, which has a config file like this:

```
#10 seconds     %S      /10     #After 10 seconds, keep every 10 seconds only
#1 minute       %S      00      #After 1 minute, keep one per minute only, when seconds is 00
#10 minutes     %M      /10     #After 10 minutes, keep every 10 minutes only
#1 hour         %M      00      #After 1 hour, keep one per hour only
#1 day          %H      00      #After 1 day, keep one per day only, when hour is 00
2 weeks         %d      /7      #After 2 weeks, keep every 7 days only (7,14,21,27)
31 days         %d      7       #After 32 days, Keep one per month only
1 year          %m      /6      #After 1 year, every 6 months only
```

**Comment by vanlummelhuizen** [comment]
I though to be clever and tried to make the writable folder accessible from Lightning. Unfortunately, a symbolic link in the shared folder to the writable folder or copying the writable folder to the shared folder and symlinking to there both did not work.

**Comment by vanlummelhuizen** [comment]
> OK, first part in place:
>
> - [x] On the container: copy the DB to the shared folder; cronjob by root
> - [x] On the host: copy the DB to a new folder in the backup folder; crontab by my account

I changed this to `scp`-ing the database directly from `writable/database` in the container to the new folder in the backup folder.

**Comment by vanlummelhuizen** [comment]
- [x] Do the same for all other things that needs to be backed up
- [x] Put pruning in place

Seems to work as expected.

**Comment by Woseseltops** [comment]
For completeness, I just discovered this https://cls.ru.nl/tsg-wiki/doku.php?id=backups, written by me in 2019
