### ISSUE TITLE
Create tool to clean up video and other_media files

### ISSUE THREAD

**Issue by Woseseltops** [Signbank/Global-signbank#833]
Create a subcommand to `develop.py` called 'remove_unused' (or something like that) with an argument that can be either `video` or `other_media` (and it would be cool if it helped the user if the command is not one of those two). This command will:
* Go over all video files, or all files in the other_media folder
* Try to find a matching Django instance in the database
* If there aren't any, add it to a list
* Show the list to the user, ask them to agree
* If so, delete all files in the list from the server

Tip: what we call `develop.py` is called `manage.py` in the rest of the world, might help googling how to add subcommands.

**Comment by susanodd** [comment]
https://github.com/Signbank/Global-signbank/blob/9dd10ca2523aae0e261557cc36bb0da1e1725540/signbank/settings/server_specific/default.py#L9-L10

https://github.com/Signbank/Global-signbank/blob/9dd10ca2523aae0e261557cc36bb0da1e1725540/signbank/settings/server_specific/default.py#L13

They're under writable:
https://github.com/Signbank/Global-signbank/blob/9dd10ca2523aae0e261557cc36bb0da1e1725540/signbank/settings/server_specific/default.py#L8

**Comment by susanodd** [comment]
If you look at the various urls, you can see some commands that relate to videos, images, and other media. The database keeps track of these files and they may or may not be in the file system. Previously, video filenames were being suffixed with ".bak" or with a number instead of overwriting them. There are many of these dangling files. When they get deleted by the user, they are deleted in the database, but the files end up staying in the file system. There are some commands to look for these files, but nothing has been done to actually remove them. That's why it will be helpful to get user feedback. It's also something say @ocrasborn ought to run since some of the files are quite old. Although there are also multitudes of "test" files which are mostly totally wrong videos that are not for the sign.

**Comment by Woseseltops** [comment]
Just remembered, in `dictionary/views.py` there is also a view `get_unused_videos` that does something similar. It makes more sense as a subcommand, though, so feel free to take inspiration from the view, and delete it when you're done :) . 

> where is the other_media folder located? And the video files?

As @susanodd showed, you can specify this in your settings file. In the production server, the paths are `/var/www/writable/glossvideo` and `/var/www/writable/othermedia` .

> Should this command be added to the video app?

Sounds like a good place to me ;)

**Comment by Jetske** [comment]
self.stdout.write(os.listdir(mediapath), ending='')
FileNotFoundError: [Errno 2] No such file or directory: '/var/www/writable/othermedia/'

Okay I see, so the files in othermedia are on the production server but not on my server. Then what would be the best way to test the command, adding an othermedia folder with some dummy files?

**Comment by susanodd** [comment]
Yes, you need this folder on your test server.

**Comment by vanlummelhuizen** [comment]
@Jetske I think you need to take care of two things:

1. As Wessel mentioned, specify the `other_media` folder in your settings file to refer to an existing directory, not necessarily `/var/www/writable/othermedia/`. (The settings should be in the file `signbank/settings/server_specific/server_specific.py` in your project folder.)
2. Add some media: for each gloss you want give some (unused) media, create a folder with the gloss-ID as name and put some media in that folder.

**Comment by Jetske** [comment]
Great, thanks! 

I think I have something working, but now I only look for instances of the files in the GlossVideo model. Is that the only relevant place or should it also be searching elsewhere in the database?

**Comment by vanlummelhuizen** [comment]
There is also https://github.com/Signbank/Global-signbank/blob/a379255be5f6e7f312b1e23d3c531cfe704a7b54/signbank/dictionary/models.py#L2119-L2166
