### ISSUE TITLE
Remove or upgrade jquery.datatables

### ISSUE THREAD

**Issue by Woseseltops** [Signbank/Global-signbank#834]
In a vulnerability scan for the ASL Signbank, they found that we are using an out of date version of jQuery DataTables: see the file https://github.com/Signbank/Global-signbank/blob/master/media/js/jquery.dataTables.min.js and the DataTables website: https://datatables.net/extensions/scroller/examples/styling/jqueryui.html . It seems like this plugin helps creating a sortable list of search results, like our gloss list view... but while I can find that we import the plugin, I cannot find a place in the code where we actually use it.

1. Please verify that this plugin is not used anywhere, for example be removing the import and checking if the search still works.
2. If it turns we ARE using it, please replace our version 1.9 with the latest 1.12, and verify everything still works.

**Comment by Woseseltops** [comment]
@susanodd , I assigned this one to @Jetske , but if you have additional info about this, let us know

**Comment by susanodd** [comment]
I suspect it's not used. We use ajax to generate each row of the table.

**Comment by susanodd** [comment]
Some of the javascript that's local on our server is self-modified for ajax and colors. This is the jquery.editable files. DO NOT DELETE.

It looks like the dataTables is really old (2016). It could be used in the feedback section?

**Comment by susanodd** [comment]
There's no use of dataTables under -R signbank.
But under the entire archive, it's found in baselayout.html
