### ISSUE TITLE
ECVs are not accessible

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#839]
Issue with permissions?
See e.g. https://signbank.cls.ru.nl/static/ecv/ngt.ecv/

**Comment by susanodd** [comment]
Probably. The deploy.sh script tends to make things become group root.

**Comment by susanodd** [comment]
Try again. It's group was signbank whereas the others are signbank-writable.

**Comment by vanlummelhuizen** [comment]
@ocrasborn Also, remove the last slash from your url so it become https://signbank.cls.ru.nl/static/ecv/ngt.ecv.

**Comment by vanlummelhuizen** [comment]
@ocrasborn I will close this now, because I believe there is no problem.
