### ISSUE TITLE
Wrong CSV export for 'show all signs'

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#851]
When I try to export a CSV file of all signs in a dataset (by selecting Show all signs from the Signs menu), I do not get the full dataset (nor a broken pipe error #432), but I get a CSV file with the results of the previous search. (Only tried this out with gloss searches.)

**Comment by susanodd** [comment]
This is solved in the field choice branches.

**Comment by susanodd** [comment]
Okay, this appears to be broken!
But now it's worse.

**Comment by susanodd** [comment]
This is awaiting review and deployment.

**Comment by vanlummelhuizen** [comment]
@susanodd @ocrasborn The merge-commit for this issue is on the live server. Could you try it out and if alright, close this issue?

**Comment by susanodd** [comment]
This works now.

**Comment by ocrasborn** [comment]
I'm afraid not, @susanodd , still the same problem.

**Comment by susanodd** [comment]
This is working again, but needs a bit more testing to check all the possible workflows.

**Comment by susanodd** [comment]
This has been pushed to master.

To test the solution, I tried repeating a query (with phonology) then export csv, then another query with show_all, then export csv, repeat, repeat, repeat.
All times sucessful in both cases.

**Comment by susanodd** [comment]
Awaiting deployment.

**Comment by susanodd** [comment]
This should be working now @ocrasborn .
