### ISSUE TITLE
Video reversion affecting test?

### ISSUE THREAD

**Issue by susanodd** [Signbank/Global-signbank#854]
There's a bug in the `test_create_and_delete_utf8_video` test. This test uses a gloss annotation with special characters:

`                                 'XXtéstlemmä%20~山脉%20'`

The bug just started showing up now. The test had been running fine and was never broken in this branch.
It is in the field choice model branch, but that branch does nothing to the video model.
The only thing "new" is that the other changes to master have since been merged to this branch. But as far as I can tell, nothing should be affecting this test.

This is what is happening on my computer:

`susan@glasshotel:~/signbank/writable/glossvideo/NGT/XX$ ls -l`
`totaal 860`
`-rw-rw-r-- 1 susan susan 130221 nov  7 13:05 XXtéstlemmä%20~山脉%20-42215_4rdH2hc.mp4`
`-rw-rw-r-- 1 susan susan  41440 nov  7 13:05 XXtéstlemmä%20~山脉%20-42215_4rdH2hc_small.mp4`
`-rw-rw-r-- 1 susan susan 130221 nov  7 13:01 XXtéstlemmä%20~山脉%20-42215_bf3lV0W.mp4`
`-rw-rw-r-- 1 susan susan  41440 nov  7 13:01 XXtéstlemmä%20~山脉%20-42215_bf3lV0W_small.mp4`
`-rw-rw-r-- 1 susan susan 130221 nov  7 13:06 XXtéstlemmä%20~山脉%20-42215_bZsHB2C.mp4`
`-rw-rw-r-- 1 susan susan  41440 nov  7 13:06 XXtéstlemmä%20~山脉%20-42215_bZsHB2C_small.mp4`
`-rw-rw-r-- 1 susan susan 130221 nov  7 12:57 XXtéstlemmä%20~山脉%20-42215.mp4`
`-rw-rw-r-- 1 susan susan 130221 nov  7 13:03 XXtéstlemmä%20~山脉%20-42215_pyL2hg8.mp4`
`-rw-rw-r-- 1 susan susan  41440 nov  7 13:03 XXtéstlemmä%20~山脉%20-42215_pyL2hg8_small.mp4`
`-rw-rw-r-- 1 susan susan  41440 nov  7 12:57 XXtéstlemmä%20~山脉%20-42215_small.mp4`

It keeps making more and more file with each test run. The test is supposed to delete a previous file and replace it if it already exists.
Is the "reversion" code doing this? Is it messed up because of the special characters?
I thought it was supposed to put .bak at the end, followed by a number. (As in the GlossVideo model.)

@vanlummelhuizen please take a look. The test resizes the video file and generates the still image.
But the test that is supposed to find the file fails.
`response = client.get(video_url, follow=True)`

As you can see, the filenames are all messed up. The same problem occurs if I remove all of those before running the test again.

**Comment by susanodd** [comment]
Hmm. It doesn't work to upload a video anymore in the GlossDetailView template.

Am I somehow "myself" running this in PyCharm runserver?
Instead of www-data ?
It seems I don't have permission according to the website. But the file system has all the correct permissions.
(Assuming the server is not running as me.)
But then why was the test working last week on Friday?

**Comment by susanodd** [comment]
Is it PyCharm that is doing this?
I tried modifying the permissions on the folders where the video is to be uploaded to.
It allows me to upload it. But "the site" under PyCharm has "me" being the owner of the new file. Not the site.
Is this the PyCharm server doing this?
I used to run the server under Apache without this problem.

**Comment by susanodd** [comment]
This is a concern because now I don't know if there is a bug in the "video" code (where the test that fails),
or if there is nothing wrong and it's just that PyCharm doesn't like it.

**Comment by susanodd** [comment]
This seems to be a one-off. I suspect it has to do with old .pyc-files since that code wasn't modified for the new FC model.

**Comment by vanlummelhuizen** [comment]
@susanodd Can this issue be closed then?
