### ISSUE TITLE
Make WRITABLE_FOLDER in create_test_db not hard coded

### ISSUE THREAD

**Issue by vanlummelhuizen** [Signbank/Global-signbank#855]
https://github.com/Signbank/Global-signbank/blob/master/signbank/dictionary/management/commands/create_test_db.py has WRITABLE_FOLDER.

We better make this use the setting WRITABLE_FOLDER.

**Comment by vanlummelhuizen** [comment]
@Jetske Is this something you could do? (@Woseseltops )

**Comment by susanodd** [comment]
Good idea. I keep needing to edit this. I've been making lots of test databases in the past months.

**Comment by Woseseltops** [comment]
Yeah @Jetske was interested in tests, this is a good opportunity. Also I apologize for this bad decision.

**Comment by Jetske** [comment]
@vanlummelhuizen  :+1: I think I could do this

**Comment by Jetske** [comment]
![image](https://user-images.githubusercontent.com/10157482/205011765-857ecebf-d4d1-495a-91b3-deafac2e7a0e.png)

It's possible with the setting WRITABLE_FOLDER but why not use settings.DATABASES? This works for me locally. 

(it was:)
![image](https://user-images.githubusercontent.com/10157482/205012210-d22a9166-cdd4-42db-b61a-290ddb9a9e0e.png)

**Comment by vanlummelhuizen** [comment]
@Jetske That seems sensible. Go for it.
