### ISSUE TITLE
Cannot edit keywords for morphemes

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#858]
I'm adding new morphemes to the NGT dataset, but cannot enter the 'abstract meaning'; I take it that's the 'keyword' field labelled in the interface as 'translation equivalents' for signs. I get an error saying 'unknown field' when I confirm the text string I entered.
<img width="1196" alt="Screenshot 2022-11-18 at 16 12 29" src="https://user-images.githubusercontent.com/10242207/202737809-19251e9a-7262-4dcc-b064-1cbbf9a7de91.png">

**Comment by susanodd** [comment]
This is an error of exactly one too many characters in a string. 'keywords' instead of 'keyword' in the update function.

**Comment by susanodd** [comment]
This has been fixed. It's awaiting deployment.

**Comment by susanodd** [comment]
This has been deployed.

**Comment by ocrasborn** [comment]
Thanks @susanodd !
