### ISSUE TITLE
Searching not possible if interface language is not English

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#865]
Just found out that I cannot search in the Dutch interface anymore; tested Chinese, same thing.

**Comment by susanodd** [comment]
I tried it just now and it works for both.
(Try logging in again in case the browser is using old javascript ?)

The new field choice model and model translations were deployed yesterday by @Woseseltops .
It could be that you tried before it was finished?

**Comment by susanodd** [comment]
Ahha. I just tried being not logged in and using the select datasets for a not logged in user.
(For some reason, Kata Kolok also shows up as a possible choice. But it only has a couple of public glosses.)
If as a not logged in user I click on Show All Signs, it doesn't show any.
But if I'm logged in it does show them.
This could have something to do with the permissions checking.
(It could also have something to do with the last used dataset. Some code was using name and other code was using acronym and other code was using dataset objects -- which get mapped to id's.)
The users last used dataset is stored in the session. But the selected datasets are stored in the user's profile.
So it could be that there is a type mis-match causing the "selected datasets" to not work properly.
(I'm trying to duplicate the error to decipher what is causing it. It seems intermittent.)

**Comment by susanodd** [comment]
@ocrasborn were you logged in when you attempted searching?

I found a bug related to permissions of anonymous users.
They are apparently not allowed to search by publication and notes.
However this is missing in the template parameters so the javascript fails before completion (trying to generate the Search by Publication panel) and no results are shown.

**Comment by susanodd** [comment]
I fixed the problem just described for anonymous users and the publication panel.

@ocrasborn can you check whether it works okay today if you're logged in?

**Comment by susanodd** [comment]
Hopefully this is fixed now. (Not deployed yet.)

**Comment by susanodd** [comment]
I pushed many revisions to the code. Hopefully this will resolve this issue.
I'm only able to mimic this issue intermittently. Sometimes I can duplicate the error. But then it seems to resolve itself.
The gloss list view didn't work at all for anonymous users. That has been fixed. Plus there were inconsistencies with the last used dataset that is stored in settings. Since all the searches depend on the selected datasets and as a side effect, the last used dataset, hopefully those repairs will fix it.
The changes are awaiting review and deployment.

**Comment by susanodd** [comment]
On master branch on my **local** machine, if I have tstMH as the selected dataset and the interface language set to Chinese, then search on Handedness is 2a, then I get 8 results:
![search-handedness-2a-tstMH-chinese-query](https://user-images.githubusercontent.com/24272544/207856259-a64bd77b-5405-4764-bc9a-7ea606545e83.png)

![search-handedness-2a-tstMH-chinese-results](https://user-images.githubusercontent.com/24272544/207856292-6522f995-c61a-4b4d-b7d7-c1b838686413.png)


Doing the same on **Global** with the interface language set to Chinese also finds the results, but most of it is not in Chinese:

![search-handedness-2a-tstMH-global-chinese-query](https://user-images.githubusercontent.com/24272544/207856532-19014959-ef13-4393-9a39-53da5b5456ba.png)

![search-handedness-2a-tstMH-Global-chinese-results](https://user-images.githubusercontent.com/24272544/207856568-e7b28ca5-c934-4265-a892-79201c39fc8c.png)

**Comment by vanlummelhuizen** [comment]
@susanodd It was a Django messages problem: only `nl` had a .mo file. I just generated .mo files for the other languages which seems to have solved the problem.

**Comment by vanlummelhuizen** [comment]
@susanodd @ocrasborn I believe this is fixed so I am closing this issue.
