### ISSUE TITLE
New Gloss Button to Copy Annotations to Lemmas

### ISSUE THREAD

**Issue by susanodd** [Signbank/Global-signbank#869]
THIS ISSUE ADDS A BUTTON TO COPY ANNOTATIONS TO THE LEMMA FIELDS WHEN CREATING A NEW GLOSS.
THIS IS LIVE NOW.....

As identified by @Woseseltops in reviewing #867, there are numerous duplicates of the same code in update.py:

> Not much to complain! I do note that a lot of the guard clauses you (beautifully) introduced contain these two lines:
> 
> ```python
> messages.add_message(request, messages.ERROR, _("Please provide a dataset."))
> return render(request, 'dictionary/add_gloss.html', {'add_gloss_form': form,
>                                                            'dataset_languages': dataset_languages,
>                                                            'selected_datasets': get_selected_datasets_for_user(request.user),
>                                                            'SHOW_DATASET_INTERFACE_OPTIONS': settings.SHOW_DATASET_INTERFACE_OPTIONS})
> ```
> 
> I'd rather see something like
> 
> ```python
> show_error(request, _('Please provide dataset'), form, dataset_languages)
> ```

This issue is to implement the suggested code improvement.

**Comment by susanodd** [comment]
@Woseseltops there is a slight problem with the above construction.
When a new lemma also must be provided, showing the error does not go back to the template, but just continues the following code of the caller. It's acting like a normal function call, not rendering.

**Comment by susanodd** [comment]
The above improvements have been implemented. There were some glitches in making sure the appropriate fields were filled in.
The pull-down menu for adding a sign shows the following page (screenshots).

The toggle between choosing an existing and creating a new lemma now shows which is active (shown first) whereas the non-active shows up as a button.

A tooltip has been added for the case where the user chooses an existing lemma.
`"Type in the initial letters to see if the lemma already exists."`

The improved error message feedback code in update.py (shown above) revealed that entering the lemma was a bit confusing. Hence the new toggle label headings.

New template format:

![add_gloss_select_existing](https://user-images.githubusercontent.com/24272544/211827341-cd2d0601-c168-4bfe-a1f5-0e2835ae3c39.png)

![add_gloss_create_new](https://user-images.githubusercontent.com/24272544/211827382-663c0242-87e5-40c3-b59a-bd3cebcbe8d5.png)

**Comment by susanodd** [comment]
This is awaiting review.

**Comment by ocrasborn** [comment]
I like what I see in the last screenshot, that helps the editor to realise that the lemma and annotation ID gloss are both needed. A single improvement for usability that I can think of is a button that copies the values for the new lemma gloss to the annotation gloss: in the typical workflow, we create a new lemma at the time of creating a new annotation gloss. Could you still add that, @susanodd ? It would save a lot of time in the end.

**Comment by susanodd** [comment]
Okay, this is what it looks like now, visible when creating a new lemma:

![add_sign_copy_annotation_to_lemma_fields_button](https://user-images.githubusercontent.com/24272544/213209595-0d8010f4-b22d-4cdc-b2aa-e9fa9d5f4279.png)

**Comment by susanodd** [comment]
This is on master now, awaiting deployment.

**Comment by susanodd** [comment]
> I like what I see in the last screenshot, that helps the editor to realise that the lemma and annotation ID gloss are both needed. A single improvement for usability that I can think of is a button that copies the values for the new lemma gloss to the annotation gloss: in the typical workflow, we create a new lemma at the time of creating a new annotation gloss. Could you still add that, @susanodd ? It would save a lot of time in the end.

This is live now, @ocrasborn !!

**Comment by susanodd** [comment]
This is live now.

**Comment by ocrasborn** [comment]
Great! Very helpful @susanodd
