### ISSUE TITLE
Feedback Menu

### ISSUE THREAD

**Issue by susanodd** [Signbank/Global-signbank#873]
The code underneath the Feedback menu contains some obsolete references to Auslan.
Nearly all of the data stored in the database is actually "testing" data of the feedback routines.

During the migration to the new Field Choice model, some migrations for the Feedback module were also needed.
During review, it was noted that some of this code was sloppy.
For example, the following illustrates a sneaky reuse of a field `like` for something else (whether it's a morpheme or not) rather than modifying the model:

https://github.com/Signbank/Global-signbank/blob/3df638a9a3b37fdfaecb229316523365517ed51c/signbank/feedback/views.py#L284

We decided at the time that it would be better to introduce a new issue for Feedback rather than reimplement Feedback inside of the Field Choice and Model Translation issues.

Nevertheless, what should be done with Feedback? Is this useful? @ocrasborn

**Comment by ocrasborn** [comment]
Hi @susanodd , yes, I think it's still useful even if we haven't used it a lot until now. One related question: is the 'missing sign feedback' already dataset-specific? We'd like feedback like this to go to the dataset manager. The present Feedback Overview is quite alright for that, but I wonder who gets to see what there: all suggestions for all datasets, or only of the selected one? Access should be limited to users in group Editor, but I bet that's already the case.

**Comment by susanodd** [comment]
Specific sign feedback is available at the bottom of the Gloss Detail View. (That was previously broken.)

I don't think datasets are used at all yet in the feedback module. I'll do that.

**Comment by susanodd** [comment]
I'm working on this issue now.

**Comment by susanodd** [comment]
I made the following changes to the Feedback code:

- removed obsolete Auslan code
- removed Interpreter feedback code (was not being used, consulted with @ocrasborn)
- revised the index.html template (visible if you just do /feedback/ rather than select from the menu)
- reformatted the templates using some bootstrap grid (this was just to make them display okay, the indentation was weird before)
- the feedback overview checks that the user is logged in and that the user belongs to group Editor
- the missing sign feedback shows the sign languages of the selected datasets
- for feedback on a missing sign, the user selects a sign language (rather than a dataset)
- separated sign feedback from morpheme feedback (this gets rid of some unpleasant code)

TO DO:

- refine dataset and permissions
- send dataset owners (missing) sign feedback for those datasets associated with a sign language
- allow users to enter feedback videos via a webcam (requested by @ocrasborn, as part of #266 @Jetske )
- figure out what the relation between morphemes and lemmas and datasets is **

** morphemes don't really have lemmas (no lemma columns in the Morpheme List View) but they need lemmas in order to appear in datasets. This required a bit of weirdness in the feedback

**Comment by susanodd** [comment]
I added tab panels to the Feedback Overview template. This helps when viewing. It was an inline list.

![feedback-overview-panels](https://user-images.githubusercontent.com/24272544/215104700-9d5fe244-8c51-456f-98e6-0ca51ab118f5.png)

**Comment by susanodd** [comment]
This is an example showing sign feedback where the Sign Language and the Dataset are shown.
The Sign field shows the Annotation rather than the Lemma.

![sign-feedback-showing-signlanguage-dataset](https://user-images.githubusercontent.com/24272544/215105732-409928f6-2d21-4805-80b6-7519a2758930.png)

**Comment by susanodd** [comment]
**Note to Self**

I'm having a bit of trouble formatting the tabs. In gloss detail view, each of the tabs is a separate html file.
Here, it's all in one file. It switches and hides appropriately, but no "red line" above the active tab. (The screenshot above has it, but to make it load as expected on visiting the page, the tab must be set as active dynamically.

**Comment by susanodd** [comment]
I separated the different kinds of feedback into different templates. Now the tabs switch between the different templates. As is done for Gloss Detail and the other Gloss templates.

**Comment by susanodd** [comment]
I made the branch `feedback_menu` be a pull request (#881) and requested feedback from @vanlummelhuizen.
I included code-specific comments in the pull request rather than here.

**Comment by susanodd** [comment]
> Hi @susanodd , yes, I think it's still useful even if we haven't used it a lot until now. One related question: is the 'missing sign feedback' already dataset-specific? We'd like feedback like this to go to the dataset manager. The present Feedback Overview is quite alright for that, but I wonder who gets to see what there: all suggestions for all datasets, or only of the selected one? Access should be limited to users in group Editor, but I bet that's already the case.

I've made it so group Editor is required to see the Feedback Overview. The feedback overview has been separated into panels for each type of feedback for the selected datasets, except for general feedback, which isn't specific.

I added a choice menu for Sign Language for the Missing Sign Feedback. I thought the idea of datasets might be alien to users. Only the Sign Languages from selected datasets are shown in the menu. A table showing which datasets are for which sign language is shown. (It is a bit difficult to get permissions to work since the user is suggesting a sign that doesn't exist. Normally nobody would have access to all of the datasets, so the example below showing all datasets is for illustration.)

![feedback-missing-ngt-tstmh](https://user-images.githubusercontent.com/24272544/215736072-cdd2ca26-6470-4a27-b603-c2706920b19d.png)

![feedback-missing-all-datasets-selected](https://user-images.githubusercontent.com/24272544/215736098-d3637cf2-e68d-4c71-85c7-1dc14299f436.png)

**Comment by susanodd** [comment]
I modified the feedback admin, so it's possible to filter sign and morpheme feedback on the dataset.
The list views now show the annotations in the list.

![morpheme-feedback-admin](https://user-images.githubusercontent.com/24272544/215780833-8bf76c3d-9946-4702-9fa4-4d807a465868.png)

**Comment by susanodd** [comment]
The updates to the code are completed as outlined above.

What remains is handing off the feedback to dataset managers.
Caveat, do we really want to send them email directly? Or how? I guess it would be something like a notification when new feedback comes in. Or perhaps it could be paired with Recently Added Signs. That somehow, it's directed but lazy.

**Comment by susanodd** [comment]
I've made a page for recent feedback, to be underneath the Datasets menu. Visible to Editor now.

![recent_feedback_selected_datasets](https://user-images.githubusercontent.com/24272544/216036584-f6692eb4-3f93-4fc1-b60b-467b26661701.png)

**Comment by susanodd** [comment]
This is live now.

**Comment by ocrasborn** [comment]
Nice @susanodd, with the tabs !! Thanks
