### ISSUE TITLE
Some changes to the interface text

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#879]
These are some heterogeneous requests, but all to do with changes to the text I see in the interface, so probably easiest to deal with in one go; all applying to the English interface:
- There's a typo: field label "Conception Concept Set" should read "Concepticon Concept Set" (with a c inserted)
- In the detail view of signs, the labels for the different tabs at the top are a little messy, let's try to shorten them like this: Public View, Details, Relations, Frequencies, Revision History, Videos; by removing 'view' as much as possible it becomes a bit more compact. The 'view' is a bit programmer speak, I realise now.
- The panel Morphosyntax used to be called and should be Semantics, I'm not sure why it changed at some point. Please rename back to Semantics.

Please try to adjust the Dutch translations (in the .po file?) accordingly; let me know if you need any suggestions there @Jetske

**Comment by susanodd** [comment]
The Query View isn't shown with the gloss, it's shown as a pull-down in the Analysis Menu.
It's true there is a `nav-tab` (a single one) in the template.
This will be expanded to allow users to see saved queries (#118), hence the use of a `nav-tab` in expectation of other functionality.

Reviewing the code #880, I think it looks weird (in English) if it's called Query List and Query (by removing the View).

The view itself is the list of search results from the most recent search, with the query parameters shown above them.
So it's **Query Parameters** plus **Query Results**.
Could also be **Query Display**
I'm not exactly sure what it is, so it was called Query View.
It used to be a panel for the Gloss, but during development, @Woseseltops pointed out that it wasn't specific to a gloss, so we moved it to the Analysis menu.

**Comment by susanodd** [comment]
I deployed the changes last week and compiled the new .po files on Global.

But now (on Apple) it has started using **en_us** instead of **en**.

This is observed by **Weak Hand** becoming **Nondominant Handshape** in the Minimal Pairs List (under Analysis).

How did this happen? Is it Safari overriding something? This is very strange because I have Safari in het Netherlands. Indeed, my MacOS is in het Nederlands.

**Comment by susanodd** [comment]
Fixed it by removing the compiled file for en_US
