### ISSUE TITLE
Error making small videos

### ISSUE THREAD

**Issue by susanodd** [Signbank/Global-signbank#891]
The VideoResizer function called by `make_small_video` in the `GlossVideo` model

`        from CNGT_scripts.python.resizeVideos import VideoResizer`

Is resulting in the following exception:

`Expecting value: line 1 column 1 (char 0)`

It doesn't seem to work on anything anymore.

**Comment by susanodd** [comment]
@vanlummelhuizen can you check the setting:

`MEDIA_URL`

This is defined in `base.py` and used in `video/models.py`

When running, in Video Admin, the video paths "go" to this location, but this ends up being an error.
(They are under writable)

(We still don't know why videos on Global are ending up having group `www-data` instead of group `signbank-writable`.
That is issue #886 )

**Comment by susanodd** [comment]
From the Apach error log:

`[Thu Mar 09 08:45:08.791877 2023] [:error] [pid 1917:tid 140008249800448] (20024)The given path is misformatted or contained invalid characters: [client 10.65.167.47:50192] xsendfile: not a file /var/www/writable/, referer: https://signbank.cls.ru.nl/signs/show_all/`

**Comment by vanlummelhuizen** [comment]
> The VideoResizer function called by `make_small_video` in the `GlossVideo` model
> 
> ` from CNGT_scripts.python.resizeVideos import VideoResizer`
> 
> Is resulting in the following exception:
> 
> `Expecting value: line 1 column 1 (char 0)`
> 
> It doesn't seem to work on anything anymore.

The problem lied in the fact that, although `avconv` was installed, `avprobe` was not. In the [resizeVideos.py of CNGT-scripts](https://github.com/vanlummelhuizen/CNGT-scripts/blob/adebb61f5cb0c0004593c506d2211ab2e303d2d9/CNGT_scripts/python/resizeVideos.py#L59) it expects that if `avconv` is used, `avprobe` is also there. 

I solved it by adding `FFMPEG_PROGRAM = "ffmpeg"` to *signbank/settings/server_specific/server_specific.py*.

**Comment by susanodd** [comment]
It works now on the tests! No errors anymore!

**Comment by susanodd** [comment]
The code that makes small videos has been commented out in some functions.
Check and see if there is a problem here.
The new perspective videos (examples received from @uklomp) are quite large screen-wise.
@Jetske also discovered that some webcam videos run at a different screen rate and the length ends up changing with they are processed.

**Comment by vanlummelhuizen** [comment]
> The code that makes small videos has been commented out in some functions.
> Check and see if there is a problem here.

What code exactly? Please give a link to the exact code snippet with using the method explained in https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-a-permanent-link-to-a-code-snippet

> The new perspective videos (examples received from @uklomp) are quite large screen-wise.
> @Jetske also discovered that some webcam videos run at a different frame rate and the length ends up changing when they are processed, so it fails.

Which ones exactly? Or how can we replicate the problem? Is there data we can use for this?

---

:bulb: **Tip**: if you want other people to look into a problem, give concrete and precise information so that the problem can be replicated quickly and investigated without (much) extra work of figuring out what you mean exactly.

**Comment by susanodd** [comment]
> > The code that makes small videos has been commented out in some functions.
> > Check and see if there is a problem here.
> 
> What code exactly? Please give a link to the exact code snippet with using the method explained in https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-a-permanent-link-to-a-code-snippet
> 
> > The new perspective videos (examples received from @uklomp) are quite large screen-wise.
> > @Jetske also discovered that some webcam videos run at a different frame rate and the length ends up changing when they are processed, so it fails.
> 
> Which ones exactly? Or how can we replicate the problem? Is there data we can use for this?
> 
> 💡 **Tip**: if you want other people to look into a problem, give concrete and precise information so that the problem can be replicated quickly and investigated without (much) extra work of figuring out what you mean exactly.


Here's where it's commented out:

https://github.com/Signbank/Global-signbank/blob/6242cc47de593c3debcd78da7a2f2a25f97f0f62/signbank/dictionary/models.py#L649-L653


https://github.com/Signbank/Global-signbank/blob/6242cc47de593c3debcd78da7a2f2a25f97f0f62/signbank/dictionary/models.py#L2408-L2414


For files and file sizes:
@uklomp sent sample perspective files, that's what I've been using.
@Jetske increased the size for uploading videos recently.

I don't have any sentence videos. 
There will also be perspective videos for sentences. Thus the size for those will also be larger.
The smaller videos will become important as signbank is serving more videos. (Future tense.)

**Comment by Woseseltops** [comment]
I'll close this for now. Feel free to make a separate more specific issue if you feel it's necessary @susanodd !
