### ISSUE TITLE
Page with Release Notes is missing

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#896]
There used to be a page About/Release Notes, where I listed feature updates and additions in a user-readable form. That page has gone missing. Where is it? Can it be restored from a backup?

**Comment by susanodd** [comment]
It's not in the current database anymore. I found it in a database from 2021.
I added the page again, using page contents from an old database.

**Comment by ocrasborn** [comment]
Thanks @susanodd !
