### ISSUE TITLE
List view contains ID number instead of value for English Lemma ID Gloss field

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#918]

**Comment by susanodd** [comment]
Yes, that's true. It's not supposed to be blank because of the sorting routines.
The ones with the IDs have no English translation.

**Comment by ocrasborn** [comment]
Ah right, that's the pattern. That's not related to the new server then, I'll go and remove the tag. Not quite sure what we should do with this (other than making our data complete).

**Comment by susanodd** [comment]
The `**Import CSV Lemma**` page has been revised. It's possible to fill in the missing English field that way.

**Comment by susanodd** [comment]
Completed, on master,  but not deployed yet.

**Comment by susanodd** [comment]
This is live now.
