### ISSUE TITLE
Not able to update a gloss

### ISSUE THREAD

**Issue by susanodd** [Signbank/Global-signbank#925]
It's not possible to update a gloss on the new server.

This happens when updating the Handedness. (The update code doesn't get to the Field Choice fields. It stumbles earlier.)

```

> NameError at /dictionary/update/gloss/8579
> name 'BooleanField' is not defined
> Request Method: | POST
> Request URL: | http://signbank-new.cls.ru.nl/dictionary/update/gloss/8579
> Django Version: | 4.1.4
> Exception Type: | NameError
> Exception Value: | name 'BooleanField' is not defined
> Exception Location: | /var/www/repo/./signbank/dictionary/update.py, line 387, in update_gloss
> Raised during: | signbank.dictionary.update.update_gloss

```

I looked it up to compare on master. On master it's NullBooleanField, with the corresponding import.
Here, the import doesn't match. I guess all three should be BooleanField

https://github.com/Signbank/Global-signbank/blob/71ab036a8e8727e7db537faaeb749e75c809ffbe/signbank/dictionary/update.py#L9

https://github.com/Signbank/Global-signbank/blob/71ab036a8e8727e7db537faaeb749e75c809ffbe/signbank/dictionary/update.py#L387

https://github.com/Signbank/Global-signbank/blob/71ab036a8e8727e7db537faaeb749e75c809ffbe/signbank/dictionary/update.py#L2057

**Comment by Jetske** [comment]
Yes, this should solve it!

**Comment by susanodd** [comment]
This works now!
