### ISSUE TITLE
Admin totally broken on new server (PyCharm runserver Ubuntu 22.04)

### ISSUE THREAD

**Issue by susanodd** [Signbank/Global-signbank#934]

**Comment by susanodd** [comment]
There's something messed up with the paths.
The view that you click on for the different models is displayed on top of the top level but "off outside of the window dimensions".
It looks like something is messed up with the static location of the admin templates.

@Woseseltops when you originally had the new server issue about django admin bootstrap, what was the solution?

**Comment by susanodd** [comment]
![broken-admin-everything-on-top-of-each-other](https://user-images.githubusercontent.com/24272544/228202088-679670fa-700a-443b-9438-82ae61ba5e2b.png)

**Comment by susanodd** [comment]
I need this to work correctly on PyCharm in order to debug code of the issues.

**Comment by susanodd** [comment]
Here is the same, zoomed out to show that it's displaying everything in a gigantic window that's still not big enough.

Is something wrong with the pip install modules used here? Or something wrong with the settings? Or has Django been upgraded to require a 4K display on a 64 inch screen?

![zoomed-out-admin-to-30-percent](https://user-images.githubusercontent.com/24272544/228203349-c5debeab-27a7-431b-926c-512c9f621c47.png)

**Comment by susanodd** [comment]
This is specific to Firefox. It works perfectly on Safari. It even uses dark mode on Safari when set.

**Comment by susanodd** [comment]
Reinstalling ALL the requirements DOES NOT fix the problem.

**Comment by susanodd** [comment]
@Woseseltops @vanlummelhuizen do you guys run ubuntu in a container rather than upgrade the OS?
On my computer, neither Firefox nor Chrome work correctly for the Django Admin. (See screenshots.)
But it works correctly on the Global Server. (But as you said, Ubuntu is only in the container there, not on the computer itself.) For me, it also does not work if I use the virtual environment to run the server. I reinstalled all the requirements and it still shows up messed up. So something is wrong with Ubuntu support.

The webpage template appears to load all of the bootstrap files correctly. It's just not displaying correctly.

**Comment by susanodd** [comment]
#908 collectstatic did not solve this.

**Comment by vanlummelhuizen** [comment]
@susanodd I cannot reproduce the problem with a local /admin. I am using Ubuntu 22.04, Firefox 110.0 and Chrome 111.0.5563.64.

Could you use developer tools in FF of Chrome (for both press F12) to see whether a javascript of css is missing or whether the console shows errors?

**Comment by susanodd** [comment]
I'm wondering about
 [Global-signbank](https://github.com/Signbank/Global-signbank)/[media](https://github.com/Signbank/Global-signbank/tree/master/media)/bootstrap/

These are really old files. They are also on my computer.

**Comment by susanodd** [comment]
I'm wondering because I just noticed that (while debugging the datasets/select)
That my menu bar does not have the outlines around the selected datasets. They are bold, but not outlined.
(That's bootstrap, right?)

**Comment by susanodd** [comment]
No, developer tools do not work. (It prints the raw html inside a popup)

**Comment by susanodd** [comment]
The only vague thing I could find was about "snap" installation. That the post said to remove Firefox and force it to install not using snap.

**Comment by susanodd** [comment]
Is Google trying to track stuff people search for on Signbank?

**Comment by vanlummelhuizen** [comment]
@susanodd Perhaps you can try to setup a completely new development environment?

**Comment by susanodd** [comment]
Okay, I compared what the global server was doing with what pycharm was doing.
I needed to change some of the symbolic links and move the virtual environment.
The admin is working again!!
