### ISSUE TITLE
Import Lemma Update CSV

### ISSUE THREAD

**Issue by susanodd** [Signbank/Global-signbank#935]
This code is very old and needs rewriting to work correctly on CSV files exported from Numbers on MacOS.

This is related to #930 as a way to fill in missing translations.

**Comment by susanodd** [comment]
@susanodd you can assume that this will be implemented soon.
It will likely take more time actually filling in the missing English translations.
(As per CSV export on the Show all lemmas page. You should only need to fill in missing ones, not remove any rows.)

**Comment by ocrasborn** [comment]
@susanodd thanks!

**Comment by susanodd** [comment]
I discovered that some of the NGT lemma translations begin with spaces. (If you search on just space in the English column, there are about 4 glosses.) Uploading a lemma csv file actually catches these as being different.

**Comment by susanodd** [comment]
This is live now, @ocrasborn 

(Currently only the url signbank-new is working.)

**Comment by susanodd** [comment]
This is completed.
