### ISSUE TITLE
Error CSRF_TRUSTED_ORIGINS

### ISSUE THREAD

**Issue by susanodd** [Signbank/Global-signbank#937]
```
  File "/var/www/repo/signbank/dictionary/tests.py", line 2642, in test_Settings
    self.assertEqual(comparison_table_first_not_in_second[first_file][second_file],[])
AssertionError: Lists differ: ['CSRF_TRUSTED_ORIGINS'] != []

First list contains 1 additional elements.
```

**Comment by susanodd** [comment]
All the tests work except this one.

But the tests that need test data that is missing are simply returning since they can't test anything.

**Comment by susanodd** [comment]
@Woseseltops is this setting needed for the "other" settings files?

CSRF_TRUSTED_ORIGINS

The settings tests fail because this is not present.
Should this setting be ignored? Or is it also relevant for ASL?
Is this related to the admin failing to display properly? (#934 )

**Comment by ocrasborn** [comment]
One colleague couldn't log in yesterday from home, getting a message with CSRF in it that I couldn't relate to anything. Related somehow?
![IMG_3685](https://user-images.githubusercontent.com/10242207/229719184-fc0016df-1adc-4134-9568-0eded487400d.jpeg)
