### ISSUE TITLE
Problems with creating new account

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#941]
New accounts can be registered, but they don't get activated and I (Onno) don't get a mail message saying someone has been given access to NGT for people who requested that.

**Comment by Jetske** [comment]
When I try to debug locally, it prints the correct emails, email addresses and account activation link. Is there an error on the server about sending emails?

**Comment by susanodd** [comment]
I checked the error log and discovered a different error. The symbolic links in media to ecv an othermedia were wrong. I fixed those. The apache2 error log was complaining about those.

**Comment by susanodd** [comment]
@ocrasborn is this still a problem?

For a short while the server_specific.py file was missing. It's possible that some required site settings were missing.
@Woseseltops added this file again last Thursday.

Without anything server specific, this is what the mails use:

https://github.com/Signbank/Global-signbank/blob/fbaabbd3ed80e8612c32523e169698cfde8cfd12/signbank/settings/server_specific/default.py#L45

**Comment by susanodd** [comment]
@ocrasborn can you check this one again?

New users are set to active (see #947).

**Comment by ocrasborn** [comment]
Thanks @susanodd and @Jetske . Works well now. I'll close this one and add an issue about a text improvement in one of the mails.
