### ISSUE TITLE
Make a backup of whole writable folder

### ISSUE THREAD

**Issue by Woseseltops** [Signbank/Global-signbank#942]
* We are worried about both data loss and data corruption (like for the database), so we want differential backups that are cleaned every x time units. 
* We want it to be set up automatically with Ansible scripts

**Comment by susanodd** [comment]
Has this been implemented, @Woseseltops @vanlummelhuizen ?

**Comment by vanlummelhuizen** [comment]
I don´t know. I assume @Woseseltops knows since he is implementing the Ansible scripts for Signbank.

Also, we probably should transfer this issue to the RU-instance repo.

**Comment by susanodd** [comment]
I make a(n extra) backup of the database to tensusers2 when I deploy. But nothing else.

**Comment by susanodd** [comment]
What is the status of this?

**Comment by Woseseltops** [comment]
It has been realized: Ansible automatically adds the necessary stuff to the crontab. Made a few changes today to prevent permission errors in the future, will check again in a week to see the effects.

**Comment by susanodd** [comment]
Great!!

**Comment by Woseseltops** [comment]
It's working
