### ISSUE TITLE
Minimal Pairs Export CSV

### ISSUE THREAD

**Issue by susanodd** [Signbank/Global-signbank#958]
It doesn't work to export CSV on NGT minimal pairs.  I had limited the focus gloss to Handedness 2s.

```
Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at webmaster@localhost to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

Apache/2.4.52 (Ubuntu) Server at signbank.cls.ru.nl Port 80
```

Dito after reducing the results further with handedness 2s and strong hand 1_krom.

**Comment by susanodd** [comment]
This is repaired. It's live now.
New: The page shows nothing on initial load.
The buttons have been relabelled to highlight the workings of the page.

**Comment by susanodd** [comment]
@vanlummelhuizen this is the question I have.

In the MinimalPairsView, the user is allowed to export CSV.

https://github.com/Signbank/Global-signbank/blob/7749caa278911a9bcca6c4f7cd6474f90ae02171/signbank/dictionary/adminviews.py#L3357-L3361

The "else" case has the effect that eventually `get_queryset` is called (again), and/or a new view or new form is created.
It seems the `render_to_response` method was deprecated out in Django 2.0.
Is it possible to revise the "else" clause in such a way that it does not call `get_queryset` again? What is an appropriate response object here?

**Comment by vanlummelhuizen** [comment]
> The "else" case has the effect that eventually `get_queryset` is called (again), and/or a new view or new form is created.
> It seems the `render_to_response` method was deprecated out in Django 2.0.

From https://docs.djangoproject.com/en/2.2/topics/http/shortcuts/#render-to-response:

> This function preceded the introduction of [render()](https://docs.djangoproject.com/en/2.2/topics/http/shortcuts/#django.shortcuts.render) and works similarly except that it doesn’t make the request available in the response.

So we could probably replace `render_to_response` to `render`. 

---

> Is it possible to revise the "else" clause in such a way that it does not call `get_queryset` again? 
@susanodd I am not sure what you mean. In the *else* clause the `render_to_response` of Django's ListView is called. When you don't want that, then you should not call it but write new code that does what you want.

> What is an appropriate response object here?

I think `render_to_response` of Django's ListView creates a response with the context and the template, just like any other default view in Django. Again, if you want something else, you can write new code.

**Comment by susanodd** [comment]
The export to csv uses the default language English (as do all of the export csv routines).
The list display shows the field values in the interface language but the field names in English.
NOTE TO SELF:

This line ends up fetching the English name and is not dynamic in the view:

https://github.com/Signbank/Global-signbank/blob/f0d97f4bf8d287a2daef14fb95754a46e84fb3c8/signbank/dictionary/models.py#L1597

**Comment by susanodd** [comment]
I tried using the actual Gloss model field obtained from Gloss.__meta and then passing around this object and then obtaining its verbose_name from it in the template. That still ends up being English.
The verbose names are all lazy translated `_( )` text. But Django doesn't seem to want to translate these.

**Comment by susanodd** [comment]
The override is used for CSV column headers. On export, the contents is also English. (This is correct.)

But in the template, the field values are shown translated (e.g., to Dutch), but the field name (verbose_name in the model which has `_( )` on it) is not translated in the list shown in the list view template.

It seems that somehow, the (gettext) text that is passed around and eventually shown in the template no longer gets translated.
(This is the upgraded Django doing this.)

**Comment by susanodd** [comment]
The translation of verbose_name is described here:

https://docs.djangoproject.com/en/4.2/topics/i18n/translation/

This seems revelant because the FieldChoiceForeignKey is a ForeignKey.
The text writes about using lower case in the verbose_name.

**Comment by susanodd** [comment]
I tried compiling messages (locally) and I get an error about gettext.

Do we need this requirement?

python-gettext 5.0

**Comment by susanodd** [comment]
I fixed the dynamic translation of the gloss verbose field name!

There's a method that postpones the translation as long as possible `gettext_noop`

**Comment by susanodd** [comment]
Yypes! Nobody compiled the languages on the new server! Doing that now...

**Comment by susanodd** [comment]
Here's the gettext_noop in action! Now the field name column is translated!!

![minimal-pairs-NL](https://user-images.githubusercontent.com/24272544/234219833-d44384bd-d192-4b4d-83f5-5c4552ef4003.png)

![minimal-pairs-chinees](https://user-images.githubusercontent.com/24272544/234219877-05d9def0-dd97-4fb7-af1a-b7b18d6c5dd0.png)

**Comment by susanodd** [comment]
(Note that this is dataset tstMH, so the example glosses are not real glosses.)

**Comment by susanodd** [comment]
I revised the code to restore the form fields after a submit action so they remain visible again.
This makes it possible to do the query, view the results, and then export to csv so the search fields are still used.

The reset button works now. It clears all the phonology and semantics fields. Although it may or may not clear the language fields. (If you just typed something in, you can clear it. But if you did a query already and the fields are in the url, then it won't clear the language fields. The url needs to be reset by reloading the page.)

**Comment by susanodd** [comment]
This is completed.
