### ISSUE TITLE
Revise Videos view to include sentence videos

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#963]
Follows #884 
The Videos tab now includes the main gloss video and the image derived from it; and possibly also items uploaded in the panel 'Other Media'?
Revise to make sure that all the sentences linked to the different senses of a sign are also displayed here, along with the sense and sentence type, like in the detail view.

**Comment by susanodd** [comment]
@Jetske for some strange reason, after I merged that and deployed it, on the live server, the "moving video previews" in the GlossListView no longer show! It's just a static image now when you hover.

**Comment by Jetske** [comment]
@susanodd That's strange because no changes were made in that template... they still move when I try it. Maybe just reload?

**Comment by susanodd** [comment]
Are you on the live server?

**Comment by susanodd** [comment]
I'll close it now!!

**Comment by susanodd** [comment]
Oops closed wrong issue.

Here, this is a problem:

https://signbank.cls.ru.nl/dictionary/gloss/1608/glossvideos

(There's a hard-coded address showing.)

**Comment by Jetske** [comment]
Oops! 
That's {{path}} in line 228 of gloss_videos.html which I added to try to show images. Can you delete that?

**Comment by susanodd** [comment]
Was that for debugging?

**Comment by Jetske** [comment]
Yes sorry, for debugging.. I didn't notice it afterwards because I don't have much other-media on my computer

**Comment by susanodd** [comment]
It's live now!
I guess this can be closed now.
The PARAPLU gloss is one I know because it has other media. (Although the videos do not display properly, there are quicktime videos. But that upload code has been broken a long time.)

Now we need a gloss with lots of sentence videos, for testing purposes. :)

I put a new version of the database on tensusers earlier. So it has the sentence types you made.

**Comment by Jetske** [comment]
Nice, I added one for FIETSTAS and it seems to work!

**Comment by susanodd** [comment]
Nice!!

**Comment by susanodd** [comment]
Okay, I'm closing it now. Looks good.
