### ISSUE TITLE
Enrich search form to include Senses and Example Sentences

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#964]
Follows on #884 
Allow for search on Sentence Type (Sign has / does not have sentence of type X), as well as text in the Sentence Translation.

**Comment by susanodd** [comment]
I've started working on this too, because of query parameters.

**Comment by susanodd** [comment]
@ocrasborn you'll love this!
I added '`Has Multiple Senses'` to the Gloss Search Form. It's under the Publication Fields at the moment, since there isn't a section for senses/sentences yet.

![query-has-multiple-senses](https://github.com/Signbank/Global-signbank/assets/24272544/0a4428ad-d848-4e6a-8a0c-83617096033d)

I confess, this was kind of added to be able to see how it's going with the senses. :)

**Comment by susanodd** [comment]
@Jetske a migration was needed to add the new search field to the query parameters, so I put a backup of the migrated database in the usual location. Remember to merge with master.

**Comment by susanodd** [comment]
@ocrasborn do you want the found sentences also in the results list?
This is going to end up very crowded since the sentences column would be very wide.
Alternatively there could be a separate search dedicated to senses and sentences and maybe a sentence video column.

**Comment by susanodd** [comment]
Example sentences are still not included in searches.

**Comment by susanodd** [comment]
> Alternatively there could be a separate search dedicated to senses and sentences and maybe a sentence video column.

I’ll work on this

**Comment by susanodd** [comment]
![senses_search_cheese](https://github.com/Signbank/Global-signbank/assets/24272544/c183ec55-b819-4bc2-8c09-5aaee57e9e65)

**Comment by susanodd** [comment]
I revised the Search Form so that most of the same fields can be applied to glosses (it searches over model GlossSense which pairs glosses with their senses). So the same searches can be applied to the Gloss part and it retrieves also the senses.
The Senses fields go over the Sense part.

**Comment by susanodd** [comment]
I revised the display a bit. Now it's possible to toggle the visibility of the language columns. This is a search on senses with English containing friend.

![search_sense_two_datasets_three_languages](https://github.com/Signbank/Global-signbank/assets/24272544/b4c3c859-581f-46a8-9aac-1df6007363fd)

![search_senses_languages_hidden](https://github.com/Signbank/Global-signbank/assets/24272544/103df426-e4f5-4946-911b-2e1d029662b3)

**Comment by susanodd** [comment]
Here's a search on "vriend" (Dutch).

![search_senses_vriend_NGT_NTS](https://github.com/Signbank/Global-signbank/assets/24272544/494da259-dc85-47cf-8098-9b1f2ef9a500)

**Comment by susanodd** [comment]
Next to add the specific form fields for search on sentences. (It would help if we had more sentences data.)

**Comment by susanodd** [comment]
![columns-sentence-type-negative](https://github.com/Signbank/Global-signbank/assets/24272544/5d5ba4e6-b65c-4fbb-887f-4db0acc9db76)

**Comment by susanodd** [comment]
Here's a query of (senses with) Interrogative sentences.

In the results, at the moment, it's showing senses that have interrogative sentences. But not merely the sentences of that type since it shows senses and their sentences.

![sentences_query_interrogative](https://github.com/Signbank/Global-signbank/assets/24272544/a2aee27a-104a-43fd-87c6-7b3bd64d5b91)

**Comment by Jetske** [comment]
Nice that it also shows the sentences type. 

What happens when a gloss has multiple senses? I see that the numbering looks a little strange now. Perhaps match that to the senses, for example: some gloss has a sense 1 with sentence 1.1, 1.2, a sense 2 wihout sentences and a sense 3 with sentences 3.1, 3.2, 3.3

**Comment by susanodd** [comment]
@Jetske Did you finish the branch to number sentences? (#1054) ?

I tried adding the sense number to it, but it looks illogical to me.
(It won't number the two sentences "broer zin 1" and "broer zin 2" as 1 and 2.
On the pull request branch do these number as expected?)

**Comment by susanodd** [comment]
I added a couple of (negative) sentences to get new numbers. It won't let me reorder the existing ones. (this queries on declarative or imperative sentences)

![sentences-numbering-include-sense_number](https://github.com/Signbank/Global-signbank/assets/24272544/c9478c29-b251-4447-9386-37ffabc5c768)

**Comment by susanodd** [comment]
Here's what searching on (Dutch) (Gloss) "BRUS" yields:

![search_gloss_BRUS_senses_sentences](https://github.com/Signbank/Global-signbank/assets/24272544/129fee46-12a3-47bf-a702-d341e800a31b)

**Comment by susanodd** [comment]
The sense number is kind of meaningless in the results.

**Comment by susanodd** [comment]
![search_friend_senses](https://github.com/Signbank/Global-signbank/assets/24272544/c83e9bac-c2d3-4f9a-a5ec-61389a8efcda)

**Comment by Jetske** [comment]
In the case of 'broer zin 1' en 'broer zin 2' I think 'order' was added to the model after creating these sentences, so their order wasn't updated from the default 1 yet. Indeed more examples would help to see how it will look..

**Comment by susanodd** [comment]
![scrollbar-results-search-senses](https://github.com/Signbank/Global-signbank/assets/24272544/93a76eb1-3560-48fc-a53c-29db2b3cdf95)

**Comment by susanodd** [comment]
![search-negative-sentences](https://github.com/Signbank/Global-signbank/assets/24272544/0a9a1b7e-78c3-4aaa-bf35-3937c7de1f85)

**Comment by susanodd** [comment]
I added a senses search on negative sentences (has negative sentences / has sentences that are not negative sentences)

Plus the scroll bar visible for the gloss detail view now shows the results of the senses search. The links are to glosses, but they are displayed as the sense of the gloss (from the sense search results).

**Comment by susanodd** [comment]
![scrollbar-senses-omit-vertical-bar-if-language-missing-from-sense](https://github.com/Signbank/Global-signbank/assets/24272544/4d28e9c9-5dba-42fa-a750-95ef585fb2b0)

The above shows that the vertical bar in the senses display is omitted if one of the dataset languages is not filled in.
(This also applies to datasets with only one language. #1053.)

**Comment by susanodd** [comment]
This is live now.
Under the Signs menu, under Search Senses

**Comment by ocrasborn** [comment]
Looks good @susanodd ! Can the issue be closed?

**Comment by susanodd** [comment]
Okay!
