### ISSUE TITLE
Modify list view to display Senses instead of Translations

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#967]
This follows on #884

**Comment by susanodd** [comment]
For a straightforward presentation, this would resemble the keywords (translations) as they are now.
Show for the gloss its senses if one of them contains the searched term. (Like 'broer'.)

For an alternative that "senses" or "sentences" could be returned as results, then perhaps something to show which glosses share the sense, and which glosses appear in the example sentences. Then being able to search on sentences containing a gloss of a particular sense.

**Comment by Jetske** [comment]
I'm working on this in my [branch](https://github.com/Signbank/Global-signbank/tree/add_sense_examplestc_884)... It looks like this now (example):

![image](https://github.com/Signbank/Global-signbank/assets/10157482/191ce60f-53a2-42f6-8b91-0bcaa2a2b6e7)
