### ISSUE TITLE
Uploading a video recorded by webcam goes wrong half of the time

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#972]
Error: "TransactionManagementError at /video/upload/
An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block."
Working on mac/chrome; hadn't seen this before

**Comment by Jetske** [comment]
Haven't seen this one before either, I'll try to find it. Can you share a screenshot of the error if it occurs?

**Comment by susanodd** [comment]
This might be related. I've been using Gloss Detail View quite a lot to test editing the fields.
On a reload, I noticed this is the console:
```

> 
> Uncaught (in promise) ReferenceError: stream is not defined
>     stopCamera http://localhost:8000/static/js/recordscript.js:85
>     onclick http://localhost:8000/static/js/recordscript.js:41
>     EventHandlerNonNull* http://localhost:8000/static/js/recordscript.js:39
> 

```

Needless to say, I'm not doing anything with videos. Just Phonology.

**Comment by susanodd** [comment]
Can this be closed? Is this still a problem?
