### ISSUE TITLE
Cannot change handhape specification

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#973]
At the top of a handshape's specifcation, I cannot deselect a checkbox for the fingers. Unselecting and clicking OK leads to an html error.
Update: Ah, in fact the change is correctly saved, it's just not displayed when I click away the error message, plus of course the error message shouldn't appear in the first place.
(I was editing https://signbank.cls.ru.nl/dictionary/handshape/15/)

**Comment by susanodd** [comment]
Ouch! This is a FieldChoice error!

**Comment by susanodd** [comment]
This has been deployed.

With a grain of salt, it's working now.

**Comment by ocrasborn** [comment]
I confirm :-), @susanodd . Thanks!
