### ISSUE TITLE
A Handshape's page hides some but not all empty phonology fields

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#979]
For the phonology of a sign, fields that are not used for a given sign are not displayed in the detail view of that sign, which is nice and easy on the eyes. For a handshape's phonological specification, however, some empty fields are hidden while others are shown. Please do the same here as for a sign, listing in the detail view of a handshape only the specified fields.

**Comment by susanodd** [comment]
This is on master, waiting for deployment.

**Comment by susanodd** [comment]
This is live now.
