### ISSUE TITLE
Add ECV to crontab in Ansible script

### ISSUE THREAD

**Issue by Woseseltops** [Signbank/Global-signbank#985]
``echo "from signbank.tools import write_ecv_files_for_all_datasets as w; w()" | /var/www/env/bin/python /var/www/repo/bin/develop.py shell``

**Comment by vanlummelhuizen** [comment]
@Woseseltops Perhaps better move this issue to our Signbank-Ansible repo on our Gitlab.

**Comment by vanlummelhuizen** [comment]
@Woseseltops Duplicate of #957 ?

**Comment by Woseseltops** [comment]
Done
