### ISSUE TITLE
Change to the message new users get after confirming their email address

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#989]
New users receive one email to ask to confirm their email address, and when they click on the link in the email, they get a message (on the site or in a new email, I forgot which) saying they will be notified once their request for access to a dataset is granted. But for the NGT dataset, requests are automatically granted and no message is sent. Please rephrase somehow.

**Comment by susanodd** [comment]
Forgot to put the # in the issue number in the commit message.

https://github.com/Signbank/Global-signbank/commit/1701f4954a5bea13025172edee410ffd2c6fec00

**Comment by susanodd** [comment]
This is live.
