### ISSUE TITLE
Tests print email welcome messages

### ISSUE THREAD

**Issue by susanodd** [Signbank/Global-signbank#994]
When running the tests, they are printing the contents of the welcome messages normally sent to a new user via email.
It didn't used to do this.
I accidentally clicked on one of those email links in the terminal window. See screenshot.
What is Falkon? This appears in the browser title page (see top of screenshot). Normally, it merely just shows Global Signbank.

![tests-welcom-links-to-this](https://github.com/Signbank/Global-signbank/assets/24272544/6d1494fb-8d73-465c-ac4b-e5241e31c67a)

**Comment by vanlummelhuizen** [comment]
@susanodd I think Falkon is the browser that is used to open links from the  terminal screen: https://www.falkon.org/ .

**Comment by susanodd** [comment]
Oh that must be new ubuntu. :)

Did anything change when you added the page model translations and the new email address for users?

It didn't used to print out things when the tests make test users.

**Comment by vanlummelhuizen** [comment]
Nothing that I can think of that is related to tests. If you want to know, you can dig in the code yourself, do some debugging. Otherwise, don't bother.
